### ISSUE TITLE
Support for better Claim status from underlying resources

### ISSUE THREAD

**Issue by lukeweber** [crossplane/crossplane#1010]
### What problem are you facing?
Problem:
- As a workspace(non-infrastructure persona) I would like to make claims, and be notified of a more detailed status of the underlying resource on the claim.

Further supporting user story:
- As an infrastructure owner, I don't want to grant any permissions to a workspace user to my infrastructure. 

### How could Crossplane help solve your problem?

If I created a MysqlInstance Claim and crossplane created an RDSInstance, I would like generic MysqlInstance status - Online, Offline, Upgrading, etc on the claim.

Currently, we get the status of bound/unbound, and ready nominally on the claim.

**Comment by prasek** [comment]
//cc @negz @jbw976

**Comment by negz** [comment]
To recap, there are three layers here, from bottom to top:

1. The external resource. The actual CloudSQL instance in Google's cloud.
1. The managed resource. The Crossplane `CloudSQLInstance` representing 1.
1. The resource claim. The Crossplane `MySQLInstance` representing 2.

`v1beta1` managed resources include a high fidelity representation of the readiness of their external resource under `.status.atProvider`. This is the most accurate representation of the status of the underlying external resource, but it is arbitrary and provider specific. One PostgreSQL compatible managed resource might have `.status.atProvider.State: READY` while another has `.status.atProvider.Online: true`. 

All extant managed resources (and all resource claims) support conditioned statuses. A conditioned status is a slice of the following struct:

```go
type Condition struct {
	// Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type ConditionType `json:"type"`

	// Status of this condition; is it currently True, False, or Unknown?
	Status corev1.ConditionStatus `json:"status"`

	// LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime metav1.Time `json:"lastTransitionTime"`

	// A Reason for this condition's last transition from one status to another.
	Reason ConditionReason `json:"reason"`

	// A Message containing details about this condition's last transition from
	// one status to another, if any.
	// +optional
	Message string `json:"message,omitempty"`
}
```

All managed resources, by convention, expose a condition of `Type: Ready`, but we treat the _reason_  a managed resource is or is not ready as arbitrary; the condition is set by `ExternalClient` authors. In practice the reason is almost always `Creating`, `Deleting`, `Available`, or `Unavailable`, but an `ExternalClient` author could set `{Type: Ready, Status: False, Reason: Inflating}` if they wanted. It's worth noting that even `v1beta1` managed resources don't typically represent every possible reason a managed resource is or is not ready via the `Ready` condition; i.e. they don't usually detect when a managed resource is in maintenance, unready due to updates being applied, etc.

When it comes to the resource claim, we currently:

* Set `{Type: Ready, Status: False, Reason: Binding}`while we're waiting to bind to the managed resource (typically because the managed resource is being dynamically provisioned or is otherwise not yet in `BindingPhase: Unbound`).
* Set `{Type: Ready, Status: True, Reason: Available}` when we bind to the managed resource.
* Set `{Type: Ready, Status: False, Reason: Deleting}` when the resource claim is deleted.

So we effectively lose a little resolution on the actual external resource's status with each layer of abstraction. Notably, the resource claim doesn't notice if the managed resource transitions from `{Type: Ready, Status: True}` back to `{Type: Ready, Status: False}` if the managed resource has become unavailable for some reason. It considers "bound" to mean "ready".

One thing we could do here would be to couple the `Type: Ready` condition of the resource claim more tightly to the `Type: Ready` condition of the managed resource; we could have a controller watch bound managed resources and propagate their `Ready` condition back to the claim.

> As an infrastructure owner, I don't want to grant any permissions to a workspace user to my infrastructure.

I'd like to explore whether this is a use case we should support. I'll use the Crossplane "managed resources" terminology to mean "infrastructure" here. Keep in mind that:

* It's possible to grant read-only access to managed resources via RBAC.
* It's possible to grant read-only access to _just the status_ of managed resources via RBAC.
* All bound resource claims reference their bound managed resource via `.spec.resourceRef`.

If we could assume that resource claim owners had at least read-only access to the status of the managed resource their claim was bound to, a workspace persona (i.e. resource claim owner) could determine the high fidelity status of their resource claim by following the `resourceRef` back to the bound managed resource and inspecting its status.

**Comment by lukeweber** [comment]
> If we could assume that resource claim owners had at least read-only access to the status of the managed resource their claim was bound to, a workspace persona (i.e. resource claim owner) could determine the high fidelity status of their resource claim by following the `resourceRef` back to the bound managed resource and inspecting its status.

I'm not immediately thinking of a solution on how we would achieve this in a generic way with RBAC.  Do you have any ideas? I see the point about crafting custom RBAC to meet a specific use-case for a specific resource, but I think I'm more thinking in terms of making the end user out of box experience for an app developer persona working with claims richer.

So this feature request is to enrich the experience around claims by providing a more feature rich experience around status I believe.

**Comment by muvaf** [comment]
> One thing we could do here would be to couple the Type: Ready condition of the resource claim more tightly to the Type: Ready condition of the managed resource; we could have a controller watch bound managed resources and propagate their Ready condition back to the claim.

@negz Recently, users asked for help on the Slack channel and our first response is usually `go look at the managed resource status`, which usually helps a lot but as expected the first thing they look at is claim. If they could see the error on the claim right away, they'd just fix and move on. So, I think this would be very valuable in terms of UX. Though I am not sure if a new controller should do it. Can't we have claim reconciler do this as part of reconcile loop? Maybe in the end of the `Reconcile` function?

**Comment by displague** [comment]
> So this feature request is to enrich the experience around claims by providing a more feature rich experience around status I believe.

Crossplane CLI [Tracing](https://github.com/crossplaneio/crossplane-cli/blob/master/docs/trace-command.md#text-output) provides similar UI/UX capabilities by following the `resourceRef`.

I was wondering how the tracing approach wouldn't fit or was limiting and found that this was stated in the issue description:

> I don't want to grant any permissions to a workspace user to my infrastructure.
---
_This comment just adds some context that wasn't obvious to me on the first read._

**Comment by negz** [comment]
I believe it's a fairly uncommon pattern to literally copy the status of one resource wholesale to another in Kubernetes, though there are patterns of one resource _summarising_ the status of the resources they represent. e.g. A `Deployment` summarises the status of its `Pod` resources. It may be illustrative to look at what kind of details a `PersistentVolumeClaim` surfaces about the health and status of their bound `PersistentVolume` resources.

I think there's a bit of a philosophical question here around what a claim should be. Is a `MySQLInstance` a _claim_, i.e. a request to be allocated, a `CloudSQLInstance` or is it literally a proxy that represents the `CloudSQLInstance`, attempting to hide the user from the fact that a `CloudSQLInstance` even exists.

> I'm not immediately thinking of a solution on how we would achieve this in a generic way with RBAC. Do you have any ideas?

How crazy would it be to assume that workspace personas had read-only access to all managed resources? I'm not currently up to speed on where our RBAC/security model thinking is at, but I presume we need some way to automatically grant the administrator persona access to work with the resources an infrastructure stack installs? Could we use that same process to grant RO access to the group representing all workspace owners by default?

While it is possible possible I don't think it's common in Kubernetes clusters to, for example, hide the details of what `Node` and `PersistentVolume` resources exist in the system. I actually tried doing exactly that in a previous life and it did not fly with my user community. It was determined that there was no real reason to prevent namespace owners from being able to _see_ (not modify) what cluster scoped resources existed, and that they found value in being able to see those details.

**Comment by lukeweber** [comment]
> How crazy would it be to assume that workspace personas had read-only access to all managed resources? I'm not currently up to speed on where our RBAC/security model thinking is at, but I presume we need some way to automatically grant the administrator persona access to work with the resources an infrastructure stack installs? Could we use that same process to grant RO access to the group representing all workspace owners by default?

I was responding to dynamically creating RBAC for the single resource that a user had claimed which I don't think there's any easy RBAC for. Certainly read access to the underlying resource that any user in any namespace has claimed is trivial. I think it's one reasonable approach, and it could easily be provided if that's what we want.

Right now, I'm trying to help define what is a workspace persona and what do they see. One idea is everything in their namespaced scope represents a complete view that the app developer needs to interact with, likewise the infrastructure view is everything that's cluster scoped. Classes has already come up as likely needing visibility at the Workspace level, even though it's cluster scoped, but it's kind of a special case during creation.

As you mentioned, hiding the underlying resources didn't fly in your previous job, and I suspect it won't in this case either. In terms of whether every client wants all underlying resources to be shared by all workspaces, I can't really comment to that either. It seems like a more permissive permission model that might also not be correct to assume.

Feel free to add your thoughts on RBAC, likely whatever we go with in terms of concepts of isolation for personas will indirectly impact design decisions in the future:
https://github.com/crossplaneio/crossplane/pull/1008

**Comment by displague** [comment]
> I believe it's a fairly uncommon pattern to literally copy the status of one resource wholesale to another in Kubernetes, though there are patterns of one resource summarising the status of the resources they represent. e.g. A Deployment summarises the status of its Pod resources. It may be illustrative to look at what kind of details a PersistentVolumeClaim surfaces about the health and status of their bound PersistentVolume resources.

@thephred was feeling the same need for `StackInstall` to reveal the status of the `Stack` (or more precisely, the Stack's install `Job`).

He points out that `Deployment` resources have  a [`spec.progressDeadlineSeconds`](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#progress-deadline-seconds) which will set the processing to failed when the conditions are met.  In the case of StackInstalls, failures are introduced through immediate failures and not eventual failures (like a Stack or Job that will never or has not completed).

The in-cluster resources of StackInstalls (Stacks and Jobs) have conditions that the StackInstall monitor can introspect to follow-up on progress.  In the case of a KubernetesApplication, this is not possible, since the monitoring user or process does not have the same level of access as the Crossplane controller.

In addition, `Jobs` don't always include a conditioned status, sometimes only revealing `status: { active: 1 }`, so the user can't always chase the child resources without intimate business logic, which arguably,  the crossplane controllers could provide.

**Comment by negz** [comment]
I think between "bidirectional patching" and configurable composite resource readiness we pretty much have this now (with some configuration required). For example an XR author could configure which managed resource composed fields must be in what state in order to consider the XR to be 'ready', and thus in turn what means the claim is ready. They could also add bespoke status information to their XR that would be derived from managed resource fields (via patching) and map that back to the claim.
