### ISSUE TITLE
Unintended deletion of CRDs causes cascaded deletion of all CRs

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1082]
### What problem are you facing?

If a CRD gets a deletion request, it cascades to all CRs and deletion is completed when there is no instance anymore. https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/finalizer/crd_finalizer.go#L55

However, deleting a CRD by accident is just too easy. A bug in controllers, unexpected behavior of tiller or unexpected garbage collection by Kubernetes can cause a deletion request to be made on CRD. We need to make sure that the deletion process of CRs doesn't start without explicit intent. This is especially more critical for infrastructure custom resources where almost all of them are stateful and recreation may not be possible with the full state.
Example; https://github.com/crossplaneio/crossplane/issues/895

### How could Crossplane help solve your problem?

Instead of just [checking](https://github.com/crossplaneio/crossplane-runtime/blob/d72012f1c2d04330f49daa49073ef22c9928ccca/pkg/meta/meta.go#L203) `deletionTimestamp`, we can have a constant annotation like `crossplane.io/explicit-deletion` to check whether the entity who is deleting the resource can confirm its intent. It's easy to have controllers to put that annotation before the `Delete` call but if a user tries to delete a managed resource, it'd be a bit more work for them to put an annotation _and_ to know that they need to put an annotation. Though this suggestion takes some amount of automation.

Another solution could be to put a finalizer to all CRDs that a `StackInstall` or `ClusterStackInstall` registers. Only entity who removes that finalizer would be the stack manager so that we lower the possibility of unexpected deletion to be cascaded to all CRs. I personally like this pattern more but it'd be a little bit cumbersome to integrate this into our CRD generation flow.

**Comment by negz** [comment]
It does not seem like the issue here - the blast radius of CRD deletion - is something we should try to solve in Crossplane. If this is a problem for Crossplane, surely it's a problem for any project that uses Kubernetes. Perhaps this should be raised and discussed upstream (if it has not already)?

If I follow correctly the proposed solution seems little broader than the problem, in that it seems to be suggesting that our controllers should require more than the presence of the deletion timestamp in order to process _any_ delete, not just cascading deletes due to CRD removal. I'm also wary about diverging from typical Kubernetes behaviour here, and would suggest discussing this upstream if we really think it's too easy to delete Kubernetes resources in general, or that there should be a class of Kubernetes resource that is extra difficult to delete.

**Comment by muvaf** [comment]
The second suggestion sounded more appealing to me but I just tested it by putting an arbitrary finalizer to CRD manually and see whether the CR instance will be deleted and they did. Apparently, the cleanup logic only checks whether there is a deletion timestamp and its own specific finalizer is in place https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/finalizer/crd_finalizer.go#L116

The first proposal is indeed divergence from Kubernetes patterns and I don't like it very much, too.

I agree that it's probably best to fix this in upstream. Nevertheless, I feel we should somehow harden it.

**Comment by negz** [comment]
Cross linking to this relevant upstream issue - https://github.com/kubernetes/kubernetes/issues/10179.
