### ISSUE TITLE
Drop Helm 2 support

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#1100]
### What problem are you facing?

Helm 3 GA recently released and has major improvements against Helm 2. However, it has breaking changes and as we try to keep supporting both, we will need to apply not-so-nice [workarounds](https://github.com/crossplaneio/crossplane/pull/1077).
### How could Crossplane help solve your problem?

Drop Helm 2 support and set minimum Helm version requirement as 3.0.0.

**Comment by muvaf** [comment]
My two cents, I don't really see a quick shift from helm2 to helm3 in the industry because of such major changes that are introduced. So, I believe it's better to keep the support for a good amount of time unless something really blocks us from doing so.

If we're not happy the way we generate the chart, maybe we can generate 2 different helm charts; one for helm2 and one for helm3 with a cleaner generation procedure.

**Comment by jbw976** [comment]
> maybe we can generate 2 different helm charts

That's what I've been leaning towards myself too, I wouldn't want to completely drop support for Helm 2 just yet and I don't want to hold off much longer on supporting Helm 3.  2 parallel charts, that hopefully can reuse resources between the 2 of them so we don't have much duplication, sounds like a viable way forward to me.

**Comment by displague** [comment]
One approach could be to create a separate repository to track our Helm2 charts.

https://github.com/mattermost/mattermost-helm is an example of this.

**Comment by hasheddan** [comment]
I think we are nearing being able to officially drop helm 2 support. August marked the last bugfix release, and November will mark the last security release. More information [here](https://helm.sh/blog/helm-v2-deprecation-timeline/).

**Comment by negz** [comment]
Let's drop it for v0.13.
