### ISSUE TITLE
Implement Resource Constrains (Policy) in the Resource Class 

### ISSUE THREAD

**Issue by ichekrygin** [crossplane/crossplane#118]
### Overview
Currently, `ResourceClass` does not support the notion of the resource constraints, and only provides a properties map. 

We need to separate properties from the constraints since those have distinct purposes.
- Properties: are only defined at the class level and should not be exposed at the `AbstraInstance` level. The example of properties: `securityGroups`,`vpcId`, etc.
- Constraints: are defined in terms of the resource constraint policy (instead of static value). For example: `engineVersion = "5.6+"`, etc. The exact resource constraint language is to be defined. 

All the resource property values defined at the `AbstractInstance` should be validated against the resource constraints at the `ResourceClass` level. If the property does not have a constraint, then the value is deemed valid.

### Related Issues:
- #20

**Comment by negz** [comment]
I believe our current thinking is that we might integrate with something like OPA to handle this, rather than inventing our own constraint concepts. It's worth noting that in the brave new world folks can author their own API definitions and how those definitions relate to a composition of resources, which can cover some rudimentary constraints (e.g. you can limit what engine versions are valid when defining your SQL instance resource).
