### ISSUE TITLE
RC tags are not picked up on master until a new commit is merged

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#1181]
### What happened?

Following the release of Crossplane `v0.7.0`, the `alpha` channel chart started using the `0.7.0` tag, but the `master` channel was still on `0.6.0-rc`. This is likely because we run explicit promotion pipeline on the release branch, but not on master for new releases. This means that the `0.6.0-rc` tag will continue to be used until a new commit is merged to master, triggering the build pipeline, which includes promotion. This is also true for each stack.

This could likely be remedied by running the promotion pipeline on `master` directly, but if we go that direction it should be added as a formal step in the [release process](https://github.com/crossplaneio/crossplane/blob/master/docs/release/release-process.md#promotion).

### How can we reproduce it?

```
$ helm search repo crossplane --devel
NAME                                    CHART VERSION           APP VERSION             DESCRIPTION                                                                                                        
crossplane-alpha/crossplane             0.7.0                   0.7.0                   Crossplane - Managed Cloud Resources Operator                                                                      
crossplane-master/crossplane            0.6.0-rc.41.g9a064f3    0.6.0-rc.41.g9a064f3    Crossplane - Managed Cloud Resources Operator 
```

### What environment did it happen in?
Crossplane version: `v0.7.0`

**Comment by jbw976** [comment]
Simply running the normal build pipeline on master after tagging the RC should take care of this fine, auto promotion is part of the build pipeline for master.

**Comment by negz** [comment]
The most recent release of Crossplane is currently `0.8.0`, but master builds are currently tagged `0.8.0-rc.XX`. This is a little confusing, because it sounds like the master builds are a release candidate for 0.8.0, whereas I think they're actually a release candidate for 0.9.0.

**Comment by jbw976** [comment]
Agreed @negz, there's been discussion in the upbound/build repo (https://github.com/upbound/build/pull/92) about how to make this versioning workflow automatic.

It's a bit tricky to automate it, but I think we can make a minor change within the crossplane release process in the meantime.  Instead of tagging `v0.9.0-rc` when we are ready for 0.9, we could do something like `v0.10.0-pre` or something like that.  Then subsequent builds in master will be pretty obvious that they are working towards v0.10, for example `v0.10.0-pre.19.g8e23c0`.
