### ISSUE TITLE
template stacks: improve code coverage

### ISSUE THREAD

**Issue by suskin** [crossplane/crossplane#1198]
### What problem are you facing?

Once the initial implementation of template stacks has stabilized and we want to ensure correctness over time, we'll want to add some unit tests so we can track correctness and notice problems more easily.

### How could Crossplane help solve your problem?

Add unit tests to help us ensure that the template stacks code is correct and remains correct over time.

The test coverage number that we've been using to represent an amount of coverage we're confident in is 80%.

**Comment by muvaf** [comment]
In templating-controller, there are 3 main packages that contain the logic and here is their coverages:
[`pkg/controllers`](https://github.com/crossplane/templating-controller/tree/master/pkg/controllers): 81%
[`pkg/operations`](https://github.com/crossplane/templating-controller/tree/master/pkg/operations): 0%
[`pkg/resource`](https://github.com/crossplane/templating-controller/tree/master/pkg/resource): 88.7%

`pkg/operations` contains helm3 and kustomize engine packages, which are more suitable to be tested by an integration test rather than unit tests. I'll try to do it via unit tests as much as I can but will switch to Daniels integration test suite if I have to.

In Crossplane repo, the controller code for `StackDefinition` [has a test](https://github.com/crossplane/crossplane/blob/4640860/pkg/controller/stacks/templates/stackdefinition_controller_test.go#L121) that tests the main logic but it's disabled. I think enabling it or preferably converting it to table tests would be good. Other places like unpack for behavior seems to be covered. @suskin I think we can close this issue right after enabling the StackDefinition controller test (or if you have bandwidth, after implementing table test that covers error cases, too) and me completing those engine tests.

**Comment by jbw976** [comment]
https://github.com/crossplane/templating-controller/pull/11 has been merged, so the coverage in the templating-controller repo is great now.

The only thing left is StackDefinition test I think? @muvaf are you going to follow up on that or should this issue be assigned to someone else? Thanks!

**Comment by muvaf** [comment]
@jbw976 I just opened a PR to convert the test to work without the api-server https://github.com/crossplane/crossplane/pull/1363
