### ISSUE TITLE
KubernetesApplication should support Helm charts

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1207]
### What problem are you facing?

Today, `KubernetesApplication` resource allows users to specify a `templates` section where they list Kubernetes resources to be deployed to the target cluster. Helm charts are heavily used to bundle the resources to be deployed to a Kubernetes cluster but current `KubernetesApplication` CR does not support that.

### How could Crossplane help solve your problem?

`KubernetesApplication` can have a field called `source` or `externalSource` to refer to a Helm chart that exists on the internet and a Helm controller (possibly a stack) can act if the source is Helm chart and deploy it to the target cluster.

**Comment by displague** [comment]
This issue sounds like https://github.com/crossplaneio/crossplane/issues/666 which https://github.com/crossplaneio/crossplane/issues/1011 would tackle via Template Stacks.

It sounds like you would like to see the "core" stack (https://github.com/crossplaneio/crossplane/issues/1154) pick up direct Helm support so that the list of Kubernetes resources could be omitted / externalized.

How would this differ from template stacks? The target cluster of KubernetesApplication is a remote cluster, while the target cluster of a Template stack is the host cluster.  That becomes more flexible with the host-aware stack manager presented in https://github.com/crossplaneio/crossplane/issues/1038 as a response to https://github.com/crossplaneio/crossplane/issues/1038.

**Comment by muvaf** [comment]
> The target cluster of `KubernetesApplication` is a remote cluster, while the target cluster of a Template stack is the host cluster.

Right, what I want here is to deploy resources to a target cluster that is provisioned/ by Crossplane or imported in the form of `KubernetesTarget`. 

> It sounds like you would like to see the "core" stack (#1154) pick up direct Helm support so that the list of Kubernetes resources could be omitted / externalized.

Actually what I'd want to see is that we can treat `KubernetesApplication` just like `KubernetesCluster` where different stacks can pick it up and do some actions. In this case, a Helm stack can look for `KubernetesApplication` with helm source and either:
- directly deploy it to the target cluster and update status under `KubernetesApplication.status` or
- print the resulting YAMLs into `KubernetesApplication.spec.templates` as output (which could possibly be done by a mutating webhook, too)

**Comment by muvaf** [comment]
Supporting this scenario via template stacks might make more sense as we think `KubernetesApplication` resource a low-level component that just deploys resources to the remote cluster. See https://github.com/crossplane/crossplane/issues/1309 for details.

**Comment by negz** [comment]
We're planning to remove KubernetesApplication, so I don't think we'll proceed with this.
