### ISSUE TITLE
GCP Wordpress example doesn't mention that  you need "Service Networking API"

### ISSUE THREAD

**Issue by dsyer** [crossplane/crossplane#1222]
When you try to use the Wordpress example it fails to create a SQL instance so the Crossplane resources are hung and never get to "Bound". The GCP console reveals that you need to enabled the "Service Networking API", which is easy, but not mentioned in the [Wordpress docs](https://crossplane.io/docs/v0.7/services/gcp-services-guide.html#install-wordpress) that I have seen (although I did find it in the end in the [GCP provider docs](https://crossplane.io/docs/v0.7/stacks-guide-gcp.html)).

**Comment by muvaf** [comment]
@dsyer We've got two Wordpress guides:
* [Stacks GCP Guide](https://crossplane.io/docs/v0.7/stacks-guide-gcp.html) includes the GCP configuration section, which shows what APIs you need to enable.
* [Services GCP Guide](https://crossplane.io/docs/v0.7/services/gcp-services-guide.html) points you to the GCP instructions that have that (although the link seems to be broken, fix is https://github.com/crossplaneio/crossplane/pull/1228).

I agree that we have an inconsistency there. I assume we'd want to keep GCP provider setup phase leaner and move the API enabling section to individual Wordpress guides since you may not need to enable those APIs for other cases. @prasek what do you think?

**Comment by negz** [comment]
We've simplified our docs and guides such that the service networking API is no longer required, so I'm going to close this issue.
