### ISSUE TITLE
Define mandatory tags at the provider level

### ISSUE THREAD

**Issue by rberrelleza** [crossplane/crossplane#1225]
### What problem are you facing?
I want all the resources created by the same AWS provider to include certain tags, on top of the user defined tags. I need this tags mainly to be able to do charge-backs, apply quotas and cleanup resources. 

### How could Crossplane help solve your problem?
I'd like to be able to specify this tags when creating/updating the provider, and have crossplane apply them. Ideally, I'd also like to be able to have some values be dynamic and generated at resource creation time (e.g. a tag with the ID of the resource, a tag with the namespace of the resource in EKS, etc...)

**Comment by muvaf** [comment]
@rberrelleza We're including tagging in our API conventions one-pager [here](https://github.com/crossplaneio/crossplane/pull/1129/files#diff-af44f0294a636aedef35de8f4f0c023fR130). After this gets merged, we'll open subsequent issues in infra stack repositories to implement it across the board.

Though, the tags that will be added automatically will be `crossplane.io/name` and `crossplane.io/kind`. As the resources are cluster-scoped, namespace will not be included. Would that solve your use case?

> I want all the resources created by the same AWS provider to include certain tags, on top of the user defined tags

If I understand that correctly, you'd like to tag them per `AWS Provider` resource to know who created what. I feel like this could be done by calling `kubectl get <crossplane.io/kind value> <crossplane.io/name>` and looking at the `spec.providerRef`. But this is all in your cluster. Is your use-case includes doing operations per IAM role in AWS console via tags because all `AWS Provider` resource does is to refer to the secret that contains the IAM role?

Could you expand what you'd like to achieve? The PR https://github.com/crossplaneio/crossplane/pull/1129 that introduces tagging pattern is not merged yet, so, it's definitely possible to add tags to address common use cases.

**Comment by hasheddan** [comment]
One thing I think we could do here is allow for global tags to be applied on the Provider, then add an option to apply them in the managed reconciler for resources that support tagging. For dynamic tagging that could be a little more difficult as we would like need some sort of transformation function or regex to be given on the Provider, then applied when tagging resource.

**Comment by rberrelleza** [comment]
> Could you expand what you'd like to achieve?

When the AWS bill comes, I want to be able to tell how much of it is "owed" by the team that owns a specific Kubernetes cluster. I'd like every AWS resource created by a specific crossplane provider to have, for example, a "Owner=TeamName"  and "Cluster=Cluster-Name" tag.

**Comment by muvaf** [comment]
@rberrelleza That'd be pretty cool. I didn't know [it was possible ](https://aws.amazon.com/tr/premiumsupport/knowledge-center/tags-billing-cost-center-project/)to group expenses via tags on AWS.

I think labelling by provider and resource class would enable interesting grouping mechanisms. Something like;
```
crossplane.io/provider: my-aws-provider
crossplane.io/class: my-eks-cluster-class
```

`crossplane.io/class` would be empty for statically provisioned resources. The name of the tag kind of mirrors the `classRef` and `providerRef` on the managed resource.

@hasheddan @negz what do you think about this addition on [API patters one-pager](https://github.com/crossplaneio/crossplane/blob/5f478ac/design/one-pager-managed-resource-api-design.md#external-resource-labeling) ?

**Comment by negz** [comment]
@muvaf Do you think our controllers should automatically apply such tags, or would it be better to allow it to be done by convention (e.g. by setting whatever field under `.spec.forProvider` corresponds to the resource's tags)?

**Comment by muvaf** [comment]
I'm not 100% sure but we have all the info we need through [`ResourceSpec`](https://github.com/crossplaneio/crossplane-runtime/blob/5ece4af/apis/core/v1alpha1/resource.go#L127) but just the method to put those labels is missing. Maybe an interface like the following could be supplied by each resource and we could add the tags:
```go
type Tagger interface{
  AddTag(mg Managed, tags map[string]string)
  RemoveTag(mg Managed, keys ...string)
}
```

Then managed reconciler could use these functions to add the tags. In fact, we could possibly tag the resource with all the labels that exist on CR alongside our specific tags that listed in the doc.

**Comment by negz** [comment]
This sounds similar to https://github.com/crossplane/crossplane-runtime/issues/254.

**Comment by muvaf** [comment]
We now have the standard tags and it can be implemented per-resource in providers. Though we can't force specific custom tags from a central place. I'd suggest looking at webhook tools like OPA that can mutate and/or validate that certain tags you'd like are there. Feel free to re-open if this wouldn't address your use case.
