### ISSUE TITLE
Stacks: StackDefinition should not depend on StackInstall

### ISSUE THREAD

**Issue by displague** [crossplane/crossplane#1257]
## What problem are you facing

> I had started plumbing `ControllerImage` into the StackDefinition controller before realizing that it was, oddly enough, not involved in generating the controller image and deployment (in this current design, `unpack`, stackinstall, and stack share that responsibility).  The StackDefinition controller does add an RBAC rule, but that's the extent of its deployment manipulation.
> As @muvaf pointed out elsewhere, this creates a dependency on the `StackInstall` controller that preventing users from deploying  standalone `StackDefinition` resources.

_Originally posted by @displague in https://github.com/crossplaneio/crossplane/timeline_

## How can Crossplane help?

The `StackDefinition` controller should not have a dependency on the installjob handler process.  StackDefinition resources should be a resource that can be created on their own and be fully reconciled.

The templating controller image value should be supplied to the stackdefinition controller (rather than the stackinstall controller).  The stackdefinition resource should define the templating-controller as a default when one is not supplied.

This would allow users creating StackDefinition resources by hand to omit or define a templating-controller.

Stack package authors of template stacks can then include an `install.yaml` that specifies the custom templating-controller or omit `install.yaml`.

**Comment by muvaf** [comment]
This was brought up during planning on how we'd like to implement template stacks. Essentially, there is a user who just create a `StackDefinition` with correct behavior and source image/repo/chart and get the template stack up and running. That user wasn't a priority as we were focused on making the existing stacks we have work with template stacks. So, we punted on supporting that scenario.

What this means in the code is that templating controller deployment is generated during `unpack` process today, which is a step that doesn't exist in this scenario. However, there is no requirement to do that in `unpack`. In fact, just moving the generation code to `StackDefinition` controller would be sufficient to support this scenario.

I think this is especially useful because the users will be able to just use an existing off-the-shelf helm chart and deploy it as helm stack when it's a supported `source` type, which is a huge boost to usability of stacks.

**Comment by negz** [comment]
I don't think we're proceeding with template stacks, so I believe we won't have to address this.
