### ISSUE TITLE
Stacks: Combine stack image references (unpack and controller image should be the same)

### ISSUE THREAD

**Issue by suskin** [crossplane/crossplane#1308]
### What problem are you facing?

As we have been using our stacks and managing them, we have discovered that having two references to each stack image is making things unnecessarily error-prone for us, and we aren't using the feature at all.

The feature works as follows. A stack image is specified in two places:

* On install, for the unpack phase
* In configuration (either `install.yaml` or `behavior.yaml`, depending on the type of stack), for the controller phase

Theoretically decoupling these two allows the user to pull the envelope (the image used for unpacking) from a different place or a different image from where the controller is pulled from, and that seems useful. But we haven't been using it yet, so we would like to not use that pattern in our codebase and revisit it later. And, since we plan to remove it from our codebase everywhere, we should probably just disable the feature until we revisit it later.

### How could Crossplane help solve your problem?

* Always pull the behavior source image (in the case of `behavior.yaml`) or the controller source image (in the case of `install.yaml`) from the stack install object, if the image is not specified in the configuration. These are changes in the stack manager.
* Add basic unit tests (one for each path) to check that this works
* Remove the source image name from `behavior.yaml` for all the stacks that we maintain
* Remove the source image name from `install.yaml` for all the stacks that we maintain
* Update the stack documentation to match the new behavior
* Update any relevant crossplane-cli scaffolding

**Comment by prasek** [comment]
@suskin looks like we'll need to remove [image: "crossplane/stack-gcp:master"](https://github.com/crossplane/provider-gcp/blob/4dc7426f1e10542b19de1e8069ba6e35665e335e/config/stack/manifests/install.yaml#L20) from the install.yaml of the various providers as well.

this will simplify things quite a bit so looking forward to getting this in the near future, thanks!

//cc @rathpc @thephred @jbw976

**Comment by prasek** [comment]
@displague sounds like `Stack Manager` could simply overwrite the controller image e.g. `image: "crossplane/stack-gcp:master"` in the [install.yaml](https://github.com/crossplane/provider-gcp/blob/4dc7426f1e10542b19de1e8069ba6e35665e335e/config/stack/manifests/install.yaml#L20) automatically for all stacks (essentially forcing all stacks to use the stack image as the controller image), and this change would be fairly isolated.

**Comment by suskin** [comment]
I was thinking about this a little more, and realized that we currently support stacks with no controllers, and we probably want to preserve that. The simplest way to do that - for now - would be to leave the `install.yaml` in the contract if you want to have a controller for your stack. But, if you leave the image blank for a container in the deployment, the stack's image will be used instead. This would leave the ability to have a stack with no controller for now, while also simplifying the version management.

In the future we'll probably want something more elegant for people who want a controller but don't care about customizing the deployment, because as a stack author it's annoying to have to create a whole `install.yaml` for no reason.

For behaviors, we can just default to the stack image if the source is left blank.

We will also want to update any relevant crossplane-cli scaffolding.

**Comment by displague** [comment]
I like the way you are thinking about this @suskin. We could preserve the no-op Stack format signalled by a missing `install.yaml`.  I recently took advantage of this to `StackInstall` a non-traditional stack (templating-controller's image with an added app.yaml and an icon) onto a cluster, since 'docker push' was not an option.

 However, I think we have already found some alternate approaches. 
 For example, `behavior.yaml` signals a template stack.  The presence of a different file could signal the next special format of a Stack.  Or, `app.yaml` properties could be used to signal this.

I think it is awkward to have the default `install.yaml` be a Deployment Spec that lacks the seemingly most important Deployment Spec component, the image.

Have a look at this thread where @turkenh and I also considered removing `install.yaml`:
https://github.com/crossplane/crossplane/issues/1317#issuecomment-593832706

Based on these conversations, we could take this approach:

1. behavior.yaml: present -> generate Stack.controller.deployment (from templating controller params) *existing behavior*
2. install.yaml: present -> use it *existing behavior*
3. install.yaml: missing -> generate Stack.controller.deployment (from stackinstall image) *design change*
4. controllerless stack? not supported, maybe it will come back later via app.yaml settings *design change*

As you suggested earlier and was discussed in #1317, we could ignore `install.yaml` entirely and skip straight to step 3.  Either way, soon after this issue is resolved, we will likely want to introduce ways to set the environment and command line parameters of the stack controller (especially for enabling `--debug` behavior #974).  Since CRDs and Stack resources can be deployed without a StackInstall, users can still customize the controllers in these ways, they just can't take advantage of StackInstall to do so, at this time.

We would be getting rid of some openness and complexity of unused features to lock things down until we are ready to address them in a more thoughtful way.

**Comment by suskin** [comment]
Discussed this with @displague and @jbw976 today. I am planning on going with the approach of injecting the `image` field into the `Deployment` specified in `install.yaml` if the field is not specified. From a simplicity standpoint, I like the approach that @displague outlined (generate a default `install.yaml`) more than the approach I plan to take. However, I do not want to do that right now because it changes the semantics of Stacks, which means it's a change with a broader scope, i.e. a design change.

I've selected the injection approach because it's the smallest change when accounting for functionality and semantics together, and it doesn't change what the system can support. I do expect that we will want to revisit this in the medium-term future so we can incorporate some of the other ideas from the discussion we've had so far.

**Comment by suskin** [comment]
I've opened a PR for the functionality. After that's merged, we'll want to:

* [ ] Update all of our stacks to use the new functionality
* [ ] Update any documentation that discusses the stack format, such as the stack design doc
* [ ] Update the crossplane-cli `init` boilerplate to omit the image name from the generated install.yaml (nice to have rather than needed, since the change is backwards-compatible)

**Comment by jbw976** [comment]
Let's follow up on this checklist so we can close out this issue and get some relief from it! 🤕

**Comment by suskin** [comment]
Here are the PRs to update our stacks functionality:

* controller image: remove explicit image crossplane/provider-gcp#199
* controller image: remove explicit image crossplane/provider-aws#153
* controller image: remove explicit image crossplane/provider-azure#120
* controller image: remove explicit image crossplane/provider-rook#48
* behavior image: remove explicit image crossplane/stack-minimal-gcp#36
* behavior image: remove explicit image crossplane/stack-minimal-aws#10
* behavior image: remove explicit image crossplane/stack-minimal-azure#10
* behavior image: remove explicit image crossplane/sample-stack-wordpress#42

Here are the documentation updates:

* https://github.com/crossplane/crossplane/pull/1336

Here is the cli PR:

* https://github.com/crossplane/crossplane-cli/pull/45
