### ISSUE TITLE
Docker compose support for app deployments with managed services

### ISSUE THREAD

**Issue by prasek** [crossplane/crossplane#1415]
### Problem
Deploying Kubernetes apps often requires a steep learning curve and many app developers are already familiar with [Docker `compose`](https://docs.docker.com/compose/) as a simple way to standup apps locally. The [Kubernetes `kompose`](https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/) tool allows you to take a standard `compose` application and run it on a Kubernetes cluster using `kompose up` or to convert a `compose` application to a set of Kubernetes yaml files using `kompose convert`.

This works as long as you're using in-cluster data services (postgres, redis), but is missing the ability to deploy managed cloud services via the Kubernetes API, which is something that Crossplane supports today for an cloud providers like GCP, AWS, Azure, and more.

### What could Crossplane do to help?
Support Crossplane managed service provisioning in a Docker `compose` file, so I can easily modify the `compose` file I use for local app dev and deploy it into staging and production using cloud services like S3, RDS, and ElasticCache -- all with very minimal changes.

This would be similar to how managed service provisioning was added to [GitLab Auto Deploy Apps](https://gitlab.com/groups/gitlab-org/-/epics/1866) with a simple [`postgres.managed` option](https://gitlab.com/gitlab-org/charts/auto-deploy-app) and the option to use the default class of service, or to specify a `postgres.managedClassSelector` -- keeping the app dev experience simple, while allowing the infra operators the ability to create a catalog of managed services that app devs can easily consume.

**Comment by muvaf** [comment]
I think we have two options here:
* Add a top level field to [Compose spec](https://github.com/compose-spec/compose-spec/blob/master/spec.md).
* Have a compose in a Kubernetes YAML and inject necessary connection secret data to containers; similar to how we mount the connection secrets to pod.
* Deploy Crossplane as container together with a Kubernetes api-server, configure the managed resources in a file in host that will be mounted to that container and share connection secrets with another volume that other containers mount.


I think the first one is a really long-shot and the main reason is that for Crossplane the Kubernetes API is a must while Docker Compose does not necessarily care about Kubernetes or its API. So, it might be hard to get them to have a top level field that will work only if you deploy Docker Compose to a Kubernetes cluster.

The second one is easier and does not impose any change on the Compose Spec. In the Crossplane Composition design, `Composition` kinds are what resource classes are today but with more capabilities. The thinking is that while we have one kind `Composition` today, we'll expand this to `HelmComposition`, `KustomizeComposition`. I can see us having a kind like `DockerComposition` where we embed the docker-compose spec and have additional Crossplane resources. After the provisioning completes, Crossplane would mount the secrets to whatever pod that compose-spec deploys.

However, the second option only brings compose into Crossplane. What we'd like to achieve is to bring Crossplane to compose so that its user base can take advantage of Crossplane without Kubernetes.

The third option, while more complex, I think is the one that is most feasible. Instead of requiring an api-server, Crossplane would ship one in itself for its own use. It might not be very good UX since you deal with files and such but it'd do the job of enabling compose-users use Crossplane.

**Comment by resouer** [comment]
Just jump in to throw my 2 cent:

> This works as long as you're using in-cluster data services (postgres, redis), but is missing the ability to deploy managed cloud services via the Kubernetes API,

It sounds we are proposing a Compose user use Docker Compose deploy apps but write K8s YAML to provision cloud resources - this is the most weird thing I've heard in 2020 🙂

Another arguement it where is the biggest user base who are mostly developers and have strong need for cloud resources? I really doubt it's Docker Compose community. Serverless/FaaS/ACI/Fargate/CloudRun would make much more sense.

This isn't to say that we shouldn't have wider collaboration with non-k8s community; just that the initial idea seems not on right track.

**Comment by muvaf** [comment]
> It sounds we are proposing a Compose user use Docker Compose deploy apps but write K8s YAML to provision cloud resources

**Comment by muvaf** [comment]
> It sounds we are proposing a Compose user use Docker Compose deploy apps but write K8s YAML to provision cloud resources - this is the most weird thing I've heard in 2020

I'm not sure whether K8s YAML is wildly different than Compose YAML. Following is an example Compose YAML from spec doc:
```yaml
version: "3"
services:
  frontend:
    image: awesome/webapp
    ports:
      - "443:8043"
    networks:
      - front-tier
      - back-tier
    configs:
      - httpd-config
    secrets:
      - server-certificate

  backend:
    image: awesome/database
    volumes:
      - db-data:/etc/data
    networks:
      - back-tier

volumes:
  db-data:
    driver: flocker
    driver_opts:
      size: "10GiB"

config:
  httpd-config:
    external: true

secrets:
  server-certificate:
    external: true

networks:
  front-tier:
  back-tier:
```

If we go with the third option we can have a plugin-like thing to convert whatever format that they are most comfortable into K8s resource that will be deployed to the internal api-server. Adding `metadata` and `apiVersion` fields would be pretty simple.

But I agree that we'd want some user demand to validate the idea before making this investment.

**Comment by resouer** [comment]
> I'm not sure whether K8s YAML is wildly different than Compose YAML

I may be opinionated as I work on K8s :-) But it's weird and heavy burden in mind if I have to take care of two data models come from two different worlds, think about writing code with Python & Java at same time.

> K8s resource that will be deployed to the internal api-server

Seems off topic but I'm also not sure how this works. You should ship a single node K8s to make Crossplane run, no?

**Comment by muvaf** [comment]
> Seems off topic but I'm also not sure how this works. You should ship a single node K8s to make Crossplane run, no?

Crossplane and the api-server would run in one container in the composition and Crossplane would target that local api-server. Crossplane doesn't have to be in a pod or run in Kubernetes as long as a `KUBECONFIG` is provided. There would probably some intricacies along the way but it should be possible.

**Comment by resouer** [comment]
>  Crossplane doesn't have to be in a pod or run in Kubernetes as long as a KUBECONFIG is provided. 

I see. I feel it's more exciting to leave this "Crossplane as a Container" idea to Fargate/Cloud Run/ACI case instead of local/Docker Compose. Provision apps and cloud resources with K8s resource model where K8s is not even there.

**Comment by prasek** [comment]
> I feel it's more exciting to leave this "Crossplane as a Container" idea to Fargate/Cloud Run/ACI case instead of local/Docker Compose.

@resouer Yes, that's a great idea too! For Crossplane + Docker Compose the idea is that the platform ops team could provide a catalog of available managed services (as Crossplane/k8s yaml), that app devs could provision by name or matchSelector from within a Compose file without having to write k8s yaml at all. Just trying to meet people where they are, esp. for the app dev users who may not want to invest heavily in learning k8s.

Given the popularity of https://github.com/kubernetes/kompose, adding managed service provisioning to that seems like a natural extension.

**Comment by resouer** [comment]
@prasek Just several inputs based on real-world use cases on our side.

> Given the popularity of https://github.com/kubernetes/kompose, adding managed service provisioning to that type of workflow seems like a natural extension

On Alibaba Cloud, the main motivation our customers use kompose is to migrate their legacy Swarm applications to Kubernetes and very few of them consume cloud service (e.g. they deploy mysql container instead of consuming Alibaba Cloud RDS). And due to lack of stickiness to cloud services, Alibaba has officially shutdown compose and kompose support for a while.

> app dev users who may not want to invest heavily in learning k8s.

Crossplane has great advantage to solve this problem by building a developer centric abstraction with K8s resource model.

**Comment by negz** [comment]
We haven't seen much demand from the community for this integration, so I'm going to close this issue. We can revisit this if and when we see folks asking for the feature.
