### ISSUE TITLE
Use v1 CustomResourceDefinitions

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#1435]
`v1beta1` `CustomResourceDefinitions` are [scheduled for removal](https://github.com/kubernetes/apiextensions-apiserver/blob/99685ba23021e88fc9a771f029157b348fd92bab/pkg/apis/apiextensions/v1beta1/types.go#L380) in the `v1.19` cycle. We should start using `v1` prior to the release of `v1.19`, which is [tentatively scheduled](https://github.com/kubernetes/sig-release/pull/1058) for Tuesday, August 25, 2020.

**Comment by muvaf** [comment]
I think we need to decide on a version interval for supported Kubernetes versions. For example, if `v1.CustomResourceDefinition` doesn't work in k8s `1.14`, I'd not use it since 1.14 is still widely used as default by cloud providers. But if the removal will render our CRDs useless in 1.19, we should document that Crossplane is not compatible with 1.19.

**Comment by negz** [comment]
Does upgrading our core providers to use v1 CRDs fall within the scope of this issue? If safe to do so it would be great to enable defaulting as part of those PRs - I believe we could use it instead of an initializer to handle the default `providerConfigRef`, `deletionPolicy`, and perhaps some other things.

**Comment by hasheddan** [comment]
@negz yes I was thinking they would be encompassed by this issue. Agreed on `providerConfigRef` and `deletionPolicy`, I wonder if there will be any for individual managed resources as well. We can always update to v1 then switch to use defaulting to any fields that we currently manually default to later if needed.

**Comment by negz** [comment]
I believe this is now done.

**Comment by negz** [comment]
Scratch that - we also need to use v1 CRDs in our providers.

**Comment by negz** [comment]
Alright, this is actually done now!
