### ISSUE TITLE
Continuous update of remote resources causes Azure LB provisioner to fail 

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1446]
### What problem are you facing?

When I try to install Wordpress, I see the following events in the `wordpress` Service that is created in the remote cluster:

```
  Normal   EnsuringLoadBalancer        19s (x2 over 84s)  service-controller  Ensuring load balancer
  Normal   EnsuredLoadBalancer         19s                service-controller  Ensured load balancer
  Warning  CreatingLoadBalancerFailed  19s                service-controller  Error creating load balancer (will retry): not persisting update to service 'muvafwp/wordpress' that has been changed since we received it: Operation cannot be fulfilled on services "wordpress": the object has been modified; please apply your changes to the latest version and try again
```

This doesn't happen all the time but I've seen it happen a few times. Workaround is simply delete the service in the remote cluster, wait for a new one to be created by `KubernetesApplicationResource` controller and hope it works this time.

### How could Crossplane help solve your problem?

Unless the values that exist in `KubernetesApplicationResource` did not change, the controller should not issue an update. If it's a `PATCH` operation, we need to check whether no-op patch increases the resource version. If it increases, then we need to check whether there is a diff and only then issue the patch.

This can also be solved in Azure LB controller side if they issued a `PATCH` instead of usual update but we don't have control over that and fix in our side is good to have in any case.

**Comment by hasheddan** [comment]
@muvaf were you able to observe the actual update that was being made on each reconciliation?

**Comment by muvaf** [comment]
@hasheddan No, I didn't debug the controller deeply.

**Comment by muvaf** [comment]
@hasheddan feel free to assign this to yourself since you're working on it.

**Comment by hasheddan** [comment]
@prasek @muvaf just an update here. I think the issue here may not be that the loadbalancer is not actually getting created, but rather that it is just not able to update the status of the `Service` because we are in fact bumping the resource version on ever reconcile. This is due to the fact that we do not "late initialize" our KAR templates, so nested arrays appear to not match when values are added. Specifically in the `Wordpress` scenario, we see the following:

```
&unstructured.Unstructured{
  	Object: map[string]interface{}{
  		"apiVersion": string("v1"),
  		"kind":       string("Service"),
  		"metadata": map[string]interface{}{
  			"annotations":       map[string]interface{}{"KubernetesApplication.workload.crossplane.io/name": string("testme-service"), "KubernetesApplication.workload.crossplane.io/namespace": string("default"), "KubernetesApplication.workload.crossplane.io/uid": string("b52c37bb-4493-4af7-8691-de93ca253c50")},
- 			"creationTimestamp": string("2020-05-06T13:48:10Z"),
  			"labels":            map[string]interface{}{"app": string("wordpress")},
  			"name":              string("wordpress"),
  			"namespace":         string("testme"),
- 			"resourceVersion":   string("1713"),
- 			"selfLink":          string("/api/v1/namespaces/testme/services/wordpress"),
- 			"uid":               string("39408b98-8fa0-11ea-b2f9-de479dba5b71"),
  		},
  		"spec": map[string]interface{}{
- 			"clusterIP":             string("10.0.31.190"),
- 			"externalTrafficPolicy": string("Cluster"),
  			"ports": []interface{}{
- 				map[string]interface{}{
- 					"nodePort":   int64(32483),
- 					"port":       int64(80),
- 					"protocol":   string("TCP"),
- 					"targetPort": int64(80),
- 				},
+ 				map[string]interface{}{"port": int64(80)},
  			},
  			"selector":        map[string]interface{}{"app": string("wordpress")},
- 			"sessionAffinity": string("None"),
  			"type":            string("LoadBalancer"),
  		},
- 		"status": map[string]interface{}{
- 			"loadBalancer": map[string]interface{}{"ingress": []interface{}{map[string]interface{}{"ip": string("138.91.138.6")}}},
- 		},
  	},
  }
```

The merge patch is trying to make an update here because it thinks the port is not being represented, while, in reality, it is just having extra values added to the port object.

**Comment by hasheddan** [comment]
We may be able to re-use this pattern https://github.com/crossplane/crossplane/blob/2c02b534d5fb71273012bfdcd09571fba071c43a/pkg/workload/apply.go#L44

**Comment by muvaf** [comment]
> we are in fact bumping the resource version on ever reconcile.

In theory, this shouldn't be much of a problem as long as other controller is able to handle it but it seems Azure LB controller can't and I can't really blame it since repetitive no-op updates are no good in any case.

> We may be able to re-use this pattern 

In the case of `KubernetesApplication`, the type of the object is known, so we're able to implement a custom logic for its local merge. In remote cluster scenario, the template could be of type anything. So, I'm not sure the solution would be as straight-forward.

However, I can see how it could be possible to handle the arrays by scanning for them recursively and make the change in-place, then issue an `Update`. Something like:
```
GET the resource from remote into _current_
Perform a depth-first search over the fields of _template_(map[string]interface{}) that we have:
  if an object is of type []interface{}:
    find the corresponding array in the _current_, scan the array and look for equality between the objects. If ours exist, then all good. If not, add the object to the array.
```

It probably won't be as straight-forward but this arrays in patch problem is something we have in other places, too, like managed resources though that's a bit easier since structs are known beforehand. I've flirted with [the idea of three-way merges](https://crossplane.slack.com/archives/CKXQHM7U3/p1585759338141200?thread_ts=1585759338.141200) in the past but didn't investigate much further.

As a short-term solution, maybe we can just `Create` and only get the updates of `status` from the remote cluster to update the local KAR so that at least the happy path works, where there is no update on the templates in KARs.

**Comment by hasheddan** [comment]
Adding some thoughts after doing additional research:

Currently we are doing a [merge patch](https://kubernetes.io/docs/tasks/run-application/update-api-object-kubectl-patch/#use-a-json-merge-patch-to-update-a-deployment) as opposed to a [strategic merge patch](https://kubernetes.io/docs/tasks/run-application/update-api-object-kubectl-patch/#use-a-strategic-merge-patch-to-update-a-deployment) when updating remote resources. This means that when updating a list we must specify the entire list and we will replace it completely. Alternatively, with a strategic merge patch, a list may be merged, but elements in the list may also be replaced. This is decided based on the **merge patch key** and the **patch strategy**.
  - If an object in a list *specifies a merge patch key and a `patch strategy: merge`*, an object that matches on that key will lead to replacement (i.e. only the new object will exist in the list).
  - If an object in a list *specifies a merge patch key and a `patch strategy: merge`*, an object that does not match on that key will be merged into the list (i.e. both the existing object and the new object will exist in the list).
  - If an object in a list *does not specify a merge patch key*, the list will be replaced with the new list because it will fall back on a `patch strategy: replace` by default.

The [`ServicePort` type](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#servicespec-v1-core) has a `patch strategy: merge` and a `merge patch key: port`, so whether we use a `merge patch` or a `strategic merge patch`, we will still constantly replace the list of ports on the `Service` because the port in the `KubernetesApplicationResource` matches the port in the remote `Service`.

This brings me to [Server Side Apply](https://kubernetes.io/docs/reference/using-api/api-concepts/#server-side-apply) (SSA). SSA allows controllers (or any object modifier) to establish management of fields in an object. If a party attempts to modify a field in an object and another party is the current manager of that field, it will result in a [Conflict](https://kubernetes.io/docs/reference/using-api/api-concepts/#conflicts). There are three options a client can take when encountering a conflict:
- Overwrite value, become sole manager.
- Don’t overwrite value, give up management claim.
- Don’t overwrite value, become shared manager.

There are also additional fields that allow for specifying a more robust [merge strategy](https://kubernetes.io/docs/reference/using-api/api-concepts/#merge-strategy). For example, an entry in a list may specify multiple keys that uniquely identify it instead of just the `merge patch key` ([this PR](https://github.com/kubernetes/community/pull/4218) has a good description of some of these changes). However, we really cannot hope to ever solve the case of editing individual fields in an object in a list. Even though we can reason about what equality means, I do not think we can arbitrarily determine whether an update to an "equal" item in a list means that it should be replaced or merged. In fact, determining equality means that we intend to replace the item with our copy.

The area where SSA may help us is if we can basically say that we won't touch fields that have been modified by a party in the remote cluster (i.e. KAR controller always gives up management claim on conflict). Therefore, we are basically saying that we will allow you to update fields from the control cluster that are set because you specified them, but you are not allowed to update fields where you specified them then a controller in the remote cluster modified them. This still seems like a pretty brittle model, but it could theoretically work.

**Comment by muvaf** [comment]
> The ServicePort type has a patch strategy: merge and a merge patch key: port, so whether we use a merge patch or a strategic merge patch, we will still constantly replace the list of ports on the Service because the port in the KubernetesApplicationResource matches the port in the remote Service.

If the API type is properly annotated by a key, we could possibly treat the array like a map in the local and, do the manipulations as necessary submit the new object. However, I can't think of a way to retrieve the patch key of that specific struct from the remote cluster.

@hasheddan were you able to try to use strategic merge patch without any extra logic just to see how it reacts if we change nothing else?

> This brings me to Server Side Apply (SSA). SSA allows controllers (or any object modifier) to establish management of fields in an object. If a party attempts to modify a field in an object and another party is the current manager of that field, it will result in a Conflict.

That's my inclination, too. I don't think SSA would be of help much since it's only about ownership of the fields. Our problem seems to be more related to the mechanics of the `PATCH` operation itself.

> The area where SSA may help us is if we can basically say that we won't touch fields that have been modified by a party in the remote cluster (i.e. KAR controller always gives up management claim on conflict)

Is this also true for fields on the elements of the array? Like does the server marks `spec.ports[1].protocol` owned by X and `spec.ports[0].protocol` owned by Y?

**Comment by hasheddan** [comment]
> were you able to try to use strategic merge patch without any extra logic

I have not tried this out but will give it a shot today 👍 

> Is this also true for fields on the elements of the array?

I don't think so, but I am not certain. The [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/0006-apply.md#lists) seems to suggest that party that added the item to the list owns the entire item:

"Items of an associative lists are owned by the person who applied the item to the list."

**Comment by hasheddan** [comment]
Followed up in k8s slack on question about granular field management above. For additional reference, here are the relevant tags on `ServicePort`:

```
// +patchMergeKey=port
// +patchStrategy=merge
// +listType=map
// +listMapKey=port
// +listMapKey=protocol
Ports []ServicePort `json:"ports,omitempty" patchStrategy:"merge" patchMergeKey:"port" protobuf:"bytes,1,rep,name=ports"`
```

https://github.com/kubernetes/kubernetes/blob/6abb8ebd190b0ba0d1e9de2063979406066d8cc6/staging/src/k8s.io/api/core/v1/types.go#L3872

**Comment by prasek** [comment]
@hasheddan this issue doesn't repro for me after moving from Kubernetes 1.14.8 to 1.15.10 for AKS: https://github.com/crossplane/stack-azure-sample/pull/25

**Comment by negz** [comment]
It seems like this might be solved, and we're also planning to remove KubernetesApplication, so I think we can close this.
