### ISSUE TITLE
Validate compositions via webhook

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1476]
### What problem are you facing?

You can put any valid YAML under `Composition.spec.to` array. However, they have to be registered on the api-server, which means they can be validated against their registered OpenAPIv3 schemas.

### How could Crossplane help solve your problem?

Implement an admission webhook that will validate every template in `Composition` resource with correct OpenAPIv3 schemas.

**Comment by wonderflow** [comment]
I think all validation work (including https://github.com/crossplane/oam-kubernetes-runtime/issues/14) can all be done by this admission webhook.

**Comment by negz** [comment]
I've deduped https://github.com/crossplane/crossplane/issues/1497 into this issue. So we should validate both:

* The base templates in a composition.
* The fieldpaths in the patches array.

**Comment by negz** [comment]
We actually already have some Composition validation code, for example:

https://github.com/crossplane/crossplane/blob/9850b98edc3362c41f66997a12d7b3adb916eace/internal/controller/apiextensions/composite/composed.go#L107

Currently this code (i.e. `RejectMixedTemplates` and `RejectDuplicateNames`) lives in the XR reconciler, and will fail to reconcile any XR that uses an invalid Composition. This was the best option available at the time, but is not ideal because:

* The person who created the XR (or claim) may not be the person who wrote the Composition. We should tell the person who wrote the Composition that it was invalid - not the person who later tried to use it.
* With CompositionRevisions we're going to make an invalid CompositionRevision of the invalid Composition, then later tell folks that revision is (and will always be) invalid when they actually try to use it.

It would be much better to have an admission control webhook run these validation checks and reject the creation of an invalid Composition in the first place. I think this could be a good "MVP" Composition validation webhook, because running these existing checks in a webhook should be easier to do than validating the schema of composed resource templates.

**Comment by phisco** [comment]
Hello all, I've been putting some thought into this issue and I do agree it makes sense to move the current validation logic to a validating webhook and that it would be really useful to also validate bases and fieldpaths.

However, I didn't find a way to do so without querying the API server. The two options that came to my mind were either to server-side dry-run apply resources leveraging the existing logic in the `APIDryRunRenderer` or to lazily get and then cache the schemas for all the resources encountered. Still, any of these two options could lead to increased latencies and/or requests amplification. Client-side dry-run is not actually checking anything at all, so it's not an option.

Even if it would be obviously easier to implement, I would discard the server-side dry-run approach, as it would be the worst option for both latency increase and requests amplification. So, either we go with some lazy getting and caching of schemas from the API server and validate using those or we accept not to validate them in a webhook and improve the error handling and propagation if needed.

What do you all think? Did you have other options in mind?

**Comment by turkenh** [comment]
It is worth clarifying that validating a composition resource, and the individual composed resources are separate, hence have different requirements.

**Validating Individual Composed Resources:**  This is something we already have today with `APIDryRunRenderer`, where XP controllers run a dry run after rendering composed resources with all the patches etc. 
- Needs a claim or composite.
- Runs periodically in each reconcile.

**Validating the `Composition` Resource:** This should happen during the creation/update of the Composition resource and is something we lack today.
- No claim or composite is available yet. So, getting the final shape of individual composed resources is not possible.
- Only to be done during the creation of the composition or whenever an update is made.

> Still, any of these two options could lead to increased latencies and/or requests amplification.

Considering this validation not being something to be done periodically in each reconciliation (assuming the configuration package reconciler is not triggering it as long as there is a change in a composition), I would be less worried about the performance impacts caused by a server-side dry run.

**Comment by phisco** [comment]
FYI: The design document for Compositions' validation was finally merged (#3756), and we also merged the first step toward implementing what's proposed there, #3921. This first PR is introducing the Webhook itself, which is now going to be created if `webhooks.enabled` is set to `true` in the Helm Chart, and is introducing "logical validation", enforcing that the Composition is well defined per se, you can see all the details in the [PR](#3921).
In following PRs we are going to introduce Validation using available schemas, therefore checking for example that paths in `to/fromFieldPaths` are actually valid and other things. See the design document for more details and let us know any feedback you might have! 🙏

**Comment by jeanduplessis** [comment]
With the foundation for composition validation having landed in 1.12 and an open issue to track maturing it, https://github.com/crossplane/crossplane/issues/3991, I'll close this issue now.
