### ISSUE TITLE
Recreate the composed resource if it is deleted

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1478]
### What problem are you facing?

If you delete a composed resource, controller won't recreate it.

### How could Crossplane help solve your problem?

Make controller create it 🤷

**Comment by negz** [comment]
I thiiiink this might have been implemented by accident during some previous refactoring of the XR reconcile - at a glance it seems like this is the behaviour we'd see today.

**Comment by negz** [comment]
Yeah, this appears to now be the case. I confirmed by applying the GCP configuration and claim from the composition getting started guide, deleting the resulting `CloudSQLInstance` and confirming that it was recreated:

```console
$ kubectl delete cloudsqlinstance --all                              
cloudsqlinstance.database.gcp.crossplane.io "my-db-vl4xn-plvg8" deleted

# A minute or two later...

$ kubectl get cloudsqlinstance
NAME                READY   SYNCED   STATE   VERSION        AGE
my-db-vl4xn-plvg8   False   False            POSTGRES_9_6   96s
```

In this instance I expect the newly created database will fail since GCP won't let us reuse the exact same name (which persists because it was stored as a reference on the XR), but in general I think this is the behaviour we want.
