### ISSUE TITLE
Consider blocking remote cluster deletion on extant resources

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#1484]
### What problem are you facing?

Some hosted k8s providers have issues with leaking resources created in response to Kubernetes objects being created in a cluster. For instance, GKE seems to leak network load balancers that are created for a `Service` in a cluster (ref: https://github.com/kubernetes/kubernetes/issues/39420). When a `GKECluster` resource is deleted in this scenario, resources can be left behind that Crossplane is unaware of and may block deletion of other resources (such as a `Network`) that Crossplane is aware of.

### How could Crossplane help solve your problem?

It would be difficult for Crossplane to be in the business of cleaning up provider resources that it did not provision itself. However, the Kubernetes cluster scenario is a bit easier because Crossplane is aware of the resources in that cluster that led to creation of other resources on the provider (like the load balancer). Because of this, Crossplane could address this problem in one of two ways:

1. Block cluster deletion on extant `KubernetesApplications` that are scheduled to it. This is a difficult solution as a Kubernetes cluster managed resource is not aware on its own of KAs that are scheduled to it. Currently we consider losing connection to a cluster successful clean-up for a deleted KA and its KAR's. We could potentially have the KA controller set finalizers on the `KubernetesTarget` / `KubernetesCluster` resources, but this chain of ownership could get messy.

2. Another solution would be to clean everything out of a remote k8s cluster before deleting it. This should be okay in the general case as a remote cluster that gets deleted should not care whether all of the resources inside of it are deleted beforehand. We could even start out by restricting this operation to just deleting objects like `Service` that are known to create external infrastructure.

Related issues:
- Azure: https://github.com/crossplane/app-wordpress/issues/48
- GCP: https://github.com/crossplane/app-wordpress/issues/58
- AWS: https://github.com/crossplane/provider-aws/issues/201
- AWS: https://github.com/crossplane/provider-aws/issues/210

**Comment by hasheddan** [comment]
This issue provides even more context on what happens here: https://github.com/kubernetes/ingress-gce/issues/136

**Comment by muvaf** [comment]
> Another solution would be to clean everything out of a remote k8s cluster before deleting it. This should be okay in the general case as a remote cluster that gets deleted should not care whether all of the resources inside of it are deleted beforehand. We could even start out by restricting this operation to just deleting objects like Service that are known to create external infrastructure.

@hasheddan I agree with your sentiment you mentioned in the meeting about this idea, i.e. we can't wait for deletions to succeed so this will only let the remote cluster know that things should be deleted, which will decrease the probability of a leak since at least a `Delete` call is made. It won't have any bad effects probably, since if the cluster is deleted you'd most probably want the resources in the cluster to be deleted as well. But it's also against the high fidelity goal, i.e. AWS could've done that when you click `Delete Cluster` in the console [but it doesn't](https://docs.aws.amazon.com/eks/latest/userguide/delete-cluster.html). It does leak the external resources. So, I'm not sure.

IMO, whatever the entity deployed the resources should take care of their deletion. In Wordpress or sample stacks cases, it's [templating-controller](https://github.com/crossplane/templating-controller/issues/17). In other manual cases, it's the user who would take care of this behavior.

**Comment by muvaf** [comment]
Fixed by https://github.com/crossplane/crossplane/pull/1567 , https://github.com/crossplane/crossplane/pull/1556 and https://github.com/crossplane/templating-controller/pull/18
