### ISSUE TITLE
Create admission webhook controller for validation

### ISSUE THREAD

**Issue by wonderflow** [crossplane/crossplane#1509]
### What problem are you facing?

Now we have some validating issues:

1. https://github.com/crossplane/oam-kubernetes-runtime/issues/14
2. https://github.com/crossplane/crossplane/issues/1476
3. https://github.com/crossplane/crossplane/issues/1497

and more...

All of them can be fixed if we have an [admission webhook](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/) to validate YAML.

### How could Crossplane help solve your problem?

Crossplane can have a separate webhook controller to do these validation. I've done it before [oam-dev/admission-controller](https://github.com/oam-dev/admission-controller) for OAM v1alpha1. I'm glad to update that project or create a new for crossplane to fix these validating issues.

What about your ideas? @negz @hasheddan

**Comment by negz** [comment]
@wonderflow What is the UX like these days for setting up the admission controller? It's been a long time since I wrote an admission control webhook, but I recall it was a little painful to get it working properly with the API server.

It seems like we should use the controller-runtime support for webhooks, since our project is build on controller-runtime; https://book.kubebuilder.io/cronjob-tutorial/webhook-implementation.html.

**Comment by wonderflow** [comment]
>  the UX like these days 

What is the `UX` here mean?

**Comment by leopoldxx** [comment]
> > the UX like these days
> 
> What is the `UX` here mean?

User experience ?

**Comment by ryanzhang-oss** [comment]
> @wonderflow What is the UX like these days for setting up the admission controller? It's been a long time since I wrote an admission control webhook, but I recall it was a little painful to get it working properly with the API server.
> 
> It seems like we should use the controller-runtime support for webhooks, since our project is build on controller-runtime; https://book.kubebuilder.io/cronjob-tutorial/webhook-implementation.html.

You can take a look at  "addon-oam-kubernetes-local" repro which comes with an admission control wehbook.  We can't use kubebuilder directly as it modifies the api go struct type which in our case is in another repro.

I created a simple framework on top of the controller-runtime framework to get around that problem. All one needs to do now is to implement a struct with a pre-defined function.

**Comment by muvaf** [comment]
A while ago, I've opened https://github.com/crossplane/crossplane/issues/1152 for a one-pager design about webhooks in Crossplane. It's needed in several places as this issue mentions but I believe some building blocks that will pave the way for all components in Crossplane ecosystem would make the implementations more streamlined and reliable. Off the top of my head, I think 1 certificate in Crossplane to be used for TLS would make it much easier for other components to implement webhooks without the overhead of handling TLS with api-server communication.

**Comment by wonderflow** [comment]
@muvaf  Your design is exactly what I want to do, and I found it was created several months ago. What blocks it to come true?

**Comment by muvaf** [comment]
@wonderflow It's about prioritization and almost all use cases we had for webhooks have been about validation, which is a nice-to-have but not a must, really. In most of those cases, Crossplane returns error in conditions and/or fires an event that's shown on `kubectl describe`.

However, I believe CRD update/versioning https://github.com/crossplane/crossplane/issues/1584 is a must for `v1beta1` and above, although we haven't had a `v1beta2` CRD yet. 

I'm personally passionate about this as it makes UX much better. We'll talk about it in this sprint planning but I can't make promises because of the reasons above.

**Comment by wonderflow** [comment]
@muvaf Thanks, Now I'm totally understood, I think we can setup this admission webhook controller together.

**Comment by muvaf** [comment]
Closing in favor of https://github.com/crossplane/crossplane/issues/1152
