### ISSUE TITLE
Add Crossplane support to the Quay operator

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1582]
### What problem are you facing?

Crossplane is [available](https://operatorhub.io/operator/crossplane) on OperatorHub. Many of its contemporary operators could make use of Crossplane in order to deploy and managed their infrastructure resources.

### How could Crossplane help solve your problem?

We'd like to investigate how it might look for an existing operator to optionally support using Crossplane to manage their infrastructure needs, while also allowing the operator to deploy their infrastructure in-cluster as most do today. The [Quay operator](https://operatorhub.io/operator/quay) has been suggested as a good operator to investigate.

This issue could be considered complete after we've produced an R&D one pager, or we could take it all the way to a PR against the Quay operator if doing so seems reasonable.

**Comment by muvaf** [comment]
I believe it's likely that we'll come up with a list of requirements as the interface of the operator. For example, we'll need it to write any credentials to a secret and give us the reference to that secret somehow. Or expose a `Ready` condition so that we know when the resource is ready.

There are somethings we can do in Crossplane as well to make it more flexible for integration. For example, right now `Composition` assumes that the secret reference should be under `spec.writeConnectionSecretRef` but we can keep this as default and allow a fieldpath to be given in `Composition.to.connectionSecretRefFieldPath` so that it's easier to integrate an operator with low/no code change.

**Comment by hasheddan** [comment]
@krishchow would you say this issue is complete?

**Comment by krishchow** [comment]
@hasheddan Yeah, we can mark this as completed :)

**Comment by jbw976** [comment]
Great work on getting ramped up on Crossplane concepts, getting the quay operator updated, and becoming a contributor to Crossplane also @krishchow! really glad to have you here! 💪 🙇‍♂️
