### ISSUE TITLE
Crossplane binaries are not being published

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#1688]
### What happened?

When searching for Crossplane binaries, which are typically consumed by the corresponding Docker image in a Helm chart, I noticed the binaries themselves are not actually being published at https://releases.crossplane.io/.

### How can we reproduce it?

Visit https://releases.crossplane.io/ and look through the `bin` directories.

### What environment did it happen in?

Binaries appear to be missing for all Crossplane versions.

**Comment by jbw976** [comment]
Good idea @hasheddan, i've assigned this to me to look further into the s3 bucket permissions

**Comment by hasheddan** [comment]
@jbw976 any updates here?

**Comment by jbw976** [comment]
I took a look at the bucket permissions today and the crossplane.releases bucket was missing bucket policy that allows public access to (only) list and get objects like the crossplane.charts bucket has.  I have updated the policy to match the charts one and confirm that the following now works:

* manual download: `wget https://releases.crossplane.io/alpha/v0.12.0/bin/linux_amd64/crossplane`
* browse and download in browser: https://releases.crossplane.io/alpha/v0.12.0/bin/linux_amd64/
  * `crossplane` is showing as a binary now, not a folder, and clicking it downloads it OK

I'm going to close this issue now since it has been fixed :)

**Comment by hasheddan** [comment]
Thanks so much @jbw976! 🙌
