### ISSUE TITLE
Consider breaking Crossplane API types into separate repo

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#1708]
### What problem are you facing?

Some projects may want to consume Crossplane API types without taking a dependency on `crossplane/crossplane`, which currently contains both the Crossplane API types as well as controllers to manage them and their related functionality. `crossplane/crossplane` should typically not be depended upon as a library.

### How could Crossplane help solve your problem?

Breaking the Crossplane API types and any libraries (such as generated clients) that are strictly used for interacting with those types could be moved to an `api` repo and the generated CRDs could be vendored by `crossplane/crossplane`. similar to what is currently done with [OAM API types](https://github.com/crossplane/crossplane/blob/365a7c3ad900ff6cf8da646fedb99e894e07c41e/apis/generate.go#L29). This would also allow for all Crossplane controllers and related logic to be moved into an `internal` directory, meaning they cannot be depended upon by other projects.

**Comment by negz** [comment]
Thanks for raising this @hasheddan! It seems like this could be part of a larger question around how we organize our codebase as the project grows.

If you think of our project as a series of Go modules, I think you can divide those modules into roughly two categories:

1. Those used to build a binary. e.g. `github.com/crossplane/crossplane` and `github.com/crossplane/provider-aws`.
1. Those containing packages shared by multiple category 1 modules. e.g. `github.com/crossplane/crossplane-runtime`.

Category 1 modules currently define the API types they expose, which means a category 1 module needs to depend on another category 1 module if they share the same API types. Providers depending on `github.com/crossplane/crossplane` for the deprecated resource claim types is an example of this.

I've personally developed a mental model that is roughly "package APIs that I'm willing to commit to support publically go in crossplane-runtime". When I create a package in crossplane-runtime I tend to be more careful about breaking API changes; I'm more likely to consider that some unknown party might be using my package's API. I don't tend to consider this for category 1 modules though - I assume no one is importing and using the packages under `github.com/crossplane/crossplane/pkg`, except for other packages in that dir or `github.com/crossplane/crossplane/cmd`. This is why I put the `fieldpath` package in crossplane-runtime despite it only being consumed from crossplane, for example.

I think it would be a good idea to consider renaming the `pkg` directory of all our category 1 modules to [`internal`](https://dave.cheney.net/2019/10/06/use-internal-packages-to-reduce-your-public-api-surface), to _enforce_ that the packages each category 1 module publishes may only be consumed by that module. [Hyrum's Law](https://www.hyrumslaw.com/) states that we'll end up with folks depending on those implementation details if we don't.

This may obviate the need to break the API types out into a distinct package - we'd know that if someone was depending on `github.com/crossplane/crossplane` it could only be for the API types, which should have a fairly rigorous compatibility contract anyhow. This is what `github.com/projectcontour/contour` does - only their API packages are public.

I think there's probably some pros and cons of breaking out the API package. @hasheddan had some good reasons not to that I'll let him weigh in on.

If we do want to assume that it's okay for folks to take a dependency on `github.com/crossplane/crossplane` - at least for the API types - we may want to consider whether we should merge crossplane-runtime back into that module. I could imagine that someone trying to build a controller that consumed Crossplane API types running into diamond dependency issues, because they'd probably have a direct dependency on crossplane-runtime as well as a transitive one via crossplane.

**Comment by negz** [comment]
In https://github.com/crossplane/crossplane/issues/1085 we considered something similar to this, though in that case the rationale was a little stronger given we were discussing the resource claim API types which are defined by the `github.com/crossplane/crossplane` but are not consumed by that module.

**Comment by negz** [comment]
Some prior art for larger, more complex (multi-module) projects breaking their API types out into a distinct module:

* https://github.com/kubernetes/api
* https://github.com/istio/api

**Comment by muvaf** [comment]
If we merge all into `crossplane/crossplane` and make the high level controllers `internal`, that'd be a nice simplification and for the people who'd like to use crossplane high level controllers, for some reason, it's fair to let them ask for it. 

Though we have to keep in mind that putting everything into `crossplane/crossplane` means that Crossplane will have opinions about which go module versions they can use in a sort of big way(I believe the `import` made in `internal` still affects the versions of modules during import by another module). For example, even if I'd like to import only an API type, I have to bear the cost of additional inflexibility brought by Crossplane's module versions. Though most of our modules are from Kubernetes project, I can see that for some use cases Crossplane could make it harder for people to manage breaking changes.

For example, we'd potentially have opinion about the versions of the following modules:
```
# crossplane-runtime
github.com/crossplane/crossplane-tools v0.0.0-20200219001116-bb8b2ce46330
github.com/go-logr/logr v0.1.0
github.com/google/go-cmp v0.4.0
github.com/hashicorp/go-getter v1.4.0
github.com/pkg/errors v0.9.1
k8s.io/api v0.18.6
k8s.io/apiextensions-apiserver v0.18.6
k8s.io/apimachinery v0.18.6
k8s.io/client-go v0.18.6
sigs.k8s.io/controller-runtime v0.6.2
sigs.k8s.io/controller-tools v0.2.4
sigs.k8s.io/yaml v1.2.0

# specific to crossplane/crossplane
github.com/docker/distribution v2.7.1+incompatible
github.com/evanphx/json-patch v4.5.0+incompatible
github.com/ghodss/yaml v1.0.0
github.com/google/uuid v1.1.1
github.com/onsi/gomega v1.8.1
github.com/opencontainers/go-digest v1.0.0-rc1 // indirect
github.com/spf13/afero v1.2.2
golang.org/x/net v0.0.0-20200202094626-16171245cfb2
gopkg.in/alecthomas/kingpin.v2 v2.2.6
k8s.io/utils v0.0.0-20200324210504-a9aa75ae1b89
```

Looking at `crossplane-runtime`, I can see that having a separate `crossplane/api` and let people import it would not be much different than moving APIs to `crossplane-runtime` because in both cases, the imported modules are pretty similar so in all cases, we'll affect their module version list with that list. If we merge all, then the ones coming from `crossplane/crossplane` are a bit more invasive and we'd have to be more careful about the dependencies we add. Do you know whether the modules that are used only in `internal` affect the `go.sum` of other projects who import that module? If they don't, then merging all into `crossplane/crossplane` would be same with moving APIs into `crossplane-runtime` from versioning perspective but also have the simplification advantage. Otherwise, moving APIs into runtime (which already has some) seems like a safer bet to me. `crossplane/api` seems like the safest but that could be too conservative as runtime doesn't really have that many different modules imported anyway.

**Comment by johnpemberton** [comment]
Just to try and add a bit more weight to this... we're working on an internal PaaS solution, whereby we define our own simplified CRDs for things like RDS, so end users don't need to worry about things like security groups and subnet groups, and we can enforce standards like encryption at rest etc..   

Our initial approach was to use our kubernetes operator (kubebuilder based) to take the CRs that our end users define and translate them into Crossplane CRs.   However, having to pull in the entire crossplane package (and all of its dependencies) caused us dependency issues - and also leads to pulling in packages we don't require which bloat our operator, so we needed to abandon that approach.   

If crossplane were to essentially package the DTO / API layer separately so we could pull this in as a dependency without the rest of the boat, this wouldn't be a problem.   

As it stands, we've had to take a less optimal approach and template the crossplane CRs in our CI/CD pipelines, which is not ideal.  We're essentially just templating yaml as opposed to working directly with the objects that the yaml represents.

**Comment by negz** [comment]
@johnpemberton Can you elaborate on what types of Crossplane CRs your operator is creating? Are you creating managed resources (things like `RDSInstance`) directly, or are you using Crossplane's Composition functionality to define your own simplified CRDs (i.e Crossplane Composite Resources, or XRs)?

**Comment by johnpemberton** [comment]
> @johnpemberton Can you elaborate on what types of Crossplane CRs your operator is creating? Are you creating managed resources (things like `RDSInstance`) directly, or are you using Crossplane's Composition functionality to define your own simplified CRDs (i.e Crossplane Composite Resources, or XRs)?

So we have our own independent CRDs for things like RDS/S3/Elasticache.   They are very simple and hide the underlying complexities from the end user engineering teams that use our platform, and enforce security, snapshots etc.  i.e. they don't need to know about subnet groups, and they can't have unencrypted things etc.   Plus we want to add additional features such as grafana dashboards and prometheus alerts for those resources out of the box, which are completely outside of Crossplane's remit. 

We then translate our simplified CRs into Crossplane CRs.   As I said, we wanted to use our operator to do this translation, but having to pull in the entire Crossplane golang package into our operator code, when we only really need an API package was a blocker due to dependency issues, so we ended up doing the translation outside of our operator and just throw Crossplane CRs directly at K8s via Flux. 

We've used our operator to implement our desired approach with other tech, such as Elasticsearch (ECK), by translating our own ES CRs into ECK CRs.  That was a lot cleaner as they expose a separate golang API package that we could import, which is essentially just the API.  We just import `github.com/elastic/cloud-on-k8s/pkg/apis/elasticsearch/v1beta1`.   
If we could do similar with Crossplane, it would make our lives a lot easier as we could work with the crossplane types directly in our operator golang code, rather than messing about templating yaml...   admittedly we're all yaml engineers now :)

Hope that makes sense @negz

**Comment by negz** [comment]
@johnpemberton The problem you're solving with your simplified, opinionated CRs that are translated into Crossplane "managed resources" (i.e. the CRs from something like provider-aws) sounds _exactly_ like the project our Composition functionality is intended to solve. In fact, we really optimise for our managed resources to be used as part of a Crossplane "composite resource" (which can be of whatever type you like, and have whatever schema you like). I highly recommend you look into this approach. We already support including configuration for things like Grafana Dashboards and Prometheus alerts via `provider-helm` and `provider-kubernetes` - for example you could define a `SimpleJohnDB` "composite resource" (aka XR), that was an abstraction on top of our `RDSInstance` resource and a Helm `Release` resource that deployed Grafana to monitor said database.

**Comment by johnpemberton** [comment]
Interesting, thanks @negz.   Just having [a read about that](https://crossplane.io/docs/v1.3/concepts/composition.html) and certainly seems useful for our purposes.   Still think it would be nice to have the option of pulling in an API package for working with crossplane resources directly in golang code.

We're loving crossplane btw... helping us solve some real problems in provisioning cloud infrastructure to live alongside our end-user k8s workloads, and so far not had any major issues with it 👍
