### ISSUE TITLE
Cleanup design doc lifecycles

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1711]
We have quite a lot of designs in the `design/` dir that are defunct, partially defunct, or quite inaccurate - including but not limited to complex workloads, design docs, composition, and the packages design. At a minimum we should take a pass over the dir and make sure all document statuses reflect their current life stage. I believe @kasey suggested moving all defunct docs into a subdir to make it easier to determine which docs are still relevant.

**Comment by negz** [comment]
Also (at the risk of yak shaving) I wonder how we should approach design documents in general. I've seen us take a few approaches.

1. Update the original design doc as our code changes.
1. Write a 'v2' design that supplants some or all of a previous design.
1. Let them rot.

So far I've personally preferred the 'v2' design approach. Rewriting or updating a design doc feels a little like rewriting history to me; I prefer to retain the historical context even if it becomes defunct.

**Comment by muvaf** [comment]
I think we should treat them by their status instead of having one approach for all. If a design is deprecated/defunct etc. then we just never update it anymore and make it more clear that it's not used anymore, this could include moving it to a subdir as well as having a `DEPRECATED` prefix in the title.

If it's implemented and still used, then the versioned updates on the same file make more sense to me unless there is a fundamental change. For example, [managed resource API doc](https://github.com/crossplane/crossplane/blob/master/design/one-pager-managed-resource-api-design.md) hasn't seen a fundamental change but incremental ones so we update the same doc by respecting its git history and having a proper versioning. This allows us to refer to it in different context without worrying about users getting redirected a few hops or getting lost in docs. But recent packages v2 design is in fact a fundamental change, so it's a separate doc and should probably be referred by the old one in somewhere close to its title.

**Comment by muvaf** [comment]
I think we should treat them by their status instead of having one approach for all. If a design is deprecated/defunct etc. then we just never update it anymore and make it more clear that it's not used anymore, this could include moving it to a subdir as well as having a `DEPRECATED` prefix in the title.

If it's implemented and still used, then the versioned updates on the same file make more sense to me unless there is a fundamental change. For example, [managed resource API doc](https://github.com/crossplane/crossplane/blob/master/design/one-pager-managed-resource-api-design.md) hasn't seen a fundamental change but incremental ones so we update the same doc by respecting its git history and having a proper versioning. This allows us to refer to it in different context without worrying about users getting redirected a few hops or getting lost in docs. But recent packages v2 design is in fact a fundamental change, so it's a separate doc and should probably be referred by the old one in somewhere close to its title.
