### ISSUE TITLE
Build and publish unpack base image

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#1714]
### What problem are you facing?

Per the [Package Format v2 design doc](https://github.com/crossplane/crossplane/blob/master/design/one-pager-package-format-v2.md), we need to create a default base image that `crank` will use when building a package. It should be able to parse package contents using the [package parser](https://github.com/crossplane/crossplane-runtime/tree/master/pkg/parser) and emit them as a valid YAML stream.

### How could Crossplane help solve your problem?

There are a couple of decisions to be made regarding the creation of this image:
1. Where will the image live? It may be desirable to version it separately from `crossplane`/`crank`, and we may support multiple Crossplane community maintained images in the future.
2. What support for arguments will it have? The design doc mentions support for the [`--context`](https://github.com/crossplane/crossplane/blob/master/design/one-pager-package-format-v2.md#consuming-an-output-stream) flag.
3. What will be present in the image? We need to be able to parse the package and emit to `stdout`, and should have as little else as possible in the image.

Note that users may hand roll their own package image, and there may be base images maintained outside of the Crossplane community. However, this will be the default when not overridden during `crank pkg build`.

**Comment by muvaf** [comment]
I've started working on this. @hasheddan do you think it makes sense if I add a command like `print` to `crank` that will emit the necessary YAMLs in the current package directory? It'll save us from maintaining another binary and will probably make it easier for people to debug & develop locally with something like `crank pkg print . | kubectl apply -f -`

**Comment by hasheddan** [comment]
@muvaf I think that would be useful! We also have discussed a `crank pkg lint` to check for errors. The tricky part with these is that the base image is not always required to be the same so doing `crank pkg print` would theoretically tell you what will be emitted if the default base image is used, but not if a different one is used. There may also be desired to version the unpack image separate from `crank`, so if it was just an image with `crank` in it that could be confusing. If we want to strictly have `crank` defer all logic to whatever base image is used, we could have `crank pkg print` actually invoke the image and then emit whatever its output is. That way you would see exactly what the package manager will see, regardless of what base image is used. Does all of that make sense?

**Comment by muvaf** [comment]
> The tricky part with these is that the base image is not always required to be the same so doing crank pkg print would theoretically tell you what will be emitted if the default base image is used, but not if a different one is used.

Yes. But as a user who uses a different base image, I'm not sure if I would expect for `crank` to be able to do that anyway. I mean, at that point, I accept that I'm on my own. So, I'd either run that app, like `cdk8s synth`, or `docker run` to run the image.

> There may also be desired to version the unpack image separate from crank, so if it was just an image with crank in it that could be confusing.

If we do version them separately, yes it'd be somewhat confusing. Though one of the benefits of merging them is to not have to version them separately, right? For example, there would be an image in DockerHub `crossplane/crank` which has only `crank` with the version same as the image tag. Then the unpack `Pod` would use that image with printing command. So, there wouldn't really be additional `Dockerfile` in the package repo or an intermediarey one that's used only during build.

> If we want to strictly have crank defer all logic to whatever base image is used, we could have crank pkg print actually invoke the image and then emit whatever its output is. That way you would see exactly what the package manager will see, regardless of what base image is used. Does all of that make sense?

That is a valid approach. Personally, I'd prefer `docker run` though because for other base images the `Dockerfile` is right there. I'd expect `crank` to do that only if a magic is involved, i.e. an image is built but there is no Dockerfile, which is what happens when I use default packaging mechanism.

**Comment by hasheddan** [comment]
> But as a user who uses a different base image, I'm not sure if I would expect for crank to be able to do that anyway. I mean, at that point, I accept that I'm on my own.

I don't think that we are actually saying that you are on your own completely here. Using a different base image does not mean that you are literally building a base image for that package. For instance, the `cdk8s` team could maintain a Crossplane base image, and you would use it by doing `crank pkg build --base=aws/cdk8s-crossplane:v1 ...`. 

> Then the unpack Pod would use that image with printing command. So, there wouldn't really be additional Dockerfile in the package repo or an intermediary one that's used only during build.

This would make sense if we were only using the default base image and we didn't care about any dynamic outputting, but we desire to support the ability to pass flags to the image, etc. If you think about it further, if are use case was scoped to just this one static build process, we wouldn't need any logic in the unpack image at all, and we could just do all building before copying into the image, then just have the image `cat` a single file or something (I actually did this for a lot of the manual testing for new package manager). However, we are not so lucky.

> Personally, I'd prefer docker run though because for other base images the Dockerfile is right there. I'd expect crank to do that only if a magic is involved, i.e. an image is built but there is no Dockerfile, which is what happens when I use default packaging mechanism.

There is still an intermediate `Dockerfile` in the case of using a custom base image, per my comment above. So under the hood, `crank` is doing `docker run` (or equivalent), and this means that we are able to "lint" regardless of alternative base images (i.e. if you built with base `aws/cdk8s-crossplane` we can still tell you if that package will be able to be parsed by the package manager when it is installed).

Note also that someone _could_ completely opt out of the `crank pkg build` process and craft a custom `Dockerfile` and build the image. In that case `crank` could still lint that package because it would just invoke that image you told it to.

**Comment by muvaf** [comment]
Maybe I'm missing something here. Let's say I run `crank pkg build --base=aws/cdk8s-crossplane:v1`, what is this command going to do for me? Create a `Dockerfile` with that image and build it?

```
FROM aws/cdk8s-crossplane:v1
...
# How is it going to know what goes in the rest of this file?
```

**Comment by hasheddan** [comment]
> # How is it going to know what goes in the rest of this file?

`crank` will first parse the `crossplane.yaml`, then add all files that are not in the `ignore` stanza. For instance, if there is no `ignore` stanza, it would be equivalent to `ADD . .`

**Comment by muvaf** [comment]
Hmm. But it's still on me to write the `ENTRYPOINT` in that `Dockerfile`, right? Like `ENTRPOINT ["cdk8s", "synth"]`

**Comment by hasheddan** [comment]
@muvaf an `ENTRYPOINT` defined in the base image will flow through if not overridden

**Comment by muvaf** [comment]
Got it, that'd work assuming that the image was specifically prepared to be a Crossplane package base image.

TBH, I feel like the user walks through a very thin line for both `build` and `print` to work for them while using a custom image. The equivalent of the golden path is:
```Dockerfile
FROM aws/cdk8s-crossplane:v1
ADD . .
ENTRPOINT ["cdk8s", "synth"]
```

and I'm not sure if any custom image will be that simple. It'll probably use an existing image, for example, most people would go for simple base images like [`brennerm/cdk8s`](https://hub.docker.com/r/brennerm/cdk8s) that has only the tool they want to use and then have a `WORKDIR` and possibly some build args passed in. In some cases, it will install other tools additionally or be built purely on top of `alpine` and installs linux packages in this `Dockerfile`. So they get out of the golden path very quickly but we'd still bear the cost of expanding these commands to cover the golden path.

I am suggesting that the `build` command will copy everything (except `ignore`) and call `crank print` as entrypoint:
```Dockerfile
FROM crossplane/crank:1.0 # base image already has a WORKDIR defined for CP files.
ADD . .
ENTRYPOINT ["crank", "print", "--path", "."]
```

This will be built and wait for the `push` command. `Dockerfile` could be written to the file system so that people can add it to their version control system and make sure they get the same thing every time a build happens. So `build` would create the `Dockerfile` only if it doesn't exist; so it will still build an image for any existing `Dockerfile`. So, the generation of `Dockerfile` would be just like a starter default that people can change as they see fit.

`print` will scan, parse and print the output stdout, but it won't even be called if the user uses another tool for printing. So, we're delegating the responsibility of `Dockerfile` to the user once they want to use a custom logic. We'd get to keep what each command do for the user very simple and predictable.

**Comment by negz** [comment]
https://github.com/crossplane/crossplane/pull/1681#discussion_r478798126

Cross-linking the above comment. It's going to be important that our default Crossplane base unpack entrypoint supports piping its output through other binaries (presumably binaries included in other layers of the OCI image). This will allow (for example) an Upbound registry metadata binary to scan a `.registry` directory that it holds opinions about, and annotate the output stream produced by the Crossplane unpack binary accordingly.

**Comment by muvaf** [comment]
@negz Just to be clear, with the separation of those binaries, the base binary will simply read YAML files and emit them through stdout, right? Then later on, we'll add additional binaries (or flags to this one), to process & annotate with additional metadata like icons, ui-schema etc.
