### ISSUE TITLE
Proposal: Observe-only Crossplane resources

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#1722]
### What problem are you facing?

I want to get configuration/status of an external resource that is not managed by Crossplane. This is especially useful while building a composition that relies on configuration/status of an already existing external resource, where resource could be managed:

- by other tools (terraform, ansible, helm ...)
- manually created from UI or a legacy one
- by another Crossplane control plane instance
- by another Crossplane composite resource

This is quite similar to [data source's in Terraform](https://www.terraform.io/docs/configuration/data-sources.html) or [fact/info modules in Ansible](https://docs.ansible.com/ansible/devel/user_guide/playbooks_vars_facts.html).

For my specific case, I am interested in [reading status of an existing Kubernetes Service (which is managed by helm)](https://github.com/crossplane-contrib/provider-helm/issues/25) to get LoadBalancer IP so that I can report in composite resource status. Even better, [I want to provision a DNS record with Crossplane](https://github.com/crossplane/crossplane/issues/1603#issuecomment-647452551) and report URL. This is quite similar to the following terraform code:

```
data "kubernetes_service" "example" {
  metadata {
    name = "terraform-example"
  }
}

resource "aws_route53_record" "example" {
  zone_id = "${data.aws_route53_zone.k8.zone_id}"
  name    = "example"
  type    = "CNAME"
  ttl     = "300"
  records = ["${data.kubernetes_service.example.load_balancer_ingress.0.hostname}"]
}

``` 

However, I feel like this would enable other possibilities like fetching any kind of data from external API's without making changes, like [looking up existing AMI images](https://github.com/hashicorp/terraform/pull/4396) or getting a [list of availability zones](https://github.com/hashicorp/terraform/pull/6669).

#### Related Issues

There were some previous discussions which seems to be related to this, but proposed solutions were around claim/class pattern which is being deprecated.

- Re-using a GCP CloudSQLInstance: https://github.com/crossplane/provider-gcp/issues/157

    From [description from @dsyer](https://github.com/crossplane/provider-gcp/issues/157#issue-559105058): 

    > There are potentially 2 separate use cases here:
    > 
    > - I would like to be able to bind to a SQL instance that already exists.
    > 
    > - I would like to be able to use Crossplane to create a SQL instance, and then have it re-used by multiple claims (e.g. I deploy the same app twice).
    > 

- Crossplane should refuse to operate on existing external resources: https://github.com/crossplane/crossplane-runtime/issues/27

    From [comment from @negz](https://github.com/crossplane/crossplane-runtime/issues/27#issuecomment-526301988): 

    ```
    # A "read only" policy, similar to a Terraform data source. Exposes the state
    # of an existing external resource via the managed resource status object.
    externalResourcePolicy:
      create: Attach
      update: Observe
      delete: Detach
    ```

- Allow existing resources to be "imported" into Crossplane to be managed: https://github.com/crossplane/crossplane-runtime/issues/22

    From [comment from @muvaf](https://github.com/crossplane/crossplane-runtime/issues/22#issuecomment-555466062):

    >  - User may run multiple Crossplane instances each in different Kubernetes clusters and they might want to consume the same resources from those different clusters. For example, an Azure resource group is a logical grouping mechanism of Azure and user wants to accumulate all the resources provisioned in a group of Crossplane instances in the same resource group or an SQL server could be consumed by different applications in different Kubernetes clusters using different databases in the same server. I'd like to set one Crossplane instance to manage the full lifecycle of resource X while other instance would just import and not touch anything except Observe and make it available in its cluster.
    > 
    >   - It restricts the adoption of Crossplane into existing infrastructure. Let's say I have an application that consumes 5 different cloud services and they are all stateful, like database. I'd like to import those resources in another cluster via Crossplane and consume them there. If everything goes well I may go further, change external policy and shut down the legacy infrastructure provisioning pipelines. I am not sure we want to tell people that you're all in or out.

#### Terraform issues for possible use cases

- Terraform issue initially proposing "data source" type: https://github.com/hashicorp/terraform/issues/4169

- Another Terraform issue which mentions some use case: https://github.com/hashicorp/terraform/issues/3646

    > I've found with my use of terraform you often need to provide a mixture of environment details from computed information (eg. instance id's) and often pre-generated resources (eg. vpc id's or subnet id's).
    > 
    > This becomes an issue for terraform to manage such a core/common/reused resource like VPCs, if you have a mixture of managed/unmanaged resources. The issue comes about when terraform wants to teardown the whole VPC and rebuild it, but there's an unmanaged resource in there preventing the VPC from being destroyed. Now you're stuck. Either teardown the instance manually or separate out the VPC from your application and include more process.

- data sources for AWS network planning: https://github.com/hashicorp/terraform/pull/6819#issue-70964851

- A lot of use case examples for data source usage (not all would apply for Crossplane though): https://github.com/hashicorp/terraform/issues/16380

### How could Crossplane help solve your problem?

Introduce a generic way for "observe-only" or "read-only" access to external resources.

I can think of two possible options:

#### Option A: Add a new parameter to spec:

- Add a new parameter (e.g. `observeOnly: true`) for [managed `ResourceSpec`](https://github.com/crossplane/crossplane-runtime/blob/master/apis/core/v1alpha1/resource.go#L178).
- Implement in managed reconciler to only call `Observe` method of reconciler in "observe-only".

Example:

```
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  annotations:
    "crossplane.io/external-name": "my-existing-subnet"
  name: my-existing-subnet
spec:
  observeOnly: true
```

#### Option B: Define new types for observe-only resources (e.g. For `Subnet` ->`SubnetObservation`)

- Define a generic pattern:
    - how to name resources, e.g. append `Observation`
    - how to implement controllers
    - which fields to support, e.g. tags, filters 
- Auto generate types (if possible) which could even be managed by the same controller of the actual resource by calling observe only.

Example:

```
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SubnetObservation
metadata:
  annotations:
    "crossplane.io/external-name": "my-existing-subnet"
  name: my-existing-subnet
```

**Option A** sounds like a quick and simple solution, however, for existing types, `spec.forProvider` is required which may not be for "observe-only" ones. So, we would need to either make them optional or define new type's as mentioned in **Option B**. Also, in some cases, we may need some specific parameters for "observe-only" case (e.g. tags, filters), supporting **Option B**.

**Comment by hasheddan** [comment]
@turkenh thanks for opening this! Wanted to point to some prior art related to this topic: https://github.com/crossplane/crossplane/issues/834

**Comment by negz** [comment]
> For my specific case, I am interested in reading status of an existing Kubernetes Service (which is managed by helm) to get LoadBalancer IP so that I can report in composite resource status. Even better, I want to provision a DNS record with Crossplane and report URL.

For this specific use case, would it make sense to have your Helm chart create a `type: NodePort` service? Then your composition could create a load balancer as a 'native' Crossplane resource, create DNS records that point to that service, etc? It seems ideal to keep as much infrastructure managed by the "core" orchestration system (Crossplane) as possible.

Putting the specific use case aside, I agree this proposal is worth investigating. I think Option B is the better approach:

* I believe it makes it more obvious to users which resources are "observation only" vs the source of truth.
* It's conceptually similar to Terraform. This will help folks from that ecosystem understand the model and help us generate controllers that use Terraform providers under the hood.
* I suspect having a separate controller (observe vs orchestrate) for each purpose will be simpler and cleaner code wise than trying to write one controller and API type that handles both cases.

I'm curious what prior art exists in the Kubernetes ecosystem for such a pattern - i.e. strongly typed resources that only reflect the status of an external system, rather than orchestrating an external system. The `Node` resource is the only thing that immediately comes to mind.

I'd like to consider this proposal holistically as it relates to #1603, #1639 and cross-resource references. In particular simply adding a `SubnetObservation` would only be one piece of the puzzle - we'd also need to teach other types that they could reference a `SubnetObservation` as well as a `Subnet` to extract values. The more we discuss this, the more it seems like we're headed toward emulating Terraform's ability for the value of any field in a resource of a particular kind to be set to a value derived by any field of another resource of an arbitrary kind. Doing that in the DAG-less eventually consistent style of the Kubernetes API is likely to be a challenge.

**Comment by turkenh** [comment]
> For this specific use case, would it make sense to have your Helm chart create a type: NodePort service? Then your composition could create a load balancer as a 'native' Crossplane resource, create DNS records that point to that service, etc? It seems ideal to keep as much infrastructure managed by the "core" orchestration system (Crossplane) as possible.

I played around a bit but couldn't do this manually, probably it is because cloud controllers do more than just creating load balancer resource when service type is `LoadBalancer ` (e.g. creating firewall rules etc) or I couldn't figure out the correct configuration. Also, I am not sure if this is even possible without reading auto-assigned port of NodePort from the created service.
However, it is possible to set `spec.loadBalancerIP` while creating the service and I could make it work by using a static IP. So, creating the static IP with Crossplane and feeding this IP to LoadBalancer type service could be a solution for this case.

**Comment by benagricola** [comment]
This looks interesting - I'm looking to implement something similar to #1603 (Create a service account and linked AWS role) but in my case, the EKS cluster is not managed by Crossplane but by `eksctl`. 

Right now, I think I need to hardcode the `cluster.identity.oidc.issuer` field, but it would be ideal if it were possible to 'import' (or attach as outlined in #834) the cluster itself to pull the `oidc.issuer` value 🙂

**Comment by jseriff** [comment]
We have a similar use case, that I believe either of the options discussed above would resolve:

We have some infrastructure "superstructures" such as Networks which we do not want to be controlled by Crossplane (because they may exist outside of scope of our Kubernetes clusters).  To simplify work for developers, we'd want to create a Network object in Crossplane that we can reference from other resources, instead of requiring developers to specify full path of the network. 

However, we absolutely do not want Crossplane to attempt to modify this Network (many clusters may all reference this Network, and we can imagine a worst case situation where they fight over the configuration of this resource).  In option (b) above, it would be critical that we could use the `NetworkObservation` object in all places that we can currently reference a `Network` object.

**Comment by negz** [comment]
> many clusters may all reference this Network, and we can imagine a worst case situation where they fight over the configuration of this resource

@jseriff Out of curiosity, would you be more comfortable having Crossplane take full RW ownership of the VPC if you could deploy Crossplane such that you had one dedicated control plane (i.e. an API server running just Crossplane) that was responsible for ownership of all your infrastructure, and were able to connect your various workload-running Kubernetes clusters up to that control plane? The idea being that your users could create an XRC in workload cluster A, which would create a corresponding XR in the central Crossplane cluster, where it would be able to refer to the VPC (which was orchestrated by Crossplane in said central cluster)?

**Comment by jseriff** [comment]
In your proposal, would this control plane be a dedicated service (ala Terraform Cloud) or are you thinking this is a dedicated cluster running crossplane to manage shared infrastructure?  I'm assuming this would include a mechanism for synchronizing connection secrets back out to the workload cluster?

While either option is something that is definitely possible for us, it feels a bit more complex to me.  For us, things like the networks are largely static (we're hybrid, so our networks are tied back to our datacenters), so real time synchronization is not really value for us, and is somewhat scary due to the high blast radius potential.

**Comment by muvaf** [comment]
When I think about the downsides of the two options, I see the following:

Option A (a field or metadata field):
* Field/Annotation/Label could be manipulated and suddenly controller will start to make changes. One can prevent this via RBAC but that'd cover every instance of the kind. Doing RBAC per-resource is not a nice UX.
* Current controllers will not override the spec fields if a value exists (late-initialization), hence, if someone changed the value of the field, they won't be able to override. We can make controller override it with special logic but it won't be trivial.

Option B (separate kind):
* I think it will make it a bit harder to browse when you look for a specific resource to reference. Instead of one type, now you need to query two types. Maybe we can add a CRD category with the kind name, like `subnet` for both `Subnet` and `SubnetObservation`.
* As pointed out, referencers work for only one type. We need to teach them to look for the observation type as well. This could be straight-forward. However, we'd use the same `subnetRef` field for two types, which could be misleading for both ref resolver and the user since when we separate the kinds, we stop guaranteeing name uniqueness, i.e. `Subnet` and `SubnetObservation` instances can have the same name.
* All other tools built on top of Crossplane will need to consider that there can be two different types for every managed resource.

Option A feels like a better UX to me except the trust part, i.e. I want to make sure there is _no way_ that controller will ever make changes. Maybe we can do a permanent mark. For example, once a `Subnet` is marked as `crossplane.io/read-only: true` via annotation, we save its UID and an admission webhook would not allow removal of that annotation(since webhook is on the path of the change, we can guarantee we save the UID before CR makes it to etcd). You'd have to recreate the CR if you want it to be reconciled. Though keep in mind that webhook would not be optional in this picture anymore.
The `SubnetObservation` type and its controller is probably implementable in a straight-forward way and it's 100% trust; there is no way to make change since its controller code will have only `Observe` but it has the problems listed above.

I feel closer to option A with prevention of a change in the annotation via webhook since it makes the big picture easier to understand for both humans and the machines(our controllers as well as others). But I'm not holding this position strongly. There is a nice peace of mind when the separation is on `kind` level.

**Comment by muvaf** [comment]
Another idea could be that we can have one new kind like `ExternalResource` that has `data` instead of `spec`, similar to `ConfigMap`. Through generic cross resource reference, we can refer to a field under `data`. One drawback of this approach is that we won't do any late-init (probably not even reconcile), user has to fill in all the values they would like to be referred, which doesn't seem too bad given that number of resources that needs to be static (GCP project, main big VPC etc.) are usually low. The UX will depend mostly on generic cross resource reference UX.

In fact, instead of a new kind, it could even be good ol' `ConfigMap` 🤔

**Comment by nabadger** [comment]
Option A) looks really nice from a UX point of view. :+1: 

We use Terraform spin up our core-infra (VPCs, EKS and currently Buckets/Databases too), and as part of a possible migration to Crossplane, I would like to use it for common application resources (Buckets, Databases, Cache etc).

I don't yet want Crossplane to manage the VPC creation, but I do want to reference it when building a new compositions (i.e Database ones).

Specifically, I would love to move away from away from things like `vpcId` and towards name-lookup references - this is would be really useful for us, since our resources are named based on the account/region/environment (i.e. `dev-eu-vpc`), which means we could make better use of templating when deploying compositions to different clusters (we could avoid hard-coding settings...and automate more).

In addition, would an observe only mode only require read-only permissions (for example `ec2:DescribeVpcs`) - if so this would be pretty comforting for us when it comes to a migration :)

**Comment by RealHarshThakur** [comment]
I think Option A is good. Although, I would incline towards having an immutable field in spec because implementation of a webhook to ensure the immutability of the filed can be used by other components in crossplane ecosystem while defining CRDs. Although, we have to enable a mechanism if the end user changes their mind about resource being reconciled by crossplane. Maybe a special command from crossplane-cli to allow such a change to happen through the webhook is possible? Meaning webhook being the only one with permissions to mutate an immutable field.  All of this is considering that immutable fields might take a while to be supported [upstream](https://github.com/kubernetes/enhancements/blob/8b9b994136371f1bc938aabf012f4c45535d684c/keps/sig-api-machinery/20190603-immutable-fields.md)

**Comment by displague** [comment]
https://cloud-native.slack.com/archives/C01DCV0BS9H/p1620300219023400

A user looking for a way to "pause" the reconciliation of a single resource may look to this feature to toggle behavior.

> Option A sounds like a quick and simple solution, however, for existing types, spec.forProvider is required which may not be for "observe-only" ones. So, we would need to either make them optional or define new type's as mentioned in 

For this "pause" behavior, a user may not want the spec or status to be updated while reconciliation is paused. Should this pause feature be handled in a different way?

Dropping a deployment's replica scale to 0 is how you would pause pods without deleting the definition from your cluster. Should a managed resource offer a way to block the production of its child resources (external resources) too?

**Comment by iAnomaly** [comment]
Excited to see this proposal and discussion! This is a critical need for us as I migrate our existing Terraform managed infra to Crossplane. @jessesanford captured the reality well that there will always be some infrastructure managed externally to Crossplane at larger organizations and glue is needed to access and build off that existing state.

My vote is for Option A as well acknowledging the concerns that @muvaf calls out around guaranteeing immutability of the underlying infra. I think the beauty in Option A is it also provides an implicit migration path for those resources to Crossplane in the future if one choses to recreate the CR without the immutable taint/metadata and uses the Crossplane external facility to inherit that infra.

**Comment by ryuheechul** [comment]
_just adding an opinion on importance of this feature_

I think this feature will be critical for adoptions as much as [Data sources](https://www.terraform.io/language/data-sources) is a critical part of Terraform's feature. In fact, without it, [this claim](https://blog.crossplane.io/announcing-terrajet/#:~:text=Crossplane%20now%20has%20full%20coverage%20of%20all%20the%20resources%20available%20in%20the%20three%20most%20popular%20cloud%20providers) doesn't sound right to me.

Option B sounds good to me except I would suggest a change below instead for two reasons:
- shorter to type and read
- consistent with Terraform (especially with TerraJet generated providers)

```diff
  apiVersion: ec2.aws.crossplane.io/v1beta1
- kind: SubnetObservation
+ kind: DataSubnet
```

**Comment by jwitrick** [comment]
I agree with the above, having the ability to specify external resources as a crossplane object AND make it readonly is REALLY important. 

In my use case (like others above) we are using a different workflow to setup/manage our external resources (AWS VPC, etc..) and then we create crossplane resources for things like Subnets, SecurityGroups, etc... and use those resources in other crossplane resources (RDS,etc...).But now that things like Subnet/SecurityGroups support updating the external-resources  im having to be very careful (and in some cases remove the crossplane resources) so it does not break my system. 

So yes having the ability to both specify existing resources as crossplane resources WITHOUT crossplane trying to take full ownership is a MUST to keep adopting crossplane.

**Comment by janwillies** [comment]
> So yes having the ability to both specify existing resources as crossplane resources WITHOUT crossplane trying to take full ownership is a MUST to keep adopting crossplane.

Other possible ways to solve this without importing the resources into crossplane might be via https://github.com/crossplane/crossplane/pull/3008 or https://github.com/crossplane/crossplane/issues/2524

**Comment by shanproofpoint** [comment]
Hi can i get a status of this?

**Comment by jbw976** [comment]
@shanproofpoint I know there is a lot of interest in this issue from the community, but it is not being actively worked on at the moment.  It remains highly positioned on the roadmap though, so its high demand is captured and would be reflected well in any planning effort by the community for upcoming releases 🙇

**Comment by bobh66** [comment]
@jbw976 Could this be handled in the crossplane-runtime managed.Reconciler instead of being implemented individually in every provider?   Considering the managementPolicy work that was done in provider-kubernetes, https://github.com/crossplane-contrib/provider-kubernetes/blob/main/internal/controller/object/object.go#L247 - it just skips the function if the management policy does not support that specific functionality.  The Reconciler could easily check the same policy and skip the call the function at that level.  In that case an "observe only" resource would only ever call the Observe function in the Reconciler, and skip all of the others.  This may be a simplistic implementation but I'm curious if it would handle a fair number of the use cases?   Obviously the providers would still need to support the resource to be observed, but as long as the external.Observe function returns the object when it exists via external-name, maybe it would be sufficient?

**Comment by shanproofpoint** [comment]
thank you @jbw976 @bobh66 !

**Comment by ytsarev** [comment]
I've just tested the temporary workaround for this problem which involves provider-terraform and Composition, example is here https://github.com/crossplane-contrib/provider-terraform/pull/113 , maybe it will be useful to somebody.

**Comment by jpoley** [comment]
I know there is a workaround for this. but are there plans / considerations of having a longer term resolution in the .11 release? just wondering

**Comment by jbw976** [comment]
Hey @jpoley, just following up here in Github too from our [Slack chat](https://crossplane.slack.com/archives/CEG3T90A1/p1668020417128639?thread_ts=1667651999.860559&cid=CEG3T90A1) - observe only resources is definitely a highly demanded feature and we are expecting some of the team to be focusing on it for 1.11.  I'm not going to say it's definitely going to make the release, it's still early days for figuring out the right experience, but folks will be spending time on it in the 1.11 timeframe 😅

**Comment by turkenh** [comment]
We are starting to work on this ticket, you can expect a design PR soon 🚀

**Comment by truongnht** [comment]
Hi guys, will Observe-only resource make it to the v1.11 release, not only in design but also implementation?

**Comment by jbw976** [comment]
Thanks for your interest in this feature @truongnht :) 

The intent/expectation for v1.11 is that observe only resources will have a finalized design - an implementation will not be included in v1.11.  Take a look at the design in #3531 if you haven't already, feedback is welcome! 🙇

**Comment by 1aziz** [comment]
Are there any updates for this ticket? I see the design was already submitted, but do we know when we possibly could expect this feature? :)

**Comment by jbw976** [comment]
Good question @1aziz - support for observe only resources was included in crossplane-runtime in https://github.com/crossplane/crossplane-runtime/pull/384 and is being included into providers right now.  `upbound/provider-azure` looks to have gotten a release with OOR support just today in fact: https://github.com/upbound/provider-azure/releases/tag/v0.31.0

Other provider PRs to incorporate OORs (should be released very soon):
* https://github.com/upbound/provider-aws/pull/672
* https://github.com/upbound/provider-gcp/pull/284

**Comment by turkenh** [comment]
I was waiting to have those releases out to close this ticket, thanks @jbw976 🙌 

Closing as done!

**Comment by waldner** [comment]
Will this ever be available somehow for upjet-based providers?

**Comment by jeanduplessis** [comment]
@waldner The Upbound Official providers are upjet-based.

You can now use the observe-only management policy with the latest providers:
- [upbound/provider-aws@v0.34.0 (release)](https://github.com/upbound/provider-aws/releases/tag/v0.34.0)
- [upbound/provider-azure@v0.31.0 (release)](https://github.com/upbound/provider-azure/releases/tag/v0.31.0)
- [upbound/provider-gcp@v0.31.0 (release)](https://github.com/upbound/provider-gcp/releases/tag/v0.31.0)

See https://github.com/crossplane/docs/pull/407/files for info on the new management policy field.

**Comment by waldner** [comment]
Ah great, I didn't know that. Thanks!

**Comment by preetsindhal** [comment]
> @waldner The Upbound Official providers are upjet-based.
> 
> You can now use the observe-only management policy with the latest providers:
> 
>     * [upbound/provider-aws@v0.34.0 (release)](https://github.com/upbound/provider-aws/releases/tag/v0.34.0)
> 
>     * [upbound/provider-azure@v0.31.0 (release)](https://github.com/upbound/provider-azure/releases/tag/v0.31.0)
> 
>     * [upbound/provider-gcp@v0.31.0 (release)](https://github.com/upbound/provider-gcp/releases/tag/v0.31.0)
> 
> 
> See https://github.com/crossplane/docs/pull/407/files for info on the new management policy field.

Any information if this would be available for `crossplane-contrib/provider-aws`

Thanks

**Comment by jeanduplessis** [comment]
@preetsindhal there's an open issue to track adding support in `crossplane-contrib/provider-aws`: https://github.com/crossplane-contrib/provider-aws/issues/1726

**Comment by turkenh** [comment]
Just created a follow-up ticket for Querying and Filtering use case, which was left as a future work due to the [reasons explained](https://github.com/crossplane/crossplane/blob/master/design/design-doc-observe-only-resources.md#querying-and-filtering) in the design document: https://github.com/crossplane/crossplane/issues/4141

**Comment by autarchprinceps** [comment]
Am I missing something here, but specifying observe-only resources by external-name, which usually is an ID, isn't really a replacement for the terraform data object, which can find resources by many properties or tags. Often the ID is exactly what you want to look up with an observe-only resource. If you need to provide it, that doesn't really help that much.

**Comment by jbw976** [comment]
@autarchprinceps this information is useful here too 🙇‍♂️ 

https://github.com/crossplane/crossplane/issues/4141#issuecomment-2148338772
