### ISSUE TITLE
ProviderConfigs should not be deleted until all resources referring to it are deleted

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1737]
### What problem are you facing?

When I delete an infra-stack, all CRDs get deletion requests, including `Provider` ones. Since there is no `finalizer` on `Provider` resources, they are deleted immediately. This leads to hanging resources with deletion timestamp because their controllers cannot make deletion calls anymore since they'd have to have `Provider` resource to give them the credentials.

### How could Crossplane help solve your problem?

Crossplane could block the deletion of a `Provider` resources until all resources that used this `Provider` are deleted from the cluster.

One mechanism could be that every resource that is successfully created could add its identification info to `finalizers` array and remove its entry when the resource is deleted.

The other alternative would be to have a `Provider` controller that scans all the resources who refer to this `Provider` instance and block the deletion until it finds none. We could somehow make use of labels for easy listing instead of `providerRef`.

**Comment by negz** [comment]
We've deprecated infra stacks, but we're now allowing ProviderConfigs inside Composite resources so we're running into the same issue.

**Comment by muvaf** [comment]
IMO, we have two options for how we'd like to proceed:
* In composition, specifically leak the resources whose kind is `ProviderConfig`. Fast and dirty hack for 0.13.
* Write controller for `ProviderConfig` kinds that will check whether there is any resource using that `ProviderConfig`.
  * The check logic is pretty generic but fetching the CRs belonging to that provider could be a bit tricky. In case of deletion;
    * Either the controller could query `aws` category (`kubectl get aws`) and all AWS managed resources will be returned.
    * Or we can have a list of types supplied during the initialization of the `ProviderConfig` controller so that it lists all of them. However, this would require each managed resource addition to register to that controller and it'd make _many_ `GET` calls, i.e. one for each type.

I feel like the category querying is simple and we can get it working fast enough compared to the hack. Though depending on category of CRD in actual controller flow feels a bit unsafe. But it's an explicit field on `CustomResourceDefinition` just like kind name so that feeling is probably because we just never used it.

**Comment by negz** [comment]
Another approach could be to have each provider controller add some metadata to the ProviderConfigs they use to authenticate - a finalizer, owner ref, annotation etc. Refuse to let the ProviderConfig be deleted while such annotations still exist. This would probably get pretty messy pretty fast though with many managed resource controllers fighting to update ProviderConfig metadata.

We could also introduce a `ProviderConfigBinding`, (or `ProviderConfigUsage`) type, e.g.:

```yaml
kind: aws.crossplane.io/v1alpha1
kind: ProviderConfigUsage
metadata:
  name: some-rds-kfnsd2
configRef:
  name: default
resourceRef:
  apiVersion: database.aws.crossplane.io/v1alpha1
  kind: RDSInstance
  name: some-rds
```

If all managed resources created a usage (with a controller ref) when they successfully created a provider client we'd be able to block deletion of the ProviderConfig while any usages still existed. It could also be a useful way to quickly discover what resources were using what provider; e.g. `kubectl get providerconfigusage -l provider=cool-provider`.

**Comment by muvaf** [comment]
> Refuse to let the ProviderConfig be deleted while such annotations still exist. This would probably get pretty messy pretty fast though with many managed resource controllers fighting to update ProviderConfig metadata.

To be fair, if it's a simple array of strings, it's probably safe to rely on api-server to handle the mutual state. So, it may not be that bad in the end. However, it'd be a bit complicated to handle the case where managed resource switches to another provider because the managed reconciler won't know about the old provider.

> An improvement on that idea could be to introduce a ProviderConfigBinding, (or ProviderConfigUsage) type

That would be proxying N kinds into 1 kind, which would necessitate some kind of unique naming. We'd have N `ProviderConfigUsage` for N managed resources in the cluster. Additionally, we'd need to handle some edge cases like what happens when user changes `spec.providerRef` of a managed resource. So, having another type (users won't really interact with) just for that purpose looks like an overkill to me.

Thinking through this, it seems to me that a mechanism centered around the `ProviderConfig` object makes most sense instead of having a self-service mechanism for managed resources. Selection via category looks viable though I don't know how much of it is handled by the client or the api-server. If it's all client-side, I'd prefer having parallel Go routines `GET` all AWS resources and filter with `providerRef` during deletion of `ProviderConfig` instead of relying on client-side category fetch.

**Comment by negz** [comment]
> To be fair, if it's a simple array of strings, it's probably safe to rely on api-server to handle the mutual state.

I doubt it would work well. If a composite resource creates N resources that all try to use the same PC, each of those resources would try to annotate the PC. They'd all race and I suspect many writes would fail due to the PC being modified between when it was read and when it was updated. I'm sure the system would eventually converge, but it would take a lot of work and noise to get there.

> Thinking through this, it seems to me that a mechanism centered around the ProviderConfig object makes most sense instead of having a self-service mechanism for managed resources. 

Perhaps this is subjective, but I disagree. It seems fragile to me to have a PC controller attempt to find every resource in the system that might be using it at deletion time.

**Comment by negz** [comment]
I'm feeling passionate about the `ProviderConfigUsage` approach - I'm going to play with it tonight to see how it works in practice.

**Comment by negz** [comment]
I've drafted up the `ProviderConfigUsage` approach at https://github.com/crossplane/provider-gcp/pull/256. I feel good about that approach and think it's worth pursuing, however as I was wrapping up the proof of concept I realised it may not actually solve our problem.

Let's say we have a composite resource that:

* Creates a kubernetes cluster of some kind - let's say an `EKSCluster`
* Creates a Helm `ProviderConfig` that points to the connection secret of that `EKSCluster`.
* Creates a `HelmRelease` that uses the aforementioned Helm `ProviderConfig`.

My draft above (if applied to the Helm provider) would ensure the Helm `ProviderConfig` was not deleted until all of the `HelmRelease` resources that used it were deleted, but it would do nothing to stop the underlying `EKSCluster` from being deleted. It's possible that we'll get lucky and the cluster's API will respond long enough for us to delete our releases, but it's not guaranteed.

**Comment by negz** [comment]
> I realised it may not actually solve our problem.

If we wanted to add some more protection, one option might be to:

1. Update `managed.Reconciler` to call `UnpublishConnection` before deleting the managed resource.
1. Update the `ProviderConfig` reconciler to add itself as an `OwnerReference` to its connection secret.
1. Add an `UnpublishConnection` implementation that refuses to delete a connection secret that is owned by anything other than the managed resource that created it.

**Comment by muvaf** [comment]
> My draft above (if applied to the Helm provider) would ensure the Helm ProviderConfig was not deleted until all of the HelmRelease resources that used it were deleted, but it would do nothing to stop the underlying EKSCluster from being deleted.

I think that's a separate problem that is when two managed resources depend on each other via a secret as common point, how we can ensure a proper deletion order.

I would like to describe my thought process around the trade-offs here for consideration.
* `ProviderConfig` controller:
  * (1) Every managed resource will have a corresponding `ProviderConfigUsage` and during deletion the controller will check whether there is any `ProviderConfigUsage` that points to the `ProviderConfig` being managed exists before allowing the deletion to go through.
  * (2) During deletion, the controller will `LIST` each kind of managed resource of the provider and check their `spec.providerRef` points to the `ProviderConfig` that is being managed before allowing the deletion to go through.
  * (3) Each managed resource can add an **annotation** (finalizers are not of option bc of the reasons @negz listed) on the `ProviderConfig` they use and during deletion the controller will check only these instances before allowing the deletion to go through.

From computational cost perspective, (1) distributes N (N: number of managed resource instances) calls to different times but it's repeated every minute throughout the lifecycle of the managed resources, (2) does M (M: number of managed resource kinds) calls only during deletion but they happen very close to each other, likely at the same time, (3) distributes N calls and makes condense N calls during the deletion. Computational costs here may affect CPU usage of api-server and provider though I don't know how good the cache of controller-runtime is so the call cost may be lower than we expect. In fact, (1) could be advantageous from api-server perspective if controller-runtime doesn't call api-server each time for no-op updates and get calls.

From UX standpoint, I believe (1) is more complex than other two because of introduction of a new type and the information that type is carrying being present elsewhere anyway, i.e. `spec.providerRef`. (3) gives more visibility to users but the `annotations` set is not guaranteed to be accurate since deletions won't be reflected. (2) would print the precise list of blocking resources during deletion, however, in the codebase we'll need to register each kind, which is already done for scheme and we might be able to reuse the list there.

In my opinion, (2) seems easier to maintain with less complexity shown to the user. I couldn't really convince myself that we need a new type just for this functionality. But I can see how (1) also makes sense.

**Comment by negz** [comment]
I believe this is a close call complexity wise, and is subjective from a UX perspective - especially if we can agree that it's worth making the consumers of a `ProviderConfig` easily discoverable even when it is _not_ being deleted.

If we go with the `ProviderConfigUsage` approach:

* In the happy path - the vast majority of cases - we make one API call to create a `ProviderConfigUsage` when a managed resource first connects. Subsequent connects may read from cache and avoid a no-op update.
* The `ProviderConfig` controller can determine whether it should remove its finalizer and inform users whether it's in use by listing one type - `ProviderConfigUsage` - from cache. The list can be filtered by a well known label.
* The `ProviderConfig` controller must watch two types - `ProviderConfig` and `ProviderConfigUsage` - in order to react immediately when a `ProviderConfig` may be safely deleted.

If we invert the responsibility of discovering usages such that the `ProviderConfig` controller handles it:

* The `ProviderConfig` controller must be aware of the N types that may use a `ProviderConfig`. We can probably register these types when instantiating the controller to avoid having to use API discovery or similar.
* The `ProviderConfig` controller must make N list calls from cache to list N heterogeneous types, and parse the `spec.providerConfigRef` from each resource of each type to determine whether it uses the provider.
* The `ProviderConfig` controller must watch 1+N types - `ProviderConfig` and the N types that may use it - in order to react immediately when a `ProviderConfig` may be safely deleted.

So complexity wise it seems like the `ProviderConfigUsage` approach trades increased storage (many instances of a small resource) for reduced compute (fewer types to list and parse, fewer watches).

UX wise it gets pretty subjective. The `ProviderConfigUsage` approach is arguably the more idiomatic - it reflects the canonical deployment-to-pod relationship in which the user determines which pods are part of a deployment by running `kubectl get pod -l some=labelselector`, not by looking at an array of pod references in the Deployment's status. There are also parallels with the RBAC `RoleBinding` type that binds a role to one or more subjects.

If the `ProviderConfig` controller were responsible for discovering which resources were using it they would presumably be displayed as an array of object references in the status of a `ProviderConfig`. This the more common approach in Crossplane controllers (e.g. the relationship between a composite resource and its composed resources, or a package revision and the resources it installs). One variation here is that the composite resource and package revision Crossplane controllers are responsible for the  lifecycle of the resources they track via object references - they create them, rather than discover them after the fact.

My assessment is that neither approach is objectively better from a performance standpoint. I still feel that the `ProviderConfigUsage` approach is slightly better from a UX and implementation-complexity standpoint.

**Comment by muvaf** [comment]
We synced with @negz and decided to see how the deletion priority we had in template stacks would solve this and related two other problems [[1]](https://github.com/crossplane/crossplane/issues/1782) [[2]](https://github.com/crossplane/crossplane/issues/1612). I opened https://github.com/crossplane/crossplane/pull/1783 that implements this idea. The biggest difference with `ProviderConfigUsage` is that deletion priorities would work with composition only. On the other hand, users are able to specify multiple levels of custom priority explicitly, which I think will be useful more we expand the use cases composition can be used.

I feel like functionality and UX-wise, deletion priorities are more explicit and seem simpler to reason about for all three problems it solves and I have a perception that more and more we're moving infra provisioning towards composition scenarios instead of singular managed resource provisioning. So, keeping managed resource level as dumb low level and having such powers at the higher level makes sense to me. But, for example, if we foresee that quite amount of users will have raw managed resources with functional inter-dependencies like this one in their Helm charts or ArgoCD pipelines, it could make sense to go with `ProviderConfigUsage`.

**Comment by negz** [comment]
I don't think see this as an either/or decision. I'd like to proceed with adding support for `ProviderConfigUsage`, and separately consider ordered deletion.

> But, for example, if we foresee that quite amount of users will have raw managed resources with functional inter-dependencies like this one in their Helm charts or ArgoCD pipelines, it could make more sense to go with ProviderConfigUsage.

Even when folks are using composition, keep in mind that a `ProviderConfig` won't always be created by the same composite resource as the managed resources that use it.

Consider for example a case in which we had two composite resources; a `KubeCluster` and a `Batteries`. The `KubeCluster` resource composes a `GKECluster` and a Helm `ProviderConfig` for that cluster.  The `Batteries` resource composes some Helm `Release` resources. The UX being that you create a `KubeCluster`, then create a `Batteries` that deploys Helm charts to that `KubeCluster. In this case the `ProviderConfig` and the `Release` resources that use it are part of separate composite resources, and we presumably still want to ensure the `ProviderConfig` sticks around until all the releases are gone.

My feeling is that ordered deletion within a composition alone won't be sufficient. That isn't to say I don't want to add ordered deletion as an option - though I would like to be able to take our time with the design and implementation. So far my testing of https://github.com/crossplane-contrib/provider-helm/pull/31 has shown that the `ProviderConfigUsage` pattern allows us to successfully delete a composite resource that composes a Kubernetes cluster, a Helm `ProviderConfig` and some Helm releases, so if we proceed with the PCU approach we'll have more time to investigate the ordered deletion approach.

**Comment by negz** [comment]
I believe the various PRs linked from this issue are good to go. I've updated them all to use the pattern we've settled on, and moved them out of draft.
