### ISSUE TITLE
Validate CompositeResourceDefinition schemas

### ISSUE THREAD

**Issue by kelvinwijaya** [crossplane/crossplane#1752]
### What happened?
My CompositeResourceDefinition is still being created, although the composite CRD has never been created successfully generated by the operator

### How can we reproduce it?

I have invalid openAPIV3Schema which contain default value that is not supposed to be there (default value is forbidden)

![image](https://user-images.githubusercontent.com/11241076/93760764-3759e980-fc3f-11ea-9b46-1175f675c4b1.png)

### What environment did it happen in?
Crossplane version: v0.13.0-rc.114.g20493ac

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit
:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-
05-21T14:50:54Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976
", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", Buil
dDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/
amd64"}

```[tasklist]
### Tasks
- [ ] https://github.com/crossplane/crossplane/issues/4266
```

**Comment by hasheddan** [comment]
@kelvinwijaya thanks for opening this! Could you add a little more context around what is happening here? Are you saying that you:

1. Created a CompositeResourceDefinition (XRD) with an invalid schema
2. A CRD was not created in reponse

If so, this seems to be working as intended. The validation would not occur until the controller attempted to create the CRD because the `OpenAPIV3Schema` is [just a runtime.RawExtension](https://github.com/crossplane/crossplane/blob/4697894db8a2bfb7b1f1072bec1e79d7935b5de8/apis/apiextensions/v1alpha1/xrd_types.go#L127). However, it would be a nice feature in the future for us to have an admission webhook (or something of similar nature) that would reject XRDs with invalid schemas.

**Comment by kelvinwijaya** [comment]
Hi @hasheddan ,

Yes I have unintentionally created CompositeResourceDefinition (XRD) with an invalid schema, when this happened , I am expecting some error might be shown in the CompositeResourceDefinition > status > conditions.

As i have no clue about why the CRD has not been created until i go into the events logs to check
Not a very big deal just that as you mention it is good to have the validation check. 

Thanks,
Kelvin

**Comment by negz** [comment]
This is definitely something we want to do. It's similar to https://github.com/crossplane/crossplane/issues/1476, which is about validating `kind: Composition` rather than `kind: CompositeResourceDefinition`. I'm going to convert this issue to a feature request, because we don't have an issue tracking that. :)

**Comment by jbw976** [comment]
@phisco does this issue accurately capture phase 2 of your composition validation work (schema validation in https://github.com/crossplane/crossplane/blob/master/design/design-doc-composition-validating-webhook.md#notes)? If so, let's track it under #1476.

**Comment by jbw976** [comment]
Thanks for the clarification @phisco - i've added this issue that focuses on XRDs to the developer experience epic as well for tracking purposes:

* #3957

**Comment by phisco** [comment]
I have it implemented [here](https://github.com/phisco/crossplane/tree/xrd-validation), but it's based on #4128 given that there was obviously some overlap there, so I'll hold on waiting for that to get in first.
