### ISSUE TITLE
Dry-run option to show the impact of changing the desired state via XR/XRC

### ISSUE THREAD

**Issue by prasek** [crossplane/crossplane#1805]
### What problem are you facing?
In Crossplane new infrastructure can be requested by creating a composite resource (XR) or composite resource claim (XRC). Changes to XR/XRCs are also propagated to the underlying managed resources. Before changes are applied, you should be able to see the impact of such changes with a `dry-run` option that can be reviewed directly on the k8s cluster or as a check in a PR approval flow.

Note: This is particularly important where the target stack will destroy and recreate resources to realize a change and this could impact application uptime, which only happens in Crossplane if you explicitly delete the XR/XRC (i.e. Crossplane has built-in safety for incidental deletes).

### How could Crossplane help solve your problem?
Provide a `dry-run` option that works either directly on the k8s cluster or as a check in a PR approval flow.

**Comment by novocodev** [comment]
I have used Atlantis with terraform and GitHub to automatically run a plan (dry run) when a PR is raised from a feature branch. This provides a pretty good DevOps experience around IAC, it allows potential issues with cloud resources being deleted and recreated (it is not always obvious when this will happen) to achieve the requested state change, to be assessed for potential service impact.

I have just started with crossplane and I am exploring a GitOps (argoCD) approach to updating the deployment model and applying that to k8s. Currently changes to the target deployment can be be reviewed, but not the impact of those changes on the cloud resources and the potential for service outages.

If the output of a crossplane dry run could be posted back to the PR for review that would allow reviewers to identify any potential service impact before applying the changes.

**Comment by muvaf** [comment]
There are a few aspects I believe worth mentioning:
* One of the main reasons of the need for `dry-run` is to make sure no managed resource is accidentally deleted, which comes from the fact that Terraform deletes the resources if `Update` operation is not possible. However, Crossplane never makes that call unless there is an explicit deletion on the custom resource, which is similar to Kubernetes, i.e. a standalone `Pod` is never deleted unless you say so.
* Getting to higher levels, we see that in Kubernetes when you delete a `Deployment`, it deletes the `Pod`s it created. So, there is a deletion call made to `Pod` and not by the user itself directly. However, the beginning of the deletion is still started by the user as opposed to Terraform where your actions could result in deletion that you didn't anticipate in the first place due to how those resources are updated. So, users don't really need a `dry-run` option when they make a deletion call to `Deployment` because their intent is inline with what happens next and they can be sure since `Deployment` always behaves the same way. When you look at it, Crossplane needs a diff facility only as much as Kubernetes needs, which comes for free due to the fact that all is in YAML and `git` is able to tell you the correct `diff`.


Now, when we go higher level in Crossplane, we see the same deletion behavior with XRC -> XR -> managed resources. It always propagates and can only be started by the user. However, there is a subtle difference between Kubernetes, that is an XR can have N _different types_ of managed resources as opposed to `Deployment` having only `Pod` and even if it's not a code-level customization, `Composition` does allow for some logic about interpreting how the changes are propagated. So, in my opinion, it is safe for users to assume that deletion will happen only if they want, so they don't really need `dry-run` for that purpose. However, due to nature of `Composition`, they do not have the same level of confidence in change propagation that they have for `Deployment` -> `Pod`. That's where the dry-run can be useful; in order to show the final form of all of the managed resources that are composed. Though because those resources are created in runtime, i.e. what you see in a PR is either XR or XRC and `Composition`, it's a bit harder to utilize usual `git diff` (similar to how you can't see `Pod` in the PR review when you edit its `Deployment)`

Given all this brain dump, I think Crossplane CLI is where this functionality makes the most sense. It's a bit challenging and maybe we can reuse some machinery of `kubectl` to do it but `kubectl crossplane apply -f xrc.yaml --dry-run`/`kubectl crossplane edit xrc postgresqlinstance --dry-run` could calculate and show you a diff and then you can interactively decide on whether you'd like to proceed or not. Maybe a PR robot in the git repo could automatically call Crossplane CLI and show the result as a comment.

We had a similar discussion related to [changes on `Composition`](https://github.com/crossplane/crossplane/issues/1481) but I think `dry-run` is useful for all changes on the composition pipeline which includes XRC, XR and Composition. If all you have in git repo is managed resources, then I don't think `dry-run` is helpful for you.

**Comment by shanproofpoint** [comment]
This definitely is a critical tool to have before merging a change in git

**Comment by jbw976** [comment]
/fresh this functionality comes up fairly frequently

**Comment by natereid72** [comment]
>.Given all this brain dump, I think Crossplane CLI is where this functionality makes the most sense. 

Seems to me that crossplane cli makes sense. But also some form of system feedback from provider with a provider config option would be useful for gitops scenarios.

But only if there is a need for `plan` functionality given you can only delete resources if you actually implicitly delete them. Plan seems to me to be an artifact of TF apply being capable of resulting in resource deletion. This isn't possible with crossplane providers.

**Comment by jonnylangefeld** [comment]
This just came up for us as well! We'd be interested in this functionality

**Comment by zekena2** [comment]
Can this issue be reopened?

**Comment by ytsarev** [comment]
@zekena2 done

**Comment by jbw976** [comment]
@HerrTamm this issue is not currently on the [published roadmap](https://github.com/crossplane/crossplane#roadmap), but I do recognize it has some interest from the community. It will be considered in future roadmap planning efforts 🙇

**Comment by devlounge** [comment]
any update on this?

**Comment by bobh66** [comment]
There has been some discussion around allowing the composition engine to run "outside" of Crossplane, for example as a `kubectl crossplane` sub-command, and that might be a good way of providing this capability.  @negz @sttts

**Comment by negz** [comment]
Have folks seen https://github.com/crossplane-contrib/xrender yet? I think it's pretty close to what this issue is describing.

**Comment by negz** [comment]
Cross-referencing https://github.com/crossplane/crossplane/issues/4670.

**Comment by negz** [comment]
In Crossplane you could imagine dry-run happening at two layers:

1. Given a claim/XR, what set of composed resources would Crossplane desire?
2. Given a set of desired composed resources, what changes would Crossplane make to external resources in the cloud?

With `xrender`, I think we have most of the first layer covered.

Right now `xrender` works like this:

```shell
$ xrender examples/xr.yaml examples/composition.yaml examples/functions.yaml
---
apiVersion: nopexample.org/v1
kind: XBucket
metadata:
  name: test-xrender
status:
  bucketRegion: us-east-2
---
apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    crossplane.io/composition-resource-name: my-bucket
  generateName: test-xrender-
  labels:
    crossplane.io/composite: test-xrender
  ownerReferences:
  - apiVersion: nopexample.org/v1
    blockOwnerDeletion: true
    controller: true
    kind: XBucket
    name: test-xrender
    uid: ""
spec:
  forProvider:
    region: us-east-2
```

Given an XR, a Composition, and a set of Functions to use `xrender` will produce the same set of desired composed resources as Crossplane would. It doesn't actually create them - it just outputs the YAML manifests.

You could imagine getting a diff vs live state pretty easily by piping the `xrender` output to another tool that would simply grab the live XR and composed resource state from the cluster and output it in the same format `xrender` does, e.g.:

```shell
xrender examples/xr.yaml examples/composition.yaml examples/functions.yaml | crossplane diff
```

You can also figure out whether the XR and composed resources produced by `xrender` are schematically valid by dry-running them against an API server where Crossplane is installed using kubectl. For example:

```shell
xrender examples/xr.yaml examples/composition.yaml examples/functions.yaml | kubectl apply --dry-run=server --server-side=true
```

I think the question then is, how important is it to be able to cover the "last mile" where we determine what a Crossplane provider would actually do given this new desired state? Most external systems (i.e. cloud providers) have no concept of dry-run at their API level, so we can't literally dry-run apply our desired state to the external system and see whether it was valid. I think the best we could do would be to produce a diff between the current observed state in the cloud and the new proposed desired state. The challenge with that will be somehow extracting the relevant logic from every provider and making it run client-side (I agree with @muvaf that this functionality belongs in a CLI tool, not in the "live" control plane).

**Comment by muvaf** [comment]
@negz `xrender` looks great! I think getting the MRs rendered and smartly diff'ed with live resources will cover plenty of use-cases because diff is most useful for the layers with complexity and we have the complex logic consolidated at XR->MR level. Because MRs are just the lowest level, seeing diff lines on them will be quite useful. One caveat could be XRs managing other XRs, hence we may need to think about recursive lookup that shows only leaf node diffs. Wonder if the updated charter of Crossplane that includes developer experience and a CLI tool could include this. Will we start publishing an official Crossplane CLI?

**Comment by bobh66** [comment]
Functions are not required in 1.14 but they will be a beta feature that will be on by default.  There is work underway to implement the  current Patch and Transform mechanism as a function which will allow us to migrate the current functionality into the function implementation which has a lot of benefits.  But at least for the short term there is no direct impact on the existing P&T/

**Comment by negz** [comment]
> Wonder if the updated charter of Crossplane that includes developer experience and a CLI tool could include this. Will we start publishing an official Crossplane CLI?

It does, and we will. 😄 Check out https://github.com/crossplane/crossplane/issues?q=is%3Aopen+is%3Aissue+label%3Acrossplane-cli

**Comment by Speeddymon** [comment]
> Functions are not required in 1.14 but they will be a beta feature that will be on by default. 

Assuming this was in answer to my question ("I like xrender, but curious about if functions are required?") -- this question was regarding xrender - is specifying a manifest with functions required on the xrender command line?

**Comment by negz** [comment]
I wrote up some ideas on an architecture that could enable end-to-end, cloud-to-claim `xrender`-like dry-run functionality in https://github.com/crossplane/crossplane/issues/4723. I think this would let us build a good user experience, but it would be a reasonably big architectural change to how we build providers today.

**Comment by negz** [comment]
>  is specifying a manifest with functions required on the xrender command line?

Yes, `xrender` only works with Functions and requires to give it a manifest of Functions so that it knows what versions of each Function it should use to render your XR.

**Comment by wojciechka** [comment]
I think this `crossplane beta render` would be very useful for resources based compositions as well. This mechanism seems less complex than functions, but currently there is no way of testing whether changes to compositions will trigger a change to the managed resources.

I agree that dry-run may not be the best option at this point, but perhaps something to allow temporarily setting `managementPolicies` to `Observe` only and then be able to test whether there are changes to be applied and ideally exactly what the changes would be.

In theory it's possible to compare `spec.forProvider` with `status.atProvider`, but the two are somewhat conflated. The only option with going that route is to set the `managementPolicies` to `Observe`, capture `spec.forProvider` before and after applying changes at the composition level.

This is a lot of potentially manual (but possible to automate) work that needs to happen. It'd also need to happen for all potentially affected resources.

**Comment by negz** [comment]
@wojciechka I don't think `crossplane beta render` will support "native" resources based Composition. This is because:

* It's awkward to do. The `crossplane` CLI would need to compile in the native P&T implementation, and you then run into all sorts of versioning issues. The `crossplane beta render` output would only be accurate if you were running a `crossplane` CLI that used the same P&T implementation as whatever control plane you planned to use your Composition with.
* Long term, I think we should deprecate native P&T per https://github.com/crossplane/crossplane/issues/4746.

If you want to use `crossplane beta render` with a P&T style Composition I recommend migrating to https://github.com/crossplane-contrib/function-patch-and-transform once v1.14 is released.

**Comment by wojciechka** [comment]
@negz Thank you for all the information. I was reading 1.13 docs and they all stated functions are alpha while P&T is stable. Good to know it's the other way around and I should get familiar with functions.

Using P&T as a function sounds like a better idea as the version of function is independent from version of crossplane.

I'll keep an eye out for 1.14 in that case. Is it still scheduled to be out later this month?

**Comment by negz** [comment]
> Is it still scheduled to be out later this month?

It is! Or I think technically we're scheduled for November 1st.

**Comment by Cliftonz** [comment]
@jbw976 Why was this removed from the roadmap? Do you have any insights of why this would not be prioritized?

**Comment by Speeddymon** [comment]
It still has the milestone...

**Comment by jbw976** [comment]
Good question guys - yes this was consciously removed from the roadmap because we don't think we'll deliver it in the near future. Leaving it in the milestone was an oversight, so thanks for pointing that out.

We have taken a big step on an impactful portion of this functionality with the `render` command ([docs ref](https://docs.crossplane.io/v1.14/cli/command-reference/#beta-render)) that is now available as of the v1.14 release.  We'll now be turning our focus towards other functionality that we believe will have a high impact on adoption and success of the project, for example:

* https://github.com/crossplane/crossplane/issues/5172
* https://github.com/crossplane/crossplane/issues/4729 

As you may expect, we will have a limited number of contributors focusing on driving big features over the next few releases and we're choosing to prioritize other items in the roadmap for now. Hope that helps! 🙇‍♂️

**Comment by KlavsKlavsen** [comment]
Our usecase for this - is that we are NOT allowed to change production systems outside service windows. This is pretty much a universal requirement in all larger corporations.
This means that we would only argocd sync in these - so technically that SHOULD not happen.
BUT sometimes people change things outside gitops - which they should not - and in that case we NEED to :
1) detect the change has happened (a controlplane diff - should do this). We do this for servers, using puppet today (it sends a report of changes it WANTS to do - and if thats none-zero we know something/someone changed something they should not have done
2) be able to test our changes - by doing what xrender above seems to do - dry-run change to verify it will result in what we think it will
3) we need to somehow ensure controlplane does not 'auto reconcile' objects it manages.. same way argocd just reports -out-of-sync- - which will trigger an alert for us - but NOT try to auto remediate it.. so that we can evaluate.. and sync/reconcile in service window.

**Comment by bobh66** [comment]
> we need to somehow ensure controlplane does not 'auto reconcile' objects it manages.. 

This seems counter-intuitive, since the purpose of using the control plane is to ensure that the resources remain synchronized to their desired spec.  If someone makes a change outside of gitops, that change will be reverted as soon as it is detected.

This workflow is more like terraform plan/apply than control-plane/gitops.

**Comment by KlavsKlavsen** [comment]
Problem is every change has riske.. sometimes people do things outside gitops for good reasons.. or bad ones.. but controlplane budding in and always reverting at will - just increases operational risk.
Thats why large corps have ITIL rulesets that say, every change only happens with a service window allocated and tracking of changes. 
Thats why its fantastic when controlplane can detect the "unregulatory change" and alert about it - but forcing a revert can be a problem too.
With Puppet - that can do both - force revert - or just report - depending on what resource is changed(per our config)- we use that a lot. Some things are set to be auto-reverted.. (and when its files its clearly marked in top with comment that this will happen)  and most are not - and this saves us a lot of grief - when we can flag a change someone made outside gitops/operations team (often without thinking or because they 'didn't have time') - then we trip them up - but we're aware of the change and can ensure it gets to git asap.

So in an inperfect world - its just nice to be able to play nice with others - but be fully aware of all changes in the environment :)

**Comment by Speeddymon** [comment]
I like `kubectl diff` for this use case. It's not perfect, admittedly, because it won't render a composition for you and show what's going to change, but if you're simply declaring provider resources directly, it's perfectly fine and will show what's going to change without any issue.

**Comment by Speeddymon** [comment]
> Problem is every change has riske.. sometimes people do things outside gitops for good reasons.. or bad ones.. but controlplane budding in and always reverting at will - just increases operational risk.

Unfortunately, this is a management problem. If you're doing gitops, management should enforce usage of gitops and any manual changes should be prohibited. If a manual change is necessary for some reason, then whoever is running gitops needs to be brought into the call so that they can pause reconciliation in the gitops controller and switch to observe only mode in Crossplane any of the resources that are going to change temporarily.

> Thats why large corps have ITIL rulesets that say, every change only happens with a service window allocated and tracking of changes.

And manual changes fall under these rules. So you should be involved in the change process in order to do that I described above. These aren't crossplane issues unfortunately. 

> Thats why its fantastic when we can detect the "unregulatory change" and alert about it - but forcing a revert can cause problems.

Crossplane will not revert resources if a destroy is required. At least not in AKS. It may depend upon the provider. Are you using the Terraform provider for crossplane? The only reverts that will happen using a native crossplane provider are those considered non destructive.

**Comment by c-p-b** [comment]
I notice Cloud Change Logs was merged a few weeks ago. Is the intent to build this diff-like feature on top of that?

**Comment by davejhahn** [comment]
Adding a comment, since there hasn't been any further updates on this in 5 months....

Not knowing if something is going to be deleted and re-created or just inadvertently deleted until the point in time a deployment is pushed out is a significant risk in my opinion.   I would say this is a critical requirement and without some ability to analyze what will happen, it is probably a showstopper in using Crossplane for me.

**Comment by Cliftonz** [comment]
@davejhahn after working with Crossplane, dry-runs are definitely not a part of the design.
The idea is that you're leveraging Crossplane to create a new plane to test what you're doing as a canary or a "dev"/"QA" system before it goes into production. 

I do agree that some visualization is needed here

**Comment by KlavsKlavsen** [comment]
so you're not supposed to use dry-plan to maintain production configurations @Cliftonz ? or am I somehow misunderstanding you?

**Comment by Cliftonz** [comment]
@KlavsKlavsen That is not correct. All I am saying is that Crossplane does not have a dry-run feature because it is inherently eventually consistent with provisioning infrastructure. 
So it's telling you what it can and cannot create/change/delete as the k8 API is trying to reconcile what Crossplane has told it.

Upbound cloud has some level of visualization which could be used in place of dry-run, but it does not have this capability in the open-source. 

Past this I do not have much more input, I agree there always tends to be "some manual change" and we need to "test" it out before making any changes, but this is definitely a weak point of Crossplane.

**Comment by liorfranko** [comment]
@denosaurtrain 
We started using Crossplane but decided to manage resources directly without compositions due to the lack of dry-run capability.
For our critical infrastructure resources, we disabled ArgoCD auto-sync, allowing us to review actual resource changes before applying them.

You can achieve similar results using a simple Helm chart (though you'll miss the function-sequencer functionality).

One remaining concern is provider upgrades - changes in provider behavior can still impact resources unexpectedly without a dry-run option to preview them.

@Cliftonz While ArgoCD is also an operator, they implemented dry-run functionality.
Adding this single feature would significantly increase Crossplane adoption.

**Comment by jcogilvie** [comment]
Following up on the community meeting today, my team would like to take a stab at taking this the last mile, especially with v2 around the corner where our immediate solution could potentially drive some requirements to make this easier or more feature-complete in the future.

I think `crossplane render` does a great job of getting us most of the way, but there's still a gap in evaluating how the rendered MRs differ from the cluster.

Since `crossplane xpkg` already reaches out to the cluster from the CLI tooling, it stands to reason that we could implement something in said tooling akin to `argocd diff` that takes some potential desired state and compares it to the live state. 

I think as a very early first draft, a client-side (ish) `crossplane beta diff` might look like this:

```
crossplane beta diff [xr1.yaml, xr2.yaml, ..., xrN.yaml] -- [manifests...]
```

```
diff():
  foreach xr in (xrs+manifests):    # xr or claim, file or stdin
    comp = kubectl get composition (xr.kind)
    extraResources = kubectl get (comp.extraResources...)
    env = kubectl get (comp.environmentConfig...)
    fns = kubectl get function (comp.functions...)
    desired = crossplane render xr comp fns -e extraResources # or should this be -o for observed resources?
    liveSchema = kubectl get xrd (xr.kind)
    _ = crossplane beta validate desired liveSchema
    foreach res in desired:
      print "$(kubectl diff -f res)\n---\n"
```

A server-side impl (which is probably the next phase, and also the best long-term solution) would replace the `crossplane render` call with a dry-run of the function pipeline executed (but not applied) on the cluster itself, which of course already has the references to the extra resources, env configs, functions, etc. at hand.

Goals:
* provide a client-side way (via CLI) to see as accurately as possible the resulting diff of MRs from any given XR change
Stretch goals:
* expand from XR changes to show diffs resulting from environmentconfig, function, provider changes

Non-goals:
* retain state of desired vs. actual configuration on crossplane with a delayed, human-initiated sync, like argocd does
* find an integration point for argocd to be able to fan-out diffs from MR changes

Concerns we'll have to address:
* derived attributes from prior pipeline steps may not exist in downstream steps (e.g., if I am creating an aws resource I won't know the ARN of a thing if I need to plumb it downstream).
  * proposal:  a dirty bit for things that reference `.status`?  like terraform `(known after apply)`

Other thoughts:
* some providers are built on terraform, and thus may have terraform plans that they could emit -- might be useful?

What are your thoughts @jbw976?

**Comment by chlunde** [comment]
> I notice Cloud Change Logs was merged a few weeks ago. Is the intent to build this diff-like feature on top of that?

I assume here you want to either:
* Get a "cloud change log" before changing a composition (as a platform developer)
* Get a "cloud change log" before changing a claim (as an end user)

I don't think that would be possible, you would have to run another copy of the provider somewhere, or create actual kubernetes resources (with managementPolicies: Observe) to get that output?

But I do think that is a valid use-case to
* de-risk migration from other tooling to crossplane (importing resources)
* for major changes, by turning a composition into Observe only mode.
 
I wonder if we could either:
* Extend the cloud logs feature by declaring that Observe could produce a change log plan/intent/diff
* Add another explicit managementPolicy "Diff" or "Plan", or some other toggle/annotation, that would make the Observe step produce a diff.

I don't think there is any clean solution to this part (provider diff) of the problem that would be part of a normal day to day operation.

If people agree, maybe this should be forked out as a different proposal issue. I think @jcogilvie talked about something like this in the community meeting.

**Comment by raweber42** [comment]
A workaround for me is to get the live yaml manifests (composition and composite), adjust them according to the changes I am planning to implement and then use `crossplane render` as described [here](https://docs.crossplane.io/latest/concepts/compositions/#test-a-composition) to check the outcome.

Not pretty, but for now does the job 😄

**Comment by c-p-b** [comment]
I took a stab at this by wrapping the [great tool](https://github.com/crossplane-contrib/crossplane-diff) @jcogilvie and team released.  Currently it has an argo/flux dependency, and some caveats about setting up your XRs/XRDs in a somewhat opinionated way. But if you're willing to work within those constraints, it does appear to work as a full atlantis-like E2E solution. There are still edge cases to be solved, as there are a fair amount of moving gears here in terms of complexity. Curious to get the community's feedback to this approach as I'm kind of new to crossplane

https://github.com/millstonehq/crossplane-plan

The primary reason I introduced the argo/flux dep here is deletion detection - it's doable without, but would require some pretty icky state management or some complex diff logic to detect all possible deletion scenarios, problems argo and flux have already solved for us.
