### ISSUE TITLE
Configuration package global parameters

### ISSUE THREAD

**Issue by marcinc** [crossplane/crossplane#1922]
### What problem are you facing?

In a configuration package containing several XRDs and compositions I often come across composite resources which require infrastructure knowledge such as (externally created) VPC IDs, Subnet IDs etc, related to a target Kubernetes cluster which configuration package is going to be deployed to. 

Currently the only solution available is to parametrise these details at XRD level. User experience is poor and it leads to unnecessary repetition. I'd like to be able to hide the platform specific details which are irrelevant to the end user at the time they claim a new managed resource, and only require parameters which mean something to them such as storage size or region etc. 

### How could Crossplane help solve your problem?

Crossplane could solve the above issue in a couple of different ways:

1) Adding global parameters section at the package level and a reference mechanism so that those parameters can be used across compositions. This way the shared infrastructure related details such as VPC IDs can be defined in a central place and referred to from the individual resource configuration, whenever necessary. 

2) Adding an additional data "container" in Crossplane to store global user defined configuration parameters and a mechanism to resolve those parameters dynamically at runtime in compositions referencing them. 

Solution one isn't ideal as it requires baking parameters in before package building and publishing which would inevitably limit its use. Package is no longer generic.

Solution two would be ideal from the package builder’s and end user’s perspective. It reduces repetition, removes necessity to collect those infra related parameters from the resource claimer, and keeps the configuration package generic.

**Comment by negz** [comment]
@marcinc Would something like a `FromConfigMap` patch type work here? i.e. You could put your globals in a ConfigMap, then have your package install a `Composition` that will patches a particular composed resource field (e.g. VPC ID) from a value it reads from a ConfigMap (or Secret?) data key?

**Comment by hasheddan** [comment]
I like the idea of pushing this to the composition layer rather than the package layer as it could become quite messy to be maintaining (potentially diverging) templating languages at each level :+1:

**Comment by marcinc** [comment]
@negz Yes, this sounds good! Composition patching by referencing existing ConfigMap key would work very well I think 👍 By the same token `FromSecret` patch would be very useful too.

**Comment by janwillies** [comment]
Yeah that sounds great. We found the same pattern in provider-helm quite useful

**Comment by turkenh** [comment]
I was about to create a new issue titled "Deploy time parameters for configuration packages" with the same arguments and found this issue. 
@marcinc explained the reasoning pretty well and I have a slightly different point. Instead of calling these as `global parameters`, I would prefer to say `deploy time parameters` which are known at configuration package deploy time by platform operators and not specific per Claim/XR instance.

As a workaround, I am finding myself packaging Crossplane compositions/XRDs as helm charts which allows me to provide parameters at deploy time and [use conditionals](https://github.com/crossplane/crossplane/issues/2712) while packaging.

In addition to the two proposed solutions in the issue description, I would like to add a third one:

3. We could define a new type called `ConfigurationParameters` and have a reference to it from Configuration Package type, similar to Provider Package -> Controller Config. Then we would need a way a mechanism to use these parameters across compositions.
