### ISSUE TITLE
Is there plan to support copying connection info from configmap?

### ISSUE THREAD

**Issue by haoqing0110** [crossplane/crossplane#1962]
### What problem are you facing?

Is there plan to support copying connection info from configmap?

2 reasons why need this support:
- Generally some connection data may not only stored in `Secret`, but also stored in `Configmap`
- This might also be a follow-up requirement of https://github.com/crossplane/crossplane/issues/1730 . 
If crossplane supports composing arbitrary Kubernetes resources, that means connection data may not only stored in writeConnectionSecretToRef. 

A similar issue is https://github.com/crossplane/crossplane/issues/1609 

### How could Crossplane help solve your problem?

What to know if there's plan to support this.

**Comment by pgodowski** [comment]
I think the binding concept shall be similar to the Service Binding Operator concepts: https://github.com/redhat-developer/service-binding-operator  , which is not limited only to `Secrets`.

**Comment by muvaf** [comment]
Hi @haoqing0110 ! What is your use case? Is this `ConfigMap` part of the `Composition`?

**Comment by haoqing0110** [comment]
@muvaf `configmap` is similar to `writeConnectionSecretToRef`, while some non-sensitive data might write not only to secret. 

A more general case is to copy `service binding info` back , as https://github.com/redhat-developer/service-binding-operator describes,  "Backing Service Operator that exposes binding information in secrets, config maps, status, and/or spec attributes. "

**Comment by muvaf** [comment]
The `writeConnectionSecretToRef` is used to reference the `Secret` that the provider will write credentials to. However, https://github.com/crossplane/crossplane/issues/1609 addresses the case where you'd like to populate that `Secret` with information that exists on the custom resources you're composing rather than their secrets.

So, do you want Crossplane to dump the credentials into a `ConfigMap` or do you have a `ConfigMap` that you need Crossplane to fetch some values from and put them into the final connection `Secret`?

**Comment by haoqing0110** [comment]
@pgodowski ^^^ any comments for above question?

**Comment by pgodowski** [comment]
@muvaf the use case scenario that we are after is that the underlaying custom resource which we're composing has both Secret and ConfigMap resources. In Secrets are kept the sensitive details (mostly, username/password), whereas ConfigMap contains basic service attributes (like connection URL, parameters of the exposed service, for service consumer's use cases). The non-sensitive data does not need to be stored in Secret.

Essentially, the ask here is to have Crossplan providing support not only for connection Secret, but also connection ConfigMap.

**Comment by muvaf** [comment]
Alright so here is what I understand, please correct me if I'm wrong. You have a managed resource that you implemented, let's call it `AcmeResource` and the controller you wrote for it creates both `Secret` and `ConfigMap` resources that contain the connection information. Now, you'd like to use `AcmeResource` in a `Composition` resource. However, in composition, we only support `resources[*].connectionDetails` to get the values from a `Secret`. What you'd like to achieve is that you want `resources[*].connectionDetails` to also go over a `ConfigMap` that was created by the controller of `AcmeResource`.

Is that what you're asking?

**Comment by haoqing0110** [comment]
@muvaf the controller will create both `Secret` and `ConfigMap`. copy `Secret` to `Secret` is already covered by crossplane,  expect Crossplane to also fetch some values (non-sensitive data) from `configmap` and put them into the final connection `configmap`.

**Comment by muvaf** [comment]
Alright. Currently, composition mechanism is designed to work with managed resources and that enforces controllers to have their output in either on the managed resource itself or in a `Secret`. I don't think we have any plans to expand the managed resources to produce a `ConfigMap` output, too. There is an [issue](https://github.com/crossplane/crossplane/issues/1730) tracking whether composition mechanism should allow any arbitrary Kubernetes resource to be composed but even if we allow any CR to be composed, we'd most probably not expand the composition engine to work with a generated `ConfigMap` (not included in `Composition`) as output or input for connection details.

**Comment by negz** [comment]
I'm a little unclear on whether this issue is actually asking if we will support copying connection details _from_ a `ConfigMap`, or _to_ a `ConfigMap`. I don't see us natively adding support to copy _from_ a `ConfigMap` - this isn't something we've had any demand for outside of this issue - though I could imagine a particular provider choosing to do that.

When it comes to writing _to_ a `ConfigMap`, I could imagine that being a sink supported by the design underway in https://github.com/crossplane/crossplane/issues/2366.

I'm not sure what further action to take here, so I'm going to close this issue. Please let me know if you think this needs further discussion.
