### ISSUE TITLE
Add field to ignore specific label propagation to Composite Resource

### ISSUE THREAD

**Issue by mcavoyk** [crossplane/crossplane#2000]
### What problem are you facing?

Background: https://crossplane.slack.com/archives/CEG3T90A1/p1607026377006100

ArgoCD uses a label to indicate ownership of a Kubernetes resource to an application. Any resource with this label that is not deployed as part of ArgoCD could be deleted as part of the next application sync. Composite Resource Claim (XRC) automatically propagate all labels and annotations to their Composite Resource (XR), this causes ArgoCD to pick up ownership of the XR and desire deletion.

### How could Crossplane help solve your problem?

One option could be support a label/annotation on XRD's which indicate to ignore propagation of a different label. @hasheddan proposed the label `ignore.crossplane.io/label: <name-of-another-label>` in slack. In this case the label value may need to support something like a comma separated string array to allow ignoring multiple labels.

**Comment by enderv** [comment]
Was taking a look at this and ran into some issues. Based on the current [setup](https://github.com/crossplane/crossplane/blob/master/internal/controller/apiextensions/claim/configurator.go#L55) looks like the only place currently to supply the label would be on the XRC which would require the end user to know what labels to ignore instead of the infrastructure operators. 
Thoughts on making this a flag at startup that can be passed down for the configurator to use?

**Comment by muvaf** [comment]
When I look at Kubernetes ownership relationships between objects, I don't really see a full-copy of labels done like we do. It's usually under spec template like `spec.podTemplate.metadata.labels`. So maybe we shouldn't copy any label/annotation of claim to composite at all and have a spec field in claims for additional metadata to be copied over to composite resource.

**Comment by negz** [comment]
@muvaf I like that idea, though if possible it might be preferable to describe which labels/annotations should be propagated between the claim and its XR be defined in the XRD.

**Comment by muvaf** [comment]
> it might be preferable to describe which labels/annotations should be propagated between the claim and its XR be defined in the XRD.

That's an interesting angle. It'd enable admins to decide what's propagated, which would cover the cases that are common to all claim<>composite instances, which would be useful for cases like #2121 . On the other hand, there are cases where you want to allow claim creators to specify the metadata that'll be propagated, like `external-name` annotation (though this could still be done by admins with optional patch).

Honestly, I'm not able to come up with a guess about which cases would be more common, but I feel like having it similar to `Deployment` and other Kubernetes resources would likely be more familiar to users. I can't really say if it's more inline with Kubernetes patterns because admins don't have an XRD level in native Kubernetes resources. I guess there is nothing stopping us having that ability in both places, but I feel like one of them would be enough to cover most cases we're aiming to cover. Happy to hear more use case examples.

Though in any case, I think we should stop copying the metadata because it's surprising (writing this more freely because I wrote that code haha).

**Comment by marshmallory** [comment]
@blut is correct for this being a workaround.  For our purposes, we did need to tweak the settings slightly since Composite was far too broad.  Also, we are on an older version: 1.7.10, so things look a little different.

This is the code we added to our project.yaml to restrict the resource:

`  clusterResourceBlacklist:
  - group: '*'
    kind: 'CompositeTelematicPattern*'`

**Comment by tlmcphillips** [comment]
I've been struggling with this same issue after watching the following video: https://www.youtube.com/watch?v=yrj4lmScKHQ

It's never really covered how you redeploy and update the various bits you deploy using CP and ArgoCD. What you'll end up seeing is that the claims will always flag your claims as not being in sync because they don't exist in the repo. This is not ideal because it goes against the very idea of GitOps. 

![image](https://user-images.githubusercontent.com/92390946/142520130-86b81c70-a600-4924-afc2-b4728846dce6.png)
