### ISSUE TITLE
Flesh out Crisscross Proof of Concept

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#2109]
### What problem are you facing?

Crossplane provides a broad library of Kubernetes custom resources that let you orchestrate systems external to Kubernetes. These include AWS S3 buckets, GCP CloudSQL instances, Azure Cosmos tables, plain old SQL databases, Helm releases, and Dominos pizzas. We call these 'managed resources'. Crossplane's goal is to allow platform teams to build their own custom resources that are in turn composed of these primitives without needing to write Kubernetes controllers in Go. [Crisscross](https://github.com/hasheddan/crisscross) is an experimental project that lets folks add new managed resources to Crossplane without writing Go code. We would love help fleshing out the Crisscross proof of concept.

### How could Crossplane help solve your problem?

This will likely take the form of writing a web service with endpoints that accept CRUD verbs from Crossplane and uses them to orchestrate an external system - for example CRUDing a DigitalOcean Droplet or an OpenStack Server. Familiarity with Go is a bonus (Crisscross itself is written in Go), but not necessary (Crisscross managed resources can be written in any language).

**Comment by diru1100** [comment]
Hey @negz,

I would like to work on this issue.

**Comment by jbw976** [comment]
hey there @diru1100, thank you for your interest and enthusiasm!  This issue is open for applications through the LFX Mentorship program, which is accepting applications until Feb 12th.  Do you mind submitting an application there so that we can consider you fairly along with the the other engineers that have already applied?  Let me know if you need any help and thanks again for your interest! 💪 

You can apply here: https://mentorship.lfx.linuxfoundation.org/project/55f5e428-bf78-480d-81db-55eef0c4d293
