### ISSUE TITLE
Cannot update Provider when CRD version is dropped in favor of new version

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#2165]
### What happened?

When upgrading `provider-aws` versions I noticed that the new version was unable to establish control of its API types because `BucketPolicy` moved from `v1alpha2` to `v1alpha3` and dropped `v1alpha2`, causing update to fail because the `status.storedVersion` did not exist in the `spec.versions`.

```
Warning  SyncPackage        4m2s (x69 over 43m)  packages/providerrevision.pkg.crossplane.io  cannot establish control of object: CustomResourceDefinition.apiextensions.k8s.io "bucketpolicies.s3.aws.crossplane.io" is invalid: status.storedVersions[0]: Invalid value: "v1alpha2": must appear in spec.versions
```

This is not necessarily a bug with the package manager, as it could be avoided by the provider supporting both versions for a release with a conversion strategy of `None`. It can also be fixed by just `kubectl delete bucketpolicies.s3.aws.crossplane.io` which will result in the package manager creating it again with just `v1alpha3`, at which point the new `ProviderRevision` will become healthy.

xref https://github.com/kubernetes/website/issues/18248

### How can we reproduce it?

1. Install `provider-aws:v0.16.0`
2. Update to `crossplane/provider-aws:v0.17.0-rc.0.82.g8e959563`
3. See `ProviderRevision` does not become healthy

### What environment did it happen in?
Crossplane version: v1.0.0

**Comment by muvaf** [comment]
This is a case where we dropped support for an alpha CRD that doesn't have any upgrade guarantees. I think this is a valid scenario that our machinery should be able to handle. `None` would not work because we don't bump the apiVersion if it's compatible in a way `None` could work.

Maybe one way to handle this is to check whether there is any instance of that old CRD, if so reject the update and expect manual intervention. If there isn't any instance, remove the old one and create the new one?

**Comment by hasheddan** [comment]
> I think this is a valid scenario that our machinery should be able to handle.

Yeah the issue with this scenario is that is valid because of the written guarantees we make, but it is not actually codified. I think maybe the machinery is essentially handling this correctly here but forcing a user to manually delete the CRD is they want to upgrade to the new version. I feel more comfortable with that than automatically cleaning up a CRD.

**Comment by muvaf** [comment]
@hasheddan do you mean you don't want to automatically delete the CRD even if there is no instance of it?

**Comment by hasheddan** [comment]
@muvaf yes. While that would be a safe operation, I like the fact that we currently have the property of never directly deleting a CRD, meaning that a CRD is only ever cleaned up via garbage collection when all of its owners are deleted. We could certainly revisit this strategy if enough folks are in favor though.

**Comment by muvaf** [comment]
> I like the fact that we currently have the property of never directly deleting a CRD, meaning that a CRD is only ever cleaned up via garbage collection when all of its owners are deleted.

Agreed, no deletion call gives peace of mind. Moving the discussion from Slack to here.

I think there are two problems here:
* Users either are not aware that they deploy alpha resources, or contract about alpha resources, or don't know how to upgrade them manually.
* Our alpha contract, i.e. no upgrade support, is hindering the usage of Crossplane because most of provider CRDs are currently alpha.

I think we should fix the first problem in all cases. With the current tools I feel like the best way would be that package manager could report back (before starting the upgrade) which alpha resources need manual upgrade, i.e. the ones with instances in the cluster, and a link to a guide. Or we can detect the error during `Apply` of those CRDs, and tell users to fix it.

While this doesn't fix the second one completely, the manual upgrade instructions would help a lot. Bumping them to beta would help as well. But additionally, if the schema change is only name change of the fields or structs that can be done easily, we can add the conversions in a `BestEffort`  manner for alpha resources, too, once webhook implementation is in place. No change in contract but less problems in practice.

**Comment by hasheddan** [comment]
> With the current tools I feel like the best way would be that package manager could report back (before starting the upgrade) which alpha resources need manual upgrade, i.e. the ones with instances in the cluster, and a link to a guide.

This feels pretty reasonable, but I do want to point out again that I think we can get tunnel-vision with how the primary providers that the crossplane community works vs the contract of what a provider actually is. I get worried about saying "this is how you can fix the alpha resource" because it may not be accurate in all cases. For example, it makes me a little uneasy to be saying something like "is there a substring of `alpha` in this version? okay then it must adhere to this strategy" because we don't actually force that on providers.

I wonder if we took a more general approach and just evaluated if any CRDs at any level are changing version, and if instances of them exist then we notify and do not upgrade unless a certain policy is set (so just a slight variation of what you are proposing). I am also wondering if folks are going to eventually want to define any custom behavior in this case. It could be that we can pretty easily cover every variation and supporting any plugin model would be overkill, but it might be worth exploring if users want to be able to say something like "block upgrades only if the `Bucket` schema / version changes", etc.

**Comment by negz** [comment]
> Users either are not aware that they deploy alpha resources, or contract about alpha resources, or don't know how to upgrade them manually.

I think investing in making this expectation more obvious would be a great start - perhaps a section on our documentation site that briefly defines what alpha, beta, and v1 APIs mean to us.
