### ISSUE TITLE
CLI Code Scaffolding

### ISSUE THREAD

**Issue by krishchow** [crossplane/crossplane#2188]
### What problem are you facing?
Currently, there isn't really a good way to scaffold new resources + controllers in a Crossplane Provider. The workflow right now (as far as I know) is just to copy code from another related resource, and then find-and-replace all the relevant fields, this works but it isn't a good DX and it can lead to small bugs.

### How could Crossplane help solve your problem?
Add code-gen functionality to the Crossplane-CLI.

**Comment by negz** [comment]
https://github.com/crossplane/crossplane-tools is where we've historically put general-purpose tooling for building Crossplane providers (e.g. tooling that isn't specific to a particular provider or pattern, like our ACK and Terraform efforts). In this case it sounds like you're proposing putting such tooling in the `kubectl crossplane` CLI, which has historically been user rather than developer facing. Do you think building this functionality in crossplane-tools would make more sense?
