### ISSUE TITLE
How to create a connection secret in the same namespace as a claim

### ISSUE THREAD

**Issue by mf-lit** [crossplane/crossplane#2195]
### What happened?

When making a composite resource claim, it would be useful to be able to have any connection secret created in the same namespace as the claim itself (certainly this seems a very likely use-case to me).

I expected to be able to do something like this in the definition of my composite to have just that:
```
    patches:
    - fromFieldPath: "metadata.namespace"
      toFieldPath: "spec.writeConnectionSecretToRef.namespace" 
```

However, that doesn't work:
`cannot use dry-run create to name composed resource: .... is invalid: spec.writeConnectionSecretToRef.namespace: Required value`

I found I can work around the problem by making the target namespace an explicit parameter:
```
    patches:
    - fromFieldPath: "spec.parameters.secretNamespace"
      toFieldPath: "spec.writeConnectionSecretToRef.namespace" 
```

That seems a bit redundant though. Is there a more intuitive way to do this?

* Kubernetes 1.19 (EKS)
* Crossplane 1.1

**Comment by muvaf** [comment]
Hi @mf-lit ! That's actually one of the main features of claims. You can use `spec.writeConnectionSecretRef.name` to specify a `Secret` name to be created in the same namespace once the claim gets ready. [Here](https://crossplane.io/docs/v1.1/getting-started/provision-infrastructure.html#claim-your-infrastructure) is an example that does that and uses the `Secret` to mount to a `Pod`.

**Comment by mf-lit** [comment]
Hi @muvaf - thanks for the quick reply! I must admit I'd completely overlooked the fact that `spec.writeConnectionSecretRef.name` could be set on a claim 😳 

This does lead me to another couple of questions though. I see in the `Composition` defined [here](https://crossplane.io/docs/v1.1/concepts/composition.html#specify-how-your-resource-may-be-composed) that a default is set.

 - Is that default compulsory? If not, where would the secret be written, or would no secret be written at all? Or would the claim be rejected for not providing a value?

 - Is it possible to make the default be the namespace of the claim?

**Comment by muvaf** [comment]
I think there is some confusion here. There are three levels:
* Managed resource connection secret: each managed resource creates a secret and you specify where it goes under `spec.writeConnectionSecretToRef` that includes namespace.
* Composite resource has a secret and you can specify its namespace using `Composition`'s `spec.writeConnectionSecretsToNamespace`.
* Finally, the claim secret which is a copy of composite one; its namespace is always the namespace of the claim but you can choose its name.

This leveling is done so that you can specify which keys from which managed resource secret you want to put into the final composite/claim connection secret. In short, there is not default namespace for claim secrets; it's always where the claim resides.

**Comment by mf-lit** [comment]
Closing this, it was indeed confusion on my part. Thanks for summary @muvaf, it was really helpful.
