### ISSUE TITLE
Document best practice for external resource updates that require delete + create

### ISSUE THREAD

**Issue by displague** [crossplane/crossplane#2258]
### What problem are you facing?

I was looking for guidance in https://github.com/crossplane/crossplane/blob/master/design/one-pager-managed-resource-api-design.md on how best to handle a resource spec property that would require the remote resource to be deleted and recreated.

My expectation in this case was that the field would act like a Terraform `ForceNew` field.  The users intention to change this field would represent an intention for the remote resource to be recreated, despite the problems that this could introduce.

The chief problems being:
* a change of external name (a new UUID at the external provider)
* a change of status properties that may be pivotal to the function of related resources (IP Addresses, secrets)

The precise situation I am trying to address is one where the user has provisioned a VM or bare metal resource with `userdata`  (relates to https://github.com/packethost/crossplane-provider-equinix-metal/issues/54).  Userdata defines the scripts and configuration typically applied on first-boot.  Depending on cloud provider, changes to this API field may be permitted or not. Depending on the OS, changes to this API field may effect reboots, or not. Depending on environment, live changes to this field may be meaningful to applications without reboot.

The cloud provider's expectation in building these APIs is that a user wanting to reboot into a changed userdata could just issue a reboot command.  Similarly, a cloud provider may expect users to delete and recreate a VM or bare metal instance to effect new userdata.

Cloud providers are aware of the problems that delete + create impose in VM and bare metal resources.  It is typical to find a `reinstall` option that will retain the external resource's UUID and IP Addresses.
 
### How could Crossplane help solve your problem?

I would like to see clarity in best practices guides on how providers are expected to behave. What conventions do Crossplane users expect so that provider authors can avoid violating those expectations.

1. The words "destroy", "delete", "recreate", and "reprovision" do not appear in the best practices (in this context). Terraform provider authors are familiar with these concerns and may look for similar guidance.

   Is there a strong expectation that a provider will never delete a remote resource? Why? What challenges would a provider face if they chose to do so (would the external name be stuck, for example)? Are these challenges only imposed by the Crossplane Runtime?

   What if a hypothetical resource does not have the negative properties of deletion (perhaps by accepting `PUT /external-name` rewrites), is it safe for a provider to effectively delete and recreate the resource on 'update' in that case?

2. It seems that behavioral changes to a resource are reasons to add `spec` fields outside of `forProvider`, is this advised?

   ```yaml
   spec:
     reinstallOnUserdataChanges: true
     forProvider:
         userdata: |
          ...
   ``` 

   Changes in `userdata` may have useful side-effects without reprovisioning , for operating-systems that use the changes on subsequent reboots, or for devices that want to read the userdata changes live from a metadata service (`http://169.254.169.254/latest/user-data`).

   For other users (other operating systems or applications), a change in `userdata` may best be materialized as a device reinstalled in place, without changing the IP addresses or external-name identifier.
   
   When a REST API includes some RPC style, imperative action endpoints, this may be a smell that indicates that those actions should be called, behaviorally, based on user intent (user imperative) or optionally in response to stateful changes. Parameters in the `spec` could toggle these behavior, resource by resource.  Depending on the scope of these behaviors (and their API endpoints), these toggles may need to reside in the `ProviderConfig`.

3.  Would a "reboot" (with potentially long delays for reprovisioning), be advised in a Crossplane provider?
   In Terraform providers, this type of cloud provider behavior may be omitted from the TF provider, resorting to the ForceNew delete + create behavior.  Users may then rely on elastic IP addresses to retain IP addresses, and in Terraform the change in the UUID of a single resource is non-symptematic, although it may force the recreation of dependent resources.

**Comment by displague** [comment]
https://github.com/crossplane/crossplane/blob/master/design/one-pager-managed-resource-api-design.md#immutable-properties gets close to discussing these concerns. It occured to me to search for "Immutable Infrastructure" after creating this issue.

**Comment by muvaf** [comment]
In Terraform, there is no user-facing object that represents the current state. The way it works is that you provide a desired final state and it calculates the steps to get to that state, then apply them. Identifier change after a recreate could be a part of the script that's calculated. Additionally, they don't promise any guarantee around the state file and its being source of truth at any point in time since it's not user-facing. All that makes it feasible for them to do that.

However, in Crossplane, the managed resource is a very tight representation of the external resource in the provider, which means their lifecycle state should be same at the same time. You can think of managed resource CR record in etcd at the same level with database entry in cloud provider database representing the physical allocations.

Due to that promise, we cannot change the identifier of the managed resource at any step; you can think of `metadata.uid` at the same level with `metadata.annotations[crossplane.io/external-name]`. This is why we cannot take any deletion action before/without a deletion is issued for the custom resource object. So we require users to delete their managed resource if they would like to update an immutable field.

Regarding limitations, I'd say we put the limitations in different parts of the codebase because of this paradigm. While it's harder to do with reconciliation pattern compared to scripting or Terraform, we could make identifier change work somehow, but we would not want to. Because these guarantees and promises are core features of Crossplane Resource Model.
