### ISSUE TITLE
Crossplane 1.2.x init-container fails if istio service-mesh is in place

### ISSUE THREAD

**Issue by haraldatbmw** [crossplane/crossplane#2297]
### What happened?
I'm running crossplane in my k8s cluster where istio service-mesh is in place too. So all connectivity is handled by a istio-proxy sidecar container.

I tried to update from crossplane 1.1.1 to 1.2.1 without success.
The new `crossplane-init` container created an error: `cannot initialize crossplane: cannot create new kubernetes client: Get "https://172.20.0.1:443/api?timeout=32s": dial tcp 172.20.0.1:443: connect: connection refused`.

Because the new container `crossplane-init` is of type initContainer, the istio-proxy sidecar container is not startet at this time. So no connectivity is given.

Crossplane version 1.1.1 work well in combination with istio.

### How can we reproduce it?
- Install istio into the k8s cluster
- Install crossplane 1.2.x via helm
- Look at the containers of the crossplane pod.
![image](https://user-images.githubusercontent.com/49680586/117456544-9ce9b480-af48-11eb-94fd-99d91036f123.png)

### What environment did it happen in?
Crossplane version: 1.2.0 and 1.2.1

**Comment by haraldatbmw** [comment]
Related istio-issue: https://github.com/istio/istio/issues/32039

**Comment by muvaf** [comment]
It seems like istio [doesn't plan to support](https://github.com/istio/istio/issues/32039#issuecomment-854795486) network access for init containers in strict mTLS mode.

**Comment by negz** [comment]
Hrm, @haraldatbmw have you managed to find any workarounds here? I'm not sure there's much we can do, apart from perhaps document some init-container-less install method.

**Comment by haraldatbmw** [comment]
@negz Our workaround was to disable istio for the crossplane-systems namespace.

**Comment by reegnz** [comment]
Could we reopen this issue please? It's not fixed, and I think there should be a better solution than just disabling the service mesh for the crossplane namespace.

One better workaround is described in this related istio ticket:

https://github.com/istio/istio/issues/23802#issuecomment-628035658
> You can run as UID 1337 in the init container, or disable iptables for specific port/ip ranges ([istio.io/docs/reference/config/annotations](https://istio.io/docs/reference/config/annotations/)).

Instead of workarounds though, could the init-container stuff just happen at the regular container startup? What's the purpose of splitting this step into an init container if it's gonna be running on pod startup anyway?

I see little justification for having to run this as a separate command in an init container instead of the beginning of the main `crossplane` container.
