### ISSUE TITLE
ToCompositeFieldPath patches are ignored if the target status fields are not defined

### ISSUE THREAD

**Issue by bandesz** [crossplane/crossplane#2301]
### What problem are you facing?

I tried to use ToCompositeFieldPath without adding the target fields to the status sub-resource in the XRD and was confused why the patches weren't working. (See https://github.com/crossplane/crossplane/issues/2300)

Didn't mark this as a bug, but might be considered one.

There were no warnings in the Kubernetes events and it wasn't immediately clear what I was doing wrong. (Even though I'm working with Kubernetes objects and controllers daily, lol. My brain didn't connect the dots today.)

### How could Crossplane help solve your problem?

When someone makes the same mistake as I did, it would be helpful to give some feedback, e.g. as Kubernetes warning events, that the target fields in the ToCompositeFieldPath patches do not exist.

Also the documentation (https://crossplane.io/docs/v1.2/concepts/composition.html) could have a note about having to create the fields in the XRD, where `ToCompositeFieldPath` is used.

I imagine this might be less obvious for people who are not familiar with Kubernetes internals.

**Comment by negz** [comment]
Thanks for raising this @bandesz! I agree that documenting this behaviour is the minimum bar. Anything beyond that (e.g. emitting events) could be tough, because the code that is trying to do this patching doesn't currently parse the schema of the thing it is patching to have knowledge of whether it's doing something sane.

Getting the code doing the patching that information - or even validating Compositions ahead of time - is definitely something we should do but it's likely to be a pretty big effort.
