### ISSUE TITLE
Consider giving providers Secret and ConfigMap access only in their own namespace

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#2384]
### What problem are you facing?

In the `ClusterRole` of providers, we add `Secret`, `ConfigMap`, `Lease` and `Event` [access](https://github.com/crossplane/crossplane/blob/master/internal/controller/rbac/provider/roles/roles.go#L66) that's not limited to any namespace. While we have to have this kind of power in core Crossplane due to how claims work, but it may not be necessary for providers. The less arbitrary access we have to `Secret`s in the cluster, the better in general due to how it can be used to get tokens of other `ServiceAccount`s.

With the generic references on managed resources, this will mean edit permission on any managed resource will get you access to any `Secret` in the cluster.

### How could Crossplane help solve your problem?

It should be possible to use providers whose managed resources write their connection `Secret`s into only single namespace. For users who consume managed resources via composition, it doesn't really matter where the connection secret of the managed resources ends up. For others who provision managed resources directly and would like connection secrets to be in the same namespace as their `Pod`, this will mean a serious limitation unless they manually grant the permissions. We can consider an option in `ControllerConfig` that will toggle whether the provider has multi-namespace access to those objects or only the namespace where the provider `Pod` is running. Since it'd be breaking, the default would be to allow it. But we could consider defaulting to single namespace for new installations.

**Comment by turkenh** [comment]
Extending `ControllerConfig` in a backward-compatible way for this sounds like a good idea to me. 

Considering, users might request [additional permissions](https://github.com/crossplane/crossplane/pull/2385#discussion_r654680659) at the configuration level, what do you think an API like the following? 

```
type ControllerConfigSpec struct {
        ...
	// +optional
	PermissionConfig PermissionConfig `json:"permissionConfig,omitempty"`
}

type PermissionConfig struct {
	DisableClusterScopedSecretAccess bool `json:"disableClusterScopedSecretAccess,omitempty"`
	DisableClusterScopedConfigmapAccess bool `json:"disableClusterScopedConfigmapAccess,omitempty"`

	ExtraPermissionRequests []PermissionRequest `json:"extraPermissionRequests,omitempty"`
}

type PermissionRequest struct {
	ClusterScoped bool `json:"clusterScoped,omitempty"`
	rbacv1.PolicyRule
}
```

**Comment by hasheddan** [comment]
@turkenh this sounds fairly reasonable, but there are two main areas of concern from me:
- `ControllerConfig` has proved fairly useful, but I am still somewhat concerned about it becoming the "kitchen sink" for anything we want to do. As it continues to grow, we may want to consider if there is a more elegant design. (I realize this a somewhat vague and unhelpful comment, but I am happy to work alongside y'all to bring this to fruition as part of the generic resource references design 🙂 )
- A somewhat lesser known feature of `Provider` packages is its [`spec.controller.permissionRequests` block](https://doc.crds.dev/github.com/crossplane/crossplane/meta.pkg.crossplane.io/Provider/v1@v1.3.0#spec-controller-permissionRequests). This made sense at the time of design because it was assumed that we would know at build-time what permissions a provider would need. With the introduction of generic resource references, this is no longer the case. Also, in order to actually give a `Provider` these requested permissions, you have to create a `ClusterRole` that is aggregated to the RBAC Manager's [`allowed-provider-permissions` `ClusterRole`](https://github.com/crossplane/crossplane/blob/8e76b9cdcf0c112e57a5ea9a281cf74baaa584b0/cluster/charts/crossplane/templates/rbac-manager-allowed-provider-permissions.yaml#L15). I would want to think carefully about how this permission request mechanism interacts with any new ones we introduce, and what the desired UX would be. I wonder if giving all providers view-only access to all managed resources by default would make sense?

**Comment by turkenh** [comment]
> ControllerConfig has proved fairly useful, but I am still somewhat concerned about it becoming the "kitchen sink" for anything we want to do. As it continues to grow, we may want to consider if there is a more elegant design. (I realize this a somewhat vague and unhelpful comment, but I am happy to work alongside y'all to bring this to fruition as part of the generic resource references design 🙂 )

Yeah, agreed. I also noticed that all existing parameters in `ControllerConfig` affect the controller pod manifest. But `PermissionConfig` would be an exception in that sense and will affect RBAC created and require changes in RBAC manager. Trying to keep it scoped to controller pod spec sounds reasonable. 
However, if it became a requirement to configure RBAC at installation time, we would need a solution.

> A somewhat lesser known feature of Provider packages is its spec.controller.permissionRequests block. This made sense at the time of design because it was assumed that we would know at build-time what permissions a provider would need. With the introduction of generic resource references, this is no longer the case. Also, in order to actually give a Provider these requested permissions, you have to create a ClusterRole that is aggregated to the RBAC Manager's allowed-provider-permissions ClusterRole. I would want to think carefully about how this permission request mechanism interacts with any new ones we introduce, and what the desired UX would be. I wonder if giving all providers view-only access to all managed resources by default would make sense?

Actually, this is a bit out of scope for this specific ticket. I just wanted to mention since it would be related if we add a `PermissionConfig` field to `ControllerConfig`. I am fine with putting this aside for now and agree that there would be other concerns regarding this.

Focusing back to the scope of this ticket, and considering we don't feel comfortable with adding such a configuration (namespace scoped access for secrets and configmap) to `ControllerConfig`, I am wondering if would it make sense to control it with a global parameter, i.e. a flag to RBAC manager?

**Comment by turkenh** [comment]
@hasheddan any quick feedback about introducing a dedicated `PermissionConfig` resource (suggested by @muvaf) instead of including that to `ControllerConfig`? 

```
// ProviderSpec specifies details about a request to install a provider to
// Crossplane.
type ProviderSpec struct {
	PackageSpec `json:",inline"`

	// ControllerConfigRef references a ControllerConfig resource that will be
	// used to configure the packaged controller Deployment.
	// +optional
	ControllerConfigReference *xpv1.Reference `json:"controllerConfigRef,omitempty"`
	// PermissionConfigRef references a PermissionConfig resource that will be
	// used to configure permissions for the provider controller.
	// +optional
	PermissionConfigReference *xpv1.Reference `json:"permissionConfigRef,omitempty"`
}
``` 

Package revision controller would take this into account while calculating `Status.PermissionRequests` for providerRevision which is used by RBAC manager to create the requested permissions.

**Comment by hasheddan** [comment]
> Actually, this is a bit out of scope for this specific ticket.

@turkenh agreed, but my desire to dig deeper on it is that I think we need to consider it while thinking about the feature that is in scoped for this ticket. In addition, how do you envision the `PermissionConfig` interacting with the "build-time" permission requests? Are you envisioning the `PermissionConfig` spec mirroring https://doc.crds.dev/github.com/crossplane/crossplane/meta.pkg.crossplane.io/Provider/v1@v1.3.0#spec-controller-permissionRequests and just taking the superset of them?
