### ISSUE TITLE
Why resourceRefs in claim write data into spec, rather then inside  status

### ISSUE THREAD

**Issue by arturobrzut** [crossplane/crossplane#2400]
Why resourceRefs in claim CR write data inside spec, rather than inside status.
Our approach:
 On the top of crossplane we have our App with K8s Controller which creates CR for our Claims.
(we have many claims CRD for many services.)
Inside our controller, we check if someone changed Claim CR for the service. 
```reconcileContext.ResourceReconciler.Reconcile(kafkaName, kafkaclaims.From(kafkaClaimCR))```

of course, we can skip checking resourceRefs , but the questions why it was designed to write it to spec rather then to the status

**Comment by negz** [comment]
> the questions why it was designed to write it to spec rather then to the status

This is a common pattern in Kubernetes in cases where the controller needs to set a (derived) field that in turn specifies the desired state of the resource, rather than simply reflecting its observed status. This is sometimes called ["late initialization"](https://github.com/kubernetes/community/blob/2f26b93380f504e4c11effdae1eee7bbe6648d5b/contributors/devel/sig-architecture/api-conventions.md#late-initialization).  A common example is `pod.spec.nodeName` being derived and set from `pod.spec.nodeSelector`.

You may be interested in https://github.com/crossplane/crossplane/pull/2385, which proposes changes to our cross resource reference API.

**Comment by hasheddan** [comment]
@arturobrzut I am going to close this one out, but please feel free to reopen if you feel your question has not been fully addressed :)
