### ISSUE TITLE
HNC and crossplane conflict with each other

### ISSUE THREAD

**Issue by jguionnet** [crossplane/crossplane#2414]
### What problem are you facing?

I would like to use [The Hierarchical Namespace Controller (HNC)](https://github.com/kubernetes-sigs/multi-tenancy/tree/master/incubator/hnc) with crossplane.

However, when I am trying to associate a namespace with a parent a namespace, it is rejected. When I create each namespace. the [crossplane RBAC Manager](https://github.com/crossplane/crossplane/blob/master/design/design-doc-rbac-manager.md) creates the crossplane roles (edit, view, admin). When I associate/reparent, then HNC by default propagate the parent roles to the child. However, as these roles already exist then the name conflict and it is rejected.

See below the error when I am executing the [HNC quickstart](https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/hnc/docs/user-guide/quickstart.md)
```
kubectl hns set team-a --parent acme-org
Setting the parent of team-a to acme-org
 
Could not update the hierarchical configuration of team-a.
Reason: admission webhook "hierarchyconfigurations.hnc.x-k8s.io" denied the request: Cannot update hierarchy because it would overwrite the following object(s):
  * Namespace "team-a": crossplane-edit (rbac.authorization.k8s.io/v1, Kind=Role)
  * Namespace "team-a": crossplane-view (rbac.authorization.k8s.io/v1, Kind=Role)
To fix this, please rename or remove the conflicting objects first.
```

### How could Crossplane help solve your problem?

Should crossplane be HNC aware?

**Comment by hasheddan** [comment]
@jguionnet thanks for raising this issue! I don't think we have considered whether Crossplane should be HNC aware, but it sounds like this problem could be addressed by either Crossplane not creating roles if the namespace is managed by HNC, or HNC supporting deferring management of certain roles to a different system (e.g. ignoring roles that have something like `hnc.x-k8s.io/ignore: true`). The latter solution sounds like a more future-proof approach to me (and could potentially be useful for other operators running alongside HNC). I would love to hear more about your architecture for using Crossplane alongside HNC if you are willing to share so that we can make sure any solution we land on fits your use case :)

**Comment by hasheddan** [comment]
As a short-term solution, @negz pointed out that you could opt to run the RBAC manager in `Basic` mode, meaning it would only manage the roles needed for core Crossplane itself, not all of the namespaces ([Helm chart docs](https://github.com/crossplane/crossplane/tree/master/cluster/charts/crossplane#configuration)):

`rbacManager.managementPolicy`: The extent to which the RBAC manager will manage permissions. `All` indicates to manage all Crossplane controller and user roles. `Basic` indicates to only manage Crossplane controller roles and the `crossplane-admin`, `crossplane-edit`, and `crossplane-view` user roles.

**Comment by anoop2811** [comment]
ping...still interested in this.
