### ISSUE TITLE
Help avoid XRD syntax mistakes using the package manager

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#2441]
### What problem are you facing?

Currently, `Configuration` packages are marked as `Installed: True` and `Healthy: True` if we are able to successfully create all `CompositeResourceDefinitions` (`XRD`) and `Compositions`. However, `XRDs` have the unique attribute that Crossplane renders `CustomResourceDefinitions` (`CRD`) in response to their creation. Therefore, if the `CRD` is not created successfully, the `XRD` is essentially not "installed", but the package will appear healthy.

The primary scenario I have noticed this is when the `metadata.name` of the `XRD` does not match that of the `<plural-kind>.<group>`.

### How could Crossplane help solve your problem?

One way this could be addressed is through [introducing validating webhooks](https://github.com/crossplane/crossplane/issues/1152). This would address the issue where the `CRD` is unable to be created because the `XRD` is ill-formatted by rejecting the creation by the package manager. However, if the `CRD` is unable to be rendered for some other reason, it would not. If we only think the former issue is important, webhooks are likely the way to address this. However, if we want to address the latter issue, and potentially address both for the short-term while webhooks are not implemented, we could check to make sure that the `CRDs` for an `XRD` are created successfully after `Configuration` installation in the package manager.

An even better (and potentially supplemental) solution, would be to do validation during package linting such that issues would be surfaced during package build (and if bypassed, during package unpack upon install). This would eliminate failure to deploy `XRDs` due to syntax issues, and the code could actually be shared with the webhooks when they are introduced.

**Comment by negz** [comment]
In general I think the right place to validate the health of an XRD is at the XRD level (i.e. XRD scoped controllers and webhooks) rather than the package level. I could imagine for example an XRD webhook doing a dry-run apply of its CRD to determine whether it was likely to be valid.

That said, I would support some lightweight investments at the package level, namely:

1. Linting a small set of high impact, unambiguous issues like the name of an XRD at package build time.
2. Teaching the package manager about XRD health, such that revisions only become healthy if all of the XRDs they deliver become healthy (per their status conditions).
