### ISSUE TITLE
Crossplane resources state in ArgoCD Dashboard

### ISSUE THREAD

**Issue by rotemjac** [crossplane/crossplane#2444]
### What happened?
When you combine Crossplane with ArgoCD and provision resources - you can only see the actual state of the CRDs but not the real state of the provisioned resources (for example the resource of AWS RDS cluster).

### How can we reproduce it?
Deploy Crossplane with ArgoCD and create a sample resource - can be a simple VPC.

### What environment did it happen in?
Crossplane version: 1.3
* Cloud Provider: AWS
* K8S version: 1.19

**Comment by vfarcic** [comment]
We would probably need to add entries to https://github.com/argoproj/argo-cd/tree/master/resource_customizations. The problem is that there must be an entry for each resource. A single provider can have anything between one and hundreds or even thousands of resources. Adding each resource to https://github.com/argoproj/argo-cd/tree/master/resource_customizations or to argocd-cm would result in a couple of thousand resources with that number rising every day. I imagine that the solution could be to create a PR to Argo CD so that health checks can be defined in the API level (skipping Kinds) and/or to extend the provider release process to automatically include additions to that repo. Otherwise, I'm afraid that any attempt to add the entries to https://github.com/argoproj/argo-cd/tree/master/resource_customizations would quickly result in it being obsolete or have missing resources given the speed with which Crossplane providers are evolving.

**Comment by negz** [comment]
> you can only see the actual state of the CRDs but not the real state of the provisioned resources (for example the resource of AWS RDS cluster).

@rotemjac to clarify, are you saying that the health of the actual `kind: CustomResourceDefinition` shows up, but the health of the `kind: VPC` (for example) does not?

If so, I wonder if Argo would be open to something like https://github.com/crossplane/crossplane/issues/2672 (if it isn't already - I don't personally use Argo much) - supporting a 'standard' condition to track readiness. All extant managed resources have a consistent `Ready` status condition that appears to be becoming somewhat of a standard even outside Crossplane.

**Comment by vfarcic** [comment]
According to the docs, Argo CD by default monitors statuses only of Deployment, ReplicaSet, StatefulSet DaemonSet, Ingress, Service, and PersistentVolumeClaim (https://argo-cd.readthedocs.io/en/stable/operator-manual/health/#overview). That means that it ignores any other resource unless defined in https://github.com/argoproj/argo-cd/tree/master/resource_customizations or in a configmap. I guess that the solution could be to modify Argo CD to have a catch-all status field that could be used as an indication of status no matter what the resource is.

**Comment by negz** [comment]
> I guess that the solution could be to modify Argo CD to have a catch-all status field that could be used as an indication of status no matter what the resource is.

That's my suggestion - we and ArgoCD both align on the `Ready` status condition, which is anecdotally common and appears to be a nascent standard per https://github.com/kubernetes-sigs/cli-utils/tree/master/pkg/kstatus.

**Comment by haarchri** [comment]
fyi one resource is available in argo: https://github.com/argoproj/argo-cd/pull/4778

**Comment by erikgb** [comment]
> > I guess that the solution could be to modify Argo CD to have a catch-all status field that could be used as an indication of status no matter what the resource is.
> 
> That's my suggestion - we and ArgoCD both align on the `Ready` status condition, which is anecdotally common and appears to be a nascent standard per https://github.com/kubernetes-sigs/cli-utils/tree/master/pkg/kstatus.

I do (no surprise) agree with @negz, and think everyone will gain on adoption some kind of standard regarding this. And the upstream [kstatus](https://github.com/kubernetes-sigs/cli-utils/blob/master/pkg/kstatus) is the best available IMO. I am not personally using ArgoCD, at least not ATM, but I suggest opening an issue there for supporting kstatus for health assessement.

It would we nice if we could get some progress on https://github.com/crossplane/crossplane/issues/2672! I will be happy to contribute (if I can), but first we need to agree on exactly what to do.
