### ISSUE TITLE
Long compile times for tests

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#2502]
### What happened?

We started compiling our `e2e` tests in https://github.com/crossplane/crossplane/pull/2486 to ensure that they did not become stale. However, this has led to almost tripling the duration of our `Publish Artifacts` stage in CI. We should try to minimize that time to cut down our runtime and resource usage of CI.

### How can we reproduce it?

Compare this run from a month ago: https://github.com/crossplane/crossplane/actions/runs/1013367625
To this run from after adding the test compilation step:  https://github.com/crossplane/crossplane/runs/3367278784?check_suite_focus=true

### What environment did it happen in?
Crossplane version: Introduced in https://github.com/crossplane/crossplane/commit/37c748bc4ae896d65582057ee6c203c0d741f1c8

**Comment by chlunde** [comment]
_Possible_ cause:

https://github.com/upbound/build/blob/master/makelib/helm.mk#L48-L54

I think overriding `XDG_*` points the Go cache to `GOCACHE="/home/chlunde/src/crossplane/.work/helm/go-build"`
which I suspect is not reflected here, because it does not run through the same Makefile variables:

https://github.com/crossplane/crossplane/blob/master/.github/workflows/ci.yml#L57

**Comment by hasheddan** [comment]
@chlunde apologies for not seeing this earlier! It would have saved me a fair amount of time. but I eventually caught up to what you had already discovered :) Thanks for pointing this out -- it has been addressed now in https://github.com/crossplane/crossplane/pull/2742
