### ISSUE TITLE
Need a way to pause reconciliation of individual resources

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#2590]
### What problem are you facing?

Recently, while I was working on the [migration guide for provider-gcp](https://github.com/crossplane/provider-gcp/blob/master/docs/upgrading-to-v0.18.x.md), I needed a way to make sure that no crossplane or provider controllers reconcile on some custom resources (managed, composite, configuration etc). However, currently, we don't have such an option today to pause reconciliation hence I had to scale down controller pods to 0.

### How could Crossplane help solve your problem?

Introduce a way to pause reconciliation on resources and ACK this in the status so that user could make sure that crossplane will no longer take any action for that resource. 

We could use an annotation like the following:

```
crossplane.io/paused: "true"
```

**Comment by negz** [comment]
I've been kind of hesitant about this in the past, but only because I worry that folks might accidentally miss that some MRs are paused. I wonder if we could solve that with events/metrics? e.g. Perhaps when this annotation existed the managed resource reconciler could return early without actually doing any meaningful reconciling, but emit a `Paused` event. We could also potentially add a new conditioned status type (e.g. `Paused`).

**Comment by praveenadini** [comment]
Hi Team, We are facing the same issue with pausing reconcile on claims or the MR's created by claims. Is there any fix that is available to achieve this.

**Comment by bobh66** [comment]
https://docs.crossplane.io/latest/concepts/managed-resources/#paused
