### ISSUE TITLE
XR and claim controllers make superfluous API server requests

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#2645]
### What happened?

While investigating Crossplane performance in https://github.com/crossplane/crossplane/issues/2568 I noticed that the XR and claim controllers were making a surprising amount of calls to the API server.

<img width="1299" alt="rps" src="https://user-images.githubusercontent.com/1049349/137987458-788bc903-b17a-4b3d-b4f6-a607b1b99622.png">

The above graph is from a test in which I created 1,000 claims. Each claim created an XR composed of 4 managed resources, and exercised most Crossplane features (connection secrets, bidirectional patching, etc).

Note that Crossplane core (`crossplane-system/crossplane`) is making 4x the API server calls of provider-gcp (`crossplane-system/crossplane-providers`). I believe this is because:

1. The claim and XR controllers aren't using a read cache. We're passing in the default controller-runtime Kubernetes client from `mgr.GetClient()`, but these controllers use `*unstructured.Unstructured` heavily, which is not cached by default. This means we're getting claims, XRs, and composed resources directly from the API server on each reconcile by default.
2. The XR controller is writing two events - `SelectedComposition` and `ComposedResources` - on every reconcile. This controller polls (requeues) every minute by default, so we're writing two events per XR per minute even when nothing is really being done (e.g. when the select and composes are no-ops).

### How can we reproduce it?

You can find the test config at https://github.com/negz/crossplane-scale. I used a GKE cluster with two e2-medium-4 notes, and Crossplane and the GCP provider both had `--max-reconcile-rate=100`, with 2 CPU cores and 2GB of memory.

### What environment did it happen in?
Crossplane version:

**Comment by negz** [comment]
> The claim and XR controllers aren't using a read cache. We're passing in the default controller-runtime Kubernetes client from mgr.GetClient(), but these controllers use *unstructured.Unstructured heavily, which is not cached by default. This means we're getting claims, XRs, and composed resources directly from the API server on each reconcile by default.

I could see this being a good first issue, especially for someone with some controller-runtime familiarity.

**Comment by enesonus** [comment]
Hi @negz I have been looking at this issue for the past week. I started with running the [crossplane-scale](https://github.com/negz/crossplane-scale) project to see if this issue still remains. Repository is a bit old but with some tweaks I managed to run it. I created a PR fixing the issues. 

I deployed crossplane-scale on a 2 node e2-medium-4 cluster on GCP

Here is the flow I followed to set up my cluster:
1. Create cluster on GCP 
2. `up uxp install --set metrics.enabled=true`
3. `git clone https://github.com/prometheus-operator/kube-prometheus/ --branch v0.9.0`
4. `kubectl apply -f kube-prometheus/manifests/setup`
5. `kubectl apply -f kube-prometheus/manifests`
6. `kubectl apply -f https://raw.githubusercontent.com/caicloud/event_exporter/master/deploy/deploy.yml`
7. `kubectl apply -f prom-pod-monitors.yaml`

After making sure that everything works by port forwarding grafana to my computer I ran the `create.sh` script. inside `etoomanycrs/` with:

`./create.sh 5 10 100` 

But I can not see any new requests on my API Server requests dashboard:
<img width="1331" alt="image" src="https://github.com/crossplane/crossplane/assets/94247411/510e2d40-c19a-4b20-b5b1-b673f257b29d">

I think CRDs get applied to the cluster because I also have this screen on my dashboard when script runs (I stopped script halfway thats why it shows only 150~ CRDs):
<img width="1331" alt="image" src="https://github.com/crossplane/crossplane/assets/94247411/d5ade51f-ba9f-4346-afa8-775907c1ba48">

I am planning to debug the behavior of controller runtime since I believe we don't get the actual API Server request count from Crossplane. If there are any leads you think would be good to look at I would be very happy!

**Comment by negz** [comment]
@enesonus Thanks for looking into this!

> I ran the create.sh script. inside etoomanycrs/ with:

That script won't generate the load on the API server this issue describes.

I was using the negz/crossplane-scale repo to test a few different scaling issues. The `etoomanycrds` directory was to test scale issue that occur due to number of CRDs (https://blog.upbound.io/scaling-kubernetes-to-thousands-of-crds).

To replicate the problem this issue describes, you'll need to create a lot of claims (and therefore XRs).

https://github.com/crossplane/crossplane/tree/master/test/e2e/manifests/apiextensions/composition/minimal

You could use the manifests from our E2E tests to create a lot of claims. These manifests would be good for this kind of testing because they use provider-dummy MRs rather than 'real' MRs that need a cloud account.

My hunch is that fixing https://github.com/crossplane/crossplane/issues/5338 will make a big difference to the load on the API server. I opened https://github.com/crossplane/crossplane/pull/5339 to do that, but I haven't had time to dig into why it causes our E2E tests to fail. I'd be very happy if you wanted to help with that.

Helping get realtime compositions to beta would have a big impact too - https://github.com/crossplane/crossplane/issues/4828. This code might not be as beginner-friendly though. I find it pretty hard to follow.
