### ISSUE TITLE
Crossplane uses default SA instead of Crossplane SA in same cases ( can not load Configuration image )

### ISSUE THREAD

**Issue by arturobrzut** [crossplane/crossplane#2691]
### What happened?
Crossplane uses default SA instead of Crossplane SA in the same cases and can not load Configuration image in such case.
Crossplane can not load Configuration image from Configuration CR

### How can we reproduce it?
1. Deploy crossplane and configuration CR , everything should work (Service Account in crossplane pod is `crossplane`,  but
2. If we add non exists secret  to the service account `default` in the namespace where is deploy crossplnae
Configuration CR change status to false. (**it means adding something to not related service account default, becuase crossplane use crossplane service account, generating errors in crossplane**)
3. Because crossplane want to use default service account instead of service account which is assigned in POD
4. Because of lib k8schain, which is used by crossplane, 
5.  during initialization k8schain we do not set a service account and in such case, the `default` service account will be used. **Which is wrong.**

![image](https://user-images.githubusercontent.com/54812713/140277766-a963493b-993b-445f-a64b-d807f7945879.png)

![image](https://user-images.githubusercontent.com/54812713/140277644-51ed33a5-e9a7-46b4-b54c-bf19be4fc4c0.png)

5. and because of non exists secret in default service account we got message 
`2021-11-02T21:19:34.045Z	DEBUG	crossplane	cannot unpack package	{"controller": "packages/configuration.pkg.crossplane.io", "request": "/crossplane-bedrock-shim-config", "uid": "6f2709c3-4cf8-4c32-967d-a96e5f9c0a5a", "version": "1074031", "name": "ibm-crossplane-bedrock-shim-config", "error": "failed to fetch package digest from remote: secrets \"docker-pull-hyc-idp-docker-local-artifactory-swg-devops-com-base-registry\" not found", "errorVerbose": "secrets \"docker-pull-hyc-idp-docker-local-artifactory-swg-devops-com-base-registry\" not found\nfailed to fetch package digest from remote\ngithub.com/crossplane/crossplane/internal/controller/pkg/manager.`

6. Easy fix is set Service account in fetch.go , of course not hardcoded as in below example
![image](https://user-images.githubusercontent.com/54812713/140278790-33e6e1f4-7547-4869-b81f-ef56a20a894e.png)

### What environment did it happen in?
Crossplane version: 
1.4

**Comment by hasheddan** [comment]
Hi @arturobrzut, thanks for opening this issue! This is actually an intentional decision (albeit one we potentially should consider revisiting) as to decouple the traditional use of imagePullSecrets on an SA from pulling package images in Crossplane. Doing so means that if you don’t explicitly specify the credentials to use when pulling a private package, Crossplane will not silently use credentials attached to its SA (as you have discovered here). Credentials can be specified explicitly on Configuration or Provider CRs.
https://doc.crds.dev/github.com/Crossplane/crossplane/pkg.crossplane.io/Configuration/v1@v1.5.0#spec-packagePullSecrets
https://doc.crds.dev/github.com/Crossplane/crossplane/pkg.crossplane.io/Provider/v1@v1.5.0#spec-packagePullSecrets

As mentioned above, I think it’s possible we would consider using the Crossplane SA as default for k8schain, but I would likely want it to remain configurable.

**Comment by arturobrzut** [comment]
For us, if this field will be configurable it will be enough good.
