### ISSUE TITLE
add a delete as a verbsSystem to provider ClusterRoles

### ISSUE THREAD

**Issue by fahedouch** [crossplane/crossplane#2730]
### What happened?

Hi folks,

Is there a reason for not giving `delete` permission by default to the provider's system service account [here](https://github.com/crossplane/crossplane/blob/4fc21863b3b71af63bcdcf3c80572a49d4012a22/internal/controller/rbac/provider/roles/roles.go#L55). I think the provider should be able to delete its CRs as well.

I would like to have your feedback before proposing a fix :). thanks

### How can we reproduce it?

By describing the provider ClusterRole 

### What environment did it happen in?
Crossplane version:  latest

**Comment by negz** [comment]
@fahedouch As far as I'm aware most (or all) providers don't need access to delete their own managed resources. For example provider-aws doesn't contain any logic that would delete a provider-aws MR - instead it responds to MRs being deleted by Crossplane (e.g. because they're part of an XR) or by some other system (kubectl, ArgoCD, etc).

Am I missing a common case where delete would be useful? I bet there are some cases, but if they're rare I'd prefer to leave it off by default and have those providers explicitly request the delete verb.
