### ISSUE TITLE
Run crossplane standalone in a docker container

### ISSUE THREAD

**Issue by bassam** [crossplane/crossplane#274]
* Feature Request
I'd like to be able to run crossplane standalone by doing the following:

```
docker run -d --restart=unless-stopped -p 443:443 crossplane/crossplaned:latest
```

This will likely require a new `cmd` that is similar to `localkube` and would start etcd, kube-apiserver, and some parts of controller-manager along with crossplane itself.

**What is use case behind this feature:**
Simplified development with crossplane, and a much quicker Quickstart :-)

**Comment by Sanhajio** [comment]
I came accross this blog post: https://kubernetes.io/blog/2018/05/01/developing-on-kubernetes/, the blog post mentions: 

>"For example, if you’re a Node.js developer and are used to a hot-reload; then dealing with containers and container images, with container registries, Kubernetes deployments, can not only be overwhelming but really take all the fun out if it.".

This is why I think this ticket is important.

I don't know how to tackle this ticket, tough, any opinions ?

The only ideas I have, are to use [Kubeadm](https://github.com/kubernetes/kubeadm), [Kind](https://github.com/kubernetes-sigs/kind), [kubeadm-dind-cluster](https://github.com/kubernetes-sigs/kubeadm-dind-cluster) or write a tool alike. Otherwise I can give a try to: [Draft](https://github.com/Azure/draft) or [skaffold](https://github.com/GoogleContainerTools/skaffold) but that might be overkill.

**Comment by jessesanford** [comment]
I would like a way of running cross plane controllers on KubeEdge. That would allow for disconnected or "occasionally" connected crossplane controllers reconciling within their own "domains"

**Comment by ytsarev** [comment]
still relevant
