### ISSUE TITLE
Coexisting two instance of crossplane on one k8s cluster

### ISSUE THREAD

**Issue by arturobrzut** [crossplane/crossplane#2770]
### What problem are you facing?
Crossplane CRDs are cluster scope and it required:
 - cluster scope permission on Secrets
 -  cluster scope permission on Crossplane CRDs

And when we have one k8s cluster which is used by two / many customers
(we separate it by namespace )
Each customer has a separate namespace where they can deploy their software.
But when we deploy crossplane then each customer can see all CRs and can / have to  manage it
and because of that he can break other customers CR

### How could Crossplane help solve your problem?
We consider an option that Crossplane should be namespace scope operator which has namespace scope CRDs

**Comment by Feggah** [comment]
Hey @arturobrzut, thanks for opening this issue!

Crossplane has the division of namespaced/cluster scope CRDs, and it is the XRC/XR respectively.

There is an extensive documentation about them that you can check it out [here](https://crossplane.io/docs/v1.5/concepts/composition.html), but just to give a **horrible** TL;DR:
- XR (`CompositeResource`) is the CRD that platform builders/cluster admins can create directly, these are cluster scoped. In normal use cases, your customers shouldn't create it directly;
- XRC (`CompositeResourceClaim`) is the CRD that customers should consume. This resource claims a XR. These claims are namespace scoped, so you can properly RBAC your users to be able to create/update/delete those resources in the proper namespace;

This TL;DR doesn't picture everything that you should know about XR and XRCs. I highly recommend you to read the reference that I linked above. You can also check out [this documentation](https://crossplane.io/docs/v1.5/guides/multi-tenant.html) that explains about this matter as well.

**Comment by negz** [comment]
We're at v1.0 with v1 custom resources, so without comment on whether we would want to, switching them from cluster scoped to namespaced is not something we can do until v2.

As @Feggah calls out, Crossplane is indeed designed such that different customers can use different namespaces within one cluster to manage their infrastructure via namespaced XRCs. @arturobrzut are you using XRCs or XRs?

**Comment by slimm609** [comment]
I was looking at Crossplane for a multi-tenant use case.   The issue with cluster scoped resources is isolation between tenants.   With XRCs, the cluster admins have to create XRCs for every use case which is not scalable.  In shared development environments where multiple teams can not see either other (namespace only access) there is no way to easily grant access to create any aws resources needed without seeing every other resource.  

Managing lots of aws resources also becomes very cluttered with cluster only scope.  In the case of multi-tenants, being able to manage services by a namespace is much more manageable.  

a VPC, subnets, s3 buckets, databases, etc for a single tenant can be grouped into a single namespace and makes that group viewable with `kubectl get aws`.  This becomes problematic when viewing lots of resources even if with using XRC/XRs. If objects were namespaces, then RBAC can still be leveraged to restrict access to only since XRs since they are different CRDs

**Comment by MisterMX** [comment]
@slimm609 you could use [vcluster](https://github.com/loft-sh/vcluster) to deploy isolated controlplanes for each team. This might be a more feasible solution than making all MRs and XRs cluster scope.

One drawback of this is that right now you cannot use vcluster in combination with IRSA (IAM roles for service accounts) and AWS EKS (see https://github.com/loft-sh/vcluster/issues/370).

**Comment by slimm609** [comment]
@MisterMX Yea, We have looked at vcluster but isn't a scalable solution when you are dealing with highly restricted environments and hundreds of clusters.  Using vcluster for each team would add several hundred clusters to have to manage and harden.

**Comment by negz** [comment]
It sounds like you might be using Crossplane without claims and XRs, which is not a use case we support per [the recently added charter](https://github.com/crossplane/crossplane/blob/master/CHARTER.md). I don't see us supporting namespaced managed resources without a major overhaul (i.e. going to at least v2 of our APIs). As @MisterMX suggested I think the best approach if you need stronger isolation is to deploy a Crossplane per tenant - keep in mind Crossplane doesn't _need_ to run on your Kubernetes clusters (you can always deploy a standalone).
