### ISSUE TITLE
Crossplane should play nice with ArgoCD

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#2773]
### What problem are you facing?

There's a lot of overlap between Crossplane and ArgoCD users - we see a lot of folks wanting to use ArgoCD to manage their Crossplane resources. This works in part, but there are several known issues that prevent parts of Argo's/Crossplane's functionality being used together:

- [x] https://github.com/crossplane/crossplane/issues/2121
- [x] https://github.com/crossplane/crossplane/issues/2444
- [x] https://github.com/crossplane/crossplane/issues/2700
- [x] https://github.com/crossplane/crossplane/issues/2928

### How could Crossplane help solve your problem?

We should work with the ArgoCD folks to ensure our projects compliment each other well - without any unusable functionality.

**Comment by negz** [comment]
I think we're also seeing an instance of https://github.com/argoproj/argo-cd/issues/5082, in which ArgoCD is unaware of the relationship between XRCs and XRs.

**Comment by negz** [comment]
@jessesuen I've been meaning to find some ArgoCD maintainers to reach out to to chat about this issue; I suspect some of the work to make the two projects work better together might fit best on the ArgoCD end. Any tips on who I should talk to?

**Comment by gresco** [comment]
I am also curious about the sitrep here in consideration to a project at my work that would benefit from this being fixed.

**Comment by jessesuen** [comment]
> Any tips on who I should talk to?

Hi @negz. Sorry for the late reply. We use crossplane at Akuity and so I fully understand and appreciate the pain point. I can be that point of contact for you.

I think the biggest issue with crossplane + Argo CD is the XRC -> XR relationship, or rather the lack thereof. Argo believes the XRs need to be pruned because the XRs had carried over the resource tracking label Argo CD put on the XRC.

Argo CD has a relatively new annotation-based resource tracking mechanism that captures the parent/managed resource. The annotation looks like this:

```yaml
  annotations:
    argocd.argoproj.io/tracking-id: 'guestbook:/Service:guestbook/kustomize-guestbook-ui'
```

In theory, the annotation provides enough information, to detect if that annotation had carried over to the child resource and so the child resource should be considered part of the app.

However, it's not quite working the way I thought it would. See my comments here:
https://github.com/argoproj/argo-cd/issues/8683#issuecomment-1059477956

IMO, I think if we encounter a resource that has an annotation pointing back to a managed resource in an Argo CD application, we should consider it an offshoot and should not be considered OutOfSync (needing pruning). Basically, I think the problem with XR and XRC relationships is very solvable at the Argo CD front, not just for crossplane, but for many other controllers that carry over metadata without ownership references.

**Comment by crenshaw-dev** [comment]
> I think if we encounter a resource that has our annotation and the annotation is not self-referential, we should consider it an offshoot and should not be considered OutOfSync (needing pruning)

I think this was done. https://github.com/argoproj/argo-cd/pull/9791 https://github.com/argoproj/argo-cd/pull/10198

**Comment by jbw976** [comment]
The activity on this issue looks to have wound down, and the issue list in the description is all completed.  Closing this issue now 👍
