### ISSUE TITLE
Prototype rootless container based composition functions

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#3001]
### What problem are you facing?

As part of https://github.com/crossplane/crossplane/issues/2524 we're prototyping a few different approaches to how we might run "XRM functions" (a slightly more opinionated superset of KRM functions). One approach we'd like to try out is using chroot inside a single container to execute a pipeline of functions as described at https://github.com/GoogleContainerTools/kpt/issues/2567#issuecomment-965899202.

### How could Crossplane help solve your problem?

For the prototype I don't think we need a controller, but rather a containerized Go binary (i.e. a simple `main.go`) that:

1. Takes an array of KRM functions as OCI images (e.g. `crossplane/my-cool-xrm-function:v1`).
2. Takes an input `ResourceList` (see https://github.com/crossplane/crossplane/pull/2886 for an example).
3. Iterates through each KRM function mutating the `ResourceList`.
4. Returns the final `ResourceList`.

I believe for each function we'd want to:

1. Pull the OCI image.
1. Create a working dir (like `/chroot/image-hash` or similar).
1. Unpack the OCI image into its working dir
1. Set `cmd.SysProcAttr = &syscall.SysProcAttr{Chroot: "/chroot/image-hash"}`
1. Plumb up `cmd.Stdin`, and `cmd.Stdout` up appropriately.
1. Call `cmd.Run()`

We can use https://github.com/google/go-containerregistry to pull the image - I believe the package manager `ImageBackend` implementation has a bunch of prior art:

https://github.com/crossplane/crossplane/blob/a9c50c15ce610230cc1b6c8fe6031a9ef1126b18/internal/controller/pkg/revision/imageback.go#L78

**Comment by negz** [comment]
We may be able to leverage gVisor to run functions inside our (typically unprivileged) container by using `runsc run --rootless` per https://github.com/google/gvisor/pull/6581. I haven't tested this though - we'll likely run into similar issues to https://github.com/google/gvisor/issues/4371 and/or its presumed containerd equivalent. This would also eliminate running Crossplane in a cluster that itself used gVisor to run containers, since (AFAIK) gVisor can't run in gVisor.

Another option would be to make gVisor optional -- basically say "if you run Crossplane in a privileged container we'll use gVisor to run functions, if you don't we'll just run them in a simple chroot".

**Comment by negz** [comment]
@sergenyalcin just a heads up, I've been reading up on this a bit and hope to take a shot at a prototype today.

**Comment by negz** [comment]
Regarding my previous comment about gVisor - I'm thinking that gVisor (runsc) and/or regular runc are probably not the best approaches, at least to begin with. As far as I can tell:

* Neither will run within Docker/containerd today without a few modifications.
* gVisor only really supports amd64, though there's [preliminary aarch64 support][1].

I'm thinking we'll be able to prove this approach out if we just start with chroots - we can always improve later by adding more isolation. My hunch is that we'll need to make this configurable though; i.e. perhaps "opt in" to runc/runsc.

[1]: https://gvisor.dev/docs/user_guide/faq/#supported-cpus

**Comment by negz** [comment]
@sergenyalcin Nice! I took a shot at integrating something very similar into Crossplane at https://github.com/negz/crossplane/commit/b537cc62cbb258525d44947525a812350c040a49. How are you feeling about the chroot vs CronJob approach at this point?

**Comment by sergenyalcin** [comment]
We have two basic POCs for the two approaches and these implementations cover only the basic scenarios. However, we had chance to observe the end-to-end running processes for both options. So, first of all, I think the approaches have some advantages and disadvantages. Describing the points may help us to pick an approach to run XRM functions (supporting many ways may also be a future plan).

### **CronJob Approach**

- The details of the POC implementation is here: https://github.com/sergenyalcin/custom-composition-poc/tree/main/poc-controller
- Init containers work in a specified order and the next one waits for the completion of previous. This is a requirement for our feature. User can control the order of functions and manipulates output for business requirements.
- For input/output pipeline, the ephemeral storage of the pods are used. However, extracting the last output (result ResourceList) needs a solution.
- We use the kpt for running the XRM functions in POC. We need a XRM runner for this approach.
- The input of XRM functions is embedded in the spec of the corresponding CR. This input is transferred to a file in the first init container (prep-resource) and processed on it.
- When creating containers in which XRM functions will run, it is assumed that the file to be executed is in a certain path (/function). So this is a problematic point about this solution and we need to propose a solution.


### **Chroot Approach**

- In this POC repository, chroot based runner was implemented: https://github.com/sergenyalcin/custom-composition-poc/tree/main/chroot
- The problem that we have thought about before, function executables do not have an exact path and this path needs to be determined, has been solved because we have image metadata in the solution method.
- Potential issues with image pulling have not been addressed in this prototype. For example, some credentials may need to be injected when trying to pull an image from a private image repo. Therefore, it will be necessary to evaluate such situations for real scenarios.
- Since the relevant XRM functions will be run repeatedly (in reconcile loops), there will be things like pulling and extracting images each time. In this case, it may be necessary to implement a cache management.

In light of the above points, as we can see, there are advantages and disadvantages of two approaches. So, choosing an approach will not be exactly unproblematic. For both options, we have open points and we need some solutions for these ones.

However, I am feeling that choosing the chroot approach will be better. Because this approach provides solutions for the some basic issues such as finding the executable path, stdout, stdin issues. And also, as we discussed before, the intended purpose of the init containers is not the running the real work in an order. So, this point can be another positive point for the chroot based solution.

**Comment by negz** [comment]
>  I am feeling that choosing the chroot approach will be better.

This is also where I'm leaning. I'm going to fill out the design document today to capture the fact that we'll take this direction. I'll note though that we may support other ways of running functions (CronJobs etc) in future since all options have some downsides.

**Comment by negz** [comment]
I've been working on the design (https://github.com/crossplane/crossplane/pull/2886) and struggling to explain why we can't use https://rootlesscontaine.rs rather than a simple chroot. In theory it should work, but in practice I've been struggling.

I finally noticed that per [this guide](https://www.redhat.com/sysadmin/podman-inside-kubernetes) rootless podman works just fine (at least to run a basic `alpine` image) inside an unprivileged container created by a pod running in `kind`. Inspecting what it was doing I was able to replicate a minimal `crun` setup to run a container:

```bash
# Run an alpine image
kubectl run --image alpine -it --attach alpine

# Inside the image add a few handy tools...
apk update && apk add ca-certificates crun skopeo umoci sudo

# Make a workdir
mkdir /crun && cd /crun

# Grab the Alpine image and write it  disk
skopeo copy docker://alpine:latest oci:alpine:latest

# Unpack the OCI image to a runtime bundle
umoci unpack --image alpine:latest bundle/

# Give ownership of the bundle to an unprivileged user (this includes the flattened roofs) 
chown -R nobody bundle/

# Most tools (in this case umoci) generate a config.json  that tries to mount proc. This usually
# won't work per https://github.com/containers/podman/issues/10864#issuecomment-901000416
# The solution appears to be to bind mount the parent container's proc (at least that's what podman does).
rm bundle/config.json
crun spec --bundle bundle/ --rootless
vi bundle/config  # Switch the proc mount to a bind mount per the patch below.

# We can now successfully enter the container! We'll be dumped into a shell where we're root, despite
# the fact that we're nobody outside the container (in the parent user namespace).
sudo -u nobody crun --debug --root /tmp/crun run --bundle bundle/ alpine
```

```diff
--- bundle/config.json
+++ bundle/config.json.fixed
@@ -58,8 +58,9 @@
        "mounts": [
                {
                        "destination": "/proc",
-                       "type": "proc",
-                       "source": "proc"
+                       "type": "bind",
+                       "source": "/proc",
+                       "options": ["noexec", "nosuid", "nodev", "rbind"]
                },
                {
                        "destination": "/dev",
```

By default the container will not have network access because it creates a network namespace inside the user namespace, and that situation typically requires userland tools (e.g. `slirp`) to be setup to connect out. It is however possible to enable network access by editing `config.json` to remove the network namespace so that the container shares its parent container's namespace.

I believe this should all work with `runc` (the reference OCI runtime) but I prefer `crun` (a slightly more cutting edge runtime) because:

* It's self-contained - it doesn't depend on external binaries (e.g. [`newuidmap`](https://man7.org/linux/man-pages/man1/newuidmap.1.html)) to make user namespaces work.
* It has nascent support for running wasm based containers, which would be a neat feature.

**Comment by negz** [comment]
I've been testing a prototype based on user namespaces and noticed that Docker's default seccomp profile actually denies the `unshare` syscall (i.e. prevents us from creating a new user namespace). Kubernetes doesn't have this restriction though.

https://docs.docker.com/engine/security/seccomp/#significant-syscalls-blocked-by-the-default-profile
