### ISSUE TITLE
Pulling packages from artifact-registry is not working in GKE cluster

### ISSUE THREAD

**Issue by mcbenjemaa** [crossplane/crossplane#3023]
### What happened?

Surprisingly, pulling packages from artifact-registry  in GKE cluster is not working with crossplane `v1.6.4`

Error: 
```
Warning  UnpackPackage  7s (x6 over 40s)  packages/provider.pkg.crossplane.io  cannot unpack package: failed to fetch package digest from remote: GET https://**********/v2/token?scope=repository%!A(MISSING)********68%!F(MISSING)docker-gke-irn70740%!F(MISSING)provider-kubernetes%!A(MISSING)pull&service=europe-docker.pkg.dev: DENIED: Permission "artifactregistry.repositories.downloadArtifacts" denied on resource "projects/irn-71889-adm-dev-ope-68/locations/europe/repositories/docker-gke-irn70740" (or it may not exist)
```

### How can we reproduce it?

Deploy crossplane `v1.6.4` and try to pull an image using imagepullsecret `dockerconfigjson`

### What environment did it happen in?
Crossplane version: v1.6.4
Cloud provider or hardware configuration: GCP
Kubernetes version (use `kubectl version`): v1.22
Kubernetes distribution (e.g. Tectonic, GKE, OpenShift): GKE

/cc @hasheddan

**Comment by btwseeu78** [comment]
testing version:
kubernetes:  1.21.9-gke.1002 
crossplane chart version : v1.6.4
values file:
[test.yaml.txt](https://github.com/crossplane/crossplane/files/8417214/test.yaml.txt)

provider-kubernetes:

`apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
  namespace: crossplane-system
spec:
  package: us-central1-docker.pkg.dev/testplane-30/crossplane/provider-kubernetes:v0.3.0
  packagePullPolicy: Always
  packagePullSecrets:
  - name: artifact-registry`
  
 secret created  using:
 
 kubectl create secret docker-registry artifact-registry \
--docker-server=https://LOCATION-docker.pkg.dev \
--docker-email=SERVICE-ACCOUNT-EMAIL \
--docker-username=_json_key \
--docker-password="$(cat KEY-FILE)"

Key File : [Download the service account key](https://cloud.google.com/iam/docs/creating-managing-service-account-keys#creating_service_account_keys) for the service account.

let me know if that's we are testing.

**Comment by btwseeu78** [comment]
this config works in my cluster.

**Comment by smileisak** [comment]
@mcbenjemaa I've created a Kind cluster and tested locally, it works. I've created as well a GKE cluster to be sure that the issue is not related to GKE and it works as well.

I think that the service account used does not have the rights to download the artifacts `artifactregistry.repositories.downloadArtifacts`. Meanwhile this service account acquired this permission. I have the same issue and by restarting Crossplane, it can now fetch the artifact correctly from Artifact Registry.

**Comment by smileisak** [comment]
As discussed with @hasheddan the issue is present in GKE when node image type is `cos` or `cos_containerd`. So I'll reopen this issue to be able to track it with Google Support Team.

**Comment by smileisak** [comment]
@mcbenjemaa could you please reopen this issue ?

**Comment by smileisak** [comment]
Forget my last comment, it is not related to the image type. Therefore, I think that I found the root cause of the issue. 
To fetch images from Artifact Registry Crossplane is using [go-containerregistry](https://github.com/google/go-containerregistry) k8schain like described bellow: https://github.com/crossplane/crossplane/blob/6b82113f952ddfd15a4fc43a945742bba45d4471/internal/xpkg/fetch.go#L119-L128

The actual version of the `go-containerregistry` `k8schain` package go through the authentication process following this order:

```golang
return authn.NewMultiKeychain(
		authn.DefaultKeychain,
		google.Keychain,
		amazonKeychain,
		azureKeychain,
		k8s,
	), nil
```

So when we are in GKE cluster the google.Keychain will resolve before the k8s keychain using the `NewEnvAuthenticator()`  See: https://godoc.org/golang.org/x/oauth2/google#FindDefaultCredentials.

It looks for credentials in the following places, preferring the first location found: 

1. A JSON file whose path is specified by the GOOGLE_APPLICATION_CREDENTIALS environment variable. For workload identity federation, refer to https://cloud.google.com/iam/docs/how-to#using-workload-identity-federation on how to generate the JSON configuration file for on-prem/non-Google cloud platforms.
2. A JSON file in a location known to the gcloud command-line tool. On Windows, this is %APPDATA%/gcloud/application_default_credentials.json. On other systems, $HOME/.config/gcloud/application_default_credentials.json.
3. On Google App Engine standard first generation runtimes (<= Go 1.9) it uses the appengine.AccessToken function.
4. On Google Compute Engine, Google App Engine standard second generation runtimes (>= Go 1.11), and Google App Engine flexible environment, it fetches credentials from the metadata server.


So it fallback with the Google Compute Engine Default Service account. This SA has `roles/editor`in the same project, that's why it worked when the artifact registry is in the same Project, but when it is in a different project it fails and with the Permission Denied message post by @mcbenjemaa .

--- 
## Possible solutions:

### 1- Use Workload Identity (Update documentation for GKE)

The best solution is to use Workload Identity to auth as the SA within the target project where the AR resides. But we need to update the documentation to warn regarding this point.

### 2 - Mount the GOOGLE_APPLICATION_CREDENTIALS (Not possible with the actual Helm Chart)

I've tested manually the update of the Crossplane deployment and it worked as well. This solution require the Helm Chart update to add additional volumes.

### 3 - Update go-containerregistry to prefer k8s 

The actual main branch of the go-containerregistry implements the right order of authentication. Is there any reason to not update the package to the last version.

https://github.com/crossplane/crossplane/blob/f60d10f28905082fe8e5537f17ed74d0117de532/go.mod#L10-L15
