### ISSUE TITLE
Deprecate `kubectl crossplane`

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#3055]
### What problem are you facing?

Under the recently merged [project charter](https://github.com/crossplane/crossplane/blob/6c1b06507db47801c7a1c7d91704783e8d13856f/CHARTER.md) CLI tooling is no longer 'in scope' for Crossplane as a project. We do however currently have a small `kubectl crossplane` extension (aka "crank). 

The extension is really just a convenience wrapper. It can:

* Install Crossplane packages (i.e. providers and configurations).
* Build and push Crossplane packages.

The former is equivalent (e.g.) `kubectl apply -f provider.yaml`, while the latter is equivalent to `docker build`.

### How could Crossplane help solve your problem?

We'll need to figure out whether we want to:

* "Grandfather" crank into the scope of the project and just leave it as is.
* Move it to crossplane-contrib (and presumably remove it from our documentation etc).
* Remove it entirely.

**Comment by Feggah** [comment]
How should we `docker build` `Configuration` packages? 

The providers already have Dockerfiles and some helpful `make` commands to build it, but for `Configurations` we don't have it. Do we just need to `COPY` all YAML manifests (XRDs and Compositions) into the container?

**Comment by MisterMX** [comment]
I agree that `kubectl crossplane install` is not necessary if you can just use `kubectl apply -f` to do exactly the same.

However, `kubectl crossplane build package` is not equivalent to `docker build`. The former construct an OCI image with a single layer that contains a single YAML file without any dependencies while the latter requires a Dockerfile and a daemon running the build command. Additionally, the `docker` command is not available in many CI environments due to security issues with Docker daemon requiring root access.

If the Crossplane CLI is going to be decomissioned, there should be an adequate replacement to easily build configuration packages.

**Comment by MisterMX** [comment]
Yes, you could use `podman` to build OCI images, but it is still not as convenient as `kubectl crossplane build package`. Especially, because the latter builds the image exactly the way it is expected by the Crossplane controller.

Its a tools that works quite well. I think it would make things worse for the user if it is dropped.

**Comment by Feggah** [comment]
I agree with @MisterMX. I think Crossplane CLI is really useful to simplify building packages. In my own experience, the crucial here is the `Configuration`, because the `Provider` is easily built with the `Makefiles` in each provider repository.

In my opinion the best option here is the "Grandfather crank into the scope of the project and just leave it as is"

**Comment by MisterMX** [comment]
@negz I would suggest to move crank into `crossplane-contrib/crossplane-cli` to give the community the opportunity to fix bugs or extend it if needed.

This would require moving all source files from `internal/` to `pkg/` because go does not allow importing internal packages.

**Comment by ttreptow** [comment]
Having the `xpkg` package be importable would be nice to have for incorporating into custom tooling as well.

In the meantime, the terrajet project template has a [Makefile](https://github.com/crossplane-contrib/provider-jet-template/blob/main/cluster/images/provider-jet-template/Makefile) for building a provider image.

It could also be done in a multi-stage dockerfile:
```
FROM bash as builder

ARG VERSION
ARG DOCKER_REGISTRY
WORKDIR /build

COPY package ./package/

RUN sed -i -e 's|VERSION|$VERSION|g' package/crossplane.yaml
RUN sed -i -e 's|DOCKER_REGISTRY|$DOCKER_REGISTRY|g' package/crossplane.yaml
RUN find package -type f -name '*.yaml' -exec cat {} >> 'package.yaml' \; -exec printf '\n---\n' \;

FROM scratch

COPY --from=builder /build/package.yaml .
```

**Comment by ytsarev** [comment]
/fresh as we are still far from consistency in that topic.

**Comment by bobh66** [comment]
I'll add my support for either keeping crank where it is or moving it to crossplane-contrib/crossplane-cli (which is definitely more work).  I understand Upbound's reasons for creating `up` but I think if Crossplane's goal is to be Kubernetes-native then it needs to integrate into the kubernetes ecosystem in as many ways as possible, one of them being kubectl sub-commands and krew (as mentioned in #3801).  The Crossplane project should not be solely dependent on `up` for CLI functionality.

**Comment by sttts** [comment]
Note that you break users following docs on the web showing "kubectl crossplane install". Even if it is just a shallow wrapper, breaking users is not good. Deprecation of the tool with a banner printed is another solution. But keep it working.

**Comment by elohmrow** [comment]
☝️ the word "deprecated" has different meanings to different people. To me, "deprecated" means: 

> _We're going to let you keep using this, but we suggest you find a different way of doing the same thing_.

To me, the word "deprecated" _does not_ mean "turned off" / "unavailable". Something _can_ be "deprecated" _with intent_ to be "turned off" or "made unavailable". 

If the intent is to "turn off" or make something currently in use "unavailable", I believe there is a duty to provide at least a couple things:
1. A timeline. Users must be notified in advance that something will be "turned off" or made "unavailable", and _when_.  
2. A different way of doing the same thing. This could be another tool, or another instruction set.

This is my long-winded way of saying I agree with @sttts here 👍

**Comment by jbw976** [comment]
I'm closing this issue out now since CLI tooling is very much in scope given the charter expansion in #4643.  A Crossplane CLI is here to stay (and get invested in)! 💪
