### ISSUE TITLE
How to deploy K8 cluster on Baremetals. 

### ISSUE THREAD

**Issue by anilnokia** [crossplane/crossplane#3068]
I am able to use crossplane for GCP. I am also interested in using crossplane to deploy kubernetes cluster on baremetal systems OR on-prem servers. How can I do that? What are the choices of software which I can easily install and start using crossplane to create K8 cluster on on-prem servers. Thanks,

**Comment by negz** [comment]
Hi @anilnokia, since this is more of a question I recommend opening a discussion under https://github.com/crossplane/crossplane/discussions.

The quick answer though is that Crossplane would need a provider to handle the bare-metal provisioning, for example an Openstack provider. Unfortunately I'm not aware of any such provider that exists today (there's a request for an OpenStack provider at https://github.com/crossplane/crossplane/issues/267 for example).
