### ISSUE TITLE
Can you add Kind:TransitGatewayRouteTableAssociation in group ec2.aws.crossplane.io

### ISSUE THREAD

**Issue by ym-Arcadia** [crossplane/crossplane#3119]
Able to create all the required resources except route table association using provider-aws, later I installed and configured provider-jet-aws to achieve it. So I feel its good to have in group ec2.aws.crossplane.io also. Thanks

**Comment by haarchri** [comment]
@jbw976 can you move to provider-aws ?

**Comment by jbw976** [comment]
I don't seem to be able to transfer this issue to https://github.com/crossplane-contrib/provider-aws, possibly because it's in a different organization? The Github UI for transferring seems different recently and it may now be missing this functionality.

https://github.com/github-community/community/discussions/5766

@ym-Arcadia would you mind closing this issue and reopening in https://github.com/crossplane-contrib/provider-aws/issues? Thank you!
