### ISSUE TITLE
Ensure full compatibility between Composition and CompositionRevision

### ISSUE THREAD

**Issue by MisterMX** [crossplane/crossplane#3274]
### What happened?

Compositions and CompositionRevisions are made of different Go structs in `apis/apiextensions/v1` and `apis/apiextensions/v1alpha1`. This frequently leads to a desynchronization between both because changes in Compositions are not propagated to CompositionRevisions:

* #2825
* #2836
* #3113
* #3130

Consistency with Compositions for CompositionRevisions should be ensured before bumping them to v1beta1 (#2656).

This gets relevant every time the Composition API is extended.

### How could Crossplane help solve your problem?

There are multiple ways to ensure compatibility between Composition and CompositionRevisions:

* Automatically copy Go types from `v1` to `v1alpha1` using a script Go code generator.
* Let `v1alpha1` import Composition structs from `v1`.
* Create a third API struct to which `v1` and `v1alpha1` types are converted to during reconcile. K8s does something similar with it's own [apiextensions](`https://pkg.go.dev/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions).

**Comment by negz** [comment]
xref to https://github.com/crossplane/crossplane/issues/2499, which was somewhat similar.

**Comment by MisterMX** [comment]
I personally tend towards option 2 because internally, a CompositionRevision is converted to a Composition using the hand-written [`AsComposition`](https://github.com/crossplane/crossplane/blob/7a8f3e03abfb7d86e350a253466259fc7d1c7672/internal/controller/apiextensions/composite/revision.go#L29) converter function. By importing the same types we can just reuse the value of `Spec` and can decrease code complexity.

**Comment by negz** [comment]
I wouldn't _normally_ be a fan of sharing the same structs across API types due to the strong coupling of APIs. That is, if we ever did want to change the v1alpha1 API we'd end up with a mix of importing types from v1 and "bespoke" types in the v1alpha1 API. Perhaps it's not as bad in this particular case where we really do want the two API types to remain mirrors of each other.

**Comment by negz** [comment]
FWIW with that in mind my preference is to use a code generator to automatically copy types. Bonus points if it's generally applicable - i.e. for next time we're in a similar situation having to maintain e.g. v1beta1 and v1 variants of the same API.

**Comment by MisterMX** [comment]
> I wouldn't normally be a fan of sharing the same structs across API types due to the strong coupling of APIs. That is, if we ever did want to change the v1alpha1 API we'd end up with a mix of importing types from v1 and "bespoke" types in the v1alpha1 API. Perhaps it's not as bad in this particular case where we really do want the two API types to remain mirrors of each other.

I agree. We have a special case here since a CompositionRevision is basically just a historic version of a Composition with different kind.

Another argument that speaks for the import solution is that CompositionRevision is expected to land in `v1` at some point in the future. And it is also something of an internal type, because users never create revisions directly.

**Comment by MisterMX** [comment]
@negz one thought that caught me during the weekend was the design of CompositionRevisions in general. What if there are breaking changes in the Composition API in the future? How does Crossplane switch between pre- and post-breaking revisions?

Maybe you have discussed this already, but wouldn't it make sense to store the composition as a JSON blob inside the Revision instead of having to revision API match the composition API?

For example

```yaml
apiVersion: apiextensions.crossplane.io/v1alpha2
kind: CompositionRevision
metadata:
  name: my-comp-abcd1234
spec:
  compositionRef:
    name: my-comp
  # Just a JSON blob
  compositionData:
    apiVersion: apiextensions.crossplane.io/
    kind: Composition
    metadata:
      name: my-comp
    spec:
      # ...
```

**Comment by negz** [comment]
> What if there are breaking changes in the Composition API in the future? How does Crossplane switch between pre- and post-breaking revisions?

The Composition API is v1, so we really can't make breaking changes. If we did, we'd have to introduce v2 and keep serving a round-trappable v1 API variant. I imagine we'd do the same with CompositionRevisions.

That aside, some revision implementations do work the way you suggest where the revision stores an opaque blob of the type under "revision control". Under this approach setting the "active" revision would just overwrite the composition with the content of the revision - the composition would be what was reconciled rather than the revision.

I forget whether there were other factors involved, but one reason to have CompositionRevisions be a real schemafied type was for symmetry with our other revision types - ConfigurationRevision and ProviderRevision. In my opinion it would be unintuitive to have three different <T>Revision types with one functioning differently from the others.

**Comment by MisterMX** [comment]
> The Composition API is v1, so we really can't make breaking changes. If we did, we'd have to introduce v2 and keep serving a round-trappable v1 API variant. I imagine we'd do the same with CompositionRevisions.

Does this mean it won't be possible to have a fluent migration from v1 to a possible future v2 Composition?

> I forget whether there were other factors involved, but one reason to have CompositionRevisions be a real schemafied type was for symmetry with our other revision types - ConfigurationRevision and ProviderRevision. In my opinion it would be unintuitive to have three different Revision types with one functioning differently from the others.

I understand. However, package revision types are somewhat of an "active" resource with a controller in the background that reconciles it and has an effect on the cluster. A CompositionRevision on the other hand is "passive" and basically just a JSON blob. It's sole presence on the cluster has no effect on anything else because there is no controller reconciling it.

I believe CompositionRevisions should be treated more like a Git commit and be loosly coupled to Compositions - unlike the hard dependencies we have currently.

**Comment by bobh66** [comment]
> I believe CompositionRevisions should be treated more like a Git commit and be loosly coupled to Compositions

I like that analogy.  We essentially want to take a snapshot of the Composition at the time the Composite is created, and only reconcile the Composite against that version/revision/commit of the Composition.  Then later on we might want to "rebase" the Composite to a later revision/commit of the Composition.

**Comment by negz** [comment]
> However, package revision types are somewhat of an "active" resource with a controller in the background that reconciles it and has an effect on the cluster. A CompositionRevision on the other hand is "passive" and basically just a JSON blob. 

I wanted to highlight something that might not be obvious. This is the case in the codebase today, but that is largely because while CompositionRevision is pre-GA we wanted to keep the code as similar as possible whether CompositionRevisions were enabled or disabled. So currently all the actual "rendering" code is attached to the `Composition` type.

While there probably won't be a "CompositionRevision controller", the intent is to move all the rendering code over to the `CompositionRevision` type once the feature is GA (and can't be disabled with a feature flag). Today we always convert a `CompositionRevision` back to a `Composition` in order to use it to reconcile an XR; once the feature is GA that code will go away and the flow will always be:

1. `Composition` controller creates a new `CompositionRevision` where necessary.
2. XR controllers are only concerned with/aware of the `CompositionRevision` type, and use them to reconcile.

**Comment by negz** [comment]
I noodled on some things that may address this today.

I tried using `go generate` to generate the `CompositionRevision` type at build time, basically by taking the `Composition` type, copying it (just using `cp composition.go revision.go`), and renaming the type. This turned out to be painful because the two types aren't actually identical; we need to "mix in" things like `spec.revision`, and `status` for revisions. I also faced a bunch of chicken-and-egg codegen issues between `gorenamer` and `deepcopygen`.

I also considered setting up a linter rule that would complain when two different versions are out of sync by diffing their generated CRD YAML. I think this could work to keep two versions of one type that should be identical, identical (e.g. CompRev v1beta1 and v1alpha1) but again gets awkward due to the _expected_ differences between compositions and composition revisions that we'd need to ignore.

I am thinking that at least _some_ of the problem could be alleviated by using something like https://github.com/jmattheis/goverter or https://github.com/switchupcb/copygen to generate the code that converts `Composition` -> `CompositionRevision`, removing the need for folks to remember to update this manually.

Perhaps if we could get automatic conversion generation working it would be possible to catch missing fields in one type or the other by adding a "round trip" test that converts from Composition -> Revision -> Composition and ensures nothing is lost in translation?

**Comment by MisterMX** [comment]
Thanks for all the work, @negz, you've put into this issue. However, I am still not satisfied with the solution. There still are some open issues for me:

1. Composition revisions are now partially generated, but still require some manual labor to get it working. As far as I understood the code generation introduced in #3479 you still have to make changes to composition revision types in v1beta1 by hand.
2. How are breaking changes handled if a potential composition v2 is introduced? Do you introduce a composition revision v2 as well? How do users migrate between those two?

I see a lot of challenges approaching and I believe revisions are not flexible enough to handle them because their API is practically hard-wired to those of compositions.

Putting my proposal from https://github.com/crossplane/crossplane/issues/3274#issuecomment-1256249426 above back into memory:

> I believe CompositionRevisions should be treated more like a Git commit and be loosly coupled to Compositions - unlike the hard dependencies we have currently.

My idea is to scrap revision from all composition related fields and instead just store the complete manifest of the composition it represents in the spec - pruning the status info, of course. The manifest does not have a predefined schema. This way composition revisions remain as flexible when it comes to future API changes.

```yaml
apiVersion: apiextensions.crossplane.io/v1alpha2
kind: CompositionRevision
metadata:
  name: sample-abc123
spec:
  revision: 2 # Works as before
  # Store the complete composition manifest in an unstructured format
  # to remain as flexible as possible in regard to future API changes.
  composition:
    apiVersion: apiextensions.crossplane.io/v1
    kind: Composition
    metadata:
      name: sample
    spec:
      resources:
        # ...
```

In Go this would look something like this:
```go
// CompositionRevisionSpec specifies the desired state of the composition
// revision.
type CompositionRevisionSpec struct {
	// Composition is the manifest of the composition object that is stored by
	// this composition revision.
	Composition extv1.JSON `json:"composition"`

	// Revision number. Newer revisions have larger numbers.
	// +immutable
	Revision int64 `json:"revision"`
}
```

At runtime, the controller would parse the composition from the revision's spec as a JSON blob:

```go
// AsComposition creates a new composition from the supplied revision.
// A compositio revision stores a JSON manifest for a composition type.
func AsComposition(cr *v1alpha2.CompositionRevision) (*v1.Composition, error) {
	comp := &v1.Composition{}
	err := json.Unmarshal(cr.Spec.Composition.Raw, comp)
	return comp, errors.Wrap(err, errParseCompositionFromManifest)
}
```

@negz I know you have stated that `CompositionRevision` should match the API of `Composition` just like `ProviderRevision` and `ConfigurationRevision` match their counterpart for the sake of consistency. However, those APIs are far more stable, much closer tied to their parent type and in opposite to `CompositionRevision`s are actively reconciled by their own controller. All this justifies a fully specified API schema.

However, this is not the case with `CompositionRevision`s and that's why I think they should be treated differently.

What do you think?

**Comment by negz** [comment]
> Composition revisions are now partially generated, but still require some manual labor to get it working. As far as I understood the code generation introduced in https://github.com/crossplane/crossplane/pull/3479 you still have to make changes to composition revision types in v1beta1 by hand.

I'd argue the manual labor is trivial.

* Right now while the composition and revision types are in different packages (v1 and v1beta1) you need to make sure to add the same types to both packages. The build will now break if you do not.
* Once revisions go to v1 they will be in the same package and can share more types.

> How are breaking changes handled if a potential composition v2 is introduced? Do you introduce a composition revision v2 as well? How do users migrate between those two?

If we introduce Composition at `apiextensions.crossplane.io/v2` we'd have to continue serving a variant at `apiextensions.crossplane.io/v1`. We'd do the same for revisions. At the time that you updated to the version of Crossplane that introduced the new v2 Composition API all existing Compositions would begin to be served at both v1 and v2 - same for revisions.


> At runtime, the controller would parse the composition from the revision's spec as a JSON blob

The only reason we currently convert from Composition -> Revision -> Composition is to ensure the XR controller can use the same type (Composition) and logic whether you have the revision feature flag on or off. Per my comment at https://github.com/crossplane/crossplane/issues/2656#issuecomment-1297823811 I expect that once revisions are v1 we will:

* Make the feature flag a no-op.
* Make the XR reconciler aware only of Revisions, not Compositions, moving all the reconcile logic over to the Revision type.

I say all of this to point out that I do expect CompositionRevision to be more like a ProviderRevision in future. It won't have its own controller but it will be integral to the XR controller logic (as Composition is today).

**Comment by MisterMX** [comment]
> Right now while the composition and revision types are in different packages (v1 and v1beta1) you need to make sure to add the same types to both packages. The build will now break if you do not.

Thats only true on a Go language level. If I add new values to an enum (i.e. `PatchType`) but don't add it manually to the revision, the build will work, but it will fail later during reconcile.
