### ISSUE TITLE
Make it possible to sideload provider and configuration packages (`*.xpkg`) into Crossplane

### ISSUE THREAD

**Issue by spkane** [crossplane/crossplane#3288]
### What problem are you facing?
During the early development of new provider and configuration packages it would be convenient to sideload any `*.xpkg` into the cluster without requiring that they be pushed up to and pulled down from an OCI registry.

### How could Crossplane help solve your problem?
Create and document a workflow for this process.

**Comment by negz** [comment]
I agree that documenting this would be good. FWIW I'm pretty sure it's possible - it's been a minute since I've done any provider development but I'm fairly sure my process is typically:

1. Make sure my current `~/.kube/config` context is pointing at the cluster where Crossplane is running.
2. `kubectl apply -f package/crds` for my provider (and if necessary make sure I have RBAC access to them)
3. `go run cmd/main.go --debug`

**Comment by spkane** [comment]
My thought was that it would be nice to sideload the actual `*.xpkg` file into the cluster in a way that the controller can use it in the same fashion that it would if pulled from a registry so that you can test the whole thing, if possible.

That being said, having directions on how to unpack the `*.xpkg` and apply the correct manifests would be useful.

**Comment by haarchri** [comment]
can you have a look at:

https://github.com/crossplane-contrib/provider-zpa/blob/main/cluster/local/integration_tests.sh#L94
https://github.com/crossplane-contrib/provider-zpa/blob/main/cluster/local/integration_tests.sh#L145
https://github.com/crossplane-contrib/provider-zpa/blob/main/cluster/local/integration_tests.sh#L159

thinks its possible today

**Comment by haarchri** [comment]
you can check: https://github.com/crossplane-contrib/provider-aws/blob/master/cluster/local/integration_tests.sh

**Comment by hasheddan** [comment]
+1 to @haarchri suggestion -- there is some light documentation on this in https://crossplane.io/docs/v1.9/concepts/packages.html#pre-populating-the-package-cache
