### ISSUE TITLE
installing kubectl plugin has dependency on env "VERSION"

### ISSUE THREAD

**Issue by eaepstein** [crossplane/crossplane#3345]
### What happened?

curl -sL https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh | sh

downloaded the wrong thing from URL=https://releases.crossplane.io/stable/v16.17.0/bin/linux_amd64/crank

### How can we reproduce it?

have the env "VERSION" set to something unexpected before running install.sh, like "v16.17.0"

### What environment did it happen in?
Crossplane version: 1.8.1

cloud vm with 64 GB RAM and 16 vCPU

Kubectl version :
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4+k3s1", GitCommit:"c3f830e9b9ed8a4d9d0e2aa663b4591b923a296e", GitTreeState:"clean", BuildDate:"2022-08-25T03:45:26Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}

kubernetes disto: k3s

OS: VERSION="20.04.4 LTS (Focal Fossa)"

uname -a
Linux kar-reefer-k3d.sl.cloud9.ibm.com 5.4.0-125-generic #141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jmrodri** [comment]
@eaepstein Looking at the script it seems that it is made generically to allow for installing multiple versions. If `VERSION` is not set it will use `current`. One way to avoid accidentally it might be if the script uses a namespaced variable like `CXP_VERSION` since `VERSION` is pretty generic. 

What were you thinking would be a workable solution?
