### ISSUE TITLE
Allow providers to be deployed to another namespace

### ISSUE THREAD

**Issue by nabuskey** [crossplane/crossplane#3414]
### What problem are you facing?
I have a customer who is trying to create custom Crossplane providers to ease migration from their current infrastructure provisioning workflow to Crossplane. Unfortunately, the team who manages Crossplane and the team who is creating the custom providers are different. Teams are given namespaces to work within clusters and are given permissions to do their jobs within their own namespaces. Therefore, it is not ideal for them to give permissions to another team to the crossplane-system namespace. 

### How could Crossplane help solve your problem?
Currently, it looks like Crossplane itself and its packages are set to run in the same namespace. Looks like it's dictated by `-n` or `POD_NAMESPACE` . 
Is it possible to provide a way to specify which namespace providers should run? Perhaps using `ControllerConfigSpec`?

**Comment by hasheddan** [comment]
@nabuskey this currently is not supported in `ControllerConfig`. Crossplane providers are only given access to types they install by default, with the exception of `Secrets` / `ConfigMaps` / `Events` / `Leases`([ref](https://github.com/crossplane/crossplane/blob/c7b3c53db6217d59cb68eedff032dd535783140f/internal/controller/rbac/provider/roles/roles.go#L69)). I'm presuming that latter group is the one that is giving this team concern?

**Comment by cebernardi** [comment]
hi, I'm the customer :) 
we would be interested into collaborating to this feature, if it's in line with the project philosophy.

our use case is exactly what @nabuskey described: we have multitenant environments with strong namespace segregation, so that users receive elevated permissions in their assigned namespaces.

While the platform team owns and maintains crossplane "parent" and a few "official" providers (sitting in the standard "crossplane-system" namespace), we wanted to extend the crossplane user experience to some other services in the company, hence we had a team contributing with a custom provider.

Today Crossplane would spin up this custom provider in "crossplane-system" namespace, which would violate our namespace segregation principle.

We resorted to deploy the provider as a normal deployment in a separate namespace, so drifting away from the Crossplane utilities, which is not ideal.

Is there any room to allow crossplane providers to be deployed in a separate namespace? As I already mentioned, we're keen to contribute to this feature.

**Comment by negz** [comment]
If I'm understanding correctly, what you're asking is to be able to _run a provider deployment_ in a different namespace from crossplane-system. Is that actually all you need, or are you asking for a team to be able to deploy a Crossplane provider that is more broadly isolated to only their namespace?

I ask because while allowing a provider deployment to run in a different namespace is (presumably?) fairly straightforward, doing so would still:

* Require someone have RBAC access to create a (cluster scoped) `kind: Provider` to deploy the provider.
* Require someone have RBAC access to create a (cluster scoped) `kind: Composition` to use the provider.
* Make the (cluster scoped) MR types installed by the Provider available to anyone in the cluster.

If what's being asked for is to actually limit "all of" a provider to a certain namespace, that's a much harder problem to solve.

**Comment by nabuskey** [comment]
Thanks for the response! I believe @cebernardi would like is to be able to run a **_provider deployment_** in a different namespace. 
@cebernardi Please correct me if I am wrong. Is what Nic outlined above something you are okay with? Perhaps you can give the other team limited access to `kind: Provider`?

**Comment by cebernardi** [comment]
>  what you're asking is to be able to run a provider deployment in a different namespace

yes, exactly. 

we would be happy just with this feature, we can manage permissions on cluster-wide resources in another way.

@negz if there are no other ongoing efforts to achieve this, I'm keen to take a stab

**Comment by cebernardi** [comment]
@negz how would you want to proceed, would you prefer a description of the proposed changes, before starting?

**Comment by jbw976** [comment]
hey there @cebernardi, I think that's a great place to start - e.g. a 1-pager that describes in a single place the motivation for the change, the use cases, and the proposal for how it would work and what impact the change has so we can assess risk together and make sure everyone is aligned.

Thank you for your initiative and enthusiasm on this scenario - hopefully we can land on a good experience that is the right fit for the project and architecture 💪

**Comment by cebernardi** [comment]
Thank you, I'll give a stab asap!

**Comment by cebernardi** [comment]
Currently Crossplane parent controller orchestrates the deployment of any added provider controller, creating any related namespaced resources in its own namespace.

So if I install Crossplane in `crossplane-system` namespace, and I drop a `Provider` definition, the provider controller will be deployed in the `crossplane-system` namespace.

I'm proposing to add an option to specify a different namespace to deploy the provider controller (and all the related namespaced resources) into. 

We could add a `TargetNamespace` field in the `ControllerConfigSpec` definition:

```
type ControllerConfigSpec struct {
	// Metadata that will be added to the provider Pod.
	// +optional
	Metadata *PodObjectMeta `json:"metadata,omitempty"`

	// TargetNamespace specifies the namespace where the controller 
        // and all the related namespaced resources will be deployed
	// This field is optional, and if omitted, it will default to the parent Crossplane namespace
	// +optional
	TargetNamespace *string `json:"targetNamespace,omitempty"`

...
```

in `deployment.go`, method `buildProviderDeployment` manages the creation of the required resources:
https://github.com/crossplane/crossplane/blob/master/internal/controller/pkg/revision/deployment.go#L55

we could override `namespace` parameter if `TargetNamespace` is specified:

```
func buildProviderDeployment(provider *pkgmetav1.Provider, revision v1.PackageRevision, cc *v1alpha1.ControllerConfig, namespace string, pullSecrets []corev1.LocalObjectReference) (*corev1.ServiceAccount, *appsv1.Deployment, *corev1.Service) {

	// if TargetNamespace is specified, we use it
	if cc!= nil && cc.Spec.TargetNamespace != nil {
		namespace = *cc.Spec.TargetNamespace
	}

...
```
 
if the user didn't specify any `TargetNamespace`, provider deployment happens in the Crossplane namespace, as it's happening now.

**Comment by cebernardi** [comment]
I created a draft PR to better show the proposed change.
I shouldn't write it, but it works on my machine ;)

**Comment by cebernardi** [comment]
The above PR was tested against creation and deletion of aws provider:

**Provider without TargetNamespace gets deployed in crossplane-system:**
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
spec:
  package: "crossplane/provider-aws:master"
```

**Provider with TargetNamespace gets deployed in the specified namespace**:

```
apiVersion: v1
kind: Namespace
metadata:
  name: aws-crossplane
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
spec:
  package: "crossplane/provider-aws:master"
  controllerConfigRef:
    name: provider-aws
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: provider-aws
spec:
  targetNamespace: aws-crossplane
```

**Comment by cebernardi** [comment]
So, that's the very very basic use case. 

I still have to cover the scenario where a Provider deployed in namespaceA is then configured to be deployed in namespaceB.

In the meantime, any early feedback on the proposed change would be greatly appreciated.
