### ISSUE TITLE
Backoff is not working if status updated

### ISSUE THREAD

**Issue by liubog2008** [crossplane/crossplane#3455]
> Backoff is not worked in some status (e.g. delete bucket but the bucket is not empty).

> Now crossplane use For with no Options as the event handler. It means all of the update events will let the queue add the item (by queue.Add) and trigger the Reconcile.

> See https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/handler/enqueue.go#L51-L66

> However, if the status is updated when reconciling, the item will be re-added into the queue directly no matter what result of reconciling is.

> For example, the bucket is failed to be deleted because it is not empty. Then the crossplane will update the error message with aws request id into the condition. However, the aws request id is always changed, so the item is always updated and re-enqueued without any backoff.

> A reasonable fix is adding the GenerationChangedPredicate options into For function.

See the detail at https://github.com/crossplane-contrib/provider-aws/issues/1572

PR attempting to fix in provider-aws: https://github.com/crossplane-contrib/provider-aws/pull/1587

### Related issues

- https://github.com/crossplane/crossplane/issues/3840

**Comment by liubog2008** [comment]
I have a fix https://github.com/crossplane-contrib/provider-aws/pull/1587

**Comment by tehlers320** [comment]
This is a very damaging bug which will cost your thousands of dollars in cloudtrail fees. Nice find.

**Comment by jbw976** [comment]
Thanks for sharing this @liubog2008! Are folks seeing this in other providers as well, or mostly just in [crossplane-contrib/provider-aws](https://github.com/crossplane-contrib/provider-aws), for situations where the same error has a unique error message each attempt? 🤔

**Comment by liubog2008** [comment]
The delete condition timestamp will be changed always. So backoff of deletion failure for ALL CRs is not worked.

**Comment by tehlers320** [comment]
I pulled this into v0.30.1 last year and it seems to be helping significantly @liubog2008 ? what do you mean

**Comment by negz** [comment]
Just dropping a note that we have a library of predicates in crossplane-runtime. It may make sense to extend that library to wrap the proposed upstream controller-runtime predicates if they are indeed the appropriate solution here.

https://github.com/crossplane/crossplane-runtime/blob/6d423/pkg/resource/predicates.go#L34

**Comment by turkenh** [comment]
I've run some experiments to observe the backoff behavior with `crossplane-contrib/provider-aws` and `crossplane-contrib/provider-gcp`. Provider controllers did a proper backoff in experiments 2 & 3 but didn't work as expected in 1 & 4.

**Experiment 1: AWS - Delete a non-empty bucket** ❌ 

I could reproduce [the original issue](https://github.com/crossplane-contrib/provider-aws/issues/1572) by attempting to delete a non-empty S3 bucket:

<img width="1254" alt="Screen Shot 2023-01-23 at 10 16 17" src="https://user-images.githubusercontent.com/9900707/214021759-df2760d7-ff09-43f9-a81d-de46239300e2.png">

**Experiment 2: AWS - Remove permissions on a previously created Bucket** ✅ 

<img width="1254" alt="Screen Shot 2023-01-23 at 14 48 32" src="https://user-images.githubusercontent.com/9900707/214033039-7fdb2b09-24ca-498b-8de1-88cdd35dcec9.png">

**Experiment 3: GCP - Remove permissions on a previously created Bucket** ✅ 

In this case, things were working as expected with no issues.

<img width="1255" alt="Screen Shot 2023-01-23 at 14 23 01" src="https://user-images.githubusercontent.com/9900707/214028860-d00f4052-9ead-4489-aa17-0bb2c6ba58fb.png">

**Experiment 4: GCP - Create a bucket without enough permissions** ❌ 

I also observed a similar behavior by tryng to create a GCP bucket with a service account that is lack of enough permissions:

<img width="1257" alt="Screen Shot 2023-01-23 at 13 56 08" src="https://user-images.githubusercontent.com/9900707/214023424-166bed2d-94cc-4a68-9459-a4cc1ca37ade.png">

**Comment by turkenh** [comment]
For the failing cases, we kept getting custom resources updated in each reconciliation, although it keeps failing. This adds the resource to the queue again, resetting the back-off window.

In the **Experiment 1**, updates were going to `status.conditions` as follows (confirming @liubog2008's findings in the issue description):

Reconcile `n`:
```
  - lastTransitionTime: "2023-01-23T07:23:58Z"
    message: 'delete failed: operation error S3: DeleteBucket, https response error
      StatusCode: 409, RequestID: BMN3T121QR25SNVD, HostID: ssnOahqQGkRVOccNzp00UMZNLhK4BvZxi91R0iFUL8LRjcQA5NK7EtPSmkZTZHR7r5oeYtSl1qc=,
      api error BucketNotEmpty: The bucket you tried to delete is not empty'
    reason: ReconcileError
    status: "False"
    type: Synced
```

Reconcile `n+1`:
```
  - lastTransitionTime: "2023-01-23T07:24:04Z"
    message: 'delete failed: operation error S3: DeleteBucket, https response error
      StatusCode: 409, RequestID: PJQ68Z89QCX2RYB0, HostID: kdGPQJLnTPyLziPisbwidsJhFl4kiyBXVebDmnnxKY/SVaPQiBaXDEO8ruP9DoN/nyTctO1f3kE=,
      api error BucketNotEmpty: The bucket you tried to delete is not empty'
    reason: ReconcileError
    status: "False"
    type: Synced
```

In the **Experiment 4** on the other hand, updates were going to `metadata.annotations` as follows:

Reconcile `n`:
```
  metadata:
    annotations:
      crossplane.io/external-create-failed: "2023-01-23T10:38:37+03:00"
      crossplane.io/external-create-pending: "2023-01-23T10:38:36+03:00"
      crossplane.io/external-name: crossplane-example-bucket-hasan-backoff
```

Reconcile `n+1`:
```
  metadata:
    annotations:
      crossplane.io/external-create-failed: "2023-01-23T10:39:14+03:00"
      crossplane.io/external-create-pending: "2023-01-23T10:39:13+03:00"
      crossplane.io/external-name: crossplane-example-bucket-hasan-backoff
```

**Comment by turkenh** [comment]
As a solution:

**The `Experiment 1` case**: We can ignore updates to the `status` subresource and not add those updates to the work queue as proposed in https://github.com/crossplane-contrib/provider-aws/pull/1587. Given `status` is only updated by the provider controller itself (and the user is never expected to make changes there), this sounds reasonable.

**The `Experiment 4` case**: This could be a bit tricky, and not sure if ignoring updates to the annotations is a good idea since users can interact with annotations, and our controllers are expected to act in those cases. Another solution could be more focused on this specific problem, and we can change the `external-create-pending/external-create-failed` implementation so that it doesn't update the timestamp each time.

**Comment by turkenh** [comment]
I just opened the following to fix the issue with **Experiment 1**, basically following the same approach proposed in https://github.com/crossplane-contrib/provider-aws/pull/1587:

- In crossplane-runtime: https://github.com/crossplane/crossplane-runtime/pull/372
- In provider-aws (just to demonstrate how runtime PR could be consumed): https://github.com/crossplane-contrib/provider-aws/pull/1645

**Comment by turkenh** [comment]
@negz for `external-create-pending/external-create-failed` (`Experiment 4`), the most straightforward solution coming to my mind is to simply NOT update the timestamp in the setter functions in Crossplane-runtime if there is a timestamp already.
What do you think, do you see any issues with that?

**Comment by negz** [comment]
```
 message: 'delete failed: operation error S3: DeleteBucket, https response error
      StatusCode: 409, RequestID: BMN3T121QR25SNVD, HostID: ssnOahqQGkRVOccNzp00UMZNLhK4BvZxi91R0iFUL8LRjcQA5NK7EtPSmkZTZHR7r5oeYtSl1qc=,
      api error BucketNotEmpty: The bucket you tried to delete is not empty'
```

```
    message: 'delete failed: operation error S3: DeleteBucket, https response error
      StatusCode: 409, RequestID: PJQ68Z89QCX2RYB0, HostID: kdGPQJLnTPyLziPisbwidsJhFl4kiyBXVebDmnnxKY/SVaPQiBaXDEO8ruP9DoN/nyTctO1f3kE=,
      api error BucketNotEmpty: The bucket you tried to delete is not empty'
```

This seems like a regression of https://github.com/crossplane-contrib/provider-aws/issues/69. We previously attempted to fix this in https://github.com/crossplane-contrib/provider-aws/pull/475, but that requires MR authors to remember to use the right functions to wrap errors.

In theory entirely avoiding reconciles on status changes per https://github.com/crossplane/crossplane-runtime/pull/372 seems like a more robust fix, but I have some concerns that I've outlined on that PR.

**Comment by negz** [comment]
* https://pkg.go.dev/github.com/crossplane/crossplane-runtime@v0.18.0/pkg/ratelimiter#Reconciler
* https://pkg.go.dev/github.com/crossplane/crossplane-runtime@v0.18.0/pkg/ratelimiter#LimitRESTConfig

I notice that crossplane-contrib/provider-aws also doesn't seem to be using the `ratelimiter` package from crossplane-runtime. If This is what actually enforces the `--max-reconcile-rate` flag, so that flag is probably being completely ignored at the moment. (I also noticed that generated providers are using `ratelimiter.Reconciler` but aren't using `LimitRESTConfig` - raised https://github.com/upbound/upjet/issues/152 to track).

* https://github.com/upbound/provider-aws/blob/887a19/internal/controller/s3/bucket/zz_controller.go#L54
* https://github.com/crossplane-contrib/provider-aws/blob/f48128/pkg/controller/s3/bucket.go#L69

I _think_ using `reconciler.RateLimiter` would avoid the issues here, since it's fairly heavy-handed in rate-limiting all reconciles regardless of whether they're returning errors, `Requeue: true`, etc.

**Comment by negz** [comment]
> The Experiment 4 case: This could be a bit tricky,

* https://github.com/crossplane/crossplane-runtime/pull/283

I wonder if using `reconciler.RateLimiter` would be good enough for this case? I'm not against changing the way the annotations work, but I do recall the bug this was fixing was fairly subtle and tricky.  The PR that introduced this functionality is linked above.

**Comment by turkenh** [comment]
> I think using reconciler.RateLimiter would avoid the issues here, since it's fairly heavy-handed in rate-limiting all reconciles regardless of whether they're returning errors, Requeue: true, etc.

I tried modifying the s3 controller setup to use `ratelimiter.NewReconciler`, rerun Experiment 1, and didn't observe much difference in the behavior (even though it somehow went down to ~0.3 rec/s from ~1 rec/s). 

However, I am not sure how could `--max-reconcile-rate` help us to obtain the desired behaviour here since it is defined as an integer to configure the _maximum number of reconciles per second_. I mean, even if we set it to its minimum value, that is 1, it would mean 1 reconciles per second, whereas we desire to have much less (hence less API call) with a backoff.

**Comment by negz** [comment]
> However, I am not sure how could --max-reconcile-rate help us to obtain the desired behaviour here since it is defined as an integer to configure the maximum number of reconciles per second.

I actually thought `ratelimiter.NewReconciler` had per-controller or per-item backoff, but I guess not. I still think we should be using it - worse case it will cap the global per-provider reconcile frequency.

**Comment by liubog2008** [comment]
@turkenh  In the experiment 4 case, maybe we can just ignore some specified annotation keys?

**Comment by liubog2008** [comment]
In fact, these annotations are `status` of objects.

**Comment by bobh66** [comment]
We are seeing a similar scenario in provider-terraform when using the AWS provider with invalid credentials - the "message" from provider-aws is slightly different on every failure because the session ID changes, but everything else is identical.  This causes an update to the status condition and sets the lastTransitionTime even though everything else is identical.

One could argue that if the Condition Type, Status and Reason are all identical and only the Message has changed that there is no "Transition" and this the lastTransitionTime should not be updated.  If updates to the Message field can be ignored so as not to trigger reconciliation maybe that would help with scenario 1.

I agree with @turkenh that it makes sense to NOT update the timestamps on the create-* annotations which would likely solve scenario 4.

**Comment by bobh66** [comment]
I applied the DesiredStateChanged event filter to provider-terraform and confirmed that it helps considerably - the reconciliations drop to 1/minute as expected instead of being constantly running.  I'm going to implement this locally in provider-terraform for now so that it will ignore unique error messages that get generated by the terraform providers and published in the Status Conditions.

**Comment by turkenh** [comment]
Update: 

I did another set of [experiments in the runtime PR](https://github.com/crossplane/crossplane-runtime/pull/372#issuecomment-1461623758) testing the `DesiredStateChanged` predicate, which are looking good. 

That will solve the "Backoff is not working if status updated" case (the `Experiment 1` in this issue and the one reported in
[the original issue](https://github.com/crossplane-contrib/provider-aws/issues/1572))

I would like to move the other case (`Experiment 4` here) to a dedicated issue as "Backoff is not working if external create fails".
