### ISSUE TITLE
reflector.go  INTERNAL_ERROR

### ISSUE THREAD

**Issue by haarchri** [crossplane/crossplane#3565]
### What happened?
after OOM - a new crossplane pod was ready but no compositions synced anymore - the only issue we found in the logs s.u. - any ideas ?

```
Defaulted container "crossplane" out of: crossplane, crossplane-init (init)
I0110 20:35:57.454987       1 leaderelection.go:248] attempting to acquire leader lease crossplane-system/crossplane-leader-election-core...
I0110 20:36:58.789262       1 leaderelection.go:258] successfully acquired lease crossplane-system/crossplane-leader-election-core
W0110 20:38:28.255232       1 reflector.go:324] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:250: failed to list *v1.Secret: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 1779; INTERNAL_ERROR; received from peer
I0110 20:38:28.255312       1 trace.go:205] Trace[112331908]: "Reflector ListAndWatch" name:sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:250 (10-Jan-2023 20:37:21.254) (total time: 67000ms):
Trace[112331908]: ---"Objects listed" error:stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 1779; INTERNAL_ERROR; received from peer 67000ms (20:38:28.255)
Trace[112331908]: [1m7.000901427s] [1m7.000901427s] END
E0110 20:38:28.255328       1 reflector.go:138] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:250: Failed to watch *v1.Secret: failed to list *v1.Secret: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 1779; INTERNAL_ERROR; received from peer
```

### What environment did it happen in?
Crossplane version:

**Comment by jbw976** [comment]
looks like a timeout (67000ms exactly is suspicious) when starting up and trying to list secrets, probably from a controller cache getting populated.  Odd to see a basic action like this taking that long, wonder if there's some slowdown in the K8s API/control plane.

Do you see similar behavior on this cluster when doing a `kubectl get secret --all-namespaces`? how about after clearing the kubectl cache?

This comment also looks relevant for the same error message: https://github.com/helm/helm/issues/7997#issuecomment-743410706

**Comment by baldorch** [comment]
We have some fairly large clusters running and experience the same problem.

For this, this problem arises when the the `revision.APIEstablisher` tries to [validate the webhook certificate](https://github.com/crossplane/crossplane/blob/065a49ede09e11777b0c3d92c72003c3727d1ad8/internal/controller/pkg/revision/establisher.go#L144). When calling `client.Get`, the Secrets cache is first initialized with `ListAndWatch` and since we have quite a lot of Secrets in our Cluster this takes longer than our API Server allows. This closes the connection.

A quick win could be configuring the Client used by the `APIEstablisher` to only cache secrets within the crossplane Namespace.

A more wholistic approach would be to limit all caches used during setup or for "internal self-management"-purposes to only cache resources within it's own Namespace.
