### ISSUE TITLE
Improvements for release issue template

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#3701]
### What problem are you facing?

We have a lovely issue template that we use as a task list for each Crossplane release: 

* releases: https://github.com/crossplane/crossplane/blob/master/.github/ISSUE_TEMPLATE/release.md
* patch releases: https://github.com/crossplane/crossplane/blob/master/.github/ISSUE_TEMPLATE/patch_release.md

Going through the v1.11.0 release in #3600, we found a few improvements that we should incorporate into these templates.

* Update the reference issue in the intro section to point to the latest example of #3600 
* There is an entirely new process for docs releases, that is captured in the [docs repo release issue template](https://github.com/crossplane/docs/blob/master/.github/ISSUE_TEMPLATE/new_release.md).  We have this captured early in the crossplane release flow, but some later steps should be updated/removed
  * We no longer need an explicit "Updated the current release version in the [Crossplane docs website repo](https://github.com/crossplane/docs)."
  * We no longer need an explicit "Updated the release branch reaching EOL with https://github.com/crossplane/crossplane/pull/3003."
* We should add a task near the end to ensure that the docs release is completed, probably before announcing on slack/twitter
* Should a verification step be added to verify that the helm chart is published/promoted on the proper channels?
* We're no longer using the configurations workflow (see #3713), so this step can be removed
  * doesn't look like we have alignment/conclusion on this one, so skip removing this for now

@phisco, what other feedback did you have to add to this issue?

**Comment by phisco** [comment]
I'd mainly specify a little bit more some of the steps:
- explicitly stating that merging an empty commit to master could not be needed, if master branch already fell behind, it could be obvious, but I had the doubt something could be relying on that
- about running the tag workflow to create the "next release candidate tag", given that it had to be done at code freeze time, I wasn't sure whether the tag should have been `v1.11.0-rc.1` as a release candidate to be tested while in the code freeze, or `v1.12.0-rc.0`, which turned out to be actually the right answer. So, I'd make that explicit too.
- again about the tag workflow, both for the release candidate and the release tag itself, I wasn't sure about the message. Given that it's a required field for the action, I went through old release and saw there was no clear pattern, but it could still be useful to explicitly mention whether there is a suggested and/or mandatory format
- specify better what to look for in the [releases.crossplane.io] `build` channel, e.g. `build/release-1.11/v1.11.0/...` should contain some binaries etc
- I'd merge the release table update on `master` and `baseBranches` steps so that we can have a single PR for that

Then, I think it would be much easier to have an example version and explicitly stating example branch names and values for workflows, e.g. assuming we are releasing v1.11.0, "create the release branch" should be "create the `release-1.11` branch". We could use vX.Y.Z, but it becomes a little bit messy as soon as you start doing arithmetics on semantic versions, which I don't think we would need with the current steps, but could be an issue later. 

I'll open a PR for this so that we can discuss changes there.

**Comment by jeanduplessis** [comment]
Something to consider is how much of these steps could be translated into steps that can be run via a GitHub action that gets manually triggered. The more we can automate the steps, the more we can reduce human error/confusion.

**Comment by negz** [comment]
Slightly meta - I wish that only reviewers/maintainers saw the release issue template. For most folks raising an issue the templates will just be cognitive noise. We might even consider not having them be an actual issue template type but just something we maintainers copy and paste when raising a release issue?
