### ISSUE TITLE
Missing node in tree error after updating a package source

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#3985]
### What happened?

After updating the source of a package without changing its version, provider/providerrevision fails with `cannot resolve package dependencies: missing node in tree`. 

No problem occurs if the version is changed while changing the source.

### How can we reproduce it?

1. Deploy a provider from one source:

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-helm
spec:
  package: crossplanecontrib/provider-helm:v0.14.0
```

2. Wait until it is installed/healthy

```
❯ kubectl get provider.pkg
NAME            INSTALLED   HEALTHY   PACKAGE                                   AGE
provider-helm   True        True      crossplanecontrib/provider-helm:v0.14.0   7s
```

3. Update `spec.package` to `xpkg.upbound.io/crossplane-contrib/provider-helm:v0.14.0`

4. Check provider/providerrevision

```bash
❯ kubectl get provider.pkg
NAME            INSTALLED   HEALTHY   PACKAGE                                                    AGE
provider-helm   True        Unknown   xpkg.upbound.io/crossplane-contrib/provider-helm:v0.14.0   2m11s

❯ kubectl get providerrevision.pkg
NAME                         HEALTHY   REVISION   IMAGE                                                      STATE    DEP-FOUND   DEP-INSTALLED   AGE
provider-helm-ce18dd03e6e4   Unknown   1          xpkg.upbound.io/crossplane-contrib/provider-helm:v0.14.0   Active                               2m13s
```

```bash
  Warning  ResolveDependencies  7s (x6 over 36s)       packages/providerrevision.pkg.crossplane.io  cannot resolve package dependencies: missing node in tree
```

### What environment did it happen in?
Crossplane version: 1.11.3

**Comment by turkenh** [comment]
Editing the `lock` works and could be used as a workaround:

```bash
kubectl edit locks.pkg.crossplane.io lock
```

```diff
apiVersion: pkg.crossplane.io/v1beta1
kind: Lock
metadata:
  creationTimestamp: "2023-04-14T09:01:39Z"
  finalizers:
  - lock.pkg.crossplane.io
  generation: 14
  name: lock
  resourceVersion: "5655"
  uid: 6e72cf50-8cf7-4ee5-a06a-0b2e3f7c8196
packages:
  - dependencies: []
    name: provider-helm-ce18dd03e6e4
-   source: crossplanecontrib/provider-helm
+   source: xpkg.upbound.io/crossplane-contrib/provider-helm
    type: Provider
    version: v0.14.0
```

**Comment by jdillet** [comment]
We are hitting this issue because there are cases when we update the package source for a provider, but not the image.
In this case, we are hitting the issue. I have done some investigation and found that when source and image are updated, a new providerrevision is created.
However, when source is updated but image is not, no new providerrevision is created, and the lock.pkg is left with inconsistent data, as described in the workaround.


1. Deploy a provider from one source:
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-helm
spec:
  package: <source-1>/crossplane-contrib/provider-helm:v0.17.0
```

2. Wait until it is installed/healthy
```
❯ kubectl get provider.pkg
NAME            INSTALLED   HEALTHY   PACKAGE                                               AGE
provider-helm   True        True      <source-1>/crossplane-contrib/provider-helm:v0.17.0   31s
```

3. Update spec.package to a different source
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-helm
spec:
  package: <source-2>/crossplane-contrib/provider-helm:v0.17.0
```

4. Check provider/providerrevision
```
❯ kubectl get provider.pkg
NAME            INSTALLED   HEALTHY   PACKAGE                                               AGE
provider-helm   True        Unknown   <source-2>/crossplane-contrib/provider-helm:v0.17.0   31s

❯ kubectl get providerrevision.pkg
NAME                         HEALTHY   REVISION   IMAGE                                                 STATE    DEP-FOUND   DEP-INSTALLED   AGE
provider-helm-eca809ae2f5f   Unknown   1          <source-2>/crossplane-contrib/provider-helm:v0.17.0   Active                               44s
```

However, if I upgrade the source and version at the same time, there are 2 providerrevisions (this is the expected case). This happens because now the image is different, as the version has changed:

3. Update spec.package to a different source and newer version
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-helm
spec:
  package: <source-2>/crossplane-contrib/provider-helm:v0.19.0
```

4. Check provider/providerrevision
```
❯ kubectl get provider.pkg
NAME            INSTALLED   HEALTHY   PACKAGE                                               AGE
provider-helm   True        True      <source-2>/crossplane-contrib/provider-helm:v0.19.0   66s

❯ kubectl get providerrevision.pkg
NAME                         HEALTHY   REVISION   IMAGE                                                 STATE      DEP-FOUND   DEP-INSTALLED   AGE
provider-helm-6ca21c0650fc   True      2          <source-2>/crossplane-contrib/provider-helm:v0.19.0   Active                                 12s
provider-helm-eca809ae2f5f   True      1          <source-1>/crossplane-contrib/provider-helm:v0.17.0   Inactive                               67s
```

Now a new providerrevision is created because providerrevision name has changed after the upgrade (and the previous one is set to Inactive).

By following the code, providerrevision name is providername + trucated image SHA. When image is moved to a different source, SHA is not changed, so providerrevision name after the upgrade is not changed. This leaves the old reference in the lock, and causes the Missing node in tree error because reconciler is searching the image with the new source in the lock.

I'm testing a possible fix for the issue by checking in PackageDependencyManager if there are packages with same name but different source. If there is any package in this state, then delete the package from the lock. In this case, the reconciler will later find the missing package and install it from the new source. With the fix, there is one providerrevision after package is installed, but now source is updated and package is healthy.

This is very similar to the workaround provided, but instead of updating the package in the lock, I am calling existing method RemoveSelf. As described, after deleting the package, the reconciler will find the package is missing from the lock and reinstall it, this time with correct source. This fix seems easier and less intrussive than changing the logic for providerrevision name or the logic in DAG.

I would like to contribute this fix. I'll open a PR with this approach to get some feedback.
