### ISSUE TITLE
Improved e2e integration testing

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#4013]
We've been discussing the need for more investment in automated end to end (e2e) integration tests for Crossplane, this issue will track the ideas and progress on this high level initiative.

Some background information:

* e2e testing will help a lot with giving us confidence during releases of Crossplane
* testing within core crossplane has a very cheap and low coverage integration test in https://github.com/crossplane/crossplane/blob/master/cluster/local/integration_tests.sh that essentially verifies a fresh install of Crossplane comes up and runs OK.
* There is also some high level scenario and upgrade related testing in https://github.com/crossplane/test/, but those are gotten a bit stale.  We can fix and improve this early starting point, or invest in something more robust for the long term. We aren't married to this repo and approach.
* @negz did some interesting test automation in the Conformance repo that is worth considering for patterns/resuse/etc.: https://github.com/crossplane/conformance.
* Upgrade testing of Crossplane from a real world perspective when various features are enabled and/or providers are installed in a previous version, then Crossplane is upgraded to the latest version and everything is verified to be healthy, would be really helpful.
* Testing at the provider level for specific resources and real world scenarios is out of scope of this core Crossplane issue.  It already has some investment with the https://github.com/upbound/uptest/ tooling and we expect this is going to be driven further soon, e.g. upgrade testing with live resources, to avoid issues like we saw with https://github.com/upbound/provider-aws/issues/646#issuecomment-1495071479, but once again this is out of scope for core Crossplane
* Further investments in integration/e2e testing of **core crossplane** would be a good area to focus on, given that the providers are going to get more investment already. @muvaf recently made https://github.com/upbound/provider-dummy that could be used to test interesting core Crossplane functionality and scenarios without having to actually spin up cloud provider resources.

**Comment by negz** [comment]
I recently came across https://github.com/kubernetes-sigs/e2e-framework - something to consider for Crossplane e2e tests. 

I'm generally not a fan of "heavyweight" testing frameworks. Put otherwise, I prefer tests to look as much like regular Go code as possible. While https://github.com/golang/go/wiki/TestComments#assert-libraries is talking more specifically about assert libraries, it captures my rationale pretty well:

> It also forces the assert package to create a whole new sub-language instead of reusing the existing programming language (Go itself).

I feel that keeping tests as close to regular `*testing.T` style code as possible lowers the barrier for contributors.

That all said, for something like E2E tests you're probably going to end up with a framework no matter what. You'll either pick one, or end up rolling your own in order to reduce the amount of boilerplate code required to do things like installing and configuring Crossplane.

So, presuming we have to have a framework of sorts, I find https://github.com/kubernetes-sigs/e2e-framework promising because:

* It's pretty close to typical Go tests. It's all `*testing.T` style `TestFoo` functions.
* It comes from the Kubernetes ecosystem, so contributors are more likely to have seen it before.
* It's designed specifically for testing Kubernetes controllers.
* It's built on the learnings from the Kubernetes E2E tests per https://github.com/kubernetes-sigs/e2e-framework/blob/main/docs/design/README.md

**Comment by negz** [comment]
Some more prior art - https://github.com/crossplane/conformance.

This is the conformance test suite we put together to make sure Crossplane distributions (like UXP) are conformant to the requirements of upstream Crossplane. In practice the tests are fairly similar to E2E tests.

**Comment by negz** [comment]
More prior art, courtesy of @ytsarev - https://github.com/k8gb-io/k8gb/tree/master/terratest

I like the look of this one too at first glance, except maybe all the "assert framework" type functionality (`require.True` etc).
