### ISSUE TITLE
Allow packages with unexpected names to satisfy dependencies

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4023]
### What problem are you facing?

I recently tried to install a provider with a package dependency on another provider. The package manager automatically tries to install the dependency if it does not exist. It names the new provider `{org}-{name}`. In this case `upbound-provider-gcp-config`.

I had accidentally already installed that same provider with a slightly different name - just `provider-gcp-config`. This caused a conflict - the package manager wasn't able to install the provider I wanted to install, or its dependency.

I notice if I manually install the dependency with the naming convention the package manager expects for dependencies - i.e. `upbound-provider-gcp-config` - the package manager works as I would expect. It finds the existing package and considers its dependency satisfied rather than trying to install a new one.

### How could Crossplane help solve your problem?

Ideally the package manager would be clever enough to notice that my existing `provider-gcp-config` package satisfied its dependency and use that rather than trying to install a duplicate.

**Comment by negz** [comment]
CC @hasheddan - I swear we've had an issue for or related to this in the past, but I couldn't find it.

**Comment by hasheddan** [comment]
@negz I couldn't find one immediately either -- https://github.com/crossplane/crossplane/issues/1985 was the closest as it was broadly about configuration of how dependencies get installed. However, I did want to point out that the original dependency design at least attempt to take this into account by using the [`source` as the identifier](https://github.com/crossplane/crossplane/blob/ba1b9a829bb2d0584d85580f544d9aaa9096afb2/apis/pkg/v1beta1/lock.go#LL67C18-L67C18), rather than the package name. That is, if the image reference (with tag stripped) matches the dependency, then it should consider them equivalent. It sounds like that is perhaps not the case here? Can you provide the following:
- `crossplane.yaml` for package declaring the dependency
- Current state of `Lock`
- Any error events on the package revision

These should help confirm whether the resolution logic is behaving in an unexpected manner.

**Comment by turkenh** [comment]
I couldn't reproduce this by following the steps below:

1. Installed the config provider with name `provider-gcp-config`:

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-config
spec:
  package: xpkg.upbound.io/upbound-release-candidates/provider-gcp-config:v0.32.0
```

```bash
❯ kubectl get providers.pkg.crossplane.io -w
NAME                  INSTALLED   HEALTHY   PACKAGE                                                                  AGE
provider-gcp-config   True        False     xpkg.upbound.io/upbound-release-candidates/provider-gcp-config:v0.32.0   11s
provider-gcp-config   True        True      xpkg.upbound.io/upbound-release-candidates/provider-gcp-config:v0.32.0   18s
```

2. Installed another provider that a dependency on the config package:

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-cloudplatform
spec:
  package: xpkg.upbound.io/upbound-release-candidates/provider-gcp-cloudplatform:v0.32.0
```

And after a while, it became `Installed` and `Healthy` as expected.

```bash
❯ kubectl get providers.pkg.crossplane.io
NAME                         INSTALLED   HEALTHY   PACKAGE                                                                         AGE
provider-gcp-cloudplatform   True        True      xpkg.upbound.io/upbound-release-candidates/provider-gcp-cloudplatform:v0.32.0   42s
provider-gcp-config          True        True      xpkg.upbound.io/upbound-release-candidates/provider-gcp-config:v0.32.0          8m38s
```

If I only install the package with the dependency, this is what I am getting:

```bash
kubectl get providers.pkg.crossplane.io
NAME                                             INSTALLED   HEALTHY   PACKAGE                                                                         AGE
provider-gcp-cloudplatform                       True        True      xpkg.upbound.io/upbound-release-candidates/provider-gcp-cloudplatform:v0.32.0   23s
upbound-release-candidates-provider-gcp-config   True        True      xpkg.upbound.io/upbound-release-candidates/provider-gcp-config:v0.32.0
```

So, even though I used a different name (`provider-gcp-config`) than what package manager would use (`upbound-release-candidates-provider-gcp-config`), package manager considered dependencies as satisfied. 

I wonder if the issue was related to the version or source of the package rather than its name.

**Comment by negz** [comment]
I was pretty sure the source and version were identical, but I don't have the manifests around anymore so I can't be sure. Given we can't reproduce this let's assume I missed something - I'll close it and we can reopen if we run into it again.
