### ISSUE TITLE
Cut Releases of Crossplane Runtime as Part of the Release Process

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#4060]
### What problem are you facing?

Currently, we don't have a coupling between Crossplane and Crosspane Runtime versions, and there is no defined procedure to cut a release of Crossplane Runtime. It should be ok to consume `rc` versions of Crossplane Runtime on the master of Crossplane, but we are finding ourselves releasing Crossplane with an `rc` version of the runtime, for example:

- In v1.12.0:  https://github.com/crossplane/crossplane/blob/e2d4033172d76df4476595e088f442b1a2071c44/go.mod#L10
- In v1.10.0: https://github.com/crossplane/crossplane/blob/55bb734f638cdd93ebfab7b261f53594a368c4eb/go.mod#L8

The problem is that we cannot backport _Crossplane Runtime_ fixes to a specific release if/when needed. This is especially problematic for older versions since consuming a new runtime version with unwanted changes could have unexpected effects.

### How could Crossplane help solve your problem?

Cut releases of Crossplane Runtime (and maybe Crossplane Tools)  as part of the Crossplane release process, ideally following the same release branch naming. This also aligns with how Kubernetes handles releases across different component repositories.

**Comment by jbw976** [comment]
Discussed in triage today - we could add an item to the release template that serves as a reminder (not a requirement) to cut a release of crossplane-runtime if we need one.

**Comment by turkenh** [comment]
We are having problems with [backporting a fix](https://github.com/crossplane/crossplane-runtime/pull/502) in runtime to Crossplane v1.12 as it [consumes an unreleased version of XP](https://github.com/crossplane/crossplane/blob/v1.12.3/go.mod#L10) hence there is no branch to backport. 

In addition to including this in the release template as a reminder, also to mitigate this specific incident, I propose using identical versions in XP runtime as in XP. Specifically, I suggest creating the following branches in the xp-runtime (from proper commits) and tagging them accordingly:

- `release-1.11`
- `release-1.12`
- `release-1.13`

We will then consume new tags from the XP. 

I believe this is also the approach that k8s components are following.

**Comment by phisco** [comment]
I totally agree with this approach, which would fix the issue at hand. So, definitely +1 for implementing it.

However, I believe that it wouldn't solve the other major problem we have. I wonder if we could find a solution that addresses everything at once. Let's consider a scenario where we have a fix in `crossplane-runtime` that needs to be backported to all supported releases (e.g., a security fix). Assuming all releases are using a proper version of `crossplane-runtime`, as ensured by the above solution, in order to include the fix in a new release patch for each supported version of Crossplane, we would need to:

-  Merge the fix into the main branch of `crossplane-runtime`.
-  Backport the fix to three release branches of `crossplane-runtime`.
-  Create three releases of `crossplane-runtime`.
-  Update the dependency on the master branch and all release branches of `crossplane` independently. These cannot be backported since they involve version bumps to different releases.
-  Create three new releases of `crossplane`.

The above procedure is so cumbersome that it could potentially discourage someone from fixing the issue altogether or delay the fix until more changes are ready for release, knowing that they would also have to go through this process.

On the Upbound side, we also need to consider additional steps to propagate the fix to UXP.

So, once again, +1 for the above solution, as it ensures a smoother process overall. However, I still believe we should address the elephant in the room and find a better approach overall.

I need to investigate further, but I have a feeling that treating `crossplane-runtime` as a folder and a dedicated module in `crossplane` could be helpful. This would enforce the same policy as mentioned above, as the lifecycle of `crossplane-runtime` would be tied to that of `crossplane` itself without the need for active enforcement. We could simply consume the changes locally from `crossplane`.
