### ISSUE TITLE
Transient RBAC issues at Provider Startup with v1.12.1

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#4086]
### What happened?

It looks like we have a regression about giving necessary RBAC permissions to the Provider Controllers in v1.12.1, possibly related to some RBAC manager improvements we made.

I am observing the following logs flow and eventually causing a restart for the provider pod:

```
E0518 19:00:03.369195       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1beta1.VaultLock: failed to list *v1beta1.VaultLock: vaultlocks.glacier.aws.upbound.io is forbidden: User "system:serviceaccount:crossplane-system:provider-aws-c757062bcb4a" cannot list resource "vaultlocks" in API group "glacier.aws.upbound.io" at the cluster scope
W0518 19:00:03.616904       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1beta1.ParameterGroup: parametergroups.redshift.aws.upbound.io is forbidden: User "system:serviceaccount:crossplane-system:provider-aws-c757062bcb4a" cannot list resource "parametergroups" in API group "redshift.aws.upbound.io" at the cluster scope
...
```

**After the restart, the provider pod operates fine, so I don't think the severity of the issue is high.**

### How can we reproduce it?

```
kind create cluster

helm upgrade --install crossplane --namespace crossplane-system crossplane-stable/crossplane --version v1.12.1 --create-namespace

# It is more likely to happen if provider starts faster (e.g. before RBAC manager does its job), so preload the image
kind load docker-image xpkg.upbound.io/upbound/provider-aws:v0.35.0

kubectl apply -f provider-aws-0.35.0.yaml
```

I also tried to reproduce the same with XP v1.11.3 but couldn't after 5 attempts.

https://github.com/crossplane/crossplane/assets/9900707/f8aead4d-e446-4469-89fb-810a4d4d99f9

### What environment did it happen in?
Crossplane version: v1.12.1

**Comment by negz** [comment]
Cross-ref https://github.com/crossplane/crossplane/discussions/4077.

It seems likely this is due to https://github.com/crossplane/crossplane/pull/4031. My guess is there's two controllers both reconciling the `ProviderRevision` type, and they're racing:

* The Package manager is trying to install CRDs and create a `Deployment`, `ServiceAccount`, etc.
* The RBAC manager is trying to create an RBAC `ClusterRole` and bind it to the `ServiceAccount` to give the provider pod permission to what it needs to do.

Previously we build the `ClusterRole` by listing all CRDs and filtering down to the ones owned by the `ProviderRevision`. Now we look at the status of the `ProviderRevision`, which contains a list of the CRDs it installs and their types. My guess is we were always susceptible to this bug, but the RBAC manager was consistently winning the race so we never saw it before.

**Comment by negz** [comment]
If my theory is right we should be eventually consistent. The provider will crash a few times, then have the RBAC permissions to operate successfully. It seems like this fits with what @turkenh observed.

I'm reluctant to do anything that couples the package manager's work too strongly with the RBAC manager's work. You should be able to turn off the RBAC manager completely and manually manage these RBAC roles if you don't trust the elevated permissions the RBAC manager requires to operate.

Perhaps we could update our providers to essentially wait in a holding pattern until they have RBAC access to operate successfully? They could just log about the issue, rather than crashing.
