### ISSUE TITLE
disabling validating webhooks requires manual intervention

### ISSUE THREAD

**Issue by mateusz-lubanski-sinch** [crossplane/crossplane#4095]
### What happened?
We upgraded crossplane from `1.11.0` to `1.12.11` which by default enabled [validating webhook](https://github.com/crossplane/crossplane/blob/master/design/design-doc-composition-validating-webhook.md). After disabling it on HelmChart (via `webhooks.enabled: false`) I had to manually:

1. delete validating webhook
```
kubectl delete validatingwebhookconfiguration crossplane
```
2. delete `spec.webhookTLSSecretName` property from `providerrevisions.pkg.crossplane.io` objects
```
for providerrevision in $(kubectl get providerrevisions.pkg.crossplane.io --output=jsonpath={.items..metadata.name}); do kubectl patch providerrevisions.pkg.crossplane.io $providerrevision --type=json -p='[{"op": "remove", "path": "/spec/webhookTLSSecretName"}]'; done
```

### What environment did it happen in?

Crossplane version: `1.21.1`
Kubernetes version: `EKS 1.23.17`

**Comment by phisco** [comment]
This is because we are not handling webhooks via helm, but directly from the operator, which is only creating them, but not cleaning them up if "disabled" later on.
Keeping this approach, would require either periodically, or at least at startup, to delete the any existing but not required ValidatingWebhookConfiguration. The only other option I can think of would be to move the creation of the ValidatingWebhookConfiguration to the helm chart, leaving only the ca injection to the operator.

**Comment by phisco** [comment]
the issue
