### ISSUE TITLE
Support tenant isolation of XR connection details

### ISSUE THREAD

**Issue by jaylevin** [crossplane/crossplane#4277]
### What problem are you facing?
The XR (composition.yaml) has no way to patch the `publishConnectionDetailsWithStoreConfigRef` field, resulting in all XR connection details associated with all claim namespaces to be sent to the same Vault Key Vault. 

We want the XR-level connection details to land in a tenant-specific Key Vault in order to achieve 100% isolation of connection details across our tenants (claim namespaces). 

Similar to how we can patch the `publishConnectionDetailsTo.configRef.name` field on the MR and XRC level (using policy engine for enforcing the field on XRC, and native crossplane P&T logic to patch the MR's `publishConnectionDetailsTo.configRef.name` field), we want to be able to patch the `StoreConfig` reference on the XR layer (`publishConnectionDetailsWithStoreConfigRef.configRef.name`)
### How could Crossplane help solve your problem?

Allow the `publishConnectionDetailsWithStoreConfigRef` field on the XR to be patched per claim namespace.

**Comment by abhigarg28** [comment]
+1

**Comment by jtucci** [comment]
I'm running into this same issue as well

**Comment by CEO-CGS** [comment]
+1

**Comment by jbw976** [comment]
Just a reminder for folks, if you have interest in a particular issue to go ahead and add a 👍 reaction to it, a la https://github.com/crossplane/crossplane/issues/4048, so it's easier to get data about the backlog 🤓

**Comment by turkenh** [comment]
Tenants interact with Claims rather than XRs. Claims are namespaced, but XRs are cluster scoped.
Putting external secret stores aside for a second, here is how it works today:

1. `Tenant A` creates a claim in `tenant-a`. 
2. Corresponding XR is created as cluster-scoped.
3. Connection secret for XR is stored the namespace configured with `writeConnectionSecretsToNamespace` in Composition, defaulting to XP installation namespace, i.e. `crossplane-system`.
4. Connection secret for the Claim lands in the namespace of the tenant, i.e. `tenant-a`
5. If another tenant creates a claim on their on namespace, they will get access to the connection secret in the same namespace.
6. None of the tenants interact/access to the XR connection secrets under `crossplane-system`

External Secret Stores, follows the same philosophy. Let's take Vault as an example and assume we created a `StoreConfig` named `vault` with `defaultScope: crossplane-system` and pointing to the path `/secret/infrastructure` and in our composition, we configured `publishConnectionDetailsWithStoreConfigRef.name: vault`. Here is what happens in this case:

1. `Tenant A` creates a claim in `tenant-a`. 
2. Corresponding XR is created as cluster-scoped.
3. Connection secret for XR (and all MRs) is stored at `/secret/infrastructure/crossplane-system<xr-name>`
4. Connection secret for the Claim is stored at `/secret/infrastructure/tenant-a/<claim-name>`
5. If another tenant creates a claim in tenant-b namespace, their claim secret will land in `/secret/infrastructure/tenant-b/<claim-name>`

So, one can achieve tenant isolation by defining Vault policies as follows:

- Cluster admins can access `/secret/infrastructure/*`
- Tenant A users can access `/secret/infrastructure/tenant-a/*`
- Tenant B users can access `/secret/infrastructure/tenant-b/*`
- and so on

This could be inferred from the [configuration guide](https://docs.crossplane.io/knowledge-base/integrations/vault-as-secret-store/) we have, but I can acknowledge that it is not explicit enough.

Please let us know if this would help with your use case and may be we can close this issue with a documentation update.

**Comment by jaylevin** [comment]
@turkenh Hi @turkenh, first off thanks for the response and information. 

However, the solution you provided does not solve the immediate problem: the XR connection details for all tenants are still stored in a single KeyVault. We want to avoid having multiple tenants' XR connection details in the same KeyVault, regardless of whether or not we expose this KeyVault to the tenant or not. 

It is more of a security requirement to reduce the blast radius in the event of a bad actor gaining access to the KeyVault.

Hope it makes sense.

**Comment by jaylevin** [comment]
@yangyang919 Great to hear our use-case is validated by your team as well. @turkenh Let us know if we can help in any way or if this is even feasible given the current design of Crossplane.
