### ISSUE TITLE
CNCF license exception request - still valid? 

### ISSUE THREAD

**Issue by amye** [crossplane/crossplane#4284]
A long while back, https://github.com/cncf/foundation/issues/187 was filed. 

Legal Committee is working through these licensing exceptions. As of right now, none of these are approved:

- github.com/hashicorp/terraform-plugin-sdk
- github.com/hashicorp/terraform-provider-aws
- github.com/hashicorp/terraform-provider-azurerm
- github.com/hashicorp/terraform-provider-google 

Is /foundation/187 still needed?

**Comment by negz** [comment]
Thanks for chasing this up @amye!

I think the answer is roughly "no, but...".

We used these HashiCorp libraries to generate (some, not all) Crossplane providers, which are plugins/extensions to Crossplane that add functionality (e.g. in this case talking to AWS, Azure, etc). Since opening https://github.com/cncf/foundation/issues/187 we've added [a project charter](https://github.com/crossplane/crossplane/blob/v1.12.2/CHARTER.md) that declares such extensions as outside of the scope/governance of the Crossplane project. So while there are Crossplane providers that use these licenses, we don't consider them part of the Crossplane project - e.g. https://github.com/upbound/provider-aws.

Where the "but" comes in is that we created https://github.com/crossplane-contrib/ as a vendor-neutral place where folks can build providers if they so choose. We do consider providers in that org to be part of the Crossplane project, and some of them are generated with tooling that I believe would currently pull in a dependency on github.com/hashicorp/terraform-plugin-sdk.

CC @ulucinar to check my math on this - what HashiCorp libraries would an upjet-generated provider depend on? 😄

**Comment by amye** [comment]
Reason I bring this up is that Legal Committee is working through a lot of these right now, so it is a good time to get this approved if still required!

**Comment by amye** [comment]
Checking back in here, can https://github.com/cncf/foundation/issues/187 be closed?

**Comment by jbw976** [comment]
Great question @amye - I think given the news on Hashicorp's licensing change, it makes sense to consolidate our efforts here with that of the greater CNCF ecosystem and other projects in https://github.com/cncf/foundation/issues/617#issuecomment-1678235192

I'll close this issue and https://github.com/cncf/foundation/issues/187 and we will definitely follow up in https://github.com/cncf/foundation/issues/617 🙇
