### ISSUE TITLE
Create one (or two?) TLS certificates per entity?

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4305]
### What problem are you facing?

Currently we use mTLS for two things:

1. https://github.com/crossplane/crossplane/pull/2919
2. https://github.com/crossplane/crossplane/pull/3884

In more detail, I believe:

* Crossplane has a server cert bundle, used to serve webhooks (to the API server).
* Providers have a server cert bundle, used to serve webhooks (to the API server).
* Crossplane has a client cert bundle, used to connect to an ESS plugin.
* Providers have a client cert bundle, used to connect to an ESS plugin.
* ESS plugins have a server bundle, used to serve requests from Crossplane and Providers.

I expect we'll have more needs for mTLS connections in future.

### How could Crossplane help solve your problem?

Currently the configuration for all of this requires setting up a webhook cert bundle and an ESS cert bundle. Right now if I wanted to add another cert bundle (e.g. to allow Crossplane to speak mTLS gRPC to a Composition Function runner) I would presumably make it possible to configure a Function cert bundle for Crossplane, even though Crossplane already _has_ a client cert bundle (to be a client of ESS).

Do we want to stick with this pattern? I suppose the benefit is that if (e.g.) ESS communications are compromised we can rotate that certificate without rotating other client certificates. On the other hand, it seems like each entity having one certificate bundle (or perhaps one client bundle and one server bundle) might be simpler and "good enough"?

**Comment by turkenh** [comment]
> Do we want to stick with this pattern? I suppose the benefit is that if (e.g.) ESS communications are compromised we can rotate that certificate without rotating other client certificates. On the other hand, it seems like each entity having one certificate bundle (or perhaps one client bundle and one server bundle) might be simpler and "good enough"?

I remember we tried to follow the same approach that kube-apiserver took where even the kube-apiserver is a single entity, it uses different client certificates to communicate with different entities (kubelet, etcd, proxy) instead of using a single one. I can understand that we are not in the same position as kubernetes where components are distributed across machines and could go with some simplification.

I feel good about using a single client/server keypair as `xp-mtls-client` and `xp-mtls-server` to be used by both ESS and composition functions (and future entities), but hesitant to combine everything down to a single certificate for everything (client+server) as I believe it wouldn't be a best practice.

**Comment by ezgidemirel** [comment]
Since we need a new certificate pair for functions, I decided to switch to this approach, create TLS certificates per entity, and use them in the long-running functions from the beginning. 

We'll start creating a root CA and use it to sign client and server certificates. Together with the root CA secret, Crossplane's client and server certificate secrets will be created empty via Helm, and will be filled by the init container. The secret names are `crossplane-tls-server`, `crossplane-tls-client`, `root-ca-certs`.

Providers' client and server certificates will be created by the package manager and stored in `provider-xxx-tls-client` and `provider-xxx-tls-server` secrets where `xxx` is the provider name. 

Functions' server certificate will be created by the package manager and stored in `function-xxx-tls-server` secret where `xxx` is the function name. 

Since, ESS plugins are not deployed by package manager, it's not straightforward to generate different certificates for them. Therefore, I suggest to keep using the old `ess-server-certs` secret and only updating the client certificates used by Crossplane and providers.

Alternatives considered:
- We can create a single k8s secret which will store both the client and server certificates with the following keys:
```
server.crt
server.key
client.crt
client.key
```
- We can create a single certificate with `ServerAuth` and `ClientAuth` key usages and store it in `provider-xxx-tls-certs` secret.

**Comment by negz** [comment]
Awesome, sounds good @ezgidemirel!

**Comment by negz** [comment]
@ezgidemirel I'm reopening this issue because I think there's a bit of follow-up we need to do some time before v1.14.

https://github.com/crossplane/crossplane/blob/master/cmd/crossplane/core/core.go#L87-L88
I think we want to remove these right, and use the new `TLSServer` variants for webhooks?

It would probably also be useful to add some commentary somewhere in `core.go` explaining why we have three sets of TLS certs - i.e. server, client, and ESS.

**Comment by negz** [comment]
I think some cleanup is also needed in `PackageRevisionSpec`. At the moment all revisions have four secret name fields. We can't remove any (that would be a breaking API change), but we should mark at least the webhook one as deprecated (I think).

**Comment by ezgidemirel** [comment]
Hi @negz, as you mentioned, we need some cleanup work left. For Crossplane webhook, it's relatively easy to switch to new TLS certificates. But I believe providers are also relying on the same certificate. Therefore, it needs to be communicated before removing it. 

We can also deprecate the ESS client certificate secret for Crossplane and providers and start using the new ones. 

I agree that we should add more comments regarding why do we have these secrets and how we'll start using them. I'll continue working on this topic in the 1.14 scope.
