### ISSUE TITLE
Providers should support K8s resource limits

### ISSUE THREAD

**Issue by stevendborrelli** [crossplane/crossplane#4308]
### What problem are you facing?

Currently when installing a Provider package, Kubernetes [resource limits](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/) are not set. These can be set in the [resources](https://doc.crds.dev/github.com/crossplane/crossplane/pkg.crossplane.io/ControllerConfig/v1alpha1@v1.12.2#spec-resources) of the controller config, but are not set by default.

The crossplane [helm chart ](https://github.com/crossplane/crossplane/blob/4161b8e57432e3010a987ac52c7f7d0f19d88865/cluster/charts/crossplane/values.yaml#L90) sets both request and limits.

Without built-in limits, there are times when provider pod CPU/Memory affects operations on the cluster. For example: 

- https://github.com/upbound/provider-aws/issues/325
- https://github.com/upbound/upjet/issues/116 
-  (there is not an open issue for this yet), provider-kubernetes spikes to 100% when the resources it deploys cannot be deleted due to finalizer of another controller. 

### How could Crossplane help solve your problem?

At the Crossplane level guidance should enforce that providers should come with reasonable default limits, or optionally the package deployment engine should deploy packages pods with requests and limits.

**Comment by negz** [comment]
I'm about to start work on a pertinent design, so I'll take this. 😄

**Comment by turkenh** [comment]
Just a heads up, this could already be achieved using `LimitRange`'s for the namespace where providers are running:

- https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/
- https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace/

**Comment by kingdonb** [comment]
Since this is the top result in search engines for "crossplane provider set requests and limits" I'd just like to mention for anyone else that arrives here and is confused about whether or not providers can have their resources set,

The `ControllerConfig` has a `spec.resources` which you can populate, to set the requests and limits.

The new `DeploymentRuntimeConfig` also has a `deploymentruntimeconfig.spec.deploymentTemplate.spec.template.spec.containers.resources` that you can use, assuming you've moved past the deprecated `ControllerConfig`. You do not need to depend on `LimitRange`, which has the decisive disadvantage that it cannot apply independent resource policies to different pods in the same namespace.

Even goldilocks VPA generator cannot set resource policies differently for different providers in the same ns, because they all use the same container name. But you can configure resources manually through the provider's runtime configurations.
