### ISSUE TITLE
Controller crashes with panic after creating XRD

### ISSUE THREAD

**Issue by undera** [crossplane/crossplane#4504]
### What happened?
While dealing with issue https://github.com/komodorio/komoplane/issues/25, I have created an XRD that causes controller pod crash. I would expect Crossplane either to not allow me to create problematic resource, or handle it correctly. The controller pod gets into CrashLoopBackoff now.

The log of container contains panic:
```
I0815 12:15:19.954028       1 leaderelection.go:255] successfully acquired lease crossplane-system/crossplane-leader-election-core
Warning: ControllerConfig.pkg.crossplane.io/v1alpha1 has been deprecated and will be removed in a future release, but only after a comparable alternative is available.
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x192f16a]

goroutine 367 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
    sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:115 +0x1fa
panic({0x1ecd4e0, 0x34b0880})
    runtime/panic.go:884 +0x213
github.com/crossplane/crossplane/internal/xcrd.genCrdVersion({{0xc0007eee50, 0x8}, 0x1, 0x1, 0x0, 0x0, 0x0, {0x0, 0x0, 0x0}})
    github.com/crossplane/crossplane/internal/xcrd/crd.go:147 +0x66a
github.com/crossplane/crossplane/internal/xcrd.ForCompositeResource(0xc00041bb80)
    github.com/crossplane/crossplane/internal/xcrd/crd.go:74 +0x50a
github.com/crossplane/crossplane/internal/controller/apiextensions/definition.CRDRenderFn.Render(0xc00074b548?, 0xc00078c0c0?)
    github.com/crossplane/crossplane/internal/controller/apiextensions/definition/reconciler.go:109 +0x1f
github.com/crossplane/crossplane/internal/controller/apiextensions/definition.(*Reconciler).Reconcile(0xc00055d860, {0x24edde0, 0xc000728e10}, {{{0x0, 0x0}, {0xc00074b548, 0x15}}})
    github.com/crossplane/crossplane/internal/controller/apiextensions/definition/reconciler.go:262 +0x5e4
github.com/crossplane/crossplane-runtime/pkg/ratelimiter.(*Reconciler).Reconcile(0xc00020eaa0, {0x24edde0, 0xc000728e10}, {{{0x0?, 0x0?}, {0xc00074b548?, 0x40e007?}}})
    github.com/crossplane/crossplane-runtime@v0.20.1/pkg/ratelimiter/reconciler.go:54 +0x16b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x24edde0?, {0x24edde0?, 0xc000728e10?}, {{{0x0?, 0x1dcac20?}, {0xc00074b548?, 0x24da200?}}})
    sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:118 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000251860, {0x24edd38, 0xc00020e7d0}, {0x1fb3300?, 0xc00039ac60?})
    sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:314 +0x377
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000251860, {0x24edd38, 0xc00020e7d0})
    sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
    sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
    sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:222 +0x587
Stream closed EOF for crossplane-system/crossplane-8697f8cff4-tldm5 (crossplane)
```

### How can we reproduce it?
I have created clean Kind cluster, installed Crossplane via Helm there, then applied following YAML:
```yaml
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: eks1.test.komodor.com
spec:
  group: test.komodor.com
  names:
    kind: EKS
    plural: ekz
  versions:
    - name: v1alpha1
      served: true
      referenceable: true

```

### What environment did it happen in?
Crossplane version: 1.13.2
Latest version of Kind on my Linux desktop.

**Comment by dcompanykrish** [comment]
It appears the underlying cause is a permission denial for the service account during installation. Based on the logs, the account needs elevated permissions to create cluster roles and role bindings.

A couple things we can try to resolve this:

Ensure the account has sufficient cluster-admin privileges before installing Crossplane.
Pass the --cluster-admin flag during installation to grant the temporary permissions required for setup:



helm install crossplane-up-aws --namespace crossplane-system crossplane-up/crossplane --set aws.region=us-west-2 --set aws.accountID=123456789012 --set configureProvider=true --set providers.aws.region=us-west-2 --set providers.aws.accountID=123456789012 --set clusterAdmin=true

Check if there are any pre-existing cluster roles or bindings with the same name that could be causing a conflict. The installation may need to create new permissions from scratch.
Let me know if the issue persists after verifying the service account permissions and passing the --cluster-admin flag. I'm happy to dig in further and troubleshoot with you. Please share any additional error messages or details from retrying the installation.

**Comment by ezgidemirel** [comment]
Hey @undera, thanks for opening the issue! As you mentioned, crossplane isn't handling the error properly. I opened a [fix](https://github.com/crossplane/crossplane/pull/4510) to prevent crashing.

**Comment by undera** [comment]
Thank you for fixing it @ezgidemirel
