### ISSUE TITLE
Create a Go SDK for building Functions

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4574]
### What problem are you facing?

We think folks will write Composition Functions in a number of languages. A recent survey confirmed Go to be the top priority to support, with Python in second place:

![screenshot_2023-09-05_at_1 19 59___pm](https://github.com/crossplane/crossplane/assets/1049349/d2266925-6328-45e3-8c19-a02d20e225c2)

### How could Crossplane help solve your problem?

We should create a Go SDK. I think the shape of this SDK will become apparent as we start writing Functions. I believe it should include at least:

* A copy of the `RunFunctionService` gRPC types.
* The generated gRPC types and server code
* Scaffolding for setting up a Function server
* Convenience utilities for working with `RunFunctionRequest` and `RunFunctionResponse`

A good goal would be for a Function author to not have to use crossplane-runtime (though I think this will involve duplicating a bunch of crossplane-runtime).

During my first pass of building a more complex Function I identified a bunch of things that might be handy. For now they're just in [this `sdk.go` file](https://github.com/negz/function-patch-and-transform/blob/8615ec628d1ea4e936e3090060091ec223f62699/sdk.go).

**Comment by negz** [comment]
By the way, I created a repo for this at https://github.com/crossplane/function-sdk-go. Right now it only has the gRPC generated code.

**Comment by phisco** [comment]
I had a look at what other similar projects do:
- https://github.com/aws/aws-lambda-go
- https://www.pulumi.com/docs/languages-sdks/go/
- kong
  - [Kong/go-pdk: Kong Go Plugin Development Kit](https://github.com/Kong/go-pdk)
  - https://github.com/Kong/go-plugins
    - [go-plugins/go-hello.go at master · Kong/go-plugins](https://github.com/Kong/go-plugins/blob/master/go-hello.go)
- [GoogleCloudPlatform/functions-framework-go: FaaS \(Function as a service\) framework for writing portable Go functions](https://github.com/GoogleCloudPlatform/functions-framework-go)

Ideally I'd like an experience similar to that of AWS lambda functions, from their README:
```go
// main.go
package main

import (
	"github.com/aws/aws-lambda-go/lambda"
)

func hello() (string, error) {
	return "Hello λ!", nil
}

func main() {
	// Make the handler available for Remote Procedure Call by AWS Lambda
	lambda.Start(hello)
}
```

An "hello world" composition function could look something like this:
```go
// main.go
package main

import (
	"github.com/crossplane/function-sdk-go/function"
)

// should adhere to the signature "RunFunction(context.Context, *RunFunctionRequest) (*RunFunctionResponse, error)"
func myAwesomeHandler(ctx context.Context, req *RunFunctionRequest) (*RunFunctionResponse, error) {
	.... do something awesome ...
}

func main() {
        opts := []function.Opt{
           // ???
           //... TLS options ...,
           //... logger options ...,
           //... grpc options...,
        }
	function.Start(myAwesomeHandler, opts...)
}
```

Ideally as you suggested we should keep dependencies to a minimum, so we could think of leveraging the new [slog](https://go.dev/blog/slog) package for logging, which we could either make available to handlers via the context or we could add to the handler's signature directly, otherwise we can leave that as a global variable in the `function` package or a dedicated `log` subpackage. No strong opinions on this.

Always to keep dependencies to a minimum, but also because I couldn't see any other projects doing that, I would leave to users to decide how to pass parameters to the binary via flags/arguments/env/files, if they need to (they probably shouldn't need to), defaulting to whatever Crossplane actually expects (port, network, TLSCertsDir), only providing options to configure these aspects on our side (`function.Opt` above). The logging level or "debug mode" could be a special case we could want to standardise for all functions and let users configure directly via the `Function` resource `spec`.

Then as you were mentioning we should provide helpers to deal with `RunFunctionRequest`s/`RunFunctionResponse`s/`Struct`s as you are doing in [sdk.go](https://github.com/negz/function-patch-and-transform/blob/8615ec628d1ea4e936e3090060091ec223f62699/sdk.go); a place for that could be a subpackage of `github.com/crossplane/function-sdk-go/function`, maybe `helpers` or `utils` for lack of a better name, or we could think of leaving it in the `function` package directly. No strong opinions on this either.

Any thought?

**Comment by negz** [comment]
@phisco Some kinda related thoughts in https://github.com/crossplane/function-sdk-go/issues/22 :)

Some other thoughts:

* I wouldn't over-index on the SDK itself having minimum dependencies.
* I think we'll probably want some "escape hatches" for slightly more complex Functions - for example I bet some Functions will want control over their CLI flags.

**Comment by negz** [comment]
I'm going to call this done. The SDK exists, we've built a handful of Functions with it, and we can iterate on it decoupled from Crossplane releases. :)
