### ISSUE TITLE
Better support on upgrading old claims/composites when xrd has new version

### ISSUE THREAD

**Issue by yangyang919** [crossplane/crossplane#4636]
### What problem are you facing?

Let's say for a xrd:
1. first we have v1alpha1, there are claims and composites gets created based on this version
2. then we create new version v1alpha2 with breaking change, and deploy webhook for conversion strategy
3. for new claim, it's working smoothly
4. for old existing claims, in its resourceRef , it still points out to v1alpha1, while in existing composite, claimRef also still points out to v1alpha1  => right now looks like we have to manually change resourceRef and claimRef by hand, which is very annoying and risky for production environment

We are wondering whether Crossplane could provide some features on this. We believe this is a very common scenario in upgrading xrds.

**Comment by zonybob** [comment]
Don't know if this can be reopened, but I'd second this ... at least an explanation on the best way to handle compositions that still reference old `apiVersions`

As an example, I upgraded provider-k8s to v0.11 - https://github.com/crossplane-contrib/provider-kubernetes/releases/tag/v0.11.0

Per the release notes, I decided to try to update my `Object` resources inside my compositions to use `v1alpha2` instead of `v1alpha1` ... but Crossplane refuses to compose my claims now because of the mismatch in kind/apiVersion.

**Comment by PierrePIRONIN** [comment]
Exactly the same issue here.
Does someone have any news about it ?
