### ISSUE TITLE
Enable user to get insights on composite reconciliation

### ISSUE THREAD

**Issue by pedjak** [crossplane/crossplane#4660]
### What problem are you facing?

If a composition does not produce an expected outcome, users can look at resources status to understand more what happened. However, if the resources are generated without errors, but do not much the expectations, it is quite common to end up in a trial and error loop until the composition is finally fixed.

### How could Crossplane help solve your problem?

User should be able to activate developer mode for a given composite by placing `crossplane.io/dev-mode` annotation on it. The annotation value could be simply `true`, or more fine grained, e.g. it could state explicitly what composition functionalities/aspects should be set in the developer mode.

With the dev mode on, at the end of composite reconciliation, the participating resources are enriched with following data:
* each resource gets `dev.crossplane.io/prev-version` annotation containing the version of the resource at the reconciliation start
* each resource gets `dev.crossplane.io/env` annotation containing the used environment
* each resource gets `dev.crossplane.io/diff` annotation containing the resource diff generated by the composition
* composite resource contains  `dev.crossplane.io/env-bootstrap` annotation containing details about how the initial environment is constructed, i.e. resource fetch order, their content, etc.

**Comment by sttts** [comment]
I like the direction of making relevant information more visible. I have some questions and concerns. Not everything must be an annotation. We can log, we can create configmap, we can create events.

In general, writing edge data (like a diff or prev-version) is a bad idea. Convergence is not trivial. Risk of update loops. And with realtime compositions, these don't make much sense. Edges will be often and last only short time. An event or logging are better here.

**Comment by dee0sap** [comment]
Hey @pedjak 

Maybe it would good to start by listing where, from a Crossplane consumer's point of view, problems may arise.      Off the top of my head, I can think of 
- Deploy tech ( helm, kustomize... ) did not produce expected results
- A patch was malformed or its transform didn't work as expected
- Selector that selects a k8s object produced didn't work as expected 
I am sure I am missing somethings.

Anyhoo, if you had such a list then we could consider what would useful for debugging each.  Hopefully a common theme emerges.  

About logging... some years ago I worked on a commercially sold on-prem product, a collection of services, and we ended up with 
- 'normal' log files that were mostly for our dev team and our support.   For the customer these were basically useless
- an audit log - Designed specifically for customer consumption.  Used terms/language they would always be able to understand
- event log - Also designed specifically for customer consumption.   Terms/language always could track back to the admin UI and or documentation.
Customer complaints and inability to provide 'self serve' support when we just had the first log compelled us to produce the latter two.

My point here is, whatever form the diagnostics take ( events, logs, configmap, stream accessed via kubectl proxy ) it would be good if it was always clear how the data mapped to what the dev has in their claim, composition etc.

And lastly, just to capture what I mentioned in the meeting today...  It would be great if turning the diagnostics on was simple process, one that was easy for a person not familiar to Crossplane to understand. ( e.g. add annotation )   This because at least here at SAP any change to a canary or prod cluster requires approval of a change request and the approvers are more likely to approve simple changes ( add annotation ) that they understand vs complex ( make X edits to a composition ) .
