### ISSUE TITLE
`init` a new function repo/project

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#4668]
We should build a new Crossplane CLI command that initializes (scaffolds) a new repository for a composition function.

This functionality is briefly described in the Composition Function design doc: https://github.com/crossplane/crossplane/blob/master/design/design-doc-composition-functions.md#use-language-sdks

Essentially, this command should initialize a repository with all of the boiler plate code, dependencies, build logic, etc. so that an XFN author can simply focus on writing just their specific function logic.

This command would probably just copy the template repo(s) for composition functions, such as https://github.com/crossplane/function-template-go/ for golang.

@negz sketched out a possible shape of the command, but we can think further about the final experience and config options:

```console
# Initialize a new Function that uses the Go SDK.
$ kubectl crossplane init function --template="github.com/crossplane/fn-template-go"
```

**Comment by phisco** [comment]
Any major difference with just:
```sh
export MY_FUNCTION=my-awesome-function
mkdir $MY_FUNCTION
gh repo create --template github.com/crossplane/function-template-go --clone --private $MY_FUNCTION
```
I guess maybe the templating of the function name all around the repo template?
Is it worth it reimplementing the repo creation from template logic? 
Do we just want to make it a "local only" init instead of creating an actual repo? one would just loose the `generated from https://github.com/crossplane/function-template-go` line I guess:

![Image](https://github.com/crossplane/crossplane/assets/5697904/f404d623-aac4-4ff0-a6c0-840b56e1732b)

**Comment by lsviben** [comment]
> Do we just want to make it a "local only" init instead of creating an actual repo? one would just loose the generated from https://github.com/crossplane/function-template-go line I guess:

I would go with that. If you do it through github, you get the `generated from..` if from CLI, then not. At least as a start. Not sure if its worth the time to implement templating when its just changing the name in a few places.
