### ISSUE TITLE
`build/compile` and `push` Functions to a registry

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#4669]
We need to invest further in the `build` and `push` commands for Composition Functions so they are able to create complete and compliant Crossplane packages that contain the Function implementation and all the proper metadata.

There is early support for building a Function package in the `master` branch that was added in #4525, but this functionality needs to be expanded as described in https://github.com/crossplane/crossplane/pull/4525#pullrequestreview-1596578473.

> I think longer term we'll want to steal the xpkg functionality from https://github.com/upbound/up so that we can build Functions where the package metadata and controller are just different layers in the same OCI image. For now this makes sense though.

Further details about this improvement can be found in the template repo for a golang based XFN: https://github.com/crossplane/function-template-go/blob/main/Dockerfile#L15-L19

This issue depends on #4657 to use the supporting `xpkg` functionality from `up`.

**Comment by lsviben** [comment]
`build` for functions was implemented in: https://github.com/crossplane/crossplane/pull/4694

**Comment by lsviben** [comment]
For `push` we could consider migrating the up [push](https://github.com/upbound/up/blob/main/cmd/up/xpkg/push.go) command.

The current crossplane push does not have much features except for simply pushing a package somewhere. With [docker-credential-up](https://github.com/upbound/up#build-and-push-packages) it can be configured to push to Upbound marketplace.

On the other hand, the `up` implementation has features for:
- logging in to upbound (so you dont need to use docker-credentials-up)
- creating a repository there if it doesnt exist
- pushing multiple packages (usefull for provider families I presume)

TBH we can for now just use the existing `push` command for pushing functions. (it just needs a slight tweak because it accepts providers and configurations only now). I would assume pushing multiple packages could be useful for provider families. But I am not sure about the upbound specific features. Maybe its better to leave it in up for now. Or add it to the `push` command as an option, as there is no other Crossplane marketplace so it would make sense to use the Upbound one.

All in all. For the first iteration, I would just use the existing `push` command, and consider iterating on it over time. cc: @phisco as you will probably be implementing that
