### ISSUE TITLE
composition functions: desired state should be set to observed state at the top of the pipeline

### ISSUE THREAD

**Issue by gotwarlost** [crossplane/crossplane#4728]
disclaimer: I'm new to crossplane and new to composition functions so please be kind :)

I'm trying to implement a crossplane composition function that uses the JSON representation for a `RunFunctionRequest` and creates a JSON response corresponding to `RunFunctionResponse` (this is not important for the question I have but it is how I saw what was going on, since I was dumping the JSON objects)

From the protobuf: 

```
  // Desired state according to a Function pipeline. The state passed to a
  // particular Function may have been accumulated by previous Functions in the
  // pipeline.
  State desired = 3;
```
The design doc also says that compositions should be stackable and composition functions should respect desired states other functions that ran before may have set.

The issue I see is that the `desired` state is empty for the first function in the pipeline. Which means that the function needs
to be coded differently based on whether it is the first one in the pipeline or not. (e.g. use observed state as the starting point if at the top of the pipeline versus using the desired state as the starting point when downstream).

The object that I see is:

```
observed:
   composite:
       resource: { xr }
desired: {}
input: { my: input }
```

I hope my analysis is correct and my observations match the implementation of functions.

So, should crossplane be setting the desired state to the observed state for the first function in the pipeline such that a function implementation can always rely on the desired state as the starting point and only use the observed state when it needs to know something very specific about the "original" version of the object before any mutations by prior functions?

**Comment by bobh66** [comment]
This makes sense to me - - @negz ?

**Comment by negz** [comment]
This is actually how Functions did work at first. I can see why it appeals in theory, but I don't think we should go back.

One issue is that:

* Crossplane considers a resource to no longer be desired when the pipeline no longer returns it as part of desired state.
* Functions don't know where in the pipeline they're being invoked (i.e. whether they're first, second, etc).

So if Crossplane "bootstraps" the desired state from the observed state, it becomes hard for a Function to communicate that a particular composed resource is no longer required. Consider a pipeline of a single Function - Function A.

On reconcile 1:
1. Crossplane invokes the Function pipeline. There are no observed resources.
2. Function A returns desired resource `foo`.
3. Crossplane thus creates the desired resource `foo.

Then, on reconcile 2:
1. Crossplane invokes the Function pipeline. It passes _observed_ resource `foo` in as a desired resource.
2. Function A no longer desires resource `foo`.

At this point, does Function A delete `foo` from the desired resources it was passed? How does it know for sure that it "owns" `foo` - that it wasn't created by some previous Function in the pipeline? (Function A has no way of knowing that it's the only Function in the pipeline.)

A similar variant of this problem exists if a Function just wants to delete a field from a desired resource. If the desired resource it previously returned is passed back into it on the next reconcile as a desired resource, it can't know for sure whether `spec.forProvider.foo` exists in the desired state because _it_ put it there, or because some other Function did.

This is all potentially solvable, but I think you end up needing something like https://kubernetes.io/docs/reference/using-api/server-side-apply/#field-management to track which Functions own which resources/fields. You thus probably end up with more branchy/complex Function code than the current design.

Another advantage of the way things currently work is that Crossplane uses Kubernetes server-side-apply to persist the desired state the Function pipeline returns. Because the Function pipeline returns desired state as an _overlay_ onto observed state it's returning what SSA would consider "fully specified intent" ([see SSA docs](https://kubernetes.io/docs/reference/using-api/server-side-apply/#field-management)), which makes it really easy to use SSA.

Related: https://github.com/crossplane/crossplane/issues/4288

**Comment by negz** [comment]
> Which means that the function needs to be coded differently based on whether it is the first one in the pipeline or not. (e.g. use observed state as the starting point if at the top of the pipeline versus using the desired state as the starting point when downstream).

I don't think this will often be the case. In my experience most Functions want to either return new desired state based on the currently observed state, or mutate the desired state produced by previous Functions.

Consider a Function doing probably the most common thing a Function will do - producing desired composed resources based on the state of the XR. I think in this case you can always operate on observed state:

* The Function pipeline can only modify the desired _status_ of the XR, not its spec or metadata.
* If you really are deriving composed resources from XR status, you'll catch up with the desired state anyway.

What I mean by the second point above is that observed state should converge on desired state. So a Function can almost always safely desired state (as an input) on reconcile N, because on reconcile N+1 the observed state should match the desired state that was returned by reconcile N.

**Comment by negz** [comment]
(Adding docs because I think this is unintuitive at first, and thus should be well documented.)

**Comment by gotwarlost** [comment]
OK, that makes sense. So the guidance is to always use the `observed` composite as the baseline, instead of using the `desired` composite as the base on which to change.
