### ISSUE TITLE
Allow Configuration Packages to include Claims

### ISSUE THREAD

**Issue by plumbis** [crossplane/crossplane#4771]
### What problem are you facing?

The Config Package spec only allows for XRD and Composition types. 

### How could Crossplane help solve your problem?

The spec should be expanded to support Claims that can be included in a package and deployed when a Configuration is installed.

This would allow a singleton Configuration package that can deploy a control plane and defined set of resources as a single, turn-key operation. 

Related: #4770

**Comment by negz** [comment]
Today all Crossplane packages extend Crossplane with support for new functionality:

* Provider - extends Crossplane with support for new kinds of MR.
* Function - extends Crossplane with support for new kinds of Composition Function.
* Configuration - extends Crossplane with support for new kinds of XR.

I don't think claims (or XRs, or MRs) fit this mental model. They're a different kind of "configuration" -  _using_ capability, not _adding_ capability. Or in programming terms, creating an instance rather than defining a new type.

With that in mind I'm not sure it makes sense to conflate these all into one type of package (Configuration). Some considerations:

* We'd need to be careful to apply XRDs before applying claims, or the claim will fail to apply.
* Would we allow only claims? What about XRs, MRs, ProviderConfigs, etc?
* Is there real demand for this? I get the sense that not many folks use Configuration packages in the first place.
* Do _claims_ (not XRs) make sense in a Configuration package? The former are namespaced, the latter are cluster scoped.

Is what's important that someone installs a single package (or more broadly, creates a single Kubernetes resource) and gets all the things they need (providers installed, functions installed, XRDs and Compositions installed, claim created)? If so, another way to achieve that would be to create a new package type meant for "instantiating stuff" (e.g. claims) that could depend on Configurations.
