### ISSUE TITLE
Support pushing packages to xpkg.upbound.io

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4785]
### What problem are you facing?

The xpkg.upbound.io is a very common place to push Crossplane packages. It's the only "Crossplane-aware" registry I know of, in that valid packages are indexed and appear with documentation etc at https://marketplace.upbound.io.

Right now it's not clear to me whether it's possible to authenticate to xpkg.upbound.io using the `crossplane` CLI.

### How could Crossplane help solve your problem?

Make it possible to authenticate and push to xpkg.upbound.io, ideally without needing to install extra configuration or binaries (e.g. `docker-credential-up` from https://github.com/upbound/up).

**Comment by jbw976** [comment]
Very supportive of this and I think it would be a miss to ship v1.14 without being able to push to xpkg.upbound.io.

We discussed in the SIG-devex meeting this morning and concluded:

* is there a possible workaround here? if so, easiest step would be to document that
* if there's no workaround, we need to implement some auth story, but hopefully in a somewhat general way to avoid special treatment for particular registries.  This may be unavoidable though.

**Comment by phisco** [comment]
`crossplane xpkg push` is currently only reading the default `.docker/config.json` file and getting credentials according to its content, `up xpkg push` was actually relying on the content of `.up/config.json` file too. `docker-credential-up` was bridging this gap by properly configuring the `.docker/config.json` file. So do we want to make `crossplane xpkg push` aware of `.up/config.json`? if so, are we fine relying on `up login` for the login?

**Comment by phisco** [comment]
so I did some investigation and currently you either have to use `docker-credential-up` or if you want to rely on `.docker/config.json` you have to manually set the auth credentials for `xpkg.upbound.io` as follows:
```
$ up login
... sets session token in `.up/config.json` ...
$ jq -r '.upbound.profiles["default"].session | "_token:"+ .' /Users/phisco/.up/config.json | base64
... base64 encoding of "_token:<session_token>" ...
```
set the above base64 in the `.docker/config.json` like this:
```json
{
	"auths": {
		"https://index.docker.io/v1/": {},
		"xpkg.upbound.io": {
			"auth": "... base64 encoding of "_token:<session_token> ..."
		}
	},
...
}
```
Then `docker pull/push` and `crossplane xpkg push` to private repositories in `xpkg.upbound.io` will work as expected, until the token expires.

One can not just do `docker login xpkg.upbound.io`, because to authenticate the user needs to use their own username (e.g. `phiscor`), which is then not accepted by `xpkg.upbound.io` for image related operations, as it expects the username to be `_token` and a session token as password. The above trick allows to bypass the issue by manually setting the credentials, similarly to what under the hood do `up login`, exchanging username and password for a token, and `docker-credential-up`, providing docker a fake username `_token` and the session token stored in `.up/config.json`. Manually setting them is not ideal as it bypass the `credsStore` configured by setting the credential in plain text in the config file instead of securely storing them wherever the user configured them to be, e.g. MacOS's `keychain`.

I think it could be an acceptable user experience to do something similar to what the [aws](https://docs.aws.amazon.com/AmazonECR/latest/userguide/getting-started-cli.html#cli-authenticate-registry) cli does for `ecr`, `aws ecr get-login-password --region region | docker login --username AWS --password-stdin aws_account_id.dkr.ecr.region.amazonaws.com`, so `up login get-token | docker login xpkg.upbound.io --username _token --password-stdin` or something similar. Letting the user know  that the token will expire in a short time and they should use robot accounts to push from CI jobs. WDYT?

**Comment by phisco** [comment]
another option would be to improve the experience around `docker-credential-up` with a command similar to `gcloud auth configure-docker` from https://cloud.google.com/artifact-registry/docs/docker/authentication#gcloud-helper

**Comment by jbw976** [comment]
Thanks for taking the time to write this up @phisco, it really helps to understand the limitations and possibilities here.

I'm fine with teaching `crossplane` CLI how to do auth with `xpkg.upbound.io` to provide as native/smooth an experience as possible - its the only registry that understands Crossplane packages. If/when other registries come along that understand Crossplane package structure too then we can add auth support for those as well.

What do you think about engineering cost here, since there isn't much time left in v1.14? It may be challenging to balance making as smooth an experience as possible in the time we have, so feel free to make a judgement call here as a maintainer on what exactly to implement.  For example, IMO it would be reasonable to do any of these (depending on cost):

* teach `crossplane` CLI to do a `login` to a registry, or something like `gcloud auth configure-docker`
* document a command pipeline that uses `up login get-token` so people know that workflow and to use robot accounts for CI

**Comment by phisco** [comment]
Totally agree we should support `xpkg.upbound.io` as a first-class registry for Crossplane, hence support pushing to it as easily as possible.

AFAICT, today using robot accounts `docker login` works just fine and users can push using whatever tool they want, `up`, `kubectl crossplane`, `docker`, so no need to make the CI experience smoother.

So, we need to smoothen out only the experience for human users, knowing only their username and password, wanting to manually push packages.

So, the current workflow using `up` is:
```
$ up login
... provide username/password, a session token is store in $HOME/.up/config.json ...
$ up xpkg push xpkg.upbound.io/...
... the package was pushed using the session token stored by the previous step ...
```
Pushing with `docker` is supported, but requires another binary `docker-credential-up` to be installed and manually configured as credential helper for docker, editing `$HOME/.docker/config.json`.

Using `kubectl crossplane`, although not mentioned in the [docs](https://docs.crossplane.io/latest/concepts/packages/#pushing-a-package), the workflow was similar to that required to use `docker`:
```
$ up login
... provide username/password, a session token is store in $HOME/.up/config.json ...
$ ... configure docker-credential-up ...
$ kubectl crossplane push <package_type> xpkg.upbound.io/...
... package was pushed using the credentials stored in $HOME/.up/config.json, retrieved by the configured credential helper docker-credential-up ...
```

I think it's clear that the best UX was the one using just `up`, so I'd say we should aim for that and add `login` capabilities to it, `crossplane marketplace login` or just `crossplane login`.  WDYT?

I'm not sure whether we should keep using `.up/config.json` or start from scratch and use `.crossplane/config.json`, using `.up` could be a bit confusing for users now that we are removing the need to use `up` and we could have different needs w.r.t. `up` which would make it hard to support both commands with a single configuration file, so I would probably lean toward the latter. WDYT?

This way the workflow would just be:
```
$ crossplane marketplace login
... provide username/password, a session token is store in $HOME/.crossplane/config.json ...
$ crossplane xpkg push xpkg.upbound.io/...
... the package was pushed using the session token stored by the previous step ...
```

The engineering effort would be minimal given that we would mostly be moving one more command over from `up`, changing just a few minor things, plus maybe the configuration file format a bit.

Later on we could add `crossplane marketplace configure-docker` or `up configure-docker` to smooth out the experience of human users wanting to use docker or similar tools to push their packages.

**Comment by jbw976** [comment]
Thanks for the write-up @phisco! I'm good now with standardizing on `xpkg.upbound.io` being THE Crossplane registry and supporting logging into it natively with something like `crossplane marketplace login` or maybe `crossplane xpkg login`.

**Comment by phisco** [comment]
Awesome, we good using `.crossplane/config.json` instead of `.up/config.json` or should we stick to the original `.up` folder? @jbw976

**Comment by jbw976** [comment]
A bit more work to do for this issue in a follow-up PR: https://github.com/crossplane/crossplane/pull/4823#issuecomment-1767062101

**Comment by jbw976** [comment]
`crossplane xpkg login` was finalized in #4832, I think we can close this issue now 🤩 

```
❯ ./_output/bin/darwin_arm64/crank xpkg login -h
Usage: crossplane xpkg login

Login to the default package registry (xpkg.upbound.io).

Flags:
  -h, --help               Show context-sensitive help.
  -v, --version            Print version and quit.
      --verbose            Print verbose logging statements.

  -u, --username=STRING    Username used to execute command ($UP_USER).
  -p, --password=STRING    Password for specified user. '-' to read from stdin
                           ($UP_PASSWORD).
  -t, --token=STRING       Token used to execute command. '-' to read from stdin
                           ($UP_TOKEN).
      --domain=https://upbound.io
                           Root Upbound domain ($UP_DOMAIN).
      --profile=STRING     Profile used to execute command ($UP_PROFILE).
  -a, --account=STRING     Account used to execute command ($UP_ACCOUNT).
      --insecure-skip-tls-verify
                           [INSECURE] Skip verifying TLS certificates
                           ($UP_INSECURE_SKIP_TLS_VERIFY).
```
