### ISSUE TITLE
crossplane creates multiple CompositeResources for same claim

### ISSUE THREAD

**Issue by mateusz-lubanski-sinch** [crossplane/crossplane#4803]
### What happened?
We are deploying crossplane claims using [Flux](https://github.com/fluxcd/flux2) HelmRelease
On non production environments we set `HelmRelease.spec.upgrade.force=true` which results in:

- new compositeresource (for our claim) is created
- claim `resourceRef` get's updated with new compositeresource
- old compositeresource still exists and points to same claim

```
kubectl get record -n crossplane-demo crossplane-demo-record-deployed-via-hr
NAME                                     SYNCED   READY   CONNECTION-SECRET   AGE
crossplane-demo-record-deployed-via-hr   True     True                        2d5h

kubectl get xrecord -l 'crossplane.io/claim-name=crossplane-demo-record-deployed-via-hr'
NAME                                           SYNCED   READY   COMPOSITION                                         AGE
crossplane-demo-record-deployed-via-hr-84shb   True     True    records.route53.aws.crossplane.sinch.com-v1alpha1   3h8m
crossplane-demo-record-deployed-via-hr-bv9ss   True     True    records.route53.aws.crossplane.sinch.com-v1alpha1   177m
crossplane-demo-record-deployed-via-hr-jqfls   True     True    records.route53.aws.crossplane.sinch.com-v1alpha1   2d5h
crossplane-demo-record-deployed-via-hr-t5cdf   True     True    records.route53.aws.crossplane.sinch.com-v1alpha1   3h5m
crossplane-demo-record-deployed-via-hr-w78d5   True     True    records.route53.aws.crossplane.sinch.com-v1alpha1   2d5h
crossplane-demo-record-deployed-via-hr-z2sq6   True     True    records.route53.aws.crossplane.sinch.com-v1alpha1   2d5h
```

### How can we reproduce it?

create claim
```
kubectl apply -f ./claim.yaml
```
run `kuybectl replace`:
```
kubectl replace -f ./claim.yaml
```

### What environment did it happen in?

* crossplane `1.13.2`
* Cloud provider: `AWS`
* Kubernetes version: 1.25.x
* Kubernetes distribution: `EKS`

**Comment by negz** [comment]
I think @bobh66 is right here. I'm going to close this, since I believe we're working as expected as long as you don't use `kubectl replace`.

**Comment by mateusz-lubanski-sinch** [comment]
We are not running `kubectl replace` directly

We are deploying our crossplane claims via Flux HelmRelease, where on non prod envs we set `spec.upgrade.force=true`  (to mitigate problem of manual changes directly on the cluster)

With this setup one Claim produced ~200 CompositeResources

**Comment by bobh66** [comment]
I'm not familiar with Flux but ArgoCD will keep the claims in sync with k8s without using replace/force.

**Comment by smileisak** [comment]
I respectfully disagree with @bobh66 and @negz on this point.

Orphaned composite resources should be garbage collected automatically—whether through Kubernetes native garbage collection or via Crossplane itself. In large-scale clusters with thousands of developers continuously deploying apps using tools like Helm or Kustomize, it’s not practical to rely solely on guidelines like “avoid replacing resources,” since tools such as helm upgrade --force perform replacements automatically under the hood.

Having a robust garbage collection mechanism in Crossplane would greatly simplify managing resource lifecycles and improve cluster stability at scale.

**Comment by bobh66** [comment]
I don't disagree that the case of replacing the claim should cause the old composite to be deleted because the `claimRef` in the composite is now invalid.  Similar to how it is invalid for an `ownerReference` to point at something the no longer exists, the composite reconciler should probably treat broken `claimRef`s as the equivalent of a delete.  At a minimum the issue should be discussed/investigated more.

I suspect that this is not an issue in v2 because of the `ownerReferences` becoming invalid so k8s will clean it up for you (although probably not using foreground cascading deletion, which could be a problem).

I still think "don't do that" is good advice - while there are reasons to `replace` a resource - mostly (I think) due to not using SSA - it should be used rarely and with care, and the user should understand that there may be side effects that they don't know about.
