### ISSUE TITLE
Removal of paused claim or namespace containing it get stuck

### ISSUE THREAD

**Issue by pedjak** [crossplane/crossplane#4839]
### What happened?

A paused claim and/or namespace containing it cannot be removed - the operation get stuck.

### How can we reproduce it?

 * Create namespace `example`
 * Create a claim in it
 * Pause claim
 *  Triy to remove namespace with `kubectl delete ns example`
 
`kubectl` hangs with the message `namespace "example" deleted` but it does not return to the prompt.

Even if I do `kubectl describe` on that claim, there is no trace saying that deletion is blocked and can be resumed when pause annotation is removed.

### What should be the behavior?

A paused resource should be removable.

We indicate that reconciliation is paused via condition of type `Synced` like this:

```yaml
reason: ReconcilePaused
status: "False"
type: Synced
```

when `False` it means that we are not syncing claim changes with the counterpart composite, i.e. we are not passing claim updates down the line. However, object deletion is not an update, at least not in CRUD/REST context, and therefore an user should be very surprised to discover that deletion of paused objects or higher order objects get stuck.
 

### What environment did it happen in?

All supported versions.

**Comment by pedjak** [comment]
@plumbis IMHO [the docs](https://docs.crossplane.io/latest/concepts/composite-resources/) are rather unclear on the topic as well:

```
Crossplane supports pausing composite resources. A paused composite resource doesn’t check or make changes on its external resources.
```

**Comment by bobh66** [comment]
I'm pretty sure there has been discussion around whether the `paused` annotation should block deletion or not, and there are good arguments in both scenarios.  I have run into the case where I `paused` a resource and forgot about it and then my delete process hung until I remembered and removed the annotation.

This is the same behavior the user will see in 1.14 when using Foreground deletion and attempting to delete a Claim that has an XR with a `Usage` pointing at it or one if it's children.  The delete command will 'hang' until the XR/child can be successfully deleted.  This is a feature-not-a-bug but is not the best user experience.  One could argue that the delete should be rejected by a webhook and the user forced to retry, but it's also valid to say that the resource deletion has been requested and Kubernetes will _eventually_ complete the deletion, once the underlying condition has been resolved.

**Comment by turkenh** [comment]
> A paused resource should be removable.

I disagree.

There are previous discussions [here](https://github.com/crossplane/crossplane/pull/4820#discussion_r1361805251) and [there](https://crossplane.slack.com/archives/CEF5N8X08/p1697618937115119?thread_ts=1697555426.091559&cid=CEF5N8X08), but as a summary, the pause annotation should pause the deletion, because:

- Deletion is also part of reconciliation, so pausing reconciliation should also pause the deletion.
- Deleting an external resource could be catastrophic (e.g. prod db) for users expecting the above.
- For those expecting deletion not to be paused, it is just a degraded UX to go and find that resource and remove the annotation to continue.
- The pause annotation is not something for regular operation; it’s more for break-glass situations, so Crossplane should do as little as possible.
- Changing this behavior today would be a breaking (behavioral if not API-wise) change for the existing users for MRs/Claims/Composites.
- It is also implemented in the same way in cluster API, which could be considered as an indication that this is what most people expect from such a functionality, see: [https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/b90810b70864664a00314f40a3f8a31d4215f1b5/controllers/awscluster_controller.go#L[…]4](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/b90810b70864664a00314f40a3f8a31d4215f1b5/controllers/awscluster_controller.go#L165-L194)

**Comment by pedjak** [comment]
> It is also implemented in the same way in cluster API, which could be considered as an indication that this is what most people expect from such a functionality

One example does not say much what the majority does or should do. 

Azure Service Operator does quite the opposite, it allows deletion when the reconciliation is paused (in their terms: skipped), see here: https://github.com/Azure/azure-service-operator/blob/main/controllers/async_controller.go#L98-L107

This operator is a business similar to Crossplane, i.e. in the same domain as [provider-azure](https://github.com/upbound/provider-azure). Hence, it could be considered as an indication that this sort of behavior is expected by users.

What kind of user experience we would like to offer?
