### ISSUE TITLE
Document function result best practices

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4947]
### What problem are you facing?

When a composition function returns a normal or warning [Result](https://buf.build/crossplane/crossplane/docs/main:apiextensions.fn.proto.v1beta1#apiextensions.fn.proto.v1beta1.Result) Crossplane will emit it as a Kubernetes event.

Typically we only want to emit events when something changes. This means function authors should be sure to only emit events when something changes. There's no way for function authors to know this - we don't document it anywhere.

### How could Crossplane help solve your problem?

We should document it. I'm raising this here rather than at https://github.com/crossplane/docs because I think there's three places we could and should document it:

* In the protobuf schema types, so it shows up in their [API docs](https://buf.build/crossplane/crossplane/docs/main:apiextensions.fn.proto.v1beta1#apiextensions.fn.proto.v1beta1.Result)
* In the function-sdk-go [Godoc](https://pkg.go.dev/github.com/crossplane/function-sdk-go@v0.1.0/response#Normal) for `response.Normal` and `response.Warning`.
* In the [guide to writing a function in Go](https://docs.crossplane.io/knowledge-base/guides/write-a-composition-function-in-go/)

**Comment by dalton-hill-0** [comment]
https://github.com/crossplane/crossplane/pull/5450 adds 
- The ability for results to optionally emit events to the claim as well as the XR.
- The ability to set status conditions on the XR and optionally the claim.

Since this functionality is closely related to the docs mentioned in this issue, we may want to document both at the same time.
