### ISSUE TITLE
ControllerConfig not modifying settings of provider pods in case of removal of labels

### ISSUE THREAD

**Issue by anshusingh64** [crossplane/crossplane#5016]
### What happened?
Removal of a label from spec.metadata.labels section of ControllerConfig is not resulting in removal of that label from spec.template.metadata.labels section of provider deployments. Addition of a new label or change of value of any existing label is working as expected but removal is not.

### How can we reproduce it?

Add a label under spec.metadata.labels section of controller config, that label will get added to the provider as well. Now remove that label and add any other label, that new label will get added to the provider pods and the old label which has been removed from the ControllerConfig will still be there on the provider along with the new one.

### What environment did it happen in?
Staging and Production

### Crossplane version: 

1.12.x

### Kubernetes version:

1.24.x

### Kubernetes Platform:

EKS

**Comment by bobh66** [comment]
Removing labels (map keys) requires Server-Side Apply.  Since ControllerConfig is deprecated and replaced by DeploymentRuntimeConfig I would not expect this to be fixed.  Can you test the same scenario with DeploymentRuntimeConfig on 1.14 and see if the problem still exists?   https://docs.crossplane.io/latest/concepts/providers/#runtime-configuration

**Comment by anshusingh64** [comment]
@bobh66 Tested it with `DeploymentRuntimeConfig ` still the same behaviour.

**Comment by turkenh** [comment]
> @bobh66 Tested it with `DeploymentRuntimeConfig ` still the same behaviour.

Thanks for reporting and testing @anshusingh64 

We already have an issue to switch server side apply here, which should fix the issue as @bobh66 pointed out: https://github.com/crossplane/crossplane/issues/4817

**Comment by anshusingh64** [comment]
@turkenh Have we started on the implementation of server side apply ?
Seems to be a significant change if we're going to replace the whole patching logic.

**Comment by anshusingh64** [comment]
Moreover, I'm just curious why can't  we override the deployment labels with CC or DeploymentRuntimeconfig ones and the selectors in place of adding only those which are available https://github.com/crossplane/crossplane/blob/master/internal/controller/pkg/revision/runtime_override_options.go#L269

**Comment by turkenh** [comment]
> @turkenh Have we started on the implementation of server side apply ? Seems to be a significant change if we're going to replace the whole patching logic.

No, not yet. Do you have any specific concerns with this?

> Moreover, I'm just curious why can't we override the deployment labels with CC or DeploymentRuntimeconfig

AFAIR, that was (incorrectly) done to keep selector labels and left untouched during the refactor for implementing `DeploymentRuntimeconfig`. For `DeploymentRuntimeconfig`, we [do not merge](https://github.com/crossplane/crossplane/blob/5b278671b2eecdb62260a40d27defe9d21386bce/internal/controller/pkg/revision/runtime_defaults.go#L55) in code like that, however, it could happen since we use the patching applicator.

**Comment by anshusingh64** [comment]
> No, not yet. Do you have any specific concerns with this?

We have faced few incidents on our production environment because of this where we removed the labels on CC and it didn't  restart the pods to consider those removal of labels. 

> AFAIR, that was (incorrectly) done to keep selector labels and left untouched during the refactor for implementing DeploymentRuntimeconfig

Does that mean we could do it in the way where the labels are overriden completely along with keeping the selector labels ?

**Comment by jbw976** [comment]
Just to put some closure on this thread, I believe this is indeed a duplicate of #4817. Looks like that one got closed as stale, so I will re-open it 😅 

* https://github.com/crossplane/crossplane/issues/4817
