### ISSUE TITLE
Support installation of stacks from private registries

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#505]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:** Currently, users can only install extensions from public registries.  They should be able to publish and install from private registries too, perhaps with `imagePullSecrets`.  Note that this would apply to multiple levels of packages/images, since all of the following can be different images:

* the Stack package (run in control plane)
* the controller (`Deployment` image) or other implementation "body" (run in control plane)
* workloads (`KubernetesApplication` component resources) that the controller generates (run in target clusters)

To put into a more concrete example using say Gitlab, this **could** be 3 separate images that could all come from a private registry:
* gitlab-package (that installs)
* gitlab-controller (that generates)
* gitlab-workload (that is propagated to a target cluster)

Note that the workload is propagated to a target cluster, so the private registry credentials would need to be propagated there also.

**What is use case behind this feature:** . Some users will not want to publish their extension package to a public registry, so we should support private registries as well.

**Comment by glyn** [comment]
Crossplane may wish to take a look at [CNAB](https://cnab.io/) and its reference implementation as a standard alternative to some of the features of stacks.

In relation to this issue, CNAB supports the notion of _image relocation_ where a "bundle" of software referring to docker/OCI images in public or private registries is relocated to a (typically private) registry. For more on image relocation, see this [gentle overview](https://github.com/deislabs/cnab-spec/blob/master/805-airgap.md) in the spec and this more detailed [guide](https://github.com/deislabs/duffle/blob/ce81bb239c0b851e1997af3136b52957bdd2c0f5/docs/guides/relocation-guide.md) in the reference implementation.

**Comment by glyn** [comment]
Let's take any discussion relating to my [earlier comment](https://github.com/crossplaneio/crossplane/issues/505#issuecomment-517811617) over to https://github.com/crossplaneio/crossplane/issues/666.

**Comment by muvaf** [comment]
This is blocking Upbound registry to be used. Is there a timeline on when we could get that feature implemented? @jbw976

**Comment by displague** [comment]
@muvaf I'll be taking this on over the next couple of weeks.
I'm tagging the relationship between this issue and https://github.com/crossplaneio/crossplane/issues/974 because we may need changes to the StackInstall or Stack type to accomodate this.

Documentation updates will be the primary output of this effort, whether or not Stack/StackInstall changes are necessary.

I expect that one path for using private registries is to take advantage of namespace wide configurations for `imagePullSecrets`:
* https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account

This approach should handle all Stack processing needs, including: mount, unpack, and deployment.  Because ClusterStackInstalls and more importantly, their Stack resource, reside in a namespace, they can also benefit from this approach.

But Crossplane may need code changes to support:
* Stack Manager InstallJob mounting private stack images for unpack when referenced from a StackInstall resources
* Stacks using deployment images from private registries 
* These two concerns may need to independent ways of defining their imagePullSecrets (but I suspect one approach could accommodate both needs)

StackInstalls and perhaps Stacks themselves, may need a spec parameter for specifying imagePullSecrets so that pods for the `StackInstall` install `Job` and `Stack` controller `Deployment` include `imagePullSecrets`: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret

**Comment by prasek** [comment]
@displague sounds like we have the first two bullets done, but still need the

**Comment by displague** [comment]
@prasek I think the third bullet warrants its own issue.

Workloads is a broad term here and could refer to any image being referenced within a `KubernetesApplication`.

This could be the image on a Pod, Job, Deployment, or even  \*_**Inception** sound effect_\* a StackInstall.  While I think we can make some effort to deeply apply imagePullSecrets, imagePullPolicy, and image source replacement for these four known resource types, this could easily get messy and unwanted.

I think it may make more sense to decouple these StackInstall specified parameters from those used within a `KubernetesApplication`.  I would love to get input from the services squad about how these parameters could be specified at the KubernetesApplication spec layer and what effect users would expect when providing those parameters.

**Comment by displague** [comment]
For host aware environments, we will want to create another issue to copy imagePullSecrets to the host environment.

These secrets will need to be given UUID names on the host side since tennant namespaces share a common controller namespace in this environment and we wouldn't want secrets from varying namespaces to be available outside of their intended namespace. In order for these renamed secrets to sync with their sources they will need to be labeled with the source name.

An alternative to using the UUID approach may be to use a simple namespace prefix, as I believe is done for other resources in the controller namespace.  The effort between these two approaches is similar, as all deep references to the secret name will need to be revised in either case.   With UUID names, we may suffice to replace imagePullSecret references.  With namespace prefixed secret names we will need to replace imagePullSecret, valueFrom, and other references.

The UUID approach is safer if any secret reference formats are missed.

**Comment by jbw976** [comment]
The remaining work discussed in this issue is being tracked in:

* #1318 - Support in workloads for images from private registries
* #1317 - Copy imagePullSecrets to Crossplane Host environments
