### ISSUE TITLE
Realtime compositions E2E tests flaky

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#5228]
### What happened?

Anecdotally the realtime compositions E2E test seems to fail a lot more often than it passes. This means I'm becoming used to seeing the little ❌ next to every Crossplane PR (and on master). Ideally it would not be so flaky.

### How can we reproduce it?

Run the E2E in GitHub Actions a few times.

### What environment did it happen in?
Crossplane version:

**Comment by negz** [comment]
FYI @sttts still seeing flakes after bumping runtime to include https://github.com/crossplane/crossplane-runtime/pull/641.

**Comment by sttts** [comment]
@negz yes, was expecting that. Matches feedback in https://github.com/crossplane/crossplane/issues/5151. Will take another look when I have time.

**Comment by negz** [comment]
https://github.com/crossplane/crossplane/pull/5651 might fix this - let's monitor for a while.

**Comment by jbw976** [comment]
Just checked on the [buildpulse flake report](https://app.buildpulse.io/@crossplane/crossplane?q=realtime&select%5B%5D=&show_type=default&sort=disruptiveness&daterange=May+1+-+July+15&starting_at=2024-05-01+07%3A00%3A00+%2B0000&ending_at=2024-07-16+06%3A59%3A59+%2B0000) and I'm going to call this one complete via #5651, great work @negz!

We can see that the realtime tests haven't failed since https://github.com/crossplane/crossplane/commit/6292789f335f56ea4d675c45dfbe622e3ad693c8 on May 20, and #5651 was merged on May 21. More than a month of no failures! ✅ 

<img width="1761" alt="Screenshot 2024-07-15 at 11 02 03 AM" src="https://github.com/user-attachments/assets/baeb60ad-7e08-4f54-bb27-c430268868ad">

**Comment by sttts** [comment]
Indeed, great work @negz!
