### ISSUE TITLE
Hello everyone, Crossplane has something similar to Terraform Plan? Something that we can see what will happen before apply.

### ISSUE THREAD

**Issue by marcelmedeiros1** [crossplane/crossplane#5863]

**Comment by jbw976** [comment]
This is definitely something that comes up in the Crossplane community and it's tracked in https://github.com/crossplane/crossplane/issues/1805. The idea of building trust and confidence in your control plane is a spectrum and we can make improvements at different phases of the life cycle.

For instance, in v1.17 we are planning to ship https://github.com/crossplane/crossplane/issues/5477, which is at the later end of the spectrum, but certainly helps build trust and confidence nonetheless.

Since this is already tracked in https://github.com/crossplane/crossplane/issues/1805, I'll go ahead and close this as a duplicate. Thanks for your interest, feel free to add a 👍 to that issue 🙇‍♂️
