### ISSUE TITLE
Ignore Specified Resource Fields During Reconciliation

### ISSUE THREAD

**Issue by humoflife** [crossplane/crossplane#5873]
### What problem are you facing?

An external compliance system mutates resource tags. The tags keys nor values are known at resource creation time. Therefore initProvider cannot solve setting the tags that should later be ignored. This is a feature request to ignore reconciliation of a forProvider field, and the current use case is for the tag field of cloud resources.

### How could Crossplane help solve your problem?

Provide an annotation that can receive an array of fields for which reconciliation is ignored, e.g. crossplane.io/external-change-ignore: ["rds.aws.upbound.io:v1beta1:Cluster:spec.forProvider.tags"]. The annotation should support wildcards for the GVK + field, e.g. ["rds.aws.upbound.io:v1beta*:*:spec.forProvider.tags"]. The latter would apply to all rds.aws.upbound.io resources of version v1beta0, 1, 2, ..., for all kinds that have a field spec.forProvider.tags. Multiple comma separated entries should be supported in the array list.

Alternatively, an implementation could set the ignore field through a meta data patch, e.g. patching a "metadata-crossplane-ignore" value to a forProvider field could trigger crossplane to ignore the changes of that specific field. However, the above annotation would be more in line with annotations that pause and resume reconciliation at the metadata annotation level.

**Comment by bobh66** [comment]
I suspect this might be more of a crossplane-runtime issue since it deals with the providers, but others can chime in.

**Comment by turkenh** [comment]
Asking to understand, shouldn't we just drop "spec.forProvider.tags" in that case (and probably disable late initialization via management policies) ?

**Comment by negz** [comment]
The suggested approach was considered and discarded during the design that ultimately resulted in `initProvider`. I'm reluctant to move toward an approach where we end up supporting both initProvider and ignore changes.

https://github.com/crossplane/crossplane/blob/v1.16.0/design/one-pager-ignore-changes.md#ignorechanges-field

> The tags keys nor values are known at resource creation time. 

Should this say the keys and values are _not_ known at creation time?

More clarity on the problem you're trying to solve would help. Is the problem that:

* There are tags that aren't known at create time.
* A third party system adds tags after create time.
* The provider doesn't see these tags in `initProvider` or `forProvider`, so it removes them?

**Comment by negz** [comment]
This isn't super intuitive, but looking at the upjet code, something like this might do the trick:

```yaml
apiVersion: example.crossplane.io/v1
kind: SomeResource
metadata:
  name: some-resource
spec:
  # Specify tags in initProvider but not forProvider.
  initProvider:
    tags: {}
  forProvider:
    widgets: 9000
```

Looking at https://github.com/crossplane/upjet/blob/v1.4.1/pkg/resource/ignored.go#L16, it seems like upjet providers will ignore changes to any field that appears in `initProvider` and doesn't appear in `forProvider`.

**Comment by haarchri** [comment]
we have a special handling with default tags for `spec.forProvider.tags` 
https://github.com/crossplane/upjet/blob/main/pkg/config/resource.go#L318
and this will send as an update here: https://github.com/crossplane/upjet/blob/main/pkg/config/resource.go#L325

test resource:
```
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: role-with-inline-policy
spec:
  initProvider:
    tags:
      chris: haar
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "eks.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
```

will lead to:

```
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    crossplane.io/external-create-pending: "2024-08-12T15:37:44Z"
    crossplane.io/external-create-succeeded: "2024-08-12T15:37:44Z"
    crossplane.io/external-name: role-with-inline-policy
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"iam.aws.upbound.io/v1beta1","kind":"Role","metadata":{"annotations":{},"name":"role-with-inline-policy"},"spec":{"forProvider":{"assumeRolePolicy":"{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Effect\": \"Allow\",\n      \"Principal\": {\n        \"Service\": \"eks.amazonaws.com\"\n      },\n      \"Action\": \"sts:AssumeRole\"\n    }\n  ]\n}\n","tags":{}},"initProvider":{"tags":{"chris":"haar"}}}}
  creationTimestamp: "2024-08-12T15:37:44Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generation: 3
  name: role-with-inline-policy
  resourceVersion: "11541"
  uid: 2c24258f-b1e9-4a59-9f85-13441d998cd6
spec:
  deletionPolicy: Delete
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "eks.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
    maxSessionDuration: 3600
    path: /
    tags:
      crossplane-kind: role.iam.aws.upbound.io
      crossplane-name: role-with-inline-policy
      crossplane-providerconfig: default
  initProvider:
    tags:
      chris: haar
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
status:
  atProvider:
    arn: arn:aws:iam::609897127049:role/role-with-inline-policy
    assumeRolePolicy: '{"Statement":[{"Action":"sts:AssumeRole","Effect":"Allow","Principal":{"Service":"eks.amazonaws.com"}}],"Version":"2012-10-17"}'
    createDate: "2024-08-12T15:37:45Z"
    description: ""
    forceDetachPolicies: false
    id: role-with-inline-policy
    maxSessionDuration: 3600
    path: /
    permissionsBoundary: ""
    tags:
      chris: haar
      crossplane-kind: role.iam.aws.upbound.io
      crossplane-name: role-with-inline-policy
      crossplane-providerconfig: default
    tagsAll:
      chris: haar
      crossplane-kind: role.iam.aws.upbound.io
      crossplane-name: role-with-inline-policy
      crossplane-providerconfig: default
    uniqueId: AROAY4AFTTSEVJ4NO2S2M
  conditions:
  - lastTransitionTime: "2024-08-12T15:37:47Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-08-12T15:37:44Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2024-08-12T15:37:45Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
```

i think we need to skip the `setExternalTagsWithPaved` when `spec.initProvider.tags` is defined - the same what we doing when resources are created in observe only mode https://github.com/crossplane/upjet/blob/main/pkg/config/resource.go#L312

**Comment by haarchri** [comment]
@ulucinar can you check if this is a way to go for upjet ?

**Comment by ulucinar** [comment]
We had better understand the issue here: I assume the external compliance system mutates the tags of the external resources and not the managed resource tags in Kubernetes. Because the Crossplane provider has an opinion, via the `Tagger` initializer, on what the tags on the external resource should be, the provider detects a drift upon a reconciliation after the external system tags the external resource and then updates the tags. This probably results in a race between the Crossplane provider and the external compliance system.

Looks like we need a way to turn off the `Tagger` initializer because we assume we cannot make those tags from the external compliance system part of the desired state. Another approach could be to initialize the tags with `spec.initProvider.tags`, instead of `spec.forProvider.tags`, so that unless `spec.forProvider.tags` is explicitly given, tags would not be considered in drift calculation in subsequent reconciliations. This would also require disabling the late-initialization as mentioned above.

What I don't like regarding initializing tags under `spec.initProvider` is that it's a breaking behavior change. Also one might argue the Crossplane provider should be reconciling those tags if they are modified externally.

I think it would be good to have a dedicated management policy that controls whether initializers are run or not on an MR. Reading [the definition of an initializer](https://github.com/crossplane/crossplane-runtime/blob/089f5f2347e2940325788a7205e65c9f78361950/pkg/reconciler/managed/reconciler.go#L183), establishing the ownership of an MR would depend on whether that specific management policy (like `Initialize`) has been enabled or not. This is also related to what sorts of actions are expected from an initializer but I think a management policy like upjet's `Tagger` would benefit from being controlled by a management policy.

However, we cannot simply add a new enabling (additive) management policy as it would again be a breaking change. A management policy with disabling (subtractive) semantics (e.g., `IgnoreInitializers`) would be backwards-compatible and would semantically be closer to what has originally been proposed here (annotations to ignore changes). But it does *not* fit into the management policies framework in my opinion. 

@haarchri, what you propose should work with a non-empty dictionary. It is another way of disabling the `Tagger` initializer, using `spec.initProvider.tags` as a gate. Setting `spec.initProvider.tags` to an empty dictionary (`{}`) will not work because it will be lost during serialization but a non-empty value could be used to disable the `Tagger` initializer. So when a user specifies at least one tag under `spec.initProvider.tags`, it would instruct the `Tagger` not to initialize tags under `spec.forProvider.tags`. If the user of the API uses `spec.initProvider.tags` to specify some initial tags, we may think that the `Tagger` should not explicitly tag the external resource via `spec.forProvider.tags`. However, this is still a breaking behavior change. But I personally believe its impact would be smaller than the other alternatives, as it's gated. It's also specific to the `Tagger` initializer, which is sort of fine as it's currently the initializer causing us issues and the implementation would be part of that initializer. But I also feel like we need a more general solution for similar situations and other providers for the long term.

**Comment by ababo** [comment]
Hey,

I’ve been following this issue because we’re hitting exactly the same class of drift / reconciliation / state-mismatch problems.

We’re building a completely different approach: **no persistent state file at all**.  
Desired state lives only in Git (Nickel configuration), observed state is derived from live infrastructure scans, and reconciliation is fully deterministic and ephemeral.

We already have a **working prototype** (successfully demonstrated with AWS EC2), but it’s still **early stage** — not a production-ready product yet.  
We are actively looking for **2–3 platform/infra teams** as the very first design partners to try the prototype in real environments, adapt it together and shape the next version.

If this resonates with the drift/reconciliation problems you’re seeing, I’d love to:
- show you the prototype live, and
- hear how this impacts your day-to-day.

No sales, no pressure — just honest technical discussion and the chance to influence the solution.

Details in these two posts:
• What if managing infrastructure felt like using git? → https://www.linkedin.com/posts/simon-golbert_what-if-managing-infrastructure-felt-like-activity-7447176625881837569-yKNO
• If deterministic, stateless, Git-driven infrastructure resonates with you → https://www.linkedin.com/posts/simon-golbert_most-infrastructure-tools-separate-configuration-activity-7434492903369891840-TfP2

Would you be open to a quick call or async feedback?
