### ISSUE TITLE
Fail to update CompositionRevision `spec.revision` when reverting to a previous composition version

### ISSUE THREAD

**Issue by duizabojul** [crossplane/crossplane#5928]
### What happened?

When attempting to rollback to a previous composition version, Crossplane fails to set it as the latest `CompositionRevision`. This results in the following error:
```
type: 'Warning' reason: 'UpdateRevision' CompositionRevision.apiextensions.crossplane.io "storage-gcpsqldatabaseinstance-v1alpha1-8e146c3" is invalid: spec.revision: Invalid value: "integer": Value is immutable
```

The issue appears to stem from [this commit](https://github.com/crossplane/crossplane/commit/ed0fb98cc8d19a96229caf460f2b0950d583438f), which made `spec.revision` immutable. 

During a rollback to a previous composition version, Crossplane doesn't create a new `CompositionRevision`. Instead, it [attempts to update](https://github.com/crossplane/crossplane/blob/1b4de654d10ad46f7c3058510c1a28f8981953df/internal/controller/apiextensions/composition/reconciler.go#L198) the `spec.revision` of the existing `CompositionRevision`. This operation is now impossible due to the field being marked as immutable.

### What environment did it happen in?
Crossplane version: 1.17.0

**Comment by jbw976** [comment]
Thanks for reporting this @duizabojul! 

> During a rollback to a previous composition version

Can you be very clear about the steps you're taking to attempt this operation? Further repro steps could be helpful so we're all thinking of the exact same process together.

Is there potentially a workaround, where you can update the composition to the same content as the previous revision, thus creating a new revision that can then be rolled "forward" to? 🤔 (not a great idea, but just trying to understand the boundaries of the problem here...)

**Comment by duizabojul** [comment]
If you update the composition content and[ it matches exactly a previous composition revision content](https://github.com/crossplane/crossplane/blob/1b4de654d10ad46f7c3058510c1a28f8981953df/internal/controller/apiextensions/composition/reconciler.go#L185), crossplane does not create a new composition revision and instead attempts to update the previous one to "promote" it the most recent (the one with the greater `spec.revision` value).

Before 1.17 it was okay to do this because you could change the value of `spec.revision` but now it is not possible.

Either we have to re-authorize the modification of `spec.revision` field, either each update of a composition should create a new composition revision, even if it means have multiple composition revisions with same content.

To reproduce the bug:
- create a composition (so a composition revision will be created)
- update the composition (so a new composition revision will be created)
- revert the composition to the first version, so crossplane should try to update first created composition revision `spec.revision` from 1 to 3, thus the error.

**Comment by negz** [comment]
I think I know what happened here.

In the first implementation of CompositionRevision the `revision` field was intended to be immutable. If you updated a Composition from state A to state B and back to state A you'd end up with three revisions: 0, 1, and 2. They'd all have non-deterministically generated random names. We added the `//+immutable` comment marker to indicate this, but nothing enforced it.

When we promoted CompositionRevision to v1beta1 (around https://github.com/crossplane/crossplane/pull/3450) we changed how it worked. Revision names are now deterministic, derived by hashing the labels, annotations, and spec of the Composition. This means that if you update a Composition from state A to state B and back to state A you'll only end up with two revisions. Instead of creating a third revision Crossplane will update the first one to change its revision number from 0 to 2, to indicate it's the latest revision of the Composition. When we made this change we neglected to remove the unenforced `//+immutable` marker.

Then finally in https://github.com/crossplane/crossplane/commit/ed0fb98cc8d19a96229caf460f2b0950d583438f we just did a find-and-replace to actually enforce all the old `//+immutable` tags, including this one that was no longer accurate.

> Either we have to re-authorize the modification of spec.revision field, either each update of a composition should create a new composition revision, even if it means having multiple composition revisions with same spec.

I think we should re-authorize modification of `spec.revision`.

In retrospect I'd have preferred that we leave revision numbers immutable and mark the latest revision explicitly, as proposed in https://github.com/crossplane/crossplane/issues/3415#issuecomment-1297813417. That way revisions are truly immutable, and it's easier to see when a Composition has reverted to an older revision. I think that ship has sailed though - we should maintain the GA behavior that we've had for some time.
