### ISSUE TITLE
Crossplane should consider the composite ready state in function responses

### ISSUE THREAD

**Issue by MisterMX** [crossplane/crossplane#6020]
### What problem are you facing?

Crossplane currenty ignores `.Desired.Composite.Ready` property in a function response. This makes it challenging to mark a claim / composite on then as ready when all resources are created and available.

In our scenario we are creating an AWS DBCluster and waiting for it to get ready before creating the DBInstance. Our users are facing the problem that the ready state of the claim constantly jumps between ready and unready since (1) the cluster is created (2) gets ready (3) the instance is created and finally (4) this gets ready.

We are currently helping ourselves with a "hack" by marking the DBCluster explicitly as unready in the response until the DBInstance exists. It works but it is not a solution we want to rely on in the long run. Instead of setting a composed resource as unready we would like to mark the composite resource itself as unready. The field exists but is currently ignored.

### How could Crossplane help solve your problem?

Crossplane should consider the `.Desired.Composite.Ready` property to determine the ready condition of the composite resource.

**Comment by phisco** [comment]
This is mainly due to the logic being "a composite resource is ready if all its composed resources are ready (according to the functions pippeline, not the Ready condition)" 😅 Unfortunately this means that with compositions waiting for resources to be ready before creating other resources, as in your case, you end up with flaky readiness.

I agree we could respect `.Desired.Composite.Ready` if set, AFAICT it should not be a breaking change either, except if some function was setting it to false deliberately for some reason.
CC @negz

**Comment by bobh66** [comment]
There is another problem related to this which is that the composite resource readiness is now decoupled from the success of the pipeline.  In legacy P&T a failed patch would leave the composite resource in the unready state, but in Composition Functions the P&T pipeline step can "fail" due to a required patch failing and the Composite Resource will still show up as `Ready` even though there are no resources associated with it.  I think the P&T function "fails" softly to not block the pipeline from executing but still results in no desired resources, so there really needs to be a way for the function to indicate that it will eventually have resources it just doesn't have them yet, and so the composite should not be Ready until it actually has the resources.

**Comment by bobh66** [comment]
Is it reasonable for P&T to assume that it should eventually create all of the resources it has in it's list?  Meaning that it could give some indication to XP that it could expect N resources from P&T, which might be filtered or sequenced or otherwise processed later.
