### ISSUE TITLE
Support dynamic ServiceAccount per Provider 

### ISSUE THREAD

**Issue by twobiers** [crossplane/crossplane#6122]
### What problem are you facing?
I'm trying to wrap my head around a multi-tenant usage of crossplane. When thinking about the Azure Provider, we are able to define a ProviderConfig per tenant. One of the best practice in Azure is to utilize [Workload Idenitties](https://azure.github.io/azure-workload-identity/docs/). 
While it's possible to use Workload Identities an implication is that we are only able to use the kubelet identity, which in turn means a single identity must have access to all subscriptions. Obviously, it would be better if we could somehow utilize a single identity per tenant which has only access to the tenants subscription. As a consequence, we would have multiple service accounts and therefore crossplane would need a way of dealing with multiple service accounts.

### How could Crossplane help solve your problem?

I think it would be a good if every ProviderConfig could reference a ServiceAccount which the underlying pod of the provider can impersonate to issue requests against the provider. This way we could introduce a service account per tenant. I think that this might benefit every provider, so maybe it's possible to have a common implementation rather than implementing that in a provider?
A similar implementation can be found in the [External Secrets Operator](https://external-secrets.io/latest/provider/azure-key-vault/#referenced-service-account).

**Comment by twobiers** [comment]
After a night of sleep I figured out, that this should be an implementation detail of the provider config.
Also, since the upjet azure provider is using terraform, it cannot that easily authenticate with a programmatically obtained token.

A possible implementation would be to have per tenant an identity and a single ProviderConfig, then have a single service account which has a 1:n mapping to the identities and is able to federate all identities.

I think for my use-case the issue is unrelated and would be better located in the provider than here, so I will close it for now.

**Comment by jtv8** [comment]
Actually @twobiers - I think your original suggestion in this issue has some merit.

I've been working on an implementation of this for Azure:

> A possible implementation would be to have per tenant an identity and a single ProviderConfig, then have a single service account which has a 1:n mapping to the identities and is able to federate all identities.

While this _does_ work functionally, it has some practical security holes that need solving.

## Problem

If we're creating a multi-tenant Crossplane cluster where each team has its own namespace, any team (or malicious actor) could create a ProviderConfig and provide the client ID for any _other_ team's managed identity.

There's nothing to tell either Crossplane or Azure that a particular managed identity "belongs" to a particular namespace. This is functionally no more secure than having one cluster-wide managed identity.

## Mitigation (and associated drawbacks)

Perhaps you could create all the ProviderConfigs centrally and prevent teams from creating their own - but there are some good reasons why you might want teams to be able to create and manage these.

For example, if they're working with multiple subscriptions, it requires one ProviderConfig per subscription due to the (unfortunate, IMO) design choices in the AzueRM Terraform provider.

Or they might need to authenticate with other Azure tenants entirely - for example, to configure cross-tenant VNet peering.

## Alternatives

Solving this probem more robustly requires every ProviderConfig to have its own distinct OIDC identity that can be used to federate with other services - much like every GitHub Actions branch has its own identity. This could be accomplished by:

1. Letting the provider pod's ServiceAccount impersonate another ServiceAccount that's specified in the ProviderConfig, or
2. Crossplane providing its own specialized OIDC issuer with the namespace + ProviderConfig name as a subject identifier

Would it then be feasible to add a feature to Upjet that would obtain an ID token for a specified identity and audience, then inject it into a provider configuration block, set it as a temporary environment variable, or write it to a temporary file before calling `terraform apply`? 

That's more or less identical to what I'd do in GitHub Actions to authenticate with a Terraform provider that supports OIDC federation - so I think it makes sense here, given that GitHub Actions + Terraform is probably what most potential Crossplane adopters are using right now.
