### ISSUE TITLE
support existing helm charts

### ISSUE THREAD

**Issue by sbawaska** [crossplane/crossplane#666]
### What problem are you facing?

As a software vendor, I would like to give my customers an option of installing my software using crossplane stack. I already have a helm chart for my software and would like to minimize the number of distributions I have to ship.

### How could Crossplane help solve your problem?

To me, it seems like stacks have a large overlap with helm 3 and cnab.
Like Helm 3 stacks define a CRD to keep track of functionality that has been installed.
Like cnab define a container image that bundles artifacts to be installed.
It is not clear if you want to implement repository from scratch or not, but Helm 3 packages are going to be stored in OCI registries, so that might an approach to implement registries.

It would be nice if the [stack design](https://github.com/crossplaneio/crossplane/blob/master/design/design-doc-stacks.md) considered leveraging helm and cnab in its implementation.

**Comment by hasheddan** [comment]
@sbawaska thanks for your thoughts here! It is definitely a priority to make generating a stack from existing work a seamless and efficient process. Would love to chat about this more, feel free to join the [slack channel](https://slack.crossplane.io/)!

**Comment by displague** [comment]
Specifically, this channel: https://crossplane.slack.com/messages/CKXQK4P27

I created a lightweight proof of concept Stack https://github.com/displague/sample-extension-metacontroller/blob/master/install.sh that could be modified to install and uninstall a helm chart, however, as @hasheddan pointed out, a more interesting solution would convert a helm chart to be stack compatible (or finding a way to fulfill all of various distribution method requirements in a single package).

**Comment by displague** [comment]
We have some open issues related to Stack design that you may be of further interest: 
https://github.com/crossplaneio/crossplane/pull/605
https://github.com/crossplaneio/crossplane/pull/604

**Comment by suskin** [comment]
Hi @sbawaska and also @glyn ! Thanks for helping us! Like @hasheddan said, we are definitely interested in feedback from the wider community. Our goal is to create the best possible experience here, and we're very early in the process, so we really appreciate that you are sharing your thoughts with us! Since we are early in the project, it may take us some time to get to everything, but we will continue to post updates and further thoughts here as we have them. Please let us know if you have any other ideas; we'd love to hear them!

**Comment by prasek** [comment]
@sbawaska we are definitely interested supporting helm charts as part of the stacks design. In fact we showed off using GitLab's helm chart at KubeCon Barcelona.

We've not looked at CNAB deeply, but at a high level even CNAB and Helm look like they have an overlap (certainly from a distribution standpoint).

We see stacks as being a bit more Kubernetes native, in fact, we define a stack as a Kubernetes controller that owns at least one CRD and uses zero or more CRDs. We think that instantiating applications should also be done in declarative manner (i.e. `kubectl apply`), vs. package manager approaches to the problem.

Stacks is still early and we would love to engage more and learn about your scenarios.

**Comment by markfisher** [comment]
CNAB can wrap Helm charts as this example illustrates:
https://github.com/deislabs/example-bundles/tree/master/hellohelm

The [base image](https://github.com/deislabs/example-bundles/blob/master/hellohelm/cnab/Dockerfile#L1) designated in the `Dockerfile` is expecting one or more Helm charts to be available in the invocation image that extends that base, so that the CNAB bundle distribution format is acting as an envelope (as opposed to the Helm chart being the distribution format itself).

CNAB provides a consistent and simple model - just a CNAB_ACTION env var, and a defined entry point - for any image that performs lifecycle operations. The spec is intentionally open-ended in terms of what the invocation image actually does, and so indeed that can extend beyond Kubernetes-native deployments, or an invocation image could use `kubectl` directly in a way that does overlap with Helm.

The CNAB packaging format provides additional metadata, such as parameters and credentials needed by the invocation image, as well as the manifest of images that will be installed - with both thick (images included) and thin (only metadata) formats. Thick bundles enable installation in air-gapped environments, and image relocation is supported via mapping files as Glyn mentioned [here](https://github.com/crossplaneio/crossplane/issues/505#issuecomment-517811617)

**Comment by glyn** [comment]
Yes, enterprise customers need to relocate images to their private registries and this is something CNAB has been focussing on. Other features of CNAB coming up are the ability to distribute software via Docker/OCI registries (cf. [Docker app](https://blog.docker.com/2018/12/docker-app-and-cnab/)) and securing the software supply chain.

Stepping back, I can see a couple of approaches:

1. We could wrap Crossplane stacks or extensions in CNAB bundles (pardon the [RAS syndrome](https://en.wikipedia.org/wiki/RAS_syndrome)). This would allow the images to be relocated, probably to a registry shared across clusters. At install time, a bundle would delegate to Crossplane to deploy the stack or extension. The main downside of this approach is how to deal with the overlap between Crossplane artefacts and CNAB. (There is also a small downside of the imperative step of running the "invocation image" of the bundle, but this can be minimised by providing a so-called "base invocation image" which understands Crossplane and then have concrete bundles include Crossplane definitions and use the base invocation image to do the installation.)

2. We could take the image relocation and potentially other features of CNAB and somehow add them to Crossplane. This seems like a recipe for excessive complexity. Given that CNAB and Crossplane are addressing mostly orthogonal requirements, it would be a shame to lose the benefits of developing these relatively independently. The one benefit of this approach, IMO, is that it would avoid the "overlap" issue.

**Comment by muvaf** [comment]
Fixed by https://github.com/crossplane-contrib/provider-helm
