### ISSUE TITLE
Rename crossplaneio GitHub org to crossplane

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#697]
The current organization name for Crossplane on GitHub is `crossplaneio` since `crossplane` was previously unavailable.  `crossplane` is now available, so we should go ahead and move the current org over to that nice clean one.

We will need to update all the golang import paths across the various repositories, and we should also think through any other consequences of this change.  We believe that GitHub will redirect from the old org to the new org, but we should figure out if that's just a temporary thing or if there's any deficiencies in that process.

The container image repo is already `crossplane/crossplane` so this GitHub org change would become aligned with that finally.  There should be nothing to change for the container image.

**Comment by negz** [comment]
Where is this at? Is it still a priority?

**Comment by muvaf** [comment]
This is frustrating when you author a stack that will be published to dockerhub `crossplane` organization while the source code is under `crossplaneio` Github org. See https://github.com/crossplaneio/stack-minimal-gcp/pull/9

I think we should just do it and move on to fixing problems caused by the change.

**Comment by jbw976** [comment]
Before just pulling the trigger, could we spend 1 hour looking into (and writing down a list) all the places that would be affected? I'd feel better about it if we just spent a little focus time figuring out what the *known* consequences are, then we can proceed with cleaning up everything we know about, as well as dealing with the unexpected that comes up.

**Comment by hasheddan** [comment]
Adding some context for potentials areas of trouble here. We likely would be primarily concerned about [non-automatic changes](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/renaming-an-organization#changes-that-arent-automatic). It appears manual action items would include:
- Updating all references to org profile (i.e. github.com/crossplaneio). Links to individual repositories will auto-redirect, but the profile page will not.
- API requests do not redirect. I imagine this could require updates to Jenkins pipelines / Upbound bot.

**Comment by jbw976** [comment]
We would really like to do this before Kubecon Amsterdam

**Comment by negz** [comment]
@jbw976 I'm guessing we'll need your expertise on the build tooling to help with any breakage that happens. Perhaps we should just pick a day when you're relatively available and do it?

**Comment by muvaf** [comment]
I've done a few renaming of the repos. In my experience, nothing really breaks for current go modules importing our repos because go mod looks for [module name in `go.mod`](https://github.com/crossplaneio/crossplane/blob/master/go.mod#L1) and this is version-controlled. This means the requests are redirected to the correct repo by Github and go mod imports will keep working since they'll look at older commits. However, when they want to bump the version, they'll need to change the module path otherwise build returns error saying `you wanted crossplaneio but this crossplane`.

One strategy could be that after the release on Friday, we can do this and issue a patch release right away. Try that patch release out in a few places and fix the things that seem to be broken. If it requires we could do another patch release that fix it, if everything goes well we'd just go on and do the next normal release in normal time.

**Comment by negz** [comment]
I suggest we get this into the next sprint and work on it first thing Monday.

**Comment by negz** [comment]
@hasheddan handled this on Tuesday!
