### ISSUE TITLE
Experience: Make uninstallation smoother

### ISSUE THREAD

**Issue by suskin** [crossplane/crossplane#847]
### What problem are you facing?

As a Crossplane operator, when I uninstall Crossplane from a cluster, it is rather inconvenient. The easiest way is to delete the whole cluster, but that doesn't seem very realistic for clusters running workloads of any value. Here is what normally happens when I am trying to preserve the cluster:

* First I try to delete the helm chart, or delete all the api-resources and deployments installed by the chart
* If I have created any Crossplane resources, this partially deletes Crossplane from the cluster, but fails when it gets to the Crossplane resources
* By this time, I have usually already successfully deleted the Crossplane deployment, but the Crossplane managed resources are hanging around still, and I end up needing to delete them by hand, in the order which the expect (for them to finalize properly). Or, I need to remove the finalizer so I can blindly delete everything. Even removing the finalizers is not very convenient; I have a script which I've written to make it simpler

### How could Crossplane help solve your problem?

I would like to be able to blindly delete or uninstall everything, and have Crossplane either magically shut down all the external resources in the right order and delete itself for me, OR leave all of my external resources alone and just remove all traces of Crossplane. It is totally possible that this is already something which is doable, and I don't know about how to do it in the right way.

**Comment by ctrox** [comment]
I have also noticed an issue with the uninstall, if you use helm to install for example the GCP stack like this:
`helm install --name crossplane --namespace crossplane-system crossplane-alpha/crossplane --set clusterStacks.gcp.deploy=true --set clusterStacks.gcp.version=alpha`

Then wait for everything to reconcile and then delete it again:
`helm delete --purge crossplane`

The `stack` and `clusterstackinstall` resources have a deletion timestamp but are stuck because they have a finalizer and the controllers have already been deleted by helm. So the only way to get rid of them is to remove the finalizers or delete those resources manually before running `helm delete`.

I'm honestly unsure if this can even be solved by helm itself.

**Comment by muvaf** [comment]
@turkenh would new `crds` directory in helm3 help here?

**Comment by turkenh** [comment]
> @turkenh do you think new crds directory in helm3 help here?

I don't think so.
The problem is the controllers (not crds) that are expected to finalize resources are gone before they do so.

A possible solution could be using [`pre-delete` helm hook](https://helm.sh/docs/topics/charts_hooks/#the-available-hooks) with a job which deletes all `stackinstall` and `clusterstackinstall` resources (and waits until they are gone).

**Comment by negz** [comment]
I believe the work @muvaf did on the init container and @hasheddan's subsequent Lock cleanup work addressed most or all of these pains.
