### ISSUE TITLE
Claims: claims can be bound but not ready

### ISSUE THREAD

**Issue by suskin** [crossplane/crossplane#851]
### What happened?

I was going through the Crossplane Stacks Guide using AWS and a Crossplane control cluster on my laptop, and I got into a weird state where I had a mysqlinstance which is Bound but not ready:

```
apiVersion: v1
items:
- apiVersion: database.crossplane.io/v1alpha1
  kind: MySQLInstance
  metadata:
    creationTimestamp: "2019-09-25T17:53:06Z"
    finalizers:
    - finalizer.resourceclaim.crossplane.io
    generation: 3
    labels:
      stack: sample-stack-wordpress
    name: wordpress-mysql-545c70c6-dfbd-11e9-b678-025000000001
    namespace: app-project1-dev
    ownerReferences:
    - apiVersion: wordpress.samples.stacks.crossplane.io/v1alpha1
      kind: WordpressInstance
      name: my-wordpressinstance
      uid: 545c70c6-dfbd-11e9-b678-025000000001
    resourceVersion: "411229"
    selfLink: /apis/database.crossplane.io/v1alpha1/namespaces/app-project1-dev/mysqlinstances/wordpress-mysql-545c70c6-dfbd-11e9-b678-025000000001
    uid: 54607bf5-dfbd-11e9-b678-025000000001
  spec:
    classRef:
      name: mysql-standard
    engineVersion: "5.7"
    resourceRef:
      apiVersion: database.aws.crossplane.io/v1alpha2
      kind: RDSInstance
      name: mysqlinstance-54607bf5-dfbd-11e9-b678-025000000001
      namespace: infra-aws
    writeConnectionSecretToRef:
      name: sql-545c70c6-dfbd-11e9-b678-025000000001
  status:
    bindingPhase: Bound
    conditions:
    - lastTransitionTime: "2019-09-25T20:05:18Z"
      reason: Managed claim is waiting for managed resource to become bindable
      status: "False"
      type: Ready
    - lastTransitionTime: "2019-09-25T17:53:07Z"
      reason: Successfully reconciled managed resource
      status: "True"
      type: Synced
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

At the same time, I also had the AWS Stack failing to reconcile an rdsinstance as described in crossplaneio/stack-aws#21 .

This seems like a weird state to get into, and it isn't completely clear how it would happen. I'm not sure whether it's something that we need to fix, but I want to make sure we are at least aware that it is something that can happen.

### How can we reproduce it?

I am not entirely sure, but one could try following the Crossplane Stacks Guide with AWS to see if it reproduces easily. I have not tried doing this yet.

### What environment did it happen in?
Crossplane version: helm alpha, which looks to be running `crossplane/crossplane:v0.3.0`
AWS Stack version: `crossplane/stack-aws:v0.1.0`
Kubernetes is Docker for Mac

**Comment by negz** [comment]
This does look like a weird state.

I don't believe it's fundamentally wrong for a claim to be bound but not ready. Readiness is a measure of the availability of a resource, while binding represents whether it has been claimed. Only claims that are ready should be eligible for binding, but we need to consider the case in which a bound managed resource becomes unavailable (for instance because it has gone into maintenance, is malfunctioning, or is being deleted). In such a case it seems reasonable that we still consider it bound.

That all said, it looks like in this specific instance the ready condition is stating that the claim is not ready because it's waiting to bind, while the binding status says it is bound. This shouldn't happen. 

https://github.com/crossplaneio/crossplane-runtime/blob/d805043/pkg/resource/claim_reconciler.go#L391

I imagine the error will be somewhere in the above logic, but I can't immediately spot it.

**Comment by negz** [comment]
We're deprecating resource claims, so this is no longer relevant. I suspect we might run into this with requirements (the code is currently pretty similar), but I'm going to optimistically close this in the hope that we the requirement code grows we don't end up with this bug.
