### ISSUE TITLE
Enable code quality checks for stack repos

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#875]
Part of #864 

### What problem are you facing?

SonarCloud provides some good code quality checks and enforcement to keep our code base healthy.  In the migration of cloud provider stacks out-of-tree to their own repositories, we did not also enable SonarCloud checks for each of those new repos, so we are missing those quality and health checks right now.

### How could Crossplane help solve your problem?

The automated build verification for the cloud provider stacks should have SonarCloud enabled so that we can keep our code at a high quality.

**Comment by negz** [comment]
At the risk of starting work on a very large bike shed I'd love it if we could reassess whether Sonarcloud is still our preferred tool, and is configured correctly for our needs before proliferating it. 😬

I personally just don't love Sonarcloud in general, but at the very least I'd like it if we could have `golangci-lint` and Sonarcloud use the same set of rules for checking code quality. It's a little frustrating for example that code will pass the linter, then get rejected by Sonarcloud (a rejection we typically seem to just ignore) for a slightly different variation of a linter rule (e.g. different cyclomatic complexity settings).

**Comment by negz** [comment]
Breadcrumbs for https://github.com/crossplaneio/crossplane/issues/880 - Sonarcloud seems to be suffering from strange coverage measurement issues. We moved from Codecov to Sonar because Codecov had similar issues.

**Comment by soorena776** [comment]
I don't have a strong opinion about to use or not use SonarCloud, but I agree with @negz that:
> I'd like it if we could have golangci-lint and Sonarcloud use the same set of rules for checking code quality.

**Comment by jbw976** [comment]
I'm removing this from the v0.4 milestone as it sounds like we'll want to do some more thorough vetting of SonarCloud or a better solution.

**Comment by negz** [comment]
Per #1283 I've removed Sonarcloud from c/c and setup https://golangci.com/ for all repositories. This means all crossplane org repositories now have linting enabled using the same configuration and heuristics as `make reviewable`, because they run `golangci-lint` and respect its configuration file. You can see an example of this in action here - https://github.com/crossplane/crossplane/pull/1284#pullrequestreview-361425863

We do still need to enable test coverage reporting for all repos; I'm going to track that in #1283.
