### ISSUE TITLE
Restrict a Stack's access to core types when the stack claims they "depend on" them

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#899]
### What problem are you facing?

As per the [stacks security and isolation design](https://github.com/crossplaneio/crossplane/blob/master/design/one-pager-stacks-security-isolation.md#allowed-resource-access), it is intended to restrict access to the resources that a Stack can perform operations on.  Specifically, a stack only gets access to the CRDs that it owns or declares that it depends on.

However, we don't discriminate at all about what resources a Stack claims it depends on.  I believe that if a stack declares it "depends on" volumes or pods, then we'd be OK with that and create the necessary RBAC to allow that access.

**Important**: Must support a run mode compatible with running Crossplane directly in the target cluster such that Crossplane stacks can manage Kubernetes core types including `Deployment`, `Ingress`, `Services`.

### How could Crossplane help solve your problem?

We should consider black or white listing the API groups or resources that stacks can get access to, even if they claim they depend on them.  If a stack says it depends on volumes or pods, we should not grant them RBAC access to them.

The code that would need to be updated lives here:
https://github.com/crossplaneio/crossplane/blob/master/pkg/stacks/unpack.go#L359-L376

**Comment by displague** [comment]
Alternatively, if a Stack requires access to core or extension types, or any unknown outside type, UI tools (the CLI or Web UIs) should prompt for user confirmation or require arguments to override the default restrictive behavior.

I believe Stacks will benefit from being able to create any type of Kubernetes resource.  We can use https://github.com/crossplaneio/crossplane/issues/758 to restrict this.

Perhaps the restrictive behavior could be toggled through a feature flag of the Stack Manager.

**Comment by displague** [comment]
We should also be cognisant of Stacks that purport to include CRDs that are redundant to existing API Version and Groups.  Such a Stack could claim to "own" an API, the duplicitous CRD would be rejected on creation because the API already exists, and the Stack controller would receive RBAC roles over the desired API.

In this way, we must restrict "owned" types as well as "depends on" types.

**Comment by displague** [comment]
I [experimented](https://github.com/crossplaneio/crossplane/commit/e45f2885f9cea1c8aa5c4c7c173b3c314c7bea44
) with restricting use to core types using a `stack manage --allowed-groups=...` argument (limiting the GVK groups permitted in Stack dependsOn fields).

In doing so, I discovered that a white list at initialization prevents Stacks from leveraging additional Stacks as dependencies.

I now wonder if what we really want here is to limit `dependsOn` to CRDs annotated by the Stack Manager.  This would push the dependency checking to the Stack controller (away from the Unpack process as was attempted [in this branch](https://github.com/crossplaneio/crossplane/compare/master...displague:stack-core-types?expand=1)).

**Comment by displague** [comment]
> If the base set of permitted CRDs are 'those owned by any Stack', then we may have a need to expand the dependsOn pool using a Stack Manager argument.

The existing RoleBinding vs ClusterRoleBinding dicotomy that differentiates StackInstall and ClusterStackInstall service accouts creates a boundary preventing namespaced Stacks from depending on cluster-scoped Stack owned types.

We may want to put more definition around these boundaries, through this dependsOn restriction work:
* a namespace stack can not dependOn a cluster-scoped CRD (this is only a pre-validation step, since the rolebinding would prevent such access)
