### ISSUE TITLE
Support Provider controller configuration

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#974]
### What problem are you facing?

Stacks are frequently powered by controller managers. These controller managers are processes running in Kubernetes pods that may be configured via environment variables, command line flags, or (hypothetically) configuration files.

For example:

* A command line flag or environment variable can be used to enable or disable debug level logging per https://github.com/crossplaneio/crossplane/issues/849.
* The `http_proxy` environment variable can be used to request infrastructure stacks send HTTP requests via a proxy.
* The version of the stack controller to run (currently hard coded in `install.yaml`)

### How could Crossplane help solve your problem?

Crossplane stacks should run with sensible default configuration that may be overridden. It should be possible to change these configurations before installing the stack, and after the stack has been installed.

**Comment by displague** [comment]
Stack controller deployments may need access to a private registry (reflected in #505).

This can be defined at a namespace level: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account 
or per deployment: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret

Stack configuration should also allow the deployment image to have access to a private registry, since this should not be a stack packaged `install.yaml` detail (requiring knowledge of not available at stack publish time). The imagepullsecrets should be configurable at StackInstall/Stack configuration time.

**Comment by displague** [comment]
> It should be possible to change these configurations before installing the stack, and after the stack has been installed.

While considering how best to cram extra options into the `StackInstall` resource, I was reminded that the end product is a `Stack` resource, not the deployment whose configuration is want to change.  

As such, the `Stack` resource can be created with all of the customizations sought by this issue.

The benefits of using a `StackInstall` resource are that the CRDs are unpacked and annotated using metadata contained within the package.

Would an unpack-only be useful in this setting?  Or perhaps an option to start the deployment replication count at 0. 

If the CRDs and Stack were created, but not enabled, the `Stack` resource could be modified to add environment variables or debug command line arguments to the `controllers` section before the deployment was enabled (by whatever means).

Do these development and edge use-cases justify `StackInstall` parameters?

**Comment by hasheddan** [comment]
In the modern packaging infrastructure, there are three points at which a provider's controller could theoretically be configured:
1. At package build time. This does not make sense (except for the image) because a package author cannot be aware of configuration that its consumers may want.
2. At Crossplane install time. This mainly refers to setting the default deployment structure, as we do now. This could also be configured using something like a `ConfigMap` or passing information directly to the Crossplane binary in the form of flags / env vars, etc. The advantage of configuring here is that you would imagine that the "most privileged" user would be installing Crossplane, so they would likely be someone who would be a good candidate to decide what a provider controller deployment looks like. The downside to configuring at this point is that Crossplane runs as (potentially many) providers come and go. It is quite restrictive to dictate how _every_ provider should be deployed (note: this is the whole reason we are having this discussion, our model right now is too restrictive).
3. At provider install time. This makes the most sense as it is specific to a single `Provider` and can even change from revision to revision. It would likely be accomplished by just adding a `PodSpec` to the `Provider` spec. However, this allows anyone who can install a `Provider` to be able to run any arbitrary `Pod`, something that is likely undesirable in many environments.

The two options that navigate the pros and cons listed above boil down to:
1. Do (3) and manage how configuration happens with something like OPA.
2. Mix (2) and (3) by configuring Crossplane in such a way that some subset of `PodSpec` fields are configurable.

It would be simpler if we could just rely on (1), but that does require an extra dependency (OPA or other policy tools) if you want "unprivileged" users to be able to create `Providers`.

The last option would be to have something like a `controllerConfigRef` in the `spec` of the `Provider`, which would point to another type that Crossplane would introduce (`ControllerConfig`). This would allow a set of controller configurations to be published by the most privileged user in an environment, and would free up users with lesser privileges to configure there `Provider` from a set of templates.

**Comment by mothershipper** [comment]
> Mix (2) and (3) by configuring Crossplane in such a way that some subset of PodSpec fields are configurable.

I feel like it's mostly overlap (at least within AWS) of how to set up IAM auth. IRSA is kind of the oddball requiring a serviceaccount as well as annotations. Assuming other cloud providers are similar, I think you could enumerate the subset of fields needed.

> Do (3) and manage how configuration happens with something like OPA.

You could also go with option 3 and a full podspec without OPA. Use a ValidatingAdmissionWebhook to verify the requesting user has "create" pod permissions and accept/deny the `Provider` based on that. An example [request body is here](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#webhook-request-and-response)

```javascript
{
  "apiVersion": "admission.k8s.io/v1",
  "kind": "AdmissionReview",
  ...
  "userInfo": {
      # Username of the authenticated user making the request to the API server
      "username": "admin",
      # UID of the authenticated user making the request to the API server
      "uid": "014fbff9a07c",
      # Group memberships of the authenticated user making the request to the API server
      "groups": ["system:authenticated","my-admin-group"],
      # Arbitrary extra info associated with the user making the request to the API server.
      # This is populated by the API server authentication layer and should be included
      # if any SubjectAccessReview checks are performed by the webhook.
      "extra": {
        "some-key":["some-value1", "some-value2"]
      }
   },
}
```

**Comment by mothershipper** [comment]
Although, now re-reading, that webhook wouldn't allow "unprivileged" users to create providers, it would just ensure they have sufficient privileges.

**Comment by mothershipper** [comment]
But if you make that webhook a flag at the Crossplane level, you could give the users an option to turn it off/bring their own webhook / OPA instance.

**Comment by lukeweber** [comment]
(2) feels like a great place for defaulting as an convenience configuration to setup how most controllers run, optionally maybe some config of whether to allow (3) or to conditionally allow it.
(3) feels required to allow for special configuration that will ultimately come up in special cases.

**Comment by negz** [comment]
I suggest we focus on the third option - making this configurable at Provider install time. I would prefer to avoid broad runtime level whitelist/blacklists (i.e. the second option), especially if we think they'll only be an interim solution.

If we're concerned about requiring something like OPA to enforce policy, we could consider implementing something like a `ProviderSecurityPolicy` - similar to an [upstream `PodSecurityPolicy`](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#what-is-a-pod-security-policy). It's possible we could get away with something simpler (e.g. have our controllers check for the existence of a policy rather than using admission webhooks, RBAC, etc).

**Comment by mothershipper** [comment]
I definitely prefer the third option as well, seems pretty future proof.

A ProviderSecurityPolicy would work for me and would be more flexible than
the admission controller.

The flip side is that it's (potentially) more configuration to support, and
if a use case isn't supported, operators would still have to add their own
OPA policy or webhook to get the safety they want.

I suggested the admission controller because it wouldn't necessarily
introduce an additional API surface to the end user. But at the same time,
I've not had a need to go much more granular than controlling who can
launch pods in the cluster. More specific requirements would already mean
I'm running something like OPA to enforce them.

**Comment by muvaf** [comment]
I agree that configuration during provider install time seems more useful for many cases. Though I'm hesitant about OPA; not because of the project itself but the idea that one needs another dependency to secure Crossplane sounds kind of odd. I know that the people who are creating `Provider`s are already privileged and they can install any provider image anyway so it's not much big difference from concrete security boundaries perspective but for sure it lowers the barrier to have it right there and also they'd be able to create `privileged` pods if not secured. So, it's not only the ability to choose the image but also configuration of the resulting `Pod` which can affect the capabilities of that chosen image.

I don't have much to back this up but I feel like `podSpecTemplate` is kind of a degradation in UX to have in `Provider`. It's optional but still a giant schema there.

So, I'm leaning towards `ControllerConfig` idea that the creator of `Provider` would reference. If they don't need to make any change in the pod, then they wouldn't have to see or be able to use `podSpecTemplate` at all.

> If we're concerned about requiring something like OPA to enforce policy, we could consider implementing something like a ProviderSecurityPolicy - similar to an upstream PodSecurityPolicy. It's possible we could get away with something simpler (e.g. have our controllers check for the existence of a policy rather than using admission webhooks, RBAC, etc).

@negz Do you mean that we'd have `podSpecTemplate` under `Provider` and check that template against a `ProviderSecurityPolicy`?

**Comment by negz** [comment]
> I don't have much to back this up but I feel like podSpecTemplate is kind of a degradation in UX to have in Provider. It's optional but still a giant schema there.

Agreed.

> Do you mean that we'd have podSpecTemplate under Provider and check that template against a ProviderSecurityPolicy?

Kind of. I'd probably go with something more targeted and grow it as we get feedback, rather than starting with an entire `podSpecTemplate`. I especially wouldn't _require_ a `podSpecTemplate` - I'd want there to be sane defaults that you could override.

**Comment by negz** [comment]
@muvaf I don't have a strong reservation.

I'm not particularly convinced that there's a meaninfgul UX gain to be had in the `ControllerConfig` approach. I think it's reasonable that the personas who we expect to install a `Provider` (i.e. platform builders and operators) will be the same people who would want to configure how a provider is run; I'm not sure we should be trying to hide the details of how a provider controller could be configured from the people responsible for configuring and operating the platform.

I'm also a little suspicious that we might be making our system more cognitively and technically complex for most folks (i.e. folks who don't need to place restrictions on what a `Provider` can configure) in order to support a seemingly niche use case (i.e. folks like Upbound Cloud who want to limit what a `Provider` author can configure. This suspicion applies to the `ProviderSecurityPolicy` approach too. My hunch is that the simplest thing we could do from the perspective of most users would be to expose these settings via the `Provider` type, with an expectation that customers with the niche use case use OPA or some other admission control webhook to restrict what folks can do with a `Provider`.

That said, I do like that putting configuration in a separate type means we could make that type v1alpha1 and give it some time to incubate as we figure out what settings should be exposed and what that API should look like. We could always deprecate `ControllerConfig` it and roll it into `Provider` once its API is more mature.

I think @hasheddan should make the final call here based on the feedback he's received. I will say that if we go for the `ControllerConfig` route I'd like us to consider a different name - perhaps `ProviderController` - unless we feel like this is likely to become a generic controller configuration type that is used by types other than `Provider`.

**Comment by hasheddan** [comment]
> That said, I do like that putting configuration in a separate type means we could make that type v1alpha1 and give it some time to incubate as we figure out what settings should be exposed and what that API should look like.

This is the crux of the decision for me. The flexibility of versioning this functionality separately from `Provider` (which we hope to make a stable API in a coming release) is a massive selling point to me. I also appreciate the RBAC isolation, which I believe will make enabling / disabling this functionality easier for folks hosting Crossplane. In general, I also appreciate separating operations that could require different privilege levels. Lastly, I would actually advocate for calling it `ControllerConfig` in the `pkg.crossplane.io` group as I think it is a possibility that we would want to use it for other package types in the future.

Just to summarize where we landed in the community call:
- Add `ControllerConfig` type that essentially is just a `PodSpec` (or a subset of it)
- Add `spec.controllerConfigRef` to `Provider` (references a cluster-scoped `ControllerConfig` by name)
- `Provider` will use the default `Deployment` configuration (hardcoded in crossplane today) if no `controllerConfigRef` is provided in `spec`. We imagine this be the functionality for the vast majority of cases.
- `Provider` will use a referenced `ControllerConfig` for `Deployment` if provided.

Points we did not explicitly state, but could be inferred:
- None of the Crossplane user-personas will be given access to `ControllerConfig`. If we view this as a separate operation from installing a `Provider`, then we should not put it at the same permission-level as a role such as `crossplane-admin`. This means that, in order to create a `ControllerConfig`, you must be manually given RBAC to do so, or be `cluster-admin`.
