### ISSUE TITLE
Include UI Metadata for Core Crossplane Types

### ISSUE THREAD

**Issue by displague** [crossplane/crossplane#979]
### What problem are you facing?

As noted in https://github.com/crossplaneio/crossplane/issues/751#issuecomment-543285321, there is a desire to provide UI metadata for all managed types supported by Crossplane.

Not all resources are managed via the Stack Manager, which is currently responsible for applying metadata to new CRDs.  The core Crossplane types (KubernetesCluster, MysqlInstance, etc) are not installed as a stack, resulting in no UI CRD annotations for these types.

### How could Crossplane help solve your problem?

Crossplane should annotate these CRDs in some way either at build time or runtime, perhaps using the Stack Manager, perhaps using Kubebuilder (which is already responsible for generating the CRDs).

**Comment by displague** [comment]
Capturing some  [Crossplane Slack thoughts](https://crossplane.slack.com/archives/CEF5N8X08/p1572018139128300):

> I'm thinking at build time we could use some of the existing stack-manager logic through a new cmd/ to annotate the kubebuilder generated CRD files.  The CRDs would be installed pre-annotated with resource/icon/ui-schema metadata files that would have to reside somewhere in the crossplane repo.
> It would be really helpful if kubebuilder provided a go annotation that allowed you to define crd annotations and labels :smile:
> `// +kubebuilder:annotation:name="crossplane.io/ui-schema",value="...."`

**Comment by displague** [comment]
An idea that @bassam and @lukeweber have floated is that the Core of Crossplane could be a Stack itself.  This would make the Stack Manager the primary tool to install and once that is installed, the Crossplane Stack as well as infrastructure Stacks would be installed using ClusterStackInstall records.

**Comment by negz** [comment]
I'm going to close this because for the time being we've parted ways with the idea of Crossplane (as a project) having UI metadata. We at @upbound however are still thinking this will be useful for products like Upbound Cloud and our `up` CLI tool, but we're going to work on that in https://github.com/upbound/universal-crossplane for now. If we see strong enough demand from the community (e.g. other folks wanting a UI standard) we may bring the work back upstream eventually.
